force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Commitment_Reoccurence__c.field-meta.xml
<CustomField>
    <fullName>Commitment_Reoccurence__c</fullName>
    <label>Commitment Reoccurence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>month</fullName>
            </value>
            <value>
                <fullName>quarter</fullName>
            </value>
            <value>
                <fullName>year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Committed_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Committed_Minutes__c</fullName>
    <description>Committed number of minutes that the customer will use for this Audio Product, which is added to the Estimated Minutes for the total.</description>
    <inlineHelpText>Committed number of minutes that the customer will use for this Audio Product, which is added to the Estimated Minutes for the total.</inlineHelpText>
    <label>Committed Minutes</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Committed_Rate__c.field-meta.xml
<CustomField>
    <fullName>Committed_Rate__c</fullName>
    <description>Committed rate that the customer will pay for this Audio Product&apos;s Minutes.</description>
    <inlineHelpText>Committed rate that the customer will pay for this Audio Product&apos;s Minutes.</inlineHelpText>
    <label>Committed Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Enterprise_Name__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offering</label>
    <referenceTo>Offerings__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Estimated_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Minutes__c</fullName>
    <description>Estimated number of minutes that the customer will use for this Audio Product, which is added to the Committed Minutes for the total.</description>
    <inlineHelpText>Estimated number of minutes that the customer will use for this Audio Product, which is added to the Committed Minutes for the total.</inlineHelpText>
    <label>Estimated Minutes</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Estimated_Rate__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Rate__c</fullName>
    <description>Estimated rate that the customer will pay for this Audio Product&#39;s Minutes.</description>
    <inlineHelpText>Estimated rate that the customer will pay for this Audio Product&#39;s Minutes.</inlineHelpText>
    <label>Estimated Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Number_of_Licensed_Named_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Licensed_Named_Users__c</fullName>
    <label>Number of Licensed Named Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Subscription_License_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Subscription_License_Term_Months__c</fullName>
    <label>Subscription License Term(Months)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offerings__c/Offerings__c.object-meta.xml
<CustomObject>
    <description>High-level Product Select in iContract</description>
    <label>CPQ - Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offerings__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Agreement Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Initial Product of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audio: GlobalMeet Audio</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Audio for Skype for Business</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Hybrid Audio for Lync Server</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Hybrid Audio for WebEx</fullName>
            </value>
            <value>
                <fullName>Audio: iMeet</fullName>
            </value>
            <value>
                <fullName>Audio: iMeetLive Managed Event</fullName>
            </value>
            <value>
                <fullName>Audio: OnNet</fullName>
            </value>
            <value>
                <fullName>Audio: Op. Assisted: Premium Event</fullName>
            </value>
            <value>
                <fullName>Audio: Op. Assisted: Standard Auditorium</fullName>
            </value>
            <value>
                <fullName>Bundle: GlobalMeet</fullName>
            </value>
            <value>
                <fullName>Bundle: GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Bundle: iMeet</fullName>
            </value>
            <value>
                <fullName>Bundle: iMeet Sales Accelerator</fullName>
            </value>
            <value>
                <fullName>Bundle: iMeet VRC</fullName>
            </value>
            <value>
                <fullName>Partner: Partner BD</fullName>
            </value>
            <value>
                <fullName>Professional Services: Modality Consulting</fullName>
            </value>
            <value>
                <fullName>Professional Services: Modality  Custom Development</fullName>
            </value>
            <value>
                <fullName>Professional Services:  Modality Support &amp; Managed Services</fullName>
            </value>
            <value>
                <fullName>Video: Managed Conference</fullName>
            </value>
            <value>
                <fullName>Video: Managed Service - Device</fullName>
            </value>
            <value>
                <fullName>Video: Managed Service - Flat Rate</fullName>
            </value>
            <value>
                <fullName>Video: Professional Service</fullName>
            </value>
            <value>
                <fullName>Web: AdobeConnect</fullName>
            </value>
            <value>
                <fullName>Web: Cisco WebEx</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Active Host</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Web for Microsoft Lync</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Web: iMeet</fullName>
            </value>
            <value>
                <fullName>Web: iMeet Agenday Enterprise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/iContractLicenseSetMappingEndpoint.cls
@RestResource(urlMapping='/iContractLicenseSetMapping/*')
global with sharing class iContractLicenseSetMappingEndpoint {
    @HttpPost
    global static List<OpportunityLineItem> mapOppLicenseSetsToProducts(List<Id> opportunityIds) {
        List<OpportunityLineItem> mappedProducts = new List<OpportunityLineItem>();
        
        /* TODO UPDATE
        Map<Id, LicenseSet__c> licenseSets = new Map<Id, LicenseSet__c>([SELECT Id, Name,
                                                                         Opportunity__c, Opportunity__r.CurrencyIsoCode, Opportunity__r.Pricebook2Id,
                                                                         Enterprise_Name__c,
                                                                         Product_Name__c, Payment_Plan__c,
                                                                         Number_of_Licensed_Named_Users__c, Price__c,
                                                                         Subscription_License_Term_Months__c,
                                                                         Estimated_Minutes__c, Committed_Minutes__c,
                                                                         Committed_Rate__c, Estimated_Rate__c, Commitment_Reoccurence__c, 
                                                                         LicenseSet__c.Enterprise_Name__r.Product__c
                                                                         FROM LicenseSet__c
                                                                         WHERE Opportunity__c IN :opportunityIds]);
        
        mappedProducts.addAll(iContract.mapLicenseSetToProducts(licenseSets));
		*/
        
        // TODO: Move this loop to the function.
        // Difficulty being keeping the separately provided Opps mapped correctly
        //for (Id opportunityId : opportunityIds) {
        //    mappedProducts.addAll(iContract.mapExistingProductLineItems(opportunityId));
        //}
        
        return mappedProducts;
    }
}