force-app/main/default/objects/FoxDen_Box__c/FoxDen_Box__c.object-meta.xml
<CustomObject>
    <description>FoxDen box includes ChromeBox, Microphone/Speaker, and Camera</description>
    <label>FoxDen Box</label>
    <nameField>
        <displayFormat>FoxDenBox-{00000}</displayFormat>
        <label>FoxDen Box Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FoxDen Boxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_Box__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for the account this FoxDen Box belongs to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FoxDen Boxes</relationshipLabel>
    <relationshipName>FoxDen_Boxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Id__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Id__c</fullName>
    <description>The UUID of the beacon</description>
    <label>Beacon Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Major_Value__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Major_Value__c</fullName>
    <label>Beacon Major Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Minor_Value__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Minor_Value__c</fullName>
    <label>Beacon Minor Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Kiosk_Email__c.field-meta.xml
<CustomField>
    <fullName>Kiosk_Email__c</fullName>
    <label>Kiosk Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Kiosk Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>Kit ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT</fullName>
            </value>
            <value>
                <fullName>ANY</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,FOXDEN_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/basePackage__c.field-meta.xml
<CustomField>
    <fullName>basePackage__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignFoxDenBoxTest.cls
@isTest
private class AssignFoxDenBoxTest {
    
    private static ApexPages.StandardController controller = new ApexPages.StandardController(new FoxDen_Box__c());
    
    //AssignFoxDenBox.AssignFoxDenBox
    static testMethod void testConstruct() {
        AssignFoxDenBox b = new AssignFoxDenBox(controller);
        b.getObjectId();
        AssignFoxDenBox.getInventory();
        
        Account a = MockAccount.getNewAccount();
        
        try{
            
            // INSERT foxDenBoxRepo;
            
            AssignFoxDenBox.assignBoxes(a.Id, new List<Id>());
        }
        catch(Exception e){
            
        }
        
        System.assert(b != null);
    }    
    static testMethod void testassignBoxes() {
       Account acc = new Account();
        acc.Name = 'testAcc';
        INSERT acc;
        Package__c pkg = new Package__c();
        INSERT pkg;
        Plan__c plan = new Plan__c();
        plan.Name = 'FoxDen Connect In-Room System';
        plan.account__c = acc.Id;
        plan.billableType__c = 'ACCOUNT';
        plan.startDate__c = Date.newInstance(2019, 11, 19);
        plan.basePackage__c = pkg.Id;
        INSERT plan;
        FoxDen_Box__c testFoxDen = new FoxDen_Box__c();
       testFoxDen.Beacon_Minor_Value__c	 = 3;
        testFoxDen.Beacon_Id__c = 'test';
        testFoxDen.Beacon_Major_Value__c = 7;
        testFoxDen.Kiosk_Email__c = 'vijay@raagvitech.com';
        testFoxDen.Password__c = 'testPass';
        testFoxDen.sku__c = 'testUniqueKey';
        INSERT testFoxDen;
        list<FoxDen_Box__c> foxDenBoxRepo = new list<FoxDen_Box__c>(); 
        foxDenBoxRepo.add(testFoxDen);
        
        
        FoxDenBox foxDenBoxRepotest = new FoxDenBox();
        List<Id> FoxIds = new List<Id>();
        for(FoxDen_Box__c box : foxDenBoxRepo){
            FoxIds.add(box.Id); 
        } 
        AssignFoxDenBox.assignBoxes(acc.Id,FoxIds);
        FoxDen_Box__c FBox = [SELECT Id,Account__c FROM FoxDen_Box__c WHERE Id =: testFoxDen.Id];
        System.assertEquals(FBox.Account__c,acc.Id);
   
    }
}