force-app/main/default/objects/Campaign/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <description>This field represents the partner campaign source for list pulls, etc.</description>
    <label>Partner</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3VL</fullName>
            </value>
            <value>
                <fullName>Acteva</fullName>
            </value>
            <value>
                <fullName>akaCRM</fullName>
            </value>
            <value>
                <fullName>AMA</fullName>
            </value>
            <value>
                <fullName>Annuitas</fullName>
            </value>
            <value>
                <fullName>Astadia</fullName>
            </value>
            <value>
                <fullName>Bluewolf</fullName>
            </value>
            <value>
                <fullName>BMA</fullName>
            </value>
            <value>
                <fullName>Card Browser</fullName>
            </value>
            <value>
                <fullName>Couch</fullName>
            </value>
            <value>
                <fullName>CTA</fullName>
            </value>
            <value>
                <fullName>Denver/Boulder Software Club</fullName>
            </value>
            <value>
                <fullName>Denver Chamber</fullName>
            </value>
            <value>
                <fullName>Downtown Denver Partnership</fullName>
            </value>
            <value>
                <fullName>Eloqua</fullName>
            </value>
            <value>
                <fullName>ExactTarget</fullName>
            </value>
            <value>
                <fullName>Frost &amp; Sullivan</fullName>
            </value>
            <value>
                <fullName>HubSpot</fullName>
            </value>
            <value>
                <fullName>Kapost</fullName>
            </value>
            <value>
                <fullName>Marketo</fullName>
            </value>
            <value>
                <fullName>MecLabs</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>NCNA</fullName>
            </value>
            <value>
                <fullName>NetProspex</fullName>
            </value>
            <value>
                <fullName>Networld Alliance</fullName>
            </value>
            <value>
                <fullName>OneSource</fullName>
            </value>
            <value>
                <fullName>Pardot</fullName>
            </value>
            <value>
                <fullName>PRNewswire</fullName>
            </value>
            <value>
                <fullName>ReachForce</fullName>
            </value>
            <value>
                <fullName>Salesforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>Suspects</fullName>
            </value>
            <value>
                <fullName>Prospects</fullName>
            </value>
            <value>
                <fullName>Subscribers</fullName>
            </value>
            <value>
                <fullName>Customers</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMonthlyGeneratorSchedulable.cls
public class CampaignMonthlyGeneratorSchedulable implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
	Set<Id> contactRecordTypeIds = ReadyTalkRecordTypeHelper.readyTalkContactRecordTypeIds;
	String query = 'SELECT Id FROM Contact WHERE CreatedDate >=: startDate AND CreatedDate <=: endDate AND RecordTypeId IN:contactRecordTypeIds ';
	
	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	public void execute(Database.BatchableContext BC, List<Contact> scope) {
		//pull back existing campaign members
		Set<Id> existingContactsInCampaign = new Set<Id>();
		for(CampaignMember cm: [SELECT Id, ContactId, CampaignId 
														FROM CampaignMember
														WHERE CampaignId =: associatedCampaign.Id
														AND ContactId IN: scope]) {
			existingContactsInCampaign.add(cm.Id);
		}
		List<CampaignMember> campaignMembersToCreate = new List<CampaignMember>();
		for(Contact c: scope) {
			if(!existingContactsInCampaign.contains(c.Id)) {
				campaignMembersToCreate.add(new CampaignMember(
					ContactId = c.Id,
					CampaignId = associatedCampaign.Id
				));
			}
		}
		Database.insert(campaignMembersToCreate, false);
	}
	
	public void finish(Database.BatchableContext BC) {
		
	}
   	public void execute(SchedulableContext sc) {
   		CampaignMonthlyGeneratorSchedulable batchJob = new CampaignMonthlyGeneratorSchedulable();
   		Database.executeBatch(batchJob);
	}
	public Date startDate {get{
		if(startDate == null) {
			startDate = PGI_Utility.startOfMonth(System.today().addMonths(-1));
		}
		return startDate;
	} set;}

	public Date endDate {get {
		return PGI_Utility.endOfMonth(startDate);
	}}

	private Campaign associatedCampaign {get {
		if(associatedCampaign == null) {
			String searchString = campaignName + '%';
			List<Campaign> campaignList = [SELECT Id FROM Campaign WHERE Name LIKE: searchString];
			if(campaignList.size() > 0) {
				associatedCampaign = campaignList[0];
			} else {
				associatedCampaign = generateNewCampaign();
			}
		}
		return associatedCampaign;
	} set;}

	public String campaignName {get {
		DateTime dt = DateTime.newInstance(startDate.year(),startDate.month(),startDate.day()); 
		return 'New User Follow-up ' + dt.format('MMMM yyyy');
	}} 

	//generate a new campaign for the month
	public Campaign generateNewCampaign() {
		Campaign newCampaign = new Campaign();
		newCampaign.StartDate = PGI_Utility.startOfNextMonth(startDate);
		newCampaign.EndDate = PGI_Utility.endOfMonth(startDate.addMonths(1));
		newCampaign.IsActive = true;
		newCampaign.Status = 'In Progress';
		newCampaign.Type = 'Other';
		newCampaign.Partner__c = 'N/A';
		newCampaign.Name = campaignName + ' | Subscribers';
		newCampaign.CampaignMemberRecordTypeId = ReadyTalkRecordTypeHelper.readyTalkCampaignMemberRecordTypes[0].Id;
		newCampaign.Target__c = 'Prospects';
		newCampaign.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkCampaignRecordTypes[0].Id;
		insert newCampaign;
		return newCampaign;
	}
}