force-app/main/default/objects/Case/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Agent working the case.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ServiceNow_Change_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignToMeLEXController.cls
public class AssignToMeLEXController {
    
    @AuraEnabled
    public static void updateRecord(String recordId, String objectName){
        
        // Case: AssignToMe QuickAction 
        if(objectName == 'Case'){
            Case caseObj = [SELECT Id, Assigned_To__c FROM Case WHERE Id =:recordId];
            caseObj.Assigned_To__c =userinfo.getuserid();
            UPDATE caseObj;
        }
        // Financial Request: AssignToMe QuickAction 
        else if(objectName == 'Financial_Request__c'){
            Financial_Request__c finReqObj = [SELECT Id, Assigned_To__c FROM Financial_Request__c WHERE Id =:recordId];
            finReqObj.Assigned_To__c =userinfo.getuserid();
            UPDATE finReqObj; 
        }
        // Request for Change: AssignToMe QuickAction 
        else if(objectName == 'Request_for_Change__c'){
            Request_for_Change__c objRFC = [SELECT Id, Assigned_To__c FROM Request_for_Change__c WHERE Id =:recordId];
            objRFC.Assigned_To__c =userinfo.getuserid();
            UPDATE objRFC; 
        }
    }
}