force-app/main/default/objects/Case/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Agent working the case.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resolve_Color_Field__c.field-meta.xml
<CustomField>
    <fullName>Resolve_Color_Field__c</fullName>
    <formula>IF(IsClosed || TEXT(Status) = &apos;Pending Client Info/Action&apos;, IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQT9&quot;, &quot;Grey&quot;),
			IF(((Scheduled_Resolve_Time__c - NOW()) * 24)  / Hours_to_Resolve_SLA__c &lt;= 0,IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQTB&quot;, &quot;Red&quot;),
IF(((Scheduled_Resolve_Time__c - NOW()) * 24) / Hours_to_Resolve_SLA__c &gt; 0.50,IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQT8&quot;, &quot;Green&quot;),
IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQTA&quot;, &quot;Yellow&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resolve Color Field</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Restore_Color_Field__c.field-meta.xml
<CustomField>
    <fullName>Restore_Color_Field__c</fullName>
    <formula>IF(TEXT(Status) = &#39;Pending Client Info/Action&#39; || Restore_Pause_Time__c &lt;&gt; &quot;&quot;, IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQT9&quot;, &quot;Grey&quot;),			
			IF(((Scheduled_Restore_Time__c - NOW()) * 24)  / Hours_to_Restore_SLA__c &lt;= 0,IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQTB&quot;, &quot;Red&quot;),
IF(((Scheduled_Restore_Time__c - NOW()) * 24) / Hours_to_Restore_SLA__c &gt; 0.50,IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQT8&quot;, &quot;Green&quot;),
IMAGE(&quot;/servlet/servlet.FileDownload?file=0151B000002xQTA&quot;, &quot;Yellow&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Restore Color Field</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_to_Resolve__c.field-meta.xml
<CustomField>
    <fullName>Time_to_Resolve__c</fullName>
    <formula>IF(NOT(ISBLANK(Resolve_Pause_Time__c)), Resolve_Pause_Time__c, 
        (           
   if(Scheduled_Resolve_Time__c - NOW() &lt; 0, &quot;-&quot;, &quot;&quot;) +
            /* hours */
            TEXT(
                ABS(FLOOR((Scheduled_Resolve_Time__c - NOW()) * 24))
            ) +
            &quot;:&quot; +
												IF(ABS(FLOOR(MOD((Scheduled_Resolve_Time__c - NOW())*1440*6,360) / 6)) &lt; 10, &quot;0&quot;, &quot;&quot;) +
            /* minutes */
            TEXT(
																ABS(FLOOR(MOD((Scheduled_Resolve_Time__c - NOW())*1440*6,360) / 6))
            )
        )
)
/*IF(NOT(ISBLANK(Resolve_Pause_Time__c)), Resolve_Pause_Time__c, IF(
    ISBLANK(ClosedDate),
        (           
   if(Scheduled_Resolve_Time__c - NOW() &lt; 0, &quot;-&quot;, &quot;&quot;) +

            TEXT(
                ABS(FLOOR((Scheduled_Resolve_Time__c - NOW()) * 24))
            ) +
            &quot;:&quot; +

            TEXT(
																ABS(FLOOR(MOD((Scheduled_Resolve_Time__c - NOW())*1440*6,360) / 6))
            )
        ),
        (
                        if(ClosedDate - NOW() &lt; 0, &quot;-&quot;, &quot;&quot;) +

            TEXT(
                ABS(FLOOR((ClosedDate - NOW()) * 24))
            ) +
            &quot;:&quot; +

            TEXT(
                ABS(FLOOR(MOD((ClosedDate - NOW())*1440*6,360) / 6))
            )
        )
))*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time to Resolve</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Time_to_Restore__c.field-meta.xml
<CustomField>
    <fullName>Time_to_Restore__c</fullName>
    <formula>/*IF(NOT(ISBLANK(Scheduled_Restore_Time__c)), IF(NOT(ISBLANK(Restore_Pause_Time__c)), Restore_Pause_Time__c, if(Restored_or_Scheduled_Restore__c - NOW() &lt; 0, &quot;-&quot;, &quot;&quot;) +
            / hours /
            TEXT(
                ABS(FLOOR((Restored_or_Scheduled_Restore__c - NOW()) * 24))
            ) +
            &quot;:&quot; +
            / minutes /
            TEXT(
				ABS(FLOOR(MOD((Restored_or_Scheduled_Restore__c - NOW())*1440*6,360) / 6)) 
            )), &#39;:&#39;)*/
												
												IF(NOT(ISBLANK(Scheduled_Restore_Time__c)), IF(NOT(ISBLANK(Restore_Pause_Time__c)), Restore_Pause_Time__c, if(Scheduled_Restore_Time__c - NOW() &lt; 0, &quot;-&quot;, &quot;&quot;) +
																																																											/* hours */
																																																											TEXT(
																																																															ABS(FLOOR((Scheduled_Restore_Time__c - NOW()) * 24))
																																																											) +
																																																											&quot;:&quot; +
																																																											/* minutes */
																																																											IF(ABS(FLOOR(MOD((Scheduled_Restore_Time__c - NOW())*1440*6,360) / 6)) &lt; 10, &quot;0&quot;, &quot;&quot;) +
																																																											TEXT(
																																																															ABS(FLOOR(MOD((Scheduled_Restore_Time__c - NOW())*1440*6,360) / 6)) 
																																																											)), &#39;:&#39;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time to Restore</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseListView.cls
public with sharing class CaseListView {
	

	public CaseListView() {
		if(ApexPages.currentPage().getParameters().get('queueId') != null) {
			queueId = (Id)ApexPages.currentPage().getParameters().get('queueId');
		}
		changeOwnerLookup = new Case();
	}
	public CaseListView(CaseCountdownTimer controller) {
		if(ApexPages.currentPage().getParameters().get('queueId') != null) {
			queueId = (Id)ApexPages.currentPage().getParameters().get('queueId');
		}
		changeOwnerLookup = new Case();
	}
	public PageReference doNothing() {
		return null;

	}
	public PageReference addParams(PageReference pr) {
		pr.getParameters().put('queueId', queueId);
		return pr;
	}
	public boolean displayPopup {get; set;}     
    
    public void closePopup() {        
        displayPopup = false;    
    }     
    public void showPopup() {        
        displayPopup = true;    
    }
	public transient List<Case> caseList {get {
		List<Case> cases = new List<Case>();
		if(queueId != null) {
			Map<String, Schema.FieldSet> caseFieldSetMap = Schema.sObjectType.Case.FieldSets.getMap();
			Set<String> caseListViewFields = new Set<String>();
			for(FieldSetMember field : caseFieldSetMap.get('PGi_Working_Views').getFields()) {
	            caseListViewFields.add(field.getFieldPath().toLowerCase());
	        }
	        caseListViewFields.addAll(new Set<String>{'time_to_restore__c', 'restore_color_field__c', 'time_to_resolve__c', 'resolve_color_field__c'});
	        String caseListViewQuery = 'SELECT ';
	        for(String field : caseListViewFields) {
	            caseListViewQuery += field + ',';
	        }
	        caseListViewQuery = caseListViewQuery.removeEnd(',');
	        caseListViewQuery += ' FROM Case WHERE IsClosed = false AND OwnerId = :queueId LIMIT 500';
	        cases = Database.query(caseListViewQuery);
	    }
	    return cases;
        
	} set;}

	

	public Id queueId {get; set;}

	public PageReference refresh(){
		return addParams(new PageReference('/apex/CaseListView').setRedirect(true));
	}

	public PageReference addQueue(){
		return addParams(new PageReference('/apex/CaseListView').setRedirect(true));
	}

	public List<Group> caseQueues {get {
		if(caseQueues == null) {
			caseQueues = [SELECT Id, Name FROM Group WHERE Type = 'Queue' AND Id IN (SELECT QueueId FROM QueueSObject WHERE SObjectType = 'Case') ORDER BY Name];
			
		}
		return caseQueues;
	} set;}

	public List<SelectOption> caseQueuesSelectionOptions { get {
		if(caseQueuesSelectionOptions == null) {
			caseQueuesSelectionOptions = new List<SelectOption>();
			for(Group q: caseQueues) {
				caseQueuesSelectionOptions.add(new SelectOption(q.Id, q.Name));
			}
		}
		return caseQueuesSelectionOptions;
	} set;}


	public List<CaseWrapper> caseWrapperList {get {
		
		if(caseWrapperList == null) {
			System.debug('constructing new list');
			caseWrapperList = new List<CaseWrapper>();
			for(Case c: caseList) {
				caseWrapperList.add(new CaseWrapper(c));
			}
		} 
		for(Case c: caseList) {
			Boolean hasCase = false;
			for(CaseWrapper cw: caseWrapperList) {
				if(cw.c.Id == c.Id) {
					System.debug('Found Match' + cw.selected);
					cw.c = c;
					hasCase = true;
					break;
				}
			}
			if(!hasCase) {
				System.debug('generating new case');
				caseWrapperList.add(new CaseWrapper(c));
			}
		}

		return caseWrapperList;
	} set;} 

	public Boolean showChangeOwner {get; set;}
	public PageReference changeOwner(){
		showChangeOwner = true;
		return null;
	}
	public Boolean notifyOwner {get; set;}
	public Case changeOwnerLookup {get; set;}
	public PageReference saveChangeOwner() {
		displayPopup = false;
		List<Case> updateCases = new List<Case>();
		for(CaseWrapper cw : caseWrapperList) {
			if(cw.selected != null && cw.selected == true) {
				updateCases.add(new Case(Id = cw.c.Id, OwnerId = changeOwnerLookup.OwnerId));
			}
		}
		if(!updateCases.isEmpty()) {
			Database.DMLOptions options = new Database.DMLOptions();
			options.EmailHeader.triggerUserEmail = true;
			options.optAllOrNone = true;
			//update updateCases;
			try {
				Boolean error = false;
				List<Database.SaveResult> srList = Database.update(updateCases, options);
				for(Database.SaveResult sr: srList) {
					if(!sr.isSuccess()) {
						ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to reassign owner.' + sr.getErrors()));
						error = true;
					}
				}
				if(error == true) {
					return null;
				}
			} catch (Exception e) {
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to reassign owner.' + e.getMessage()));
				return null;
			}
		}
		return addParams(new PageReference('/apex/CaseListView').setRedirect(true));
	}

	public PageReference assignToMe() {
		List<Case> updateCases = new List<Case>();
		for(CaseWrapper cw : caseWrapperList) {
			if(cw.selected != null && cw.selected == true) {
				updateCases.add(new Case(Id = cw.c.Id, Assigned_To__c = UserInfo.getUserId()));
			}
		}
		if(!updateCases.isEmpty()) {
			update updateCases;
		}
		return addParams(new PageReference('/apex/CaseListView').setRedirect(true));
	}
	
	//used for change owner
	public Case cse {get; set;}
	//used for change owner
	public Boolean sendNotification {get; set;}
	public class CaseWrapper {
		public Boolean selected {get; set;}
		public Case c {get; set;}
		public CaseWrapper(Case c) {
			this.c = c;
		}
	}
}