force-app/main/default/objects/Case/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Agent working the case.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FinReqSoftDeleteButtonController.cls
public with sharing class FinReqSoftDeleteButtonController {
    public String finReqId {get; set;}
    public FinReqSoftDeleteButtonController() {
        if (System.currentPageReference().getParameters().get('finReqId') != null){
            finReqId = System.currentPageReference().getParameters().get('finReqId');
        }        
    }
    public PageReference assignItToQueue(){
        
        String queueId = [SELECT Id FROM Group WHERE Type ='Queue' AND DeveloperName = 'Junk_Spam_Placeholder' Limit 1].Id;
        //if(queueId == nu)
        Financial_Request__c objFinReq = [SELECT Id, OwnerId, Assigned_To__c FROM Financial_Request__c WHERE Id =: finReqId Limit 1];
        objFinReq.OwnerId = queueId;
        objFinReq.Assigned_To__c = null; 
        UPDATE objFinReq;
        String UITheme  = UserInfo.getUiThemeDisplayed();
        String navigationURL = '';
        if(UITheme == 'Theme4d' || UITheme == 'Theme4t' || UITheme == 'Theme4u'){
            navigationURL = '/lightning/r/Case/'+objFinReq.Id+'/view';
        }else{
            navigationURL = '/'+objFinReq.Id;
        }
        PageReference pageRef = new PageReference(navigationURL);
        pageRef.setRedirect(true);
        return pageRef;
    }
}