force-app/main/default/objects/Case/fields/Bill_To_Client__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>Bill To Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases (Bill To Client)</relationshipLabel>
    <relationshipName>Cases_of_Bill_To</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Bill_To_Client__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>Bill To Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Bill To Client)</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Associated Client)</relationshipLabel>
    <relationshipName>Financial_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Error</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error-InterCall</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error-Level 3</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error-PGi</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure-InterCall</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure-Level 3</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure-PGi</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Service-GX Outage</fullName>
            </value>
            <value>
                <fullName>Service-InterCall Outage</fullName>
            </value>
            <value>
                <fullName>Service-PGi Outage</fullName>
            </value>
            <value>
                <fullName>Service-RT Outage</fullName>
            </value>
            <value>
                <fullName>Setup Error-RT</fullName>
            </value>
            <value>
                <fullName>Subscription Frequency Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Feedback</fullName>
            </value>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Billing Actions Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Not Needed</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Customer Replied</fullName>
            </value>
            <value>
                <fullName>Customer UAT</fullName>
            </value>
            <value>
                <fullName>Delayed Release</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Manual Release - Prod</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New - Transferred</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Pending Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Reactivated</fullName>
            </value>
            <value>
                <fullName>Ready for Demo</fullName>
            </value>
            <value>
                <fullName>Ready for Release</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Amendment Request</fullName>
            </value>
            <value>
                <fullName>Billing Cycle Change</fullName>
            </value>
            <value>
                <fullName>Billing External Report</fullName>
            </value>
            <value>
                <fullName>Billing Internal Report</fullName>
            </value>
            <value>
                <fullName>Billing Method Change</fullName>
            </value>
            <value>
                <fullName>Bill To Change</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Company Cancellation</fullName>
            </value>
            <value>
                <fullName>Company Inactivation</fullName>
            </value>
            <value>
                <fullName>Contact Information Change</fullName>
            </value>
            <value>
                <fullName>Contract: Manual Edit Request</fullName>
            </value>
            <value>
                <fullName>Contract/Pricing</fullName>
            </value>
            <value>
                <fullName>Copy of Outstanding Invoice</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Email Support</fullName>
            </value>
            <value>
                <fullName>End Date Shortfall and/or Commitment</fullName>
            </value>
            <value>
                <fullName>General Question/Feedback</fullName>
            </value>
            <value>
                <fullName>Help with Reporting</fullName>
            </value>
            <value>
                <fullName>I Want Something New</fullName>
            </value>
            <value>
                <fullName>Licenses (New Acct)</fullName>
            </value>
            <value>
                <fullName>Licenses (w/ an Existing Acct)</fullName>
            </value>
            <value>
                <fullName>Login/Permission</fullName>
            </value>
            <value>
                <fullName>MOM Corrections</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Company Setup Complete</fullName>
            </value>
            <value>
                <fullName>One-Time Manual Charge</fullName>
            </value>
            <value>
                <fullName>Online Billing Center</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CAB Approved</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <color>#0B6FCE</color>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Urgent</fullName>
                <color>#78C953</color>
                <label>Urgent</label>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <color>#E27001</color>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Vendor</fullName>
                <color>#A845DC</color>
                <label>Vendor</label>
            </value>
            <value>
                <fullName>Release</fullName>
                <color>#F3D904</color>
                <label>Release</label>
            </value>
            <value>
                <fullName>Unauthorized</fullName>
                <color>#A53711</color>
                <label>Unauthorized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignToMeDetailControllerTest.cls
@isTest
public class AssignToMeDetailControllerTest {
    
    static testmethod void testupdateRecord(){
        Case c = new Case();
        C.Status = 'New';
        C.Origin = 'Phone';
        insert c;
        
        PGi_Client__c pgiClientObj=new PGi_Client__c();
        pgiClientObj.Client_ID__c='PGITest12';
        insert pgiClientObj;
        
        Financial_Request__c FinReqObj=new Financial_Request__c();
        FinReqObj.Status__c='New';
        FinReqObj.Type__c='Other';
        FinReqObj.Reason__c='NA';
        FinReqObj.Bill_To_Client__c=pgiClientObj.Id;
        insert FinReqObj;
        
        Request_for_Change__c objRFC=new Request_for_Change__c();
        objRFC.Assignment_Group__c='PGi-RFC-GL-Audio Projects';
        objRFC.Type__c='Normal';
        objRFC.Risk__c='Low';
        objRFC.Planned_Start_Date_Time__c=System.today();
        objRFC.Planned_End_Date_Time__c=System.today().addDays(2);
        insert objRFC;
        
        AssignToMeDetailController.updateRecord(FinReqObj.Id);
        AssignToMeDetailController.updateRecord(c.Id);
        AssignToMeDetailController.updateRecord(objRFC.Id);
        
        System.assertEquals('Other', FinReqObj.Type__c);
    }
    
}