force-app/main/default/objects/Case/fields/Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>Caller_Name__c</fullName>
    <label>Caller Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Email_address__c.field-meta.xml
<CustomField>
    <fullName>Email_address__c</fullName>
    <inlineHelpText>Ex: list@pgi.com</inlineHelpText>
    <label>Email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated__c.field-meta.xml
<CustomField>
    <fullName>Escalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Escalates Case (sends email to owner and assigned to user)</description>
    <label>User Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_Up_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Email_Address__c</fullName>
    <inlineHelpText>Separate additional email addresses with a comma.</inlineHelpText>
    <label>Follow-Up Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Company ID.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Lync/IM</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>PGi Contract</fullName>
            </value>
            <value>
                <fullName>PGi Service Catalog</fullName>
            </value>
            <value>
                <fullName>SvcNow</fullName>
            </value>
            <value>
                <fullName>PIDR</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Associated Client)</relationshipLabel>
    <relationshipName>Financial_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/SuppliedEmail__c.field-meta.xml
<CustomField>
    <fullName>SuppliedEmail__c</fullName>
    <label>Web Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EscalateEmailCaseController.cls
/*********************************************************************
Name : EscalateEmailCase
Created On : Oct 10, 2019
Created By : Anup
Description :  
**********************************************************************/
public class EscalateEmailCaseController {

	// public String currentRecordId {get;set;}
 
    // public EscalateEmailCaseController(ApexPages.StandardController controller) {
    //     currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
    // }
	// public Case record;

	// public EscalateEmailCaseController(ApexPages.StandardController sc) {
	// 	this.record = (Case)sc.getRecord();
	// }
	// public Case caseDetailsRecord {get; set;}
	// public PageReference init(){
	// 	caseDetailsRecord = [SELECT Id, Escalated__c, PGi_Client__c, PGi_Company__c FROM Case WHERE Id =: record.Id];
	// 	system.debug('==>'+caseDetailsRecord);
	// 	// if(this.record.Escalated__c == false) {
	// 	// 	//this.record.Escalated__c = true;
	// 	// 	try {
	// 	// 		update record;
	// 	// 		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Your case was successfully escalated.'));
	// 	// 	} catch (exception e) {
	// 	// 		ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Failed to escalate case. ' + e.getMessage()));
	// 	// 	}
	// 	// } else {
	// 	// 	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'This case has already been escalated.'));
	// 	// }
	// 	 return null;
	// }
	@AuraEnabled
	public static Case getCaseRecord(String recordId){
		return [SELECT Id, IsEscalated, PGi_Client__c, PGi_Company__c, Caller_Name__c, Origin, Subject, Status FROM Case WHERE Id =: recordId];
	}
	@AuraEnabled
	public static Boolean getIsEscalated(String recordId){
		// system.debug('====>'+recTypeName);
		// String recName = '%'+recTypeName+'%';
		// String query = 'SELECT Id, Name FROM RecordType WHERE name LIKE \'PGi-' + recTypeName + '\' and SobjectType =\''+ObjectName+'\'';
		// system.debug('query==>'+query);
		// 	system.debug('=query=====>'+Database.query(query));
		//  system.debug('====aaaa=='+[SELECT Id FROM RecordType WHERE name LIKE :('PGi-' + recTypeName + '') and SobjectType =: ObjectName]);
		//system.debug('-[SELECT Id FROM RecordType WHERE name LIKE'+ '%recTypeName%'+'and SobjectType=Case]->'+[SELECT Id FROM RecordType WHERE name LIKE recName and SobjectType ='Case']);
		return [SELECT Escalated__c FROM Case where id=:recordId].Escalated__c;
	}
	@AuraEnabled
	public static Id createCase(String recordId, Id recTypeId){
		List<String> fields = new List<String>(Case.SObjectType.getDescribe().fields.getMap().keySet());
		String soql = ''
       			 + ' select ' + String.join(fields, ',')
       			 + ' from Case '
				 + ' WHERE Id =: recordId ';
		Case caseRecord = Database.query(soql);	
				System.debug('===>'+caseRecord);
		Case escalatedRecord = caseRecord.clone();
		escalatedRecord.RecordTypeId = recTypeId;
		escalatedRecord.IsEscalated = true;
		Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;
            escalatedRecord.setOptions(dmo);
		INSERT escalatedRecord;
		system.debug('cloned=>'+escalatedRecord);
		return escalatedRecord.Id;
	}
	/**
	get current recordId , “Escalation Type” picklist of “Case” or “Financial Request” and dependent values.
	 */
	@AuraEnabled
	public static String createEscalationRecord(String recordId, String escalationType, String escalationRecordType ){

		Id recordTypeId = [SELECT Id FROM RecordType WHERE name LIKE :('%' + escalationRecordType + '%') and SobjectType =: escalationType limit 1].Id;
		Case currentCase = [SELECT ID, PGi_Client__c, Escalated__c,Email_address__c, PGi_Company__c, Subject, Caller_Name__c, ParentId, Follow_Up_Email_Address__c  
							FROM Case 
							WHERE Id =: recordId];
		String returnId ='';
		if(escalationType == 'Case'){
			Case escalatedCase = new Case(Origin = 'Email', 
									recordTypeId = recordTypeId,
									PGi_Client__c = currentCase.PGi_Client__c,
									PGi_Company__c = currentCase.PGi_Company__c,
									Follow_Up_Email_Address__c = currentCase.Email_address__c,
									Subject = currentCase.Subject,
									Caller_Name__c = currentCase.Caller_Name__c);
			INSERT escalatedCase;
			currentCase.ParentId = escalatedCase.Id;
			currentCase.Escalated__c = true;
			UPDATE currentCase;
			returnId = escalatedCase.Id;
		}else{
			
			Financial_Request__c finReq = new Financial_Request__c(
									recordTypeId = recordTypeId,
									PGi_Client__c = currentCase.PGi_Client__c,
									PGi_Company__c = currentCase.PGi_Company__c,
									SuppliedEmail__c = currentCase.Email_address__c, 
									Subject__c = currentCase.Subject,
									Origin__c = 'Email',
									Related_Case__c = currentCase.Id);			
			INSERT finReq;
			currentCase.Escalated__c = true;
			UPDATE currentCase;
			returnId = finReq.Id;
		}
		return returnId;
	}
}