force-app/main/default/objects/Case/fields/Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>Caller_Name__c</fullName>
    <label>Caller Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated__c.field-meta.xml
<CustomField>
    <fullName>Escalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Escalates Case (sends email to owner and assigned to user)</description>
    <label>User Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EscalateCaseControllerTest.cls
@isTest
public class EscalateCaseControllerTest {
    @testSetup static void setup() {
        Case caseRecord = new Case(Escalated__c = false,
                                   Caller_Name__c = 'Test1',
                                   Origin = 'Email',
                                   Status = 'New'
                                  );
        INSERT caseRecord;
        ApexPages.StandardController sc = new ApexPages.StandardController(caseRecord);
    }
    @istest
    static  void escalateCaseTest1(){
        
        Case caseRecord =[Select Id, Escalated__c 
                            From Case 
                            Where Escalated__c = false AND Origin='Email' Limit 1];
        EscalateCaseController escalateCase = new EscalateCaseController(new ApexPages.StandardController (caseRecord));
        escalateCase.selectedEscalationType ='Case';
        escalateCase.selectedEscalationRecordType = 'PGi-Client External Support';
        escalateCase.currentRecordId = caseRecord.Id;
        escalateCase.init();
        escalateCase.getEscalationType();
        escalateCase.handleRecord();
        escalateCase.getEscalationRecordType();
        escalateCase.handleRecordButton();
        case newEscalatedCase = [Select Id,ParentId From Case where id =: caseRecord.Id];
        system.assertEquals(escalateCase.returnId, newEscalatedCase.ParentId);
    }
     @istest
    static  void escalateCaseTest2(){
        Case caseRecord =[Select Id, Escalated__c 
                            From Case 
                            Where Escalated__c = false AND Origin='Email' Limit 1];
        EscalateCaseController escalateCase = new EscalateCaseController(new ApexPages.StandardController (caseRecord));
        escalateCase.selectedEscalationType ='Financial_Request__c';
        escalateCase.selectedEscalationRecordType = 'PGi-Credit Request';
        escalateCase.currentRecordId = caseRecord.Id;
        escalateCase.init();
        escalateCase.getEscalationType();
        escalateCase.handleRecord();
        escalateCase.getEscalationRecordType();
        escalateCase.handleRecordButton();
        Financial_Request__c newEscalatedFinReq = [Select Id, Related_Case__c From Financial_Request__c where Id=:escalateCase.returnId];
        system.assertEquals(newEscalatedFinReq.Related_Case__c , caseRecord.Id);
    }
}