force-app/main/default/objects/Case/fields/Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>Caller_Name__c</fullName>
    <label>Caller Name</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Escalated__c.field-meta.xml
<CustomField>
    <fullName>Escalated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Escalates Case (sends email to owner and assigned to user)</description>
    <label>User Escalated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_Up_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Email_Address__c</fullName>
    <inlineHelpText>Separate additional email addresses with a comma.</inlineHelpText>
    <label>Follow-Up Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Company ID.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Lync/IM</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>PGi Contract</fullName>
            </value>
            <value>
                <fullName>PGi Service Catalog</fullName>
            </value>
            <value>
                <fullName>SvcNow</fullName>
            </value>
            <value>
                <fullName>PIDR</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Associated Client)</relationshipLabel>
    <relationshipName>Financial_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/SuppliedEmail__c.field-meta.xml
<CustomField>
    <fullName>SuppliedEmail__c</fullName>
    <label>Web Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EscalateCaseController.cls
/* Class Name : EscalateCaseController
 * Developer  : Anup
 * Ticket     : RT-293
 */
public class EscalateCaseController {
    public  String selectedEscalationType {get; set;}
    public  String selectedEscalationRecordType {get; set;}
    public  Boolean isContinue{get; set;}
    public  string currentRecordId {get; set;}
    public  Boolean isEscalated{get; set;}
    public  String returnId {get;set;}
    /* Method Name : EscalateCaseController
    *  Description : Constructor method to initialise the fields
    */
    public EscalateCaseController(ApexPages.StandardController controller) {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        isContinue = true;
        selectedEscalationType ='';
        selectedEscalationRecordType='';
    }
    /* Method Name : init
    *  Description : This method will be called when the vf page loads
    */
    public  void init(){
        isEscalated = [SELECT Escalated__c FROM Case where id=:currentRecordId].Escalated__c;
        if(isEscalated) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'This Email has already been escalated, please view the Parent Case or related FinReq for further actions.'));
        }
    }
    /* Method Name : getEscalationType
    *  Description : Assigning Escalation type to the select box
    */
    public  List<SelectOption> getEscalationType() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--None--'));
        options.add(new SelectOption('Case','Case'));
        options.add(new SelectOption('Financial_Request__c','FinReq'));
        return options;
    }
    /* Method Name : handleRecordButton
    *  Description : 
    */
    public  void handleRecordButton(){
        isContinue = false;
    }
    /* Method Name : handleRecord
    *  Description : The record will be created based on the selected escalation type and record type
    */
    public  void handleRecord(){
        System.debug('Id->'+currentRecordId);
        isContinue = true;
        Id recordTypeId = [SELECT Id FROM RecordType WHERE name LIKE :('%' + selectedEscalationRecordType + '%') and SobjectType =: selectedEscalationType limit 1].Id;
        Case currentCase = [SELECT ID, PGi_Client__c, Escalated__c,SuppliedEmail, PGi_Company__c, Subject, Caller_Name__c, ParentId, Follow_Up_Email_Address__c  
                            FROM Case 
                            WHERE Id =: currentRecordId];
        if(selectedEscalationType == 'Case'){
            Case escalatedCase = new Case(Origin = 'Email', 
                                    recordTypeId = recordTypeId,
                                    PGi_Client__c = currentCase.PGi_Client__c,
                                    PGi_Company__c = currentCase.PGi_Company__c,
                                    Follow_Up_Email_Address__c = currentCase.SuppliedEmail,
                                    Subject = currentCase.Subject,
                                    Caller_Name__c = currentCase.Caller_Name__c);
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule = true;
            escalatedCase.setOptions(dmo);
            INSERT escalatedCase;
            currentCase.ParentId = escalatedCase.Id;
            currentCase.Escalated__c = true;
            UPDATE currentCase;
            returnId = escalatedCase.Id;
        }else{
            
            Financial_Request__c finReq = new Financial_Request__c(
                                    recordTypeId = recordTypeId,
                                    PGi_Client__c = currentCase.PGi_Client__c,
                                    PGi_Company__c = currentCase.PGi_Company__c,
                                    SuppliedEmail__c = currentCase.SuppliedEmail, 
                                    Subject__c = currentCase.Subject,
                                    Origin__c = 'Email',
                                    Related_Case__c = currentCase.Id);          
            INSERT finReq;
            currentCase.Escalated__c = true;
            UPDATE currentCase;
            returnId = finReq.Id;
        }
    }
    /* Method Name : getEscalationRecordType
    *  Description : Assigning Escalation record type to the select box
    */
    public  List<SelectOption> getEscalationRecordType() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--None--'));
        if(selectedEscalationType!='null' && selectedEscalationType != '' && selectedEscalationType != 'undefined'){
            if(selectedEscalationType == 'Case'){
                options.add(new SelectOption('Internal Support','Internal Support'));
                options.add(new SelectOption('Client External Support','Client External Support'));
                options.add(new SelectOption('Reservations Request','Reservations Request'));
                options.add(new SelectOption('Parent Ticket (NOC)','Parent Ticket (NOC)'));
                return options;
            }
            else if(selectedEscalationType == 'Financial_Request__c'){
                options.add(new SelectOption('Billing Support','Billing Support'));
                options.add(new SelectOption('Company Credit','Company Credit'));
                options.add(new SelectOption('Payment Research Request','Payment Research Request'));
                options.add(new SelectOption('Credit Request','Credit Request'));
                options.add(new SelectOption('Pricing Help Request','Pricing Help Request'));
                options.add(new SelectOption('Profile Request','Profile Request'));
                options.add(new SelectOption('Rate Entry Request','Rate Entry Request'));
                options.add(new SelectOption('Request for Adjustment','Request for Adjustment'));
                options.add(new SelectOption('Revenue Assurance Audit Request','Revenue Assurance Audit Request'));
                return options;
            }
        }
            return options;
    }
    
    
}