force-app/main/default/objects/Case/fields/Caused_by_Change__c.field-meta.xml
<CustomField>
    <fullName>Caused_by_Change__c</fullName>
    <label>Caused by Change?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Does_Monitoring_Exist__c.field-meta.xml
<CustomField>
    <fullName>Does_Monitoring_Exist__c</fullName>
    <label>Does Monitoring Exist?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/How_was_Outage_Detected__c.field-meta.xml
<CustomField>
    <fullName>How_was_Outage_Detected__c</fullName>
    <label>How was Outage Detected?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Notification</fullName>
            </value>
            <value>
                <fullName>Internal Notification</fullName>
            </value>
            <value>
                <fullName>Monitoring</fullName>
            </value>
            <value>
                <fullName>Vendor Notification</fullName>
            </value>
            <value>
                <fullName>Trending</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Impact_Level__c.field-meta.xml
<CustomField>
    <fullName>Impact_Level__c</fullName>
    <label>Impact Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>No Impact</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Temporary_Fix__c.field-meta.xml
<CustomField>
    <fullName>Temporary_Fix__c</fullName>
    <label>Temporary Fix?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tracking_Root_Category__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Root_Category__c</fullName>
    <label>Tracking Root Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tracking_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Active Directory</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Application - Other</fullName>
            </value>
            <value>
                <fullName>Application - PGi</fullName>
            </value>
            <value>
                <fullName>Billing</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Client Transport Issue</fullName>
            </value>
            <value>
                <fullName>Cloud Vendor</fullName>
            </value>
            <value>
                <fullName>Collaboration Services</fullName>
            </value>
            <value>
                <fullName>Deskside Systems</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>DHCP</fullName>
            </value>
            <value>
                <fullName>DNS</fullName>
            </value>
            <value>
                <fullName>Duplicate Ticket</fullName>
            </value>
            <value>
                <fullName>Email Services</fullName>
            </value>
            <value>
                <fullName>End User Device</fullName>
            </value>
            <value>
                <fullName>End User Education/Request</fullName>
            </value>
            <value>
                <fullName>End User Error</fullName>
            </value>
            <value>
                <fullName>File &amp; Print Services</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>FTP</fullName>
            </value>
            <value>
                <fullName>Instant Messaging</fullName>
            </value>
            <value>
                <fullName>Laptop</fullName>
            </value>
            <value>
                <fullName>Mobile/Smartphone</fullName>
            </value>
            <value>
                <fullName>MVAS</fullName>
            </value>
            <value>
                <fullName>Network Interface</fullName>
            </value>
            <value>
                <fullName>No Action Required</fullName>
            </value>
            <value>
                <fullName>No Common Root Cause</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Urgency_Level__c.field-meta.xml
<CustomField>
    <fullName>Urgency_Level__c</fullName>
    <label>Urgency Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/X411_Bridge_Convened_Recorded__c.field-meta.xml
<CustomField>
    <fullName>X411_Bridge_Convened_Recorded__c</fullName>
    <label>411 Bridge Convened/Recorded</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/X911_Bridge_Convened_Recorded__c.field-meta.xml
<CustomField>
    <fullName>X911_Bridge_Convened_Recorded__c</fullName>
    <label>911 Bridge Convened/Recorded</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_AutoUpdateChildforNOCcases.cls
@isTest
public class Test_AutoUpdateChildforNOCcases{
    static testMethod void autoupdatechild(){
        
        Id nOCRecordTypeIdCase = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PGi-Parent Ticket (NOC)').getRecordTypeId();
        Case parentcase = new Case();
        parentcase.Status = 'New';
        parentcase.Subject = 'Test NOC';
        parentcase.Description = 'test desc';
        parentcase.RecordtypeId = nOCRecordtypeIdCase;
        parentcase.Impact_Level__c = 'Low';
        parentcase.Urgency_Level__c = 'Low';
        parentcase.Origin = 'Case Submission';
        parentcase.X911_Bridge_Convened_Recorded__c = 'No';
        parentcase.X411_Bridge_Convened_Recorded__c = 'No';
        parentcase.How_was_Outage_Detected__c = 'Monitoring';
        parentcase.Does_Monitoring_Exist__c = 'No';
        parentcase.Temporary_Fix__c = 'No';
        parentcase.Caused_by_Change__c = 'No';  
        parentcase.Tracking_Root_Category__c = 'Billing';  
        
        insert parentcase;
        
        Id externalSupportRT = Schema.SObjectType.Case.getRecordTypeInfosByName().get('PGi-Client External Support').getRecordTypeId();
        Case childcase = new Case();
        childcase.Status = 'New';
        childcase.Subject = 'Child NOC';
        childcase.Description = 'test desc';
        childcase.RecordtypeId = externalSupportRT;
        childcase.Impact_Level__c = 'Low';
        childcase.Urgency_Level__c = 'Low';
        childcase.Origin = 'Case Submission';
        childcase.X911_Bridge_Convened_Recorded__c = 'No';
        childcase.X411_Bridge_Convened_Recorded__c = 'No';
        childcase.How_was_Outage_Detected__c = 'Monitoring';
        childcase.Does_Monitoring_Exist__c = 'No';
        childcase.Temporary_Fix__c = 'No';
        childcase.Caused_by_Change__c = 'No';  
        childcase.Parentid = parentcase.id;  
        childcase.Tracking_Root_Category__c = null;
        
        insert childcase;
        
        Test.startTest();
        
        parentcase.Status = 'Closed';
        update parentcase;
        
        Case c = [SELECT id,Tracking_Root_Category__c FROM Case where id =: childcase.id];
        system.assertequals(c.Tracking_Root_Category__c,'Billing');
        
        Test.stopTest();
    }
}