force-app/main/default/objects/Case/fields/Email_address__c.field-meta.xml
<CustomField>
    <fullName>Email_address__c</fullName>
    <inlineHelpText>Ex: list@pgi.com</inlineHelpText>
    <label>Email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Company ID.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Requested_For__c.field-meta.xml
<CustomField>
    <fullName>Requested_For__c</fullName>
    <inlineHelpText>This will default to the email of the person entering the request.  If this request is for a different PGi Associate please change this to their email address.</inlineHelpText>
    <label>Requested For</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/RequestorsEmail__c.field-meta.xml
<CustomField>
    <fullName>RequestorsEmail__c</fullName>
    <label>Requestor&#39;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/SLA_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>SLA_in_Minutes__c</fullName>
    <label>SLA (in Minutes)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Lync/IM</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>PGi Contract</fullName>
            </value>
            <value>
                <fullName>PGi Service Catalog</fullName>
            </value>
            <value>
                <fullName>SvcNow</fullName>
            </value>
            <value>
                <fullName>PIDR</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Associated Client)</relationshipLabel>
    <relationshipName>Financial_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>APAC - North</fullName>
            </value>
            <value>
                <fullName>APAC - South</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Requested_For__c.field-meta.xml
<CustomField>
    <fullName>Requested_For__c</fullName>
    <inlineHelpText>This will default to the email of the person entering the request. If this request is for a different PGi Associate please change this to their email address.</inlineHelpText>
    <label>Requested For</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/RequestorsEmail__c.field-meta.xml
<CustomField>
    <fullName>RequestorsEmail__c</fullName>
    <label>Requestor&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/SuppliedEmail__c.field-meta.xml
<CustomField>
    <fullName>SuppliedEmail__c</fullName>
    <label>Web Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Chat Transcripts</relationshipLabel>
    <relationshipName>Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Location_Region__c</fullName>
    <description>To be populated based on Country in geolocation Location field</description>
    <label>Location_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>To set the case origin when escalating a chat. &#39;Chat&#39; or &#39;Chat - In Product&#39;</description>
    <label>Origin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Chat Transcripts</relationshipLabel>
    <relationshipName>Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Chat Transcripts</relationshipLabel>
    <relationshipName>Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Query_Topic__c.field-meta.xml
<CustomField>
    <fullName>Query_Topic__c</fullName>
    <label>Query Topic</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EscalateUnavailableChat.cls
public with sharing class EscalateUnavailableChat {

    public class Input {
        @InvocableVariable(required=true)
        public Id routableId;
    }
    
    public class Output {
        @InvocableVariable(required=false)
        public String ticketNumber;
    }

    @InvocableMethod(label='Escalate No Agent Chat')
    public static List<Output> escalateChat(List<Input> inputs) {

        Input input = inputs[0];
    
        LiveChatTranscript currentChatTranscript = [SELECT Id, ContactId, PGi_Client__c, Email_Address__c, Name__c, PGi_Company__c, Subject__c, Location_Region__c, Query_Topic__c FROM LiveChatTranscript WHERE Id = :input.routableId];
        
        Output output = new Output();
        
        switch on currentChatTranscript.Query_Topic__c {
            when 'Web or Audio Meetings', 'Unknown' {
                Case newCase = new Case(
                    Origin = 'Chat', 
                    RecordTypeId = [SELECT Id FROM RecordType WHERE name LIKE '%Inbound Email Support%' and SobjectType = 'Case' LIMIT 1].Id,
                    OwnerId = [SELECT Id FROM Group WHERE DeveloperName = 'PGi_Email_GL_Tier_1'].Id,
                    ContactId = currentChatTranscript.ContactId,
                    SLA_in_Minutes__c = 120,
                    PGi_Client__c = currentChatTranscript.PGi_Client__c,
                    PGi_Company__c = currentChatTranscript.PGi_Company__c,
                    SuppliedName = currentChatTranscript.Name__c,
                    SuppliedEmail = currentChatTranscript.Email_Address__c,
                    Subject = currentChatTranscript.Subject__c
                );
                
                INSERT newCase;
                currentChatTranscript.CaseId = newCase.Id;
                UPDATE currentChatTranscript;
                output.ticketNumber = 'Case# ' + [SELECT CaseNumber From Case WHERE Id = :newCase.Id].CaseNumber;
            }
            when 'Operator Assisted Events' {
                Case newCase = new Case(
                    Origin = 'Email - GL - RES - CallBack Email - PGiBrand',
                    RecordTypeId = [SELECT Id FROM RecordType WHERE name LIKE '%Inbound Email Support%' and SobjectType = 'Case' LIMIT 1].Id,
                    OwnerId = [SELECT Id FROM Group WHERE DeveloperName = 'PGi_Email_GL_Attended'].Id,
                    ContactId = currentChatTranscript.ContactId,
                    SLA_in_Minutes__c = 120,
                    PGi_Client__c = currentChatTranscript.PGi_Client__c,
                    PGi_Company__c = currentChatTranscript.PGi_Company__c,
                    SuppliedName = currentChatTranscript.Name__c,
                    SuppliedEmail = currentChatTranscript.Email_Address__c,
                    Subject = currentChatTranscript.Subject__c
                );
                
                INSERT newCase;
                currentChatTranscript.CaseId = newCase.Id;
                UPDATE currentChatTranscript;
                output.ticketNumber = 'Case# ' + [SELECT CaseNumber From Case WHERE Id = :newCase.Id].CaseNumber;
            }
            when 'Business Phone Systems' {
                Case newCase = new Case(
                    Origin = 'Chat',
                    RecordTypeId = [SELECT Id FROM RecordType WHERE name LIKE '%Inbound Email Support%' and SobjectType = 'Case' LIMIT 1].Id,
                    OwnerId = [SELECT Id FROM Group WHERE DeveloperName = 'PGi_Email_GL_Tier_1'].Id,
                    ContactId = currentChatTranscript.ContactId,
                    SLA_in_Minutes__c = 120,
                    PGi_Client__c = currentChatTranscript.PGi_Client__c,
                    PGi_Company__c = currentChatTranscript.PGi_Company__c,
                    SuppliedName = currentChatTranscript.Name__c,
                    SuppliedEmail = currentChatTranscript.Email_Address__c,
                    Subject = currentChatTranscript.Subject__c
                );
                
                INSERT newCase;
                currentChatTranscript.CaseId = newCase.Id;
                UPDATE currentChatTranscript;
                output.ticketNumber = 'Case# ' + [SELECT CaseNumber From Case WHERE Id = :newCase.Id].CaseNumber;
            }
            when 'Billing' {
                Financial_Request__c newFinReq = new Financial_Request__c(
                    Origin__c = 'Chat', 
                    RecordTypeId = [SELECT Id FROM RecordType WHERE name LIKE '%Billing Support%' and SobjectType = 'Financial_Request__c' LIMIT 1].Id,
                    Region__c = (currentChatTranscript.Location_Region__c != 'Unknown' ? currentChatTranscript.Location_Region__c : 'NA'),
                    PGi_Client__c = currentChatTranscript.PGi_Client__c,
                    PGi_Company__c = currentChatTranscript.PGi_Company__c,
                    SuppliedEmail__c = currentChatTranscript.Email_Address__c,
                    Requested_For__c = currentChatTranscript.Email_Address__c,
                    RequestorsEmail__c = currentChatTranscript.Email_Address__c,
                    Subject__c = currentChatTranscript.Subject__c
                );
                
                INSERT newFinReq;
                currentChatTranscript.Financial_Request__c = newFinReq.Id;
                UPDATE currentChatTranscript;
                output.ticketNumber = [SELECT Name From Financial_Request__c WHERE Id = :newFinReq.Id].Name;
            }
            when 'Sales' {
                Case newCase = new Case(
                    Origin = 'Chat', 
                    RecordTypeId = [SELECT Id FROM RecordType WHERE name LIKE '%Inbound Email Support%' and SobjectType = 'Case' LIMIT 1].Id,
                    OwnerId = [SELECT Id FROM Group WHERE DeveloperName = 'PGi_Email_GL_Tier_1'].Id,
                    ContactId = currentChatTranscript.ContactId,
                    SLA_in_Minutes__c = 120,
                    PGi_Client__c = currentChatTranscript.PGi_Client__c,
                    PGi_Company__c = currentChatTranscript.PGi_Company__c,
                    SuppliedName = currentChatTranscript.Name__c,
                    SuppliedEmail = currentChatTranscript.Email_Address__c,
                    Subject = currentChatTranscript.Subject__c
                );
                
                INSERT newCase;
                currentChatTranscript.CaseId = newCase.Id;
                UPDATE currentChatTranscript;
                output.ticketNumber = 'Case# ' + [SELECT CaseNumber From Case WHERE Id = :newCase.Id].CaseNumber;
            }
        }
        
        List<Output> returnWrapper = new List<Output>();
        returnWrapper.add(output);
    
        return returnWrapper;
    }
}