force-app/main/default/objects/Case/fields/X3rd_Party_Vendor_2__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Vendor_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Party Vendor #2</label>
    <referenceTo>PGi_Vendor_List__c</referenceTo>
    <relationshipLabel>Cases (3rd Party Vendor #2)</relationshipLabel>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/X3rd_Party_Vendor_3__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Vendor_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Party Vendor #3</label>
    <referenceTo>PGi_Vendor_List__c</referenceTo>
    <relationshipLabel>Cases (3rd Party Vendor #3)</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/X3rd_Party_Vendor__c.field-meta.xml
<CustomField>
    <fullName>X3rd_Party_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>3rd Party Vendor</label>
    <referenceTo>PGi_Vendor_List__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Vendor_List__c/PGi_Vendor_List__c.object-meta.xml
<CustomObject>
    <description>List of PGi Vendors, including carriers and 3rd Party vendors</description>
    <label>PGi Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Vendor_List__c/fields/Show_on_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Show_on_Surveys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show on Surveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/Vendor_Scorecard__c.object-meta.xml
<CustomObject>
    <label>Vendor Scorecard</label>
    <nameField>
        <displayFormat>VSC-{0000}</displayFormat>
        <label>Vendor Scorecard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Communicates_network_impacting_issues__c.field-meta.xml
<CustomField>
    <fullName>Communicates_network_impacting_issues__c</fullName>
    <label>Total for CNIS</label>
    <summarizedField>Vendor_Survey__c.Communicates_network_impacting_issues__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Communicates_network_impacting_issues__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Familiar_with_PGi_business_and_troubles__c.field-meta.xml
<CustomField>
    <fullName>Familiar_with_PGi_business_and_troubles__c</fullName>
    <label>Total for FBT</label>
    <summarizedField>Vendor_Survey__c.Familiar_with_PGi_business_and_trouble__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Familiar_with_PGi_business_and_trouble__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Knowledgeable_of_outstanding_problems__c.field-meta.xml
<CustomField>
    <fullName>Knowledgeable_of_outstanding_problems__c</fullName>
    <label>Total for KOP</label>
    <summarizedField>Vendor_Survey__c.Knowledgeable_of_outstanding_problems__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Knowledgeable_of_outstanding_problems__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <label>Month Year</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Provides_accurate_timely_ticket_updates__c.field-meta.xml
<CustomField>
    <fullName>Provides_accurate_timely_ticket_updates__c</fullName>
    <label>Total for PATTU</label>
    <summarizedField>Vendor_Survey__c.Provides_accurate_timely_ticket_updates__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Provides_accurate_timely_ticket_updates__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Related_PGi_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Related_PGi_Vendor__c</fullName>
    <label>Related PGi Vendor</label>
    <referenceTo>PGi_Vendor_List__c</referenceTo>
    <relationshipLabel>Vendor Scorecards</relationshipLabel>
    <relationshipName>Vendor_Scorecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Responsive_when_PGi_escalations_occur__c.field-meta.xml
<CustomField>
    <fullName>Responsive_when_PGi_escalations_occur__c</fullName>
    <label>Total for REO</label>
    <summarizedField>Vendor_Survey__c.Responsive_when_PGi_escalations_occur__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Responsive_when_PGi_escalations_occur__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/Vendor_Survey__c.object-meta.xml
<CustomObject>
    <label>Vendor Survey</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vendor Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Survys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Survey__c/fields/Communicates_network_impacting_issues__c.field-meta.xml
<CustomField>
    <fullName>Communicates_network_impacting_issues__c</fullName>
    <label>Communicates network impacting issues</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Familiar_with_PGi_business_and_trouble__c.field-meta.xml
<CustomField>
    <fullName>Familiar_with_PGi_business_and_trouble__c</fullName>
    <label>Familiar with PGi business and troubles</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Knowledgeable_of_outstanding_problems__c.field-meta.xml
<CustomField>
    <fullName>Knowledgeable_of_outstanding_problems__c</fullName>
    <label>Knowledgeable of outstanding problems</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Provides_accurate_timely_ticket_updates__c.field-meta.xml
<CustomField>
    <fullName>Provides_accurate_timely_ticket_updates__c</fullName>
    <label>Provides accurate/timely ticket updates</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Responsive_when_PGi_escalations_occur__c.field-meta.xml
<CustomField>
    <fullName>Responsive_when_PGi_escalations_occur__c</fullName>
    <label>Responsive when PGi escalations occur</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Vendor_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Scorecard__c</fullName>
    <label>Vendor Scorecard</label>
    <referenceTo>Vendor_Scorecard__c</referenceTo>
    <relationshipLabel>Vendor Survies</relationshipLabel>
    <relationshipName>Vendor_Survies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScorecardController.cls
/*
    Class : ScorecardController
*/
public class ScorecardController{
     
    public List<Case> lstCase{get;set;}
    public Integer TotalOpenCases{get;set;}
    public Integer TotalClosedCases{get;set;}
    public Integer TotalCases{get;set;}
    public String showDatafor{get;set;}
    public List<ModelClass> lstModelClass{get;set;}
    public List<Vendor_Scorecard__c> LVenScore{get;set;}
    public Id currentVid{get;set;}
    public String VName{get;set;}
    public Integer pageNumber{get;set;}
    public Integer TotalPages{get;set;}
    public Boolean preBtnDisabled{get;set;}
    public Boolean nxtBtnDisabled{get;set;}
    public set<Id> setVendorIdWithSurveys{get;set;}
    public set<Id> setVendorIdWithoutSurveys{get;set;}
    public Boolean hidetable{get;set;}
    public Integer pagesCount{get;set;}
    public map<Id,Integer> mapforPageNumber{get;set;}
    public map<Id,String> mapVendorName{get;set;}
    public boolean chkURLError{get;set;}
    public Date theGivenMonthDate{get;set;}
    
    
    public ScorecardController(){
        showDatafor = '';
        currentVid = Null;
        preBtnDisabled = true;
        nxtBtnDisabled = false; 
        pagesCount = 0; 
        VName = '';
        hidetable = false; 
        lstCase = new List<Case>();
        TotalOpenCases = 0;
        TotalClosedCases = 0;
        TotalCases = 0;
        lstModelClass = new List<ModelClass>();
        mapVendorName  = new map<Id,String>();
        mapforPageNumber  = new map<Id,Integer>();
        pageNumber = 1;
        TotalPages = 1;
        
        //get data from url 
        showDatafor = apexpages.currentpage().getParameters().get('data');  
        
        //Fatch vendors with survey records
        setVendorIdWithSurveys = vendorHaveSurvey();      
         //Fatch vendors without survey records 
        setVendorIdWithoutSurveys = vendorHaveWithoutSurvey(setVendorIdWithSurveys);  
        
        //Call first record 
        if( '' != showDatafor  && Null != showDatafor  && showDatafor.length()== 8 && setVendorIdWithoutSurveys!= Null){
            
            LVenScore= [Select id,Related_PGi_Vendor__c,Month_Year__c,Related_PGi_Vendor__r.Id,Related_PGi_Vendor__r.Name  from Vendor_Scorecard__c Where Month_Year__c =: showDatafor and Related_PGi_Vendor__c IN:setVendorIdWithoutSurveys and Related_PGi_Vendor__r.Show_on_Surveys__c = true ORDER BY Related_PGi_Vendor__r.Id];           
            if(LVenScore != Null && LVenScore.size()>0){
                currentVid = LVenScore.get(0).Related_PGi_Vendor__r.Id;
                if(currentVid != Null){
                    loadQestionAnswer(currentVid,showDatafor);
                    pageNumber = mapforPageNumber.get(currentVid);  
                }  
            }else{
                hidetable = true;
            }           
        }else{
            if(Null == showDatafor || '' == showDatafor){
                chkURLError = true;
            }else{
                hidetable = true;
            }
        }  
    }
    
    //This method used to call next vendor survey record.
    public void nextVendor(){
          
        preBtnDisabled = false;
        List<Vendor_Survey__c> lsVs = new List<Vendor_Survey__c>();
        Vendor_Survey__c vs = new Vendor_Survey__c();
        
        Boolean isInsert = false;
        
        if(lstModelClass!= Null && lstModelClass.size()>0){
            for(ModelClass mc : lstModelClass){
                if(mc.isApp == null){
                }else{
                    if(mc.question == 'Communicates network impacting issues' ){
                        vs.Communicates_network_impacting_issues__c = Decimal.ValueOf(mc.isApp);
                    }
                    if(mc.question ==  'Familiar with PGi business and troubles' ){
                        vs.Familiar_with_PGi_business_and_trouble__c = Decimal.ValueOf(mc.isApp);
                    }
                    if(mc.question ==  'Knowledgeable of outstanding problems' ){
                        vs.Knowledgeable_of_outstanding_problems__c = Decimal.ValueOf(mc.isApp);
                    }
                    if(mc.question ==  'Provides accurate timely ticket updates' ){
                        vs.Provides_accurate_timely_ticket_updates__c = Decimal.ValueOf(mc.isApp);
                    }
                    if(mc.question ==  'Responsive when PGi escalations occur' ){
                        vs.Responsive_when_PGi_escalations_occur__c = Decimal.ValueOf(mc.isApp);
                    }
                    vs.Vendor_Scorecard__c = Id.ValueOf(mc.vScoreCardId);
                    if(mc.isSurveyId == Null){
                        isInsert = true;
                    }
                }
            }
            if(isInsert){
                lsVs.add(vs);
            }
            if(lsVs != Null && lsVs.size()>0){
                insert lsVs;
            }
        }
        lstModelClass.Clear();
        if(TotalPages == pageNumber){
            VName ='';
            nxtBtnDisabled = true;
            TotalOpenCases = 0;
            TotalClosedCases = 0;
            TotalCases = 0; 
            loadQestionAnswer(currentVid,showDatafor);
        }else{
            //Fatch vendors with survey records
            setVendorIdWithSurveys = vendorHaveSurvey();      
             //Fatch vendors without survey records 
            setVendorIdWithoutSurveys = vendorHaveWithoutSurvey(setVendorIdWithSurveys);    
            if(setVendorIdWithoutSurveys != Null && setVendorIdWithoutSurveys.size()>0){
                LVenScore = [Select id,Related_PGi_Vendor__c,Month_Year__c,Related_PGi_Vendor__r.Id,Related_PGi_Vendor__r.Show_on_Surveys__c,Related_PGi_Vendor__r.Name  from Vendor_Scorecard__c 
                        Where Month_Year__c =: showDatafor and Related_PGi_Vendor__r.Show_on_Surveys__c = true and Related_PGi_Vendor__r.Id >: currentVid and Related_PGi_Vendor__c IN:setVendorIdWithoutSurveys ORDER BY Related_PGi_Vendor__r.Id ];
                if(LVenScore != Null && LVenScore.size()>0){
                    currentVid = LVenScore.get(0).Related_PGi_Vendor__r.Id;
                    loadQestionAnswer(currentVid,showDatafor);
                    pageNumber = mapforPageNumber.get(currentVid);
                } 
            }else{
                nxtBtnDisabled = true;
            }
        } 
        if(pageNumber == 1){
            preBtnDisabled = true;
        }
    }
    //This method used to call privious vendor  survey record.
    public void previousVendor(){
        
        nxtBtnDisabled = false;
        if(pageNumber == 1){
            preBtnDisabled = true;
        }
        //Fatch vendors with survey records
        setVendorIdWithSurveys = vendorHaveSurvey();      
         //Fatch vendors without survey records 
        setVendorIdWithoutSurveys = vendorHaveWithoutSurvey(setVendorIdWithSurveys);  
        if(setVendorIdWithoutSurveys != Null && setVendorIdWithoutSurveys.size()>0){ 
            LVenScore = [Select id,Related_PGi_Vendor__c,Month_Year__c,Related_PGi_Vendor__r.Id,Related_PGi_Vendor__r.Show_on_Surveys__c,Related_PGi_Vendor__r.Name  from Vendor_Scorecard__c 
                            Where Month_Year__c =: showDatafor and Related_PGi_Vendor__r.Show_on_Surveys__c = true and Related_PGi_Vendor__r.Id <: currentVid and Related_PGi_Vendor__c IN:setVendorIdWithoutSurveys  ORDER BY Related_PGi_Vendor__r.Id DESC ];
            if(LVenScore != Null && LVenScore.size()>0){
                currentVid = LVenScore.get(0).Related_PGi_Vendor__r.Id;
                loadQestionAnswer(currentVid,showDatafor);
                pageNumber = mapforPageNumber.get(currentVid); 
            }   
        }
        if(pageNumber == 1){
            preBtnDisabled = true;
        }
    }
    //This method is used to initilaze the model class record on page. 
    public void loadQestionAnswer(Id selectedVendorId,String showDatafor){
        lstModelClass.Clear();
        
        if(selectedVendorId != Null ){
             
            String ftDate = calculateStartEndDate(showDatafor,true);
            String edDate = calculateStartEndDate(showDatafor,false);
            
            String qary = 'Select Id,Status,Subject,X3rd_Party_Vendor__c FROM Case WHERE (X3rd_Party_Vendor__c =:selectedVendorId OR X3rd_Party_Vendor_2__c =:selectedVendorId OR X3rd_Party_Vendor_3__c =:selectedVendorId) and (CreatedDate >='+ftDate+'  and CreatedDate <= '+edDate+')';
            lstCase = Database.query(qary);
            TotalCases = lstCase.size();
            qary = 'Select Id,Status,Subject,X3rd_Party_Vendor__c FROM Case WHERE Status = \'Closed\' AND (X3rd_Party_Vendor__c =:selectedVendorId OR X3rd_Party_Vendor_2__c =:selectedVendorId OR X3rd_Party_Vendor_3__c =:selectedVendorId) and  (ClosedDate >='+ftDate+'  and ClosedDate <= '+edDate+')';
            lstCase = Database.query(qary);
            //TotalOpenCases = lstCase.size();
            TotalClosedCases = lstCase.size();
            /* 
            system.debug(lstCase.size());
            lstCase = [Select Id,Status,Subject,Vendor__c from Case Where Vendor__c =:selectedVendorId and  Status != 'Closed' and  ( CreatedDate >=: Datetime.ValueOf(ftDate) and CreatedDate <=: Datetime.ValueOf(edDate)  )  ];
            system.debug(lstCase + ' - '+lstCase.size());
            List<CaseHistory> lstCH = [Select Id,CaseId  From CaseHistory Where Case.Vendor__c =: selectedVendorId and ((Field ='Closed') or (Field ='Status') ) and  ( CreatedDate >=: Datetime.ValueOf(ftDate) and CreatedDate <=: Datetime.ValueOf(edDate)  )  ];
            TotalOpenCases = lstCase.size();
            system.debug(lstCH + ' - '+lstCH.size());
            */
            LVenScore= [Select id,Communicates_network_impacting_issues__c,Familiar_with_PGi_business_and_troubles__c,
                                    Knowledgeable_of_outstanding_problems__c,Month_Year__c,Provides_accurate_timely_ticket_updates__c,
                                                Related_PGi_Vendor__c,Related_PGi_Vendor__r.Name,Responsive_when_PGi_escalations_occur__c from Vendor_Scorecard__c 
                                                    Where Related_PGi_Vendor__c =: selectedVendorId and Month_Year__c=:showDatafor];
            VName = mapVendorName.get(selectedVendorId);
            
            if(LVenScore != Null && LVenScore.size()>0 ){
                List<Vendor_Survey__c> lstVenSurvey = [Select id  from Vendor_Survey__c Where  Vendor_Scorecard__r.Related_PGi_Vendor__c =: selectedVendorId and Vendor_Scorecard__r.Month_Year__c =:showDatafor
                                                        and  Vendor_Scorecard__c =:LVenScore.get(0).Id and CreatedBy.Id =: UserInfo.getUserId()]; 
                if(lstVenSurvey.size()==0 ){
                    ModelClass mc = new ModelClass();
                    mc.question = 'Communicates network impacting issues';
                    mc.whichMonthYear = showDatafor;  
                    mc.vScoreCardId = LVenScore.get(0).id;
                    mc.isSurveyId = Null;
                    lstModelClass.add(mc);
                    
                    mc = new ModelClass();
                    mc.question = 'Familiar with PGi business and troubles';
                    mc.whichMonthYear = showDatafor;
                    mc.vScoreCardId = LVenScore.get(0).id;
                    mc.isSurveyId = Null;
                    lstModelClass.add(mc);
                
                    mc = new ModelClass();
                    mc.question = 'Knowledgeable of outstanding problems';
                    mc.whichMonthYear = showDatafor;
                    mc.vScoreCardId = LVenScore.get(0).id;
                    mc.isSurveyId = Null;
                    lstModelClass.add(mc);
                
                    mc = new ModelClass();
                    mc.question = 'Provides accurate timely ticket updates';
                    mc.whichMonthYear = showDatafor;
                    mc.vScoreCardId = LVenScore.get(0).id;
                    mc.isSurveyId = Null;
                    lstModelClass.add(mc);
                    
                    mc = new ModelClass();
                    mc.question = 'Responsive when PGi escalations occur';
                    mc.whichMonthYear = showDatafor;
                    mc.vScoreCardId = LVenScore.get(0).id;
                    mc.isSurveyId = Null;
                    lstModelClass.add(mc);
                }
            }
        }
    }
    
    //This method return the set of all vendors which have a survey record of current users.
    public set<Id> vendorHaveSurvey(){
        List<Vendor_Survey__c> lstVenSur = [Select id,Vendor_Scorecard__c,Vendor_Scorecard__r.Month_Year__c, Vendor_Scorecard__r.Related_PGi_Vendor__c from Vendor_Survey__c Where 
                                             Vendor_Scorecard__r.Month_Year__c =:showDatafor and  CreatedBy.Id =: UserInfo.getUserId()]; 
        set<Id> setVendorIds = new set<Id>();       
        if(lstVenSur!= Null && lstVenSur.size()>0){
            for(Vendor_Survey__c vs : lstVenSur ){
                setVendorIds.add(vs.Vendor_Scorecard__r.Related_PGi_Vendor__c);
            }
            return setVendorIds;
        } 
        return null;
    }
    //This method return the set of all vendors which does not have a survey record of current users.
     public set<Id> vendorHaveWithoutSurvey(set<Id> setVendorHaveSurvey){
        if(setVendorIdWithSurveys != Null && setVendorIdWithSurveys.size()>0){
            LVenScore= [Select id,Related_PGi_Vendor__c,Related_PGi_Vendor__r.Name  from Vendor_Scorecard__c Where Related_PGi_Vendor__r.Show_on_Surveys__c = true and Month_Year__c =: showDatafor and Related_PGi_Vendor__c NOT IN:setVendorHaveSurvey ORDER BY Related_PGi_Vendor__r.Id];
        }else{
            LVenScore= [Select id,Related_PGi_Vendor__c,Related_PGi_Vendor__r.Name  from Vendor_Scorecard__c Where Related_PGi_Vendor__r.Show_on_Surveys__c = true and  Month_Year__c =: showDatafor ORDER BY Related_PGi_Vendor__r.Id];            
        }
         
        pagesCount =1; 
        set<Id> setVendorIds = new set<Id>();       
        if(LVenScore!= Null && LVenScore.size()>0){
            for(Vendor_Scorecard__c vs : LVenScore ){
                setVendorIds.add(vs.Related_PGi_Vendor__c);
                mapforPageNumber.put(vs.Related_PGi_Vendor__c,pagesCount);
                pagesCount = pagesCount+1;
                mapVendorName.put(vs.Related_PGi_Vendor__c,vs.Related_PGi_Vendor__r.Name);
            }
            TotalPages = LVenScore.size();
            return setVendorIds; 
        } 
        return null; 
    }
    
    public static String calculateStartEndDate(String showDatafor,Boolean isStart){
        
        try{
            String tDate = '';
        
            String [] tVar= showDatafor.split('-');
             
            String tMonth = tVar[0];
            Integer tYear = Integer.ValueOf(tVar[1]);
            tMonth = tMonth.toLowerCase();
            Integer fMonth =0;
            
            if(tMonth == 'jan'){
                fMonth = 1;
            }else if(tMonth == 'feb'){
                fMonth = 2;
            }else if(tMonth == 'mar'){
                fMonth = 3;
            }else if(tMonth == 'apr'){
                fMonth = 4;
            }else if(tMonth == 'may'){
                fMonth = 5;
            }else if(tMonth == 'jun'){
                fMonth = 6;
            }else if(tMonth == 'jul'){
                fMonth = 7;
            }else if(tMonth == 'aug'){
                fMonth = 8;
            }else if(tMonth == 'sep'){
                fMonth = 9;
            }else if(tMonth == 'oct'){
                fMonth = 10;
            }else if(tMonth == 'nov'){
                fMonth = 11;
            }else if(tMonth == 'dec'){
                fMonth = 12;
            }
            
            if(isStart){
                tDate = String.ValueOf(Date.newInstance(tYear, fMonth, 1));
                tDate = tDate.left(10);
                tDate = tDate+'T00:00:00.000+0000';
            }else{
                Integer dInMonth = Date.daysInMonth(tYear, fMonth);
                tDate = String.ValueOf(Date.newInstance(tYear, fMonth, dInMonth));
                tDate = tDate.left(10);
                tDate = tDate+'T23:59:59.000+0000';
            }
            
             
            system.debug(tDate);
            
            
            return tDate;
        }catch(exception e){
            system.debug(e);
        }
        
        return null;
        
    } 
    
    public class ModelClass{
        public String question{get;set;}
        public String isApp{get;set;} 
        public Id vScoreCardId{get;set;}
        public String whichMonthYear{get;set;}
        public Id isSurveyId{get;set;}
    }
    
}