force-app/main/default/objects/CustomSchedule__c/CustomSchedule__c.object-meta.xml
<CustomObject>
    <label>Custom Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomSchedule__c/fields/baseScheduleType__c.field-meta.xml
<CustomField>
    <fullName>baseScheduleType__c</fullName>
    <description>Parent Schedule Usage Type</description>
    <formula>TEXT(baseSchedule__r.scheduleType__c)</formula>
    <inlineHelpText>Parent Schedule Usage Type</inlineHelpText>
    <label>Schedule Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/NegotiatedProduct__c.object-meta.xml
<CustomObject>
    <description>Configured Components under Products assigned to an Account.</description>
    <label>Negotiated Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NegotiatedProduct__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT</fullName>
            </value>
            <value>
                <fullName>ANY</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,FOXDEN_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/QuantityEnabled__c.field-meta.xml
<CustomField>
    <fullName>QuantityEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QuantityEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the default plan used (for plan&apos;s on this Account).</description>
    <label>isDefault</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/package__c.field-meta.xml
<CustomField>
    <fullName>package__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/recurringCharge__c.field-meta.xml
<CustomField>
    <fullName>recurringCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Recurring Charge</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/scheduleName__c.field-meta.xml
<CustomField>
    <fullName>scheduleName__c</fullName>
    <formula>schedule__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Schedule Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/singleCharge__c.field-meta.xml
<CustomField>
    <fullName>singleCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Single Charge</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/useAssignedScheduleAsDefault__c.field-meta.xml
<CustomField>
    <fullName>useAssignedScheduleAsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use the schedule assigned to this product as the default value in the drop down when selecting plan/products.</description>
    <label>Use Assigned Schedule As Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/scheduleType__c.field-meta.xml
<CustomField>
    <fullName>scheduleType__c</fullName>
    <description>Usage Type for this Schedule</description>
    <inlineHelpText>Select the appropriate usage type for this schedule</inlineHelpText>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audio</fullName>
                <default>true</default>
                <label>Audio</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Hosting</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ScheduleOverride__c/ScheduleOverride__c.object-meta.xml
<CustomObject>
    <label>Schedule Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleOverride__c/fields/customSchedule__c.field-meta.xml
<CustomField>
    <fullName>customSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Custom Schedule</label>
    <referenceTo>CustomSchedule__c</referenceTo>
    <relationshipLabel>Schedule Overrides</relationshipLabel>
    <relationshipName>ScheduleOverrides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Schedule Overrides</relationshipLabel>
    <relationshipName>ScheduleOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleOverride__c/fields/scheduleName__c.field-meta.xml
<CustomField>
    <fullName>scheduleName__c</fullName>
    <formula>IF( ISBLANK(standardSchedule__c)  ,  customSchedule__r.Name , standardSchedule__r.Name)</formula>
    <label>scheduleName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddPlanController.cls
global with sharing class AddPlanController {
  
  private List<Package__c> packages;
  private List<RT_Product__c> products;   
  private Map<String,ScheduleOverride__c> productsWithCustomSchedules;
  private Package__c assignedPackage;
  private Plan__c assignedPlan;  
  private Id accountId;    
  private Id assignedPackageId;
  private Boolean quantityEnabled;
  public Account account {get; set;}
  
  private final Pkg pkg = new Pkg();
  
  public AddPlanController(ApexPages.StandardController controller) {
    this.accountId = ApexPages.currentPage().getParameters().get('id');    
    account = (Account)controller.getRecord();
    this.packages = pkg.findAllPackages(); 
  }
  
  /**
   * Return all Packages as select options
   */
  public List<SelectOption> getPackageItems() {
    List<SelectOption> options = new List<SelectOption>();
    for(Package__c p : this.packages) {
      options.add(new SelectOption(p.id,p.name));
    }
    return options;    
  }
  
  /**
   * Return all products for the selected package
   */
  public List<RT_Product__c> getProducts() {
    productsWithCustomSchedules = new Map<String,ScheduleOverride__c>();

    if(this.assignedPackageId == null)
      this.assignedPackage = this.packages.get(0);
    else
      this.assignedPackage = pkg.findById(this.assignedPackageId);      
    
    CustomSchedule customSchedulelookup = new CustomSchedule();
    Schedule scheduleLookup = new Schedule();
    List<RT_Product__c> products = new List<RT_Product__c>();
    List<CustomSchedule__c> customSchedules = customSchedulelookup.findByAccountId(this.accountId);

    for(RT_Product__c product : this.assignedPackage.RT_Products__r) {
      Schedule__c schedule = scheduleLookup.findById(product.schedule__c);
      String scheduleType = null;

      if(schedule != null)
        scheduleType = schedule.scheduleType__c;
      
      //If the base product doesn't have the schedule flagged as "use by default", then use a Custom Schedule
      if(!product.useAssignedScheduleAsDefault__c){
        for(CustomSchedule__c cs : customSchedules){
          if(cs.baseScheduleType__c.equals(scheduleType) && cs.isDefault__c){
            ScheduleOverride__c so = new ScheduleOverride__c();
            so.customSchedule__c = cs.Id;
            productsWithCustomSchedules.put(product.Id, so);
          }
        }
      }

      if(!productsWithCustomSchedules.containsKey(product.Id))
        productsWithCustomSchedules.put(product.Id, new ScheduleOverride__c());

      products.add(product);
    }
    
    //Set the billable type to the selected Package's billable type
    this.assignedPlan = new Plan__c();
    this.assignedPlan.billableType__c = this.assignedPackage.billableType__c;
    this.assignedPlan.name = this.assignedPackage.name;
    this.quantityEnabled = this.assignedPackage.QuantityEnabled__c;

    return products;
  }
    
  /**
   * Add a new plan, replicating the current plan's products; add overrides as necessary
   */
  @RemoteAction
  global static boolean addPlan(String accountId, String packageId, String planName, String billableType, String startDate, String endDate, String quantity, String quantityStartDate, String planProducts) {
    return doAddPlan(accountId, packageId, planName, billableType, startDate, endDate, quantity, quantityStartDate, planProducts);
  }

//  @RemoteAction
//  global static boolean addPlan(String accountId, String packageId, String planName, String billableType, String startDate, String endDate, String planProducts) {
//    return doAddPlan(accountId, packageId, planName, billableType, startDate, endDate, null, null, planProducts);
//  }

  private static boolean doAddPlan(String accountId, String packageId, String planName, String billableType, String startDate, String endDate, String quantity, String quantityStartDate, String planProducts) {
    Pkg pkgLookup = new Pkg();
    Plan planRepo = new Plan();
    Schedule scheduleLookup = new Schedule();
    CustomSchedule customScheduleLookup = new CustomSchedule();
    NegotiatedProduct npRepo = new NegotiatedProduct();

    Package__c pkg = pkgLookup.findById(packageId);
    Account a = (Account) [select name,parentID from Account where id =: accountId];
    List<Schedule__c> schedules = scheduleLookup.findAllSchedules();

    if (pkg.QuantityEnabled__c && (quantity == null || quantity == '')) {
      throw new ValidationException('Quantity is a required field.');
    }

    if (pkg.QuantityEnabled__c && Integer.valueOf(quantity) < 1) {
      throw new ValidationException('Quantity must be greater than 0.');
    }

    //Support for parent account's custom schedule assignments
    List<CustomSchedule__c> customSchedules = new List<CustomSchedule__c>();

    if(a.parentID != null)
      customSchedules = customScheduleLookup.findByAccountIdOrParentAccountId(accountId, a.parentID);
    else
      customSchedules = customScheduleLookup.findByAccountId(accountId);

    //Create plan
    Plan__c newPlan = planRepo.savePlan(planName, a.id, pkg.id, billableType, startDate, endDate, quantity, quantityStartDate);

    //Create Negotiated Products
    Map<String, Object> m = (Map<String, Object>) JSON.deserializeUntyped(planProducts);
    List<Object> jsonProducts = (List<Object>) m.get('products');

    //Loop through incoming
    for(Object jsonProduct : jsonProducts) {
      //Parse incoming JSON into objects
      String productName = StringUtils.nullIfEmpty(JsonUtils.getJsonValue(jsonProduct, 'productName'));
      String productId = StringUtils.nullIfEmpty(JsonUtils.getJsonValue(jsonProduct, 'id'));
      Decimal singleCharge = StringUtils.decimalValueOf(JsonUtils.getJsonValue(jsonProduct, 'singleCharge').replaceAll('\\$', '').replaceAll(',', ''));
      Decimal recurringCharge = StringUtils.decimalValueOf(JsonUtils.getJsonValue(jsonProduct, 'recurringCharge').replaceAll('\\$', '').replaceAll(',', ''));
      String recurringChargeFrequency = StringUtils.nullIfEmpty(JsonUtils.getJsonValue(jsonProduct, 'recurringChargeFrequency'));
      String schedule = StringUtils.nullIfEmpty(JsonUtils.getJsonValue(jsonProduct, 'schedule'));
      Id scheduleId = null;
      Id customScheduleId = null;

      //Match the incoming schedule to the corresponding schedule/custom schedule based on it's name
      for(Schedule__c s : schedules) {
        if(s.name==schedule)
          scheduleId = s.id;
      }

      for(CustomSchedule__c c : customSchedules) {
        if(c.name==schedule)
          customScheduleId = c.id;
      }

      //Get the product we are dealing with
      RT_Product__c product = getProductFromPackage(pkg, productId);

      //Save negotiated product
      NegotiatedProduct__c np = npRepo.saveNegotiatedProduct(productName, productId, newPlan.id, a.id);

      //Save single charge override
      if(product != null && product.singleCharge__c != singleCharge) {
        SingleChargeOverride scoDao = new SingleChargeOverride();
        scoDao.saveSingleChargeOverride(productName, product.singleCharge__c, np.id, singleCharge, startDate, endDate);
      }

      //Save recurring charge override
      if(product != null && (product.recurringCharge__c != recurringCharge || product.recurringChargeFrequency__c != recurringChargeFrequency)) {
        RecurringChargeOverride rcoDao = new RecurringChargeOverride();
        rcoDao.saveRecurringChargeOverride(productName, product.recurringCharge__c, np.id, recurringCharge, recurringChargeFrequency, startDate, endDate);
      }

      //Save schedule override
      if(product != null && schedule != product.scheduleName__c) {
        ScheduleOverride scheduleDao = new ScheduleOverride();
        scheduleDao.saveScheduleOverride(productName, np.id, scheduleId, customScheduleId, startDate, endDate);
      }
    }
    return true;
  }
       
  private static RT_Product__c getProductFromPackage(Package__c pkg, String productId) {
    for(RT_Product__c product : pkg.RT_Products__r) {
      if(product.id==productId) {
        return product;
      }        
    }
    return null;
  }
  
  public PageReference packageSelect() {
    getProducts();
    return null;
  }
  
  public String getAccountId() {
    return this.accountId;
  }  
  
  public Package__c getAssignedPackage() {
    return this.assignedPackage;
  }  
  
  public void setAssignedPackage(Package__c assignedPackage) {
    this.assignedPackage = assignedPackage;
  }
  
  public Id getAssignedPackageId() {
    return this.assignedPackageId;
  }  
  
  public void setAssignedPackageId(Id assignedPackageId) {
    this.assignedPackageId = assignedPackageId;
  }  
  
  public Plan__c getAssignedPlan() {
    return this.assignedPlan;
  }
  
  public void setAssignedPlan(Plan__c assignedPlan) {
    this.assignedPlan = assignedPlan;
  }   

  public Map<String,ScheduleOverride__c> getProductsWithCustomSchedules() {
    return this.productsWithCustomSchedules;
  }

  public Boolean getQuantityEnabled() {
    return this.quantityEnabled;
  }

  public void setQuantityEnabled(Boolean enabled) {
    this.quantityEnabled = enabled;
  }
}