force-app/main/default/objects/PGi_ServiceCatalog_Category__c/PGi_ServiceCatalog_Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Category</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_ServiceCatalog_Category__c/fields/Navigate_to__c.field-meta.xml
<CustomField>
    <fullName>Navigate_to__c</fullName>
    <description>If the navigate to is left blank, then the user is shown the category options</description>
    <inlineHelpText>If the navigate to is left blank, then the user is shown the category options</inlineHelpText>
    <label>Navigate to</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Category_Option__c/PGi_ServiceCatalog_Category_Option__c.object-meta.xml
<CustomObject>
    <label>Category Option</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Category Option</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Category Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_ServiceCatalog_Category_Option__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>PGi_ServiceCatalog_Category__c</referenceTo>
    <relationshipLabel>Category Options</relationshipLabel>
    <relationshipName>Category_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Category_Option__c/fields/Navigate_to__c.field-meta.xml
<CustomField>
    <fullName>Navigate_to__c</fullName>
    <description>If the navigate to is left blank, then the user is shown the field input, otherwise they will be directed to this url</description>
    <inlineHelpText>If the navigate to is left blank, then the user is shown the field input, otherwise they will be directed to this url</inlineHelpText>
    <label>Navigate to</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Category_Option__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
                <default>true</default>
                <label>Case</label>
            </value>
            <value>
                <fullName>PGi_ServiceCatalog_Category__c</fullName>
            </value>
            <value>
                <fullName>Object_Does_Not_Exist__c</fullName>
            </value>
            <value>
                <fullName>Human_Resource_Form__c</fullName>
            </value>
            <value>
                <fullName>Request_for_Change__c</fullName>
            </value>
            <value>
                <fullName>Product_Launch_Process__c</fullName>
            </value>
            <value>
                <fullName>Financial_Request__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Hidden_Input_Value__c/PGi_ServiceCatalog_Hidden_Input_Value__c.object-meta.xml
<CustomObject>
    <label>Hidden Input Value</label>
    <nameField>
        <displayFormat>H-{00000}</displayFormat>
        <label>Hidden Input Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hidden Input Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_ServiceCatalog_Hidden_Input_Value__c/fields/Category_Option__c.field-meta.xml
<CustomField>
    <fullName>Category_Option__c</fullName>
    <label>Category Option</label>
    <referenceTo>PGi_ServiceCatalog_Category_Option__c</referenceTo>
    <relationshipLabel>Hidden Input Values</relationshipLabel>
    <relationshipName>Hidden_Input_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Hidden_Input_Value__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <formula>TEXT(Category_Option__r.Object_API_Name__c)</formula>
    <label>Object API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Hidden_Input_Value__c/fields/Set_Value__c.field-meta.xml
<CustomField>
    <fullName>Set_Value__c</fullName>
    <description>What do you want to set the selected API name to?</description>
    <inlineHelpText>What do you want to set the selected API name to?</inlineHelpText>
    <label>Set Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Section__c/PGi_ServiceCatalog_Section__c.object-meta.xml
<CustomObject>
    <label>Section</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Section Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_ServiceCatalog_Section__c/fields/Category_Option__c.field-meta.xml
<CustomField>
    <fullName>Category_Option__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category Option</label>
    <referenceTo>PGi_ServiceCatalog_Category_Option__c</referenceTo>
    <relationshipLabel>Sections</relationshipLabel>
    <relationshipName>Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Section__c/fields/Field_Set_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Set_API_Name__c</fullName>
    <description>The API Name of the Field Set to display</description>
    <inlineHelpText>The API Name of the Field Set to display</inlineHelpText>
    <label>Field Set API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_ServiceCatalog_Section__c/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <formula>TEXT(Category_Option__r.Object_API_Name__c)</formula>
    <label>Object API Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PGI_ServiceCatalogTests.cls
@isTest
private class PGI_ServiceCatalogTests
{
    @isTest
    static void testCatalogTrigger() {
        PGi_ServiceCatalog_Category__c cat = createCategory();
        boolean failure = false;
        try {
            PGi_ServiceCatalog_Category_Option__c option = createCategoryOption(cat, 'nosuchobject');
        } catch (exception e) {
            failure = true;
        }
        system.assert(failure, 'Expected to fail on bad sojbect name');
        failure = false;
        
        PGi_ServiceCatalog_Category_Option__c option = createCategoryOption(cat, 'Case');
        
        try {
            PGi_ServiceCatalog_Hidden_Input_Value__c input = createHiddenInput(option, 'nosuchfield');
        } catch (exception e) {
            failure = true;
        }
        system.assert(failure, 'Expected to fail on bad sojbect field name');
        failure = false; 
        
        PGi_ServiceCatalog_Hidden_Input_Value__c input = createHiddenInput(option, 'Status');
        
        try {
            system.debug('==cat===>');
            PGi_ServiceCatalog_Section__c section = createSection(option, 'invalid_name');
            system.debug('==cat===>');
        } catch (exception e) {
            failure = true;
        }
        system.assert(failure, 'Section insert fails without valid field set');
        
        PGi_ServiceCatalogController controller = new PGi_ServiceCatalogController();
        List<PGi_ServiceCatalog_Section__c> sectionList = controller.displaySectionList;
        system.assert(sectionList.size() == 0);
        List<PGi_ServiceCatalog_Category_Option__c> catOptionList =  controller.displayCategoryOptionList;
        system.assert(catOptionList.size() == 0);
        controller.home();
        controller.fieldSetList('Case');
        controller.saveServiceCatalog();
        controller.selectedCategoryId 		= cat.Id;
        controller.rerender();
        /* test re-rendering of category options */
        catOptionList =  controller.displayCategoryOptionList;
        system.assert(catOptionList.size() == 1); 
        controller.selectedCategoryId = cat.Id;
        controller.cancel();
        
        system.assert(controller.selectedCategoryId == null);
        catOptionList =  controller.displayCategoryOptionList;
        system.assert(catOptionList.size() == 0); 
        
        
        controller.selectedCategoryId = cat.Id;
        controller.selectedCategoryOptionId = option.Id;
        system.assert(controller.allowSave == true);
        //controller.populateHiddenValues();
        controller.saveServiceCatalog();
        
        Case c = [Select Id FROM Case];
        
        Map<Id, List<Schema.FieldSetMember>> sectionfields = controller.sectionIdToFields;
        system.assert(null == controller.nullValue);
        system.assert(controller.theRecord != null);
        controller.cancel();
        
        system.assert(controller.theRecord == null);
        controller.navigateToRecord();
    }
    static testMethod void testCatogeryListError(){
        PGi_ServiceCatalogController controller = new PGi_ServiceCatalogController();
        List<PGi_ServiceCatalog_Category__c> categoryList =  controller.categoryList; 
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertEquals(1, pageMessages.size());
        String baseUrl = controller.baseUrl;
        System.assertequals(0,controller.fieldSetList('text').size());
        Boolean allowSave =controller.allowSave;
        System.assertEquals(false, allowSave);
    }
    static testMethod void testCatogeryList(){
        PGi_ServiceCatalog_Category__c cat = createCategory();
        cat.Navigate_to__c='google.com';
        Update cat;
        PGi_ServiceCatalog_Category_Option__c option = createCategoryOption(cat, 'Case');
        ApexPages.currentPage().getParameters().put('category',cat.Id);
        ApexPages.currentPage().getParameters().put('categoryOption',option.Id);
        PGi_ServiceCatalogController controller = new PGi_ServiceCatalogController();
        List<PGi_ServiceCatalog_Category__c> categoryList =  controller.categoryList; 
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertEquals(0, pageMessages.size());
        String baseUrl = controller.baseUrl;
        System.assertequals(0,controller.fieldSetList('text').size());
        Boolean allowSave =controller.allowSave;
        System.assertEquals(true, allowSave);
        controller.rerender();
    }
    //to cover selectedCategoryOption
    static testMethod void testCatogeryListrerender(){
        PGi_ServiceCatalog_Category__c cat = createCategory();
        cat.Navigate_to__c=null;
        Update cat;
        PGi_ServiceCatalog_Category_Option__c option = createCategoryOption(cat, 'Case');
        option.Navigate_to__c ='https://google.com';
        Update option;   
        PGi_ServiceCatalog_Section__c section = createSection(option, 'PGi_Client_Billing_Help_Desk');
        ApexPages.currentPage().getParameters().put('category',cat.Id);
        ApexPages.currentPage().getParameters().put('categoryOption',option.Id);
        PGi_ServiceCatalogController controller = new PGi_ServiceCatalogController();
        List<PGi_ServiceCatalog_Category__c> categoryList =  controller.categoryList; 
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertEquals(0, pageMessages.size());
        String baseUrl = controller.baseUrl;
        System.assertequals(0,controller.fieldSetList('text').size());
        List<PGi_ServiceCatalog_Section__c> displaySectionList = controller.displaySectionList;
        controller.rerender();
        Map<Id, List<Schema.FieldSetMember>> sectionIdToFields = controller.sectionIdToFields;
        Boolean allowSave =controller.allowSave;
        System.assertEquals(true, allowSave);
        ApexPages.currentPage().getParameters().put('devPreview','test');
        controller.home();
        sObject theRecord =controller.theRecord;
        theRecord=section;
        controller.navigateToRecord(); 
    }
    //to cover selectedCategoryOption
    static testMethod void testCatogeryListrerenderelse(){
        PGi_ServiceCatalog_Category__c cat = createCategory();
        cat.Navigate_to__c=null;
        Update cat;
        PGi_ServiceCatalog_Category_Option__c option = createCategoryOption(cat, 'Case');
        option.Navigate_to__c ='google.com';
        Update option;     
        ApexPages.currentPage().getParameters().put('category',cat.Id);
        ApexPages.currentPage().getParameters().put('categoryOption',option.Id);
        PGi_ServiceCatalogController controller = new PGi_ServiceCatalogController();
        List<PGi_ServiceCatalog_Category__c> categoryList =  controller.categoryList; 
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertEquals(0, pageMessages.size());
        String baseUrl = controller.baseUrl;
        String rerender = controller.rerender;
        System.assertequals(0,controller.fieldSetList('text').size());
        controller.rerender();
        Boolean allowSave =controller.allowSave;
        System.assertEquals(true, allowSave);
        
    }
    private static PGi_ServiceCatalog_Category__c createCategory() {
        PGi_ServiceCatalog_Category__c cat = new PGi_ServiceCatalog_Category__c(Active__c = true, Navigate_to__c ='https://google.com');
        insert cat; 
        system.debug('==cat===>'+cat);
        return cat; 
    }
    private static PGi_ServiceCatalog_Category_Option__c createCategoryOption(PGi_ServiceCatalog_Category__c category, String apiName) {
        PGi_ServiceCatalog_Category_Option__c option = new PGi_ServiceCatalog_Category_Option__c(Category__c = category.Id, Object_API_Name__c = apiName, Active__c = true);
        insert option;
        return option;
    }
    private static PGi_ServiceCatalog_Section__c createSection(PGi_ServiceCatalog_Category_Option__c option, String apiName) {
        PGi_ServiceCatalog_Section__c section = new PGi_ServiceCatalog_Section__c(Category_Option__c = option.Id, Field_Set_API_Name__c = apiName);
        insert section;
        system.debug('=section==>'+section);
        return section;
    }
    private static PGi_ServiceCatalog_Hidden_Input_Value__c createHiddenInput(PGi_ServiceCatalog_Category_Option__c option, String apiName) {
        PGi_ServiceCatalog_Hidden_Input_Value__c input = new PGi_ServiceCatalog_Hidden_Input_Value__c(Category_Option__c = option.Id, Field_API_Name__c = apiName, Set_Value__c = 'New');
        insert input;
        return input;
    }
}