force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Call Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be populated if provided from the DNIS/IVR,otherwise you can insert before escalating as needed.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CallLogTriggerHandler.cls
public class CallLogTriggerHandler extends TriggerHandler {
    public CallLogTriggerHandler() {
        super('CallLogTriggerHandler');
    }
    protected override void afterUpdate() {
        updateClientTasks((List<Call_Log__c>)Trigger.new, (Map<Id, Call_Log__c>)Trigger.oldMap);
    }
    private void updateClientTasks(List<Call_Log__c> callLogs, Map<Id, Call_Log__c> oldMap) {
        Set<Id> cIds = new Set<Id>();
        for(Call_Log__c cl: callLogs) {
            if(cl.PGi_Client__c != oldMap.get(cl.Id).PGI_Client__c) {
                cIds.add(cl.Id);
            }
        }
        if(cIds.size() > 0) {
            List<Task> tasksToUpdate = [SELECT Id FROM Task WHERE WhatId IN: cIds];
            Database.update(tasksToUpdate, false); 
        }
    }
}