force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Call Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be populated if provided from the DNIS/IVR,otherwise you can insert before escalating as needed.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CallLogTest.cls
@IsTest
public class CallLogTest {
    @IsTest
    public static void testTaskUpdate() {
        PGI_Client__c client = new PGI_Client__c();
        insert client;
        Call_Log__c cl = new Call_Log__c();
        insert cl;
        Task t = new Task(WhatId = cl.Id, Subject = 'test');
        insert t;
        cl.PGI_Client__c = client.Id;
        update cl;
        t = [SELECT PGi_Client__c FROM Task];
        System.assertEquals(t.Pgi_Client__c, client.Id);
    }
}