force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Call Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Actionable (No further action required)</fullName>
            </value>
            <value>
                <fullName>Escalation Needed</fullName>
            </value>
            <value>
                <fullName>Follow Up On Existing Case</fullName>
            </value>
            <value>
                <fullName>Follow Up On Existing FinReq</fullName>
            </value>
            <value>
                <fullName>Other (Not actionable)</fullName>
            </value>
            <value>
                <fullName>Transferring Call</fullName>
            </value>
            <value>
                <fullName>Unsupported Product</fullName>
            </value>
            <value>
                <fullName>Wrong Number</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Escalation_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Record_Type__c</fullName>
    <label>Escalation Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Escalation_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Client External Support</fullName>
            </value>
            <value>
                <fullName>Reservations Request</fullName>
            </value>
            <value>
                <fullName>Internal Support</fullName>
            </value>
            <value>
                <fullName>Parent Ticket (NOC)</fullName>
            </value>
            <value>
                <fullName>Billing Support</fullName>
            </value>
            <value>
                <fullName>Company Credit Hold</fullName>
            </value>
            <value>
                <fullName>Credit Request</fullName>
            </value>
            <value>
                <fullName>Payment Research Request</fullName>
            </value>
            <value>
                <fullName>Pricing Help Request</fullName>
            </value>
            <value>
                <fullName>Profile Request</fullName>
            </value>
            <value>
                <fullName>Rate Entry Request</fullName>
            </value>
            <value>
                <fullName>Request for Adjustment</fullName>
            </value>
            <value>
                <fullName>Revenue Assurance Audit Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Escalation_Type__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Type__c</fullName>
    <label>Escalation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
            </value>
            <value>
                <fullName>FinReq</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be populated if provided from the DNIS/IVR,otherwise you can insert before escalating as needed.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be populated if provided from the DNIS/IVR,otherwise you can insert before escalating as needed.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case #</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Log__c/fields/Related_FinReq__c.field-meta.xml
<CustomField>
    <fullName>Related_FinReq__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related FinReq #</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Auto_Generated_For_Case__c.field-meta.xml
<CustomField>
    <fullName>Auto_Generated_For_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Generated For Case #</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Company ID.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Associated Client)</relationshipLabel>
    <relationshipName>Financial_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Related_Case__c.field-meta.xml
<CustomField>
    <fullName>Related_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Related_FinReq__c.field-meta.xml
<CustomField>
    <fullName>Related_FinReq__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Does this relate to another FinReq</inlineHelpText>
    <label>Related FinReq</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CallLogExtension.cls
public with sharing class CallLogExtension {
	private ApexPages.StandardController controller {get; set;}
	private Call_Log__c record { get {
		if(record == null) {
			record = (Call_Log__c)controller.getRecord();
		}
		return record;
	} set;}
	private class CallLogExtensionException extends Exception {}

	 //RT-228
	@RemoteAction
    public static PGI_Client__c getClientInfo(String clientName, Id clientId) {
        List<PGI_Client__c> clients = new List<PGi_Client__c>();
        try {
            if(!String.isBlank(clientId)) {
                clients = [SELECT Id, PGI_Company__c, PGI_Company__r.Name FROM PGI_Client__c WHERE Id =: clientId]; 
            } 
			if(clients.size() == 0) {
                clients = [SELECT Id, PGI_Company__c, PGI_Company__r.Name FROM PGI_Client__c WHERE Name =: clientName]; 
            }
			if(clients.size() > 0) {
				return clients[0];
			}
        } catch (exception e) {
            System.debug(e);
        }
        return null;
    }
	
	private String i {get {
		i = (Id)ApexPages.currentPage().getParameters().get('Id');
		if(String.isBlank(i)) {
			i = (Id)ApexPages.currentPage().getParameters().get('Call_Log__c.Id');
		}
		return i;
	} set;}
	public static List<String> fieldList = new List<String>(Schema.getGlobalDescribe().get('Call_Log__c').getDescribe().fields.getMap().keyset()); 
	public CallLogExtension (ApexPages.StandardController controller) {
        if(String.isNotBlank(i)) {
			ApexPages.currentPage().getParameters().put('Id', i);
		}
		if(!Test.isRunningTest()){ 
            // Add fields to controller. This is to avoid the SOQL error in visualforce page
            controller.addFields(fieldList);
        }
		
		this.controller = controller;
		if(!Test.isRunningTest()){
			//id theRecordTypeIdToDescribe = LayoutDescriberHelper.LayoutDescriberHelper.getDefaultRecordType(record);
			//get the layout section items
			layoutSections = LayoutDescriberHelper.describeSectionWithFields(LayoutDescriberHelper.getDefaultRecordType(record), 'Call_Log__c');
			//get the assignment section for displaying 
			assignmentSections = LayoutDescriberHelper.describeAssignment(LayoutDescriberHelper.getDefaultRecordType(record), 'Call_Log__c');
		}
	}
	private Id getRecordType(String objectName, String rtName) {
		String pgiRtName = 'PGi-' + rtName;
		List<RecordType> rtList = [SELECT Id FROM RecordType WHERE sObjectType =: objectName AND (Name =: rtName OR Name =: pgiRtName)];
		if(rtList.size() > 0) {
			return rtList[0].Id;
		} else {
			return null;
		}
	}
	public PageReference createCallLog() {
		try {
			if(record.Id == null) {
				if(record.Call_Status__c == 'Escalation Needed') {
					String recordType = record.Escalation_Record_Type__c;
					String escalationType = record.Escalation_Type__c;
					if (escalationType == 'Case') {
						escalationType = record.Escalation_Type__c;
						String recordTypeId = getRecordType('Case', recordType);
						if(String.isBlank(recordTypeId)) {
							throw new CallLogExtensionException('No valid record type named ' + recordType);
						}
						Case c = (Case)Case.sObjectType.newSObject(recordTypeId, true);
						c.PGi_Client__c = record.PGi_Client__c;
						c.PGi_Company__c = record.PGi_Company__c;
						c.IsEscalated = true;
						// STRAT RT-431: Automatically run assignment rules for the new Case created.
						Database.DMLOptions dmo = new Database.DMLOptions();
						dmo.assignmentRuleHeader.useDefaultRule = true;
						c.setOptions(dmo);

						insert c;
						System.debug('The id Is'+c.Id);
						record.Related_Case__c = c.Id;
						insert record;
						PageReference p = new PageReference('/apex/CaseTabViewer');
						// p.getParameters().put('email', emailMsgLst);
						p.getParameters().put('id', c.Id);
						p.getParameters().put('isNew', 'true');
						p.getParameters().put('RecordType', recordTypeId);
						p.setRedirect(true);
						return p;
						//return new PageReference('/'+ c.Id + '/e');
					} else if (escalationType == 'FinReq') {
						String recordTypeId = getRecordType('Financial_Request__c', recordType);
						if(String.isBlank(recordTypeId)) {
							throw new CallLogExtensionException('No valid record type named ' + recordType);
						}
						Financial_Request__c f = (Financial_Request__c)Financial_Request__c.sObjectType.newSObject(recordTypeId, true);
						f.PGi_Client__c = record.PGi_Client__c;
						f.PGi_Company__c = record.PGi_Company__c;
						insert f;
						record.Related_FinReq__c = f.Id;
						insert record;
						return new PageReference('/'+ f.Id + '/e');
	 				} else if (String.isBlank(recordType) || String.isBlank(escalationType)) {
	 					throw new CallLogExtensionException('For Status = Escalation Needed, must populate Escalation Type and Record Type');
	 				}
				} else {
					insert record;
				}
			} else {
				if(record.Call_Status__c == 'Escalation Needed' && String.isBlank(record.Related_Case__c)) {
					String recordType = record.Escalation_Record_Type__c;
					String escalationType = record.Escalation_Type__c;
					if (escalationType == 'Case') {
						escalationType = record.Escalation_Type__c;
						String recordTypeId = getRecordType('Case', recordType);
						if(String.isBlank(recordTypeId)) {
							throw new CallLogExtensionException('No valid record type named ' + recordType);
						}
						Case c = (Case)Case.sObjectType.newSObject(recordTypeId, true);
						c.PGi_Client__c = record.PGi_Client__c;
						c.PGi_Company__c = record.PGi_Company__c;
						c.Auto_Generated_For_Case__c = true;
						// STRAT RT-431: Automatically run assignment rules for the new Case created.
						Database.DMLOptions dmo = new Database.DMLOptions();
						dmo.assignmentRuleHeader.useDefaultRule = true;
						c.setOptions(dmo);

						insert c;
						System.debug('The id Is'+c.Id);
						record.Related_Case__c = c.Id;
						update record;

						// related RT-431: users dont have to set default on the page layouts,remember to check the box and can't uncheck the box
						PageReference p = new PageReference('/apex/CaseTabViewer');
						// p.getParameters().put('email', emailMsgLst);
						p.getParameters().put('id', c.Id);
						p.getParameters().put('isNew', 'true');
						p.getParameters().put('RecordType', recordTypeId);
						p.setRedirect(true);
        				return p;
						//return new PageReference('/'+ c.Id + '/e');
					} else if (escalationType == 'FinReq' && String.isBlank(record.Related_FinReq__c)) {
						String recordTypeId = getRecordType('Financial_Request__c', recordType);
						if(String.isBlank(recordTypeId)) {
							throw new CallLogExtensionException('No valid record type named ' + recordType);
						}
						Financial_Request__c f = (Financial_Request__c)Financial_Request__c.sObjectType.newSObject(recordTypeId, true);
						f.PGi_Client__c = record.PGi_Client__c;
						f.PGi_Company__c = record.PGi_Company__c;
						insert f;
						record.Related_FinReq__c = f.Id;
						update record;
						return new PageReference('/'+ f.Id + '/e');
	 				} else if (String.isBlank(recordType) || String.isBlank(escalationType)) {
	 					throw new CallLogExtensionException('For Status = Escalation Needed, must populate Escalation Type and Record Type');
	 				}
	 			}
	 			update record;
			}

		//	Upon saving, IF a user selected the Call Status of "Escalation Needed" they must pick which object (Case or FinReq) and which Record Type. 
		// Based off what they select, we want the user experience to be that they then select SAVE it should automatically take them into the new record that needs creating so they can begin creating that escalation record:
		//When going into the escalation record the PGi Client and PGi Company fields should carry forward IF they were populated on the Call Log
		//	IF creating a Case from the escalation process, please set the Case Origin value to "Direct Dial" if we can
		//	Once that record is saved, it should populate the "Related Case #" or the "Related FinReq #" back on the original Call Log so that the records are associated to each other.
		} catch (exception ex) {
			System.debug(ex);
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage()));
			return null;
		}
		return new PageReference('/' + record.Id);
	}
	public List<LayoutDescriberHelper.LayoutSection> 	layoutSections {get; set; }
	public List<LayoutDescriberHelper.AssignmentModel> 	assignmentSections {get; set; }
}