force-app/main/default/objects/Call_Log__c/Call_Log__c.object-meta.xml
<CustomObject>
    <label>Call Log</label>
    <nameField>
        <displayFormat>CL-{0000}</displayFormat>
        <label>Call Log #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Log__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be populated if provided from the DNIS/IVR,otherwise you can insert before escalating as needed.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Call Logs</relationshipLabel>
    <relationshipName>Call_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RequestorsEmail__c.field-meta.xml
<CustomField>
    <fullName>RequestorsEmail__c</fullName>
    <label>Requestor&#39;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TaskTriggerHandlerTest.cls
@isTest
private class TaskTriggerHandlerTest {
	
	@TestSetup
	static void makeData(){
		PGi_Client__c objPgiClient = new PGi_Client__c(name = 'test 0001');
		INSERT objPgiClient;
        
		Call_Log__c callLogObj = new Call_Log__c();
        callLogObj.PGi_Client__c = objPgiClient.Id;
        INSERT callLogObj;
        
		Id PgiClientRecordType = [SELECT Id FROM RecordType WHERE SobjectType = 'Case' AND DeveloperName = 'PGi_Client_VIP_Request'].Id;
		Case objCase = new Case(Type = 'Issue', Status = 'New', Subject= 'Test', Description = 'test abnn', 
								RequestorsEmail__c ='fake@fake.com', RecordTypeId = PgiClientRecordType, PGi_Client__c = objPgiClient.Id  );
		INSERT objCase;
        
		List<Task> taskList =  new List<Task>();		
		Task objTask =PGITestUtilities.getTaskDetails(objCase.Id);
        taskList.add(objTask);
        Task objTaskCall =PGITestUtilities.getTaskDetails(callLogObj.Id);
        taskList.add(objTaskCall);
		INSERT taskList;
	} 
	
	@isTest static void test_methodOne() {
        Case objCase = [SELECT Id FROM Case Limit 1 ];
		PGi_Client__c pgiClient = [SELECT Id FROM PGi_Client__c Limit 1 ];
		Task objTask = [SELECT Id, PGi_Client__c FROM Task where whatId =: objCase.ID  Limit 1];
		System.assertEquals(pgiClient.Id, objTask.PGi_Client__c);
        
        Call_Log__c callLogObj = [SELECT Id FROM Call_Log__c Limit 1 ];
        Task objTaskCall = [SELECT Id, PGi_Client__c FROM Task where whatId =: callLogObj.ID  Limit 1];
		System.assertEquals(pgiClient.Id, objTaskCall.PGi_Client__c);
	}
	
}