force-app/main/default/objects/Contract_Terms__c/Contract_Terms__c.object-meta.xml
<CustomObject>
    <label>CPQ - Contract Product Verbiage</label>
    <nameField>
        <label>Contract Product Verbiage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Contract Product Verbiage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract_Terms__c/fields/Version_History__c.field-meta.xml
<CustomField>
    <fullName>Version_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Version History</label>
    <referenceTo>Version_History__c</referenceTo>
    <relationshipLabel>CPQ - Contract Product Verbiage</relationshipLabel>
    <relationshipName>CPQ_Contract_Product_Verbiage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Version_History__c/Version_History__c.object-meta.xml
<CustomObject>
    <description>To store the details of Compared Versions</description>
    <label>Version History</label>
    <nameField>
        <label>Version History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VersionTriggerHandlerTest.cls
@isTest
public without sharing class VersionTriggerHandlerTest {
    @testSetup static void setup() {
        Contract_Terms__c contractObject = new Contract_Terms__c(
            Language__c = 'en_US',
            Name = 'Test 001',
            Unique_ID__c = 'Test Unique'
        );
        Insert contractObject;
        Contract_Terms__c contractObject2 = new Contract_Terms__c(
            Language__c = 'en_UK',
            Name = 'Test 002',
            Unique_ID__c = 'Test Unique 1'
        );
        Insert contractObject2;
    }
    static  testmethod void testCreateNewAttachment(){
        Contract_Terms__c contractObject = [SELECT Language__c, Name, Version_History__c
                                            FROM Contract_Terms__c 
                                            WHERE name = 'Test 001' ];
        contractObject.Language__c = 'en_UK';
        UPDATE contractObject; 
        String verHistoryId = [SELECT  Version_History__c FROM Contract_Terms__c 
                                WHERE id =: contractObject.Id].Version_History__c;
        AggregateResult agregatedResults =[SELECT ParentId, COUNT(Id) size 
                                            FROM Attachment 
                                            WHERE ParentId =: verHistoryId
                                            GROUP BY ParentId ]; 
         System.assertEquals(2,agregatedResults.get('size'));       
    }
    static  testmethod void testExsitingAttachment(){
        Contract_Terms__c contractObject = [SELECT Language__c, Name,Version_History__c 
                                            FROM Contract_Terms__c
                                            WHERE name = 'Test 002' ];
        contractObject.Language__c = 'en_US';
        UPDATE contractObject;   
        contractObject.Name ='Test 003';
        UPDATE contractObject;   
        String verHistoryId = [SELECT  Version_History__c FROM Contract_Terms__c 
                                WHERE id =: contractObject.Id].Version_History__c;
        AggregateResult agregatedResults = [SELECT ParentId, COUNT(Id) size 
                                            FROM Attachment 
                                            WHERE ParentId =: verHistoryId
                                            GROUP BY ParentId ]; 
       System.assertEquals(3,agregatedResults.get('size'));  
    }
}