force-app/main/default/objects/NetSuite_Financial__c/NetSuite_Financial__c.object-meta.xml
<CustomObject>
    <description>Posting transactions from NetSuite including Cash Sales, Invoices, Customer Payments, Credit Memos, Cash Refunds, Journal Entries, etc.</description>
    <label>Financial</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NetSuite_Financial__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Displays account name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Shipping_Total__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Total__c</fullName>
    <description>Shipping subtotal.</description>
    <label>Shipping Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <description>Transaction subtotal before any discounts, shipping cost, handling cost or tax.</description>
    <inlineHelpText>Amount due (total charges + FUSF) for invoice transaction.</inlineHelpText>
    <label>Subtotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <description>Transaction total.</description>
    <inlineHelpText>If invoice transaction, displays total amount due.
If payment transaction, shows payment total.</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Type of transaction (cash sale, invoice, payment, credit memo, cash refund, customer refund, customer deposit).</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash Refund</fullName>
            </value>
            <value>
                <fullName>Cash Sale</fullName>
            </value>
            <value>
                <fullName>Credit Memo</fullName>
            </value>
            <value>
                <fullName>Customer Deposit</fullName>
            </value>
            <value>
                <fullName>Customer Refund</fullName>
            </value>
            <value>
                <fullName>Deferred Revenue</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Sales Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CeligoTestCreditMemoTotal.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class CeligoTestCreditMemoTotal {

  @isTest static void myUnitTest() {
        NetSuite_Financial__c credit = new NetSuite_Financial__c();
        Account a = MockAccount.getNewAccount();
        credit.Subtotal__c = 1.25;
        credit.Total__c = 1.50;
        credit.Shipping_Total__c = 0.25;
        credit.Name = 'Test Credit';
        credit.Type__c = 'Credit Memo';
        credit.Account__c = a.id;
        
        NetSuite_Financial__c invoice = new NetSuite_Financial__c();
        invoice.Subtotal__c = 2.00;
        invoice.Total__c = 2.50;
        invoice.Name = 'Test Invoice';
        invoice.Type__c = 'Invoice';
        invoice.Account__c = a.id;
        
        insert credit;
        insert invoice;
        
      system.debug('idd>>'+credit.id);
        NetSuite_Financial__c finCredit = [SELECT Id, Subtotal__c, Total__c 
                                           FROM NetSuite_Financial__c 
                                           WHERE ID = :credit.Id];
        NetSuite_Financial__c finInvoice = [SELECT Id, Subtotal__c, Total__c 
                                            FROM NetSuite_Financial__c 
                                            WHERE ID = :invoice.Id];
        
        System.assertEquals(finCredit.Subtotal__c, -1.25);
        System.assertEquals(finCredit.Total__c, -1.50);
        System.assertEquals(finInvoice.Subtotal__c, 2.00);
        System.assertEquals(finInvoice.Total__c, 2.50);
        
    }
}