force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent To Customer</fullName>
            </value>
            <value>
                <fullName>Customer Accepted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contract Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Contract Pricing Rejected</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Manager Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting RVP Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting SVP Approval</fullName>
            </value>
            <value>
                <fullName>Pending Pricing Approval</fullName>
            </value>
            <value>
                <fullName>Downloaded</fullName>
            </value>
            <value>
                <fullName>Pending Legal Approval</fullName>
            </value>
            <value>
                <fullName>Legal Approved</fullName>
            </value>
            <value>
                <fullName>Legal Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>agTempValue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Owners_RVP__c.field-meta.xml
<CustomField>
    <fullName>Owners_RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner&apos;s RVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RVP_on_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Owners_SVP__c.field-meta.xml
<CustomField>
    <fullName>Owners_SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner&apos;s SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SVP_on_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Legal__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Legal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Legal Approval.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Legal Approval.</inlineHelpText>
    <label>Required Approval: Legal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Pricing_RVP__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Pricing_RVP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Pricing Approval from the owner&#39;s RVP.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Pricing Approval from the owner&#39;s RVP.</inlineHelpText>
    <label>Required Approval: Pricing - RVP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Pricing_SVP__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Pricing_SVP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Pricing Approval from the owner&apos;s SVP.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Pricing Approval from the owner&apos;s SVP.</inlineHelpText>
    <label>Required Approval: Pricing - SVP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/recordTypes/iContract.recordType-meta.xml
<RecordType>
    <fullName>iContract</fullName>
    <active>true</active>
    <description>NA Contract going through the iContract system</description>
    <label>NA Contract</label>
</RecordType>

force-app/main/default/objects/User/fields/RVP__c.field-meta.xml
<CustomField>
    <fullName>RVP__c</fullName>
    <label>RVP</label>
    <relationshipName>RVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <label>SVP</label>
    <relationshipName>SVP</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/test_iContractStartLegalApproval.cls
@isTest
public class test_iContractStartLegalApproval {
     @testSetup static void setup() {
       PGITestUtilities.disableSalesWings();
    }
	
    private static String LOG_TAG = 'iContractStartLegalApproval:';
    private static final String REQUEST_URI = '/services/apexrest/iContractStartApproval/';
    
    static String request(String parameters) {
        RestRequest req   = new RestRequest();
        RestResponse res   = new RestResponse();
        req.requestURI     = REQUEST_URI + parameters;
        req.httpMethod     = 'GET';

        RestContext.request = req;
        RestContext.response= res;
        return iContractStartLegalApproval.ApprovalRequest();
    }

    static testMethod void test_NoApprovalRequest() {
        System.debug(LOG_TAG + 'test_NoApprovalRequest Initializing!');
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Status__c = 'New';
        insert ctrctest;
        
        System.debug(LOG_TAG + 'test_NoApprovalRequest Started!');
        test.startTest();
        
        system.assertEquals(iContract.UNNECESSARY, request(ctrctest.id));
        CONMAN_Contract__c foundContract = [SELECT CreatedDate, Contract_Status__c from CONMAN_Contract__c where id= :ctrctest.id];
        system.assertEquals(ctrctest.id, foundContract.Id);
        
		system.assertEquals('New',  foundContract.Contract_Status__c, 'Contract Status not changed');

        try {
            ProcessInstance pi = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ctrctest.id];
        	System.assert(false, 'Approval Process found on Contract!');
        } catch (Exception e) {
        	System.assert(true, 'No Approval Process on Contract');
        }
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_NoApprovalRequest Finished!');
    }

    static testMethod void test_RVPApprovalRequest() {
        System.debug(LOG_TAG + 'test_RVPApprovalRequest Initializing!');
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User m = new User(Alias = 'standtm', Email='standardusermanager@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber='12345', 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusermanager@pgi.com');
        insert m;
        User u = new User(Alias = 'standt', Email='standarduser@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, RVP__c = m.Id, EmployeeNumber='12345',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@pgi.com');
        insert u;
        
        ConMan_Contract__c ctrctest;
        System.runAs(u) {
            Account accttest = PGITestUtilities.getAccountDetails();
            insert accttest;
            
            Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
            insert opptytest;
            
            Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
            insert cntcttest;
            
            ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
            ctrctest.OwnerId = u.Id;
            ctrctest.Owners_RVP__c = m.Id;
            ctrctest.Required_Approval_Pricing_RVP__c = true;
            ctrctest.Required_Approval_Pricing_SVP__c = false;
            insert ctrctest;
        
        	system.assertEquals(iContract.SUCCESS, request(ctrctest.id));
        }
        
        System.debug(LOG_TAG + 'test_RVPApprovalRequest Started!');
        test.startTest();
        
        CONMAN_Contract__c foundContract = [SELECT CreatedDate, Contract_Status__c from CONMAN_Contract__c where id= :ctrctest.id];
        system.assertEquals(ctrctest.id, foundContract.Id);
        
		system.assertEquals('Pending Approval',  foundContract.Contract_Status__c, 'Contract Status not changed');

        ProcessInstance pi = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ctrctest.id];
        System.assertEquals(foundContract.CreatedDate.Date(), pi.CreatedDate.Date(), 'No Approval Process on Contract');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_RVPApprovalRequest Finished!');
    }

    static testMethod void test_SVPApprovalRequest() {
        System.debug(LOG_TAG + 'test_SVPApprovalRequest Initializing!');
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User m = new User(Alias = 'standtm', Email='standardusermanager@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber='12345',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusermanager@pgi.com');
        insert m;
        User u = new User(Alias = 'standt', Email='standarduser@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, SVP__c = m.Id, EmployeeNumber='12345',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@pgi.com');
        insert u;
        
        ConMan_Contract__c ctrctest;
        System.runAs(u) {
            Account accttest = PGITestUtilities.getAccountDetails();
            insert accttest;
            
            Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
            insert opptytest;
            
            Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
            insert cntcttest;
            
            ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
            ctrctest.OwnerId = u.Id;
            ctrctest.Owners_SVP__c = m.Id;
            ctrctest.Required_Approval_Pricing_SVP__c = true;
             ctrctest.Required_Approval_Pricing_RVP__c = false;
            insert ctrctest;
                
        	system.assertEquals(iContract.SUCCESS, request(ctrctest.id));
        }
        
        System.debug(LOG_TAG + 'test_SVPApprovalRequest Started!');
        test.startTest();
        
        CONMAN_Contract__c foundContract = [SELECT CreatedDate, Contract_Status__c from CONMAN_Contract__c where id= :ctrctest.id];
        system.assertEquals(ctrctest.id, foundContract.Id);
        
		system.assertEquals('Pending Approval',  foundContract.Contract_Status__c, 'Contract Status not changed');

        ProcessInstance pi = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ctrctest.id];
        System.assertEquals(foundContract.CreatedDate.Date(), pi.CreatedDate.Date(), 'No Approval Process on Contract');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_SVPApprovalRequest Finished!');
    }

    static testMethod void test_NoRVPApprovalRequest() {
        System.debug(LOG_TAG + 'test_NoRVPApprovalRequest Initializing!');
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User u = new User(Alias = 'standt', Email='standarduser@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber='12345',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@pgi.com');
        insert u;
        
        ConMan_Contract__c ctrctest;
        System.runAs(u) {
            Account accttest = PGITestUtilities.getAccountDetails();
            insert accttest;
            
            Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
            insert opptytest;
            
            Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
            insert cntcttest;
            
            ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
            ctrctest.Required_Approval_Pricing_RVP__c = true;
            ctrctest.Contract_Status__c = 'New';
            ctrctest.OwnerId = u.Id;
            insert ctrctest;
            
        	system.assertEquals(iContract.SUCCESS, request(ctrctest.id));
        }
        
        System.debug(LOG_TAG + 'test_NoRVPApprovalRequest Started!');
        test.startTest();
        
        CONMAN_Contract__c foundContract = [SELECT CreatedDate, Contract_Status__c from CONMAN_Contract__c where id= :ctrctest.id];
        system.assertEquals(ctrctest.id, foundContract.Id);
        
		system.assertEquals('Rejected',  foundContract.Contract_Status__c, 'Contract Status not changed');

        try {
            ProcessInstance pi = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ctrctest.id];
        	System.assert(true, 'Approval Process not found on Contract!');
        } catch (Exception e) {
        	System.assert(false, 'Approval Process found on Contract');
        }
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_NoRVPApprovalRequest Finished!');
    }

    static testMethod void test_LegalApprovalRequest() {
        System.debug(LOG_TAG + 'test_LegalApprovalRequest Initializing!');
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User m = new User(Alias = 'standtm', Email='standardusermanager@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber='12345',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardusermanager@pgi.com');
        User u = new User(Alias = 'standt', Email='standarduser@pgi.com', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, EmployeeNumber='12345',
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduser@pgi.com',
                          Manager=m);
        insert m;
        insert u;
        
        ConMan_Contract__c ctrctest;
        System.runAs(u) {
            Account accttest = PGITestUtilities.getAccountDetails();
            insert accttest;
            
            Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
            insert opptytest;
            
            Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
            insert cntcttest;
            
            ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
            ctrctest.Required_Approval_Legal__c = true;
            ctrctest.OwnerId = u.Id;
            insert ctrctest;
            
        	system.assertEquals(iContract.SUCCESS, request(ctrctest.id));
        }
        
        System.debug(LOG_TAG + 'test_LegalApprovalRequest Started!');
        test.startTest();
        
        CONMAN_Contract__c foundContract = [SELECT CreatedDate, Contract_Status__c from CONMAN_Contract__c where id= :ctrctest.id];
        system.assertEquals(ctrctest.id, foundContract.Id);
        
		system.assertEquals('Pending Approval',  foundContract.Contract_Status__c, 'Contract Status not changed');

        ProcessInstance pi = [SELECT TargetObjectId, CreatedDate FROM ProcessInstance WHERE TargetObjectId = :ctrctest.id];
        System.assertEquals(foundContract.CreatedDate.Date(), pi.CreatedDate.Date(), 'No Approval Process on Contract');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_LegalApprovalRequest Finished!');
    }
}