force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Status__c</fullName>
    <label>Contract Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sent To Customer</fullName>
            </value>
            <value>
                <fullName>Customer Accepted</fullName>
            </value>
            <value>
                <fullName>Customer Rejected</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Contract Pricing Approved</fullName>
            </value>
            <value>
                <fullName>Contract Pricing Rejected</fullName>
            </value>
            <value>
                <fullName>Awaiting Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Manager Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting RVP Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting SVP Approval</fullName>
            </value>
            <value>
                <fullName>Pending Pricing Approval</fullName>
            </value>
            <value>
                <fullName>Downloaded</fullName>
            </value>
            <value>
                <fullName>Pending Legal Approval</fullName>
            </value>
            <value>
                <fullName>Legal Approved</fullName>
            </value>
            <value>
                <fullName>Legal Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>agTempValue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Deal_Desk_Approved__c.field-meta.xml
<CustomField>
    <fullName>Deal_Desk_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is set by the Approval Process in order to trigger limit modifications.</description>
    <inlineHelpText>This is set by the Approval Process in order to trigger limit modifications.</inlineHelpText>
    <label>Deal Desk Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Product_Details_Were_Manually_Changed__c.field-meta.xml
<CustomField>
    <fullName>Product_Details_Were_Manually_Changed__c</fullName>
    <label>Product Details Were Manually Changed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Related_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Related_Account_Name__c</fullName>
    <formula>Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Related_Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Ultimate_Parent_Account__c</fullName>
    <formula>Account_Name__r.Ultimate_Parent_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Ultimate Parent Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/T_Cs_Were_Manually_Changed__c.field-meta.xml
<CustomField>
    <fullName>T_Cs_Were_Manually_Changed__c</fullName>
    <label>T&amp;Cs Were Manually Changed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Contracts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>PGi_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CPQ_Contract_Approved_Version__c/CPQ_Contract_Approved_Version__c.object-meta.xml
<CustomObject>
    <description>When a PGi Contract is approved, one of these records are created with a PDF attachment of the Contract.</description>
    <label>CPQ - Contract Approved Version</label>
    <nameField>
        <displayFormat>CAV-{00000}</displayFormat>
        <label>CPQ - Contract Approved Version Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CPQ - Contract Approved Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQ_Contract_Approved_Version__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>CPQ - Contract Approved Versions</relationshipLabel>
    <relationshipName>CPQ_Contract_Approved_Versions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PGiContractTriggerHandler.cls
public without sharing class PGiContractTriggerHandler extends TriggerHandler {
	public PGiContractTriggerHandler() {
		super('PGiContractTriggerHandler');
	}
	protected override void beforeUpdate(){ 
		updateUltimateParentAccount();
		// validateDealDesk();
	}
	protected override void beforeInsert(){ 
		updateUltimateParentAccount();
	}
	protected override void afterInsert() {
		closeOpp();
	}
	protected override void afterUpdate() {
		closeOpp();
		checkApprovedContracts();
	}
	// Set CONMAN_Contract__c.Ultimate_Parent_Account__c
	// CONMAN_Contract__c.Related_Ultimate_Parent_Account__c
	// CONMAN_Contract__c.Related_Account_Name__c
	private void updateUltimateParentAccount() {
		for(CONMAN_Contract__c pgiContract : (List<CONMAN_Contract__c>)Trigger.new) {
			if(pgiContract.Ultimate_Parent_Account__c != pgiContract.Related_Ultimate_Parent_Account__c && !pgiContract.Related_Account_Name__c.contains('unmatch')) {
				pgiContract.Ultimate_Parent_Account__c = pgiContract.Related_Ultimate_Parent_Account__c;
			}
		}
	}
	// private void validateDealDesk(){
	// 	for(CONMAN_Contract__c contract: (List<CONMAN_Contract__c>)Trigger.new) {
	// 		CONMAN_Contract__c oldValue = (CONMAN_Contract__c)Trigger.oldMap.get(contract.Id);
	// 		if(contract.Deal_Desk_Approved__c == true && oldValue.Deal_Desk_Approved__c == false) {
	// 			if(contract.T_Cs_Were_Manually_Changed__c == null || contract.Product_Details_Were_Manually_Changed__c == null){
    // 				contract.addError('Please edit the PGi Contract and specify a value for the following fields: \'T&Cs Were Manually Changed\' and \'Product Details Were Manually Changed\'');
	// 			}
	// 		}
	// 	}
	// }
	private void closeOpp() {
		Map<Id, Opportunity> oppsToUpdate = new Map<Id, Opportunity>();
		for(CONMAN_Contract__c cont: (List<CONMAN_Contract__c>)Trigger.new) {
			if(isChanged('Contract_Status__c', cont) && cont.Contract_Status__c == 'Customer Accepted') {
				Opportunity opp = relatedOpp.get(cont.Opportunity__c);
				if(opp != null  && opp.RecordType.Name == 'PGi Opportunity') {
					if(opp.isClosed == false && opp.StageName != 'Closed Pending Approval' && opp.StageName != 'Closed Won') {
						opp.StageName = 'Closed Pending Approval';
						oppsToUpdate.put(opp.Id, opp);
					} 
				} 
			}
		}
		update oppsToUpdate.values();
	}

	private static Set<Id> approvedIdsProcessed = new Set<Id>();
	private void checkApprovedContracts(){
		Set<Id> approvedContractIds = new Set<Id>();
		for(CONMAN_Contract__c contract : (List<CONMAN_Contract__c>)Trigger.new) {
			if(isChanged('Contract_Status__c', contract) && contract.Contract_Status__c == 'Approved' && !approvedContractIds.contains(contract.Id)) {
				approvedContractIds.add(contract.Id);
			}
		}
		if (!approvedContractIds.isEmpty()){
			approvedIdsProcessed.addAll(approvedContractIds);
			createApprovedVersion(approvedContractIds);
		}
	}

	@future(callout=true)
	private static void createApprovedVersion(Set<Id> approvedContractIds) {
		List<CPQ_Contract_Approved_Version__c> approvedVersionsToCreate = new List<CPQ_Contract_Approved_Version__c>();
		Map<Id, Attachment> attachmentsToCreateMap = new Map<Id, Attachment>();

		List<CONMAN_Contract__c> contracts = new List<CONMAN_Contract__c>([SELECT Id, Contract_Status__c FROM CONMAN_Contract__c WHERE Id IN :approvedContractIds]);
		for(CONMAN_Contract__c contract : contracts) {
			CPQ_Contract_Approved_Version__c approvedVersion = new CPQ_Contract_Approved_Version__c();
			approvedVersion.PGi_Contract__c = contract.Id;
			approvedVersionsToCreate.add(approvedVersion);

			PageReference contractPdf = Page.iContract_NA_Master;
			contractPdf.getParameters().put('id', contract.Id);
			contractPdf.getParameters().put('pdfDownload', 'true');

			Attachment att = new Attachment();
			att.Name = 'Approved Version - ' + Datetime.now().format('yyyy-MM-dd') + '.pdf';
			if (!System.Test.isRunningTest()){
				att.body = contractPdf.getContent();
			} else {
				att.body = EncodingUtil.convertFromHex('00000000000000000000000000000000');
			}
			attachmentsToCreateMap.put(contract.Id, att);
		}		
		if (approvedVersionsToCreate.size() > 0) {
			insert approvedVersionsToCreate;
			for (CPQ_Contract_Approved_Version__c approvedVersion : approvedVersionsToCreate){
				attachmentsToCreateMap.get(approvedVersion.PGi_Contract__c).parentId = approvedVersion.Id;
			}
			insert attachmentsToCreateMap.values();
		}
	}

	private static Map<Id, Opportunity> relatedOpp {get {
		if(relatedOpp == null) {
			Set<Id> oppIds = new Set<Id>();
			for(CONMAN_Contract__c cont: (List<CONMAN_Contract__c>)Trigger.new) {
				oppIds.add(cont.Opportunity__c);
			}
			oppIds.remove(null);
			relatedOpp = new Map<Id, Opportunity>([SELECT Id, IsClosed,RecordType.Name, StageName FROM Opportunity WHERE Id in: OppIds AND RecordType.Name = 'PGi Opportunity']);
		}
		return relatedOpp;
	} set;}
}