force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Owners_RVP__c.field-meta.xml
<CustomField>
    <fullName>Owners_RVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner&apos;s RVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RVP_on_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Owners_SVP__c.field-meta.xml
<CustomField>
    <fullName>Owners_SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner&apos;s SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SVP_on_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_ARG__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_ARG__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Pricing Approval from ARG Team.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Pricing Approval from ARG Team.</inlineHelpText>
    <label>Required Approval: ARG</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Billing__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required Approval: Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Deal_Desk__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Deal_Desk__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Pricing Approval from the Deal Desk.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Pricing Approval from the Deal Desk.</inlineHelpText>
    <label>Required Approval: Deal Desk</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Legal__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Legal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Legal Approval.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Legal Approval.</inlineHelpText>
    <label>Required Approval: Legal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Pricing_RVP__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Pricing_RVP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Pricing Approval from the owner&#39;s RVP.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Pricing Approval from the owner&#39;s RVP.</inlineHelpText>
    <label>Required Approval: Pricing - RVP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Pricing_SVP__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Pricing_SVP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Pricing Approval from the owner&apos;s SVP.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Pricing Approval from the owner&apos;s SVP.</inlineHelpText>
    <label>Required Approval: Pricing - SVP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/recordTypes/iContract.recordType-meta.xml
<RecordType>
    <fullName>iContract</fullName>
    <active>true</active>
    <description>NA Contract going through the iContract system</description>
    <label>NA Contract</label>
</RecordType>

force-app/main/default/classes/iContractStartLegalApproval.cls
@RestResource(urlMapping='/iContractStartApproval/*')
// While the class is called 'LegalApproval', this now starts the normal 'Approval'
global class iContractStartLegalApproval {
    @HttpGet
    global static String ApprovalRequest() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String contractIdRequest = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Id contractId;
        try {
            contractId = contractIdRequest;
        } catch (Exception e) {
            return 'Invalid PGi Contract ID: ' + contractIdRequest;
        }	
        
        CONMAN_Contract__c foundContract = [SELECT Id, OwnerId, Owner.Email, Owner.Name,
                                            Required_Approval_ARG__c,
                                            Required_Approval_Legal__c,
                                            Required_Approval_Pricing_RVP__c,
                                            Required_Approval_Pricing_SVP__c,
                                            Required_Approval_Deal_Desk__c,
                                            Required_Approval_Billing__c,
                                            Owners_RVP__r.Email, Owners_SVP__r.Email
                                            FROM CONMAN_Contract__c
                                            WHERE id = :contractId];

        // Simply return an 'unnecessary' message when nothing was required
        if (!foundContract.Required_Approval_Billing__c &&
            !foundContract.Required_Approval_Legal__c &&
            !foundContract.Required_Approval_Pricing_RVP__c &&
            !foundContract.Required_Approval_Pricing_SVP__c &&
            !foundContract.Required_Approval_Deal_Desk__c &&
            !foundContract.Required_Approval_ARG__c) {
                return iContract.UNNECESSARY;
            }
        
        
  //      try {
            // Start by submitting for approval
            String result = iContract.startApproval(foundContract.Id, foundContract.OwnerId);
            
        	// Send a 'skipped' email to RVP and SVP (Approval Process cannot do anything with them)
            if (result == iContract.SUCCESS &&
                foundContract.Required_Approval_Deal_Desk__c &&
                (foundContract.Required_Approval_Pricing_RVP__c || foundContract.Required_Approval_Pricing_SVP__c)) {
                    
            		// Render email
                    EmailTemplate templateId = [SELECT Id FROM EmailTemplate WHERE Name = 'iContract Submitted for Approval (Skipped)'];
                    Messaging.SingleEmailMessage mail = Messaging.renderStoredEmailTemplate(templateId.Id, foundContract.OwnerId, foundContract.Id);
                    mail.setSenderDisplayName(foundContract.Owner.Email);
                    mail.setReplyTo(foundContract.Owner.Email);
                    List<String> emailAddresses = new List<String>();
                    if (foundContract.Required_Approval_Pricing_RVP__c)
                        emailAddresses.add(foundContract.Owners_RVP__r.Email);
                    if (foundContract.Required_Approval_Pricing_SVP__c)
                        emailAddresses.add(foundContract.Owners_SVP__r.Email);
                    mail.setToAddresses(emailAddresses);
                    mail.setSaveAsActivity(false);

            		// Send email
                    List<Messaging.SingleEmailMessage> allEmails = new List<Messaging.SingleEmailMessage>();
                    allEmails.add(mail);
                    List<Messaging.SendEmailResult> emailResults = Messaging.sendEmail(allEmails, false);
            
            		// Check for issues
            		String emailErrorMessage = '';
                    for (Messaging.SendEmailResult emailResult : emailResults) {
                        emailErrorMessage = '';
                    	for (Messaging.SendEmailError error : emailResult.getErrors())
                            emailErrorMessage += error.getMessage() + '\n';
                        if (!emailResult.isSuccess() || !String.isEmpty(emailErrorMessage))
                            System.debug('Unable to send emails: ' + emailErrorMessage);
                    }
                }
            
            return result;
     /*   } catch (Exception e) {
            return iContract.formatException(e);
        } */
    }
}