force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Total_ACV__c.field-meta.xml
<CustomField>
    <fullName>Total_ACV__c</fullName>
    <description>Annual Contract Value</description>
    <inlineHelpText>Annual Contract Value</inlineHelpText>
    <label>Total ACV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Enterprise_Name__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offering</label>
    <referenceTo>Offerings__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Number_of_Licensed_Named_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Licensed_Named_Users__c</fullName>
    <label>Number of Licensed Named Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Subscription_License_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Subscription_License_Term_Months__c</fullName>
    <label>Subscription License Term(Months)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Offerings__c/Offerings__c.object-meta.xml
<CustomObject>
    <description>High-level Product Select in iContract</description>
    <label>CPQ - Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offerings__c/fields/Tab__c.field-meta.xml
<CustomField>
    <fullName>Tab__c</fullName>
    <description>The tab this product appears in in iContract</description>
    <inlineHelpText>The tab this product appears in in iContract</inlineHelpText>
    <label>Tab</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Legacy GlobalMeet and iMeet</fullName>
            </value>
            <value>
                <fullName>New GlobalMeet Bundles</fullName>
            </value>
            <value>
                <fullName>iMeetLive</fullName>
            </value>
            <value>
                <fullName>Automated Conf.</fullName>
            </value>
            <value>
                <fullName>Event Conf.</fullName>
            </value>
            <value>
                <fullName>Skype</fullName>
            </value>
            <value>
                <fullName>WebEx</fullName>
            </value>
            <value>
                <fullName>Web Services</fullName>
            </value>
            <value>
                <fullName>OA Conf. (old)</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_RollUpHelper.cls
@isTest
public class Test_RollUpHelper{
    /* DEAD/UNMAINTAINED
    static testMethod void validaterolluphelper() {
            Opportunity testOppty123 = PGITestUtilities.getOpportunityDetails();
            testOppty123.StageName = 'Awareness';
            testOppty123.CloseDate = Date.today().addDays(10);
            insert testOppty123;
            Account testAcct123 = PGITestUtilities.getAccountDetails();
            testAcct123.NumberOfEmployees = 1000;
            insert testAcct123;
            CONMAN_Contract__c testContract123 = PGITestUtilities.getConManContractDetails(testAcct123.Id, testOppty123.Id);
            insert testContract123;      
            Offerings__c offr123 = new Offerings__c(Name='Test123', Licensed_Product__c=true, Unique_ID__c='1', Tab__c='N/A', Type__c='N/A');
            insert offr123;
            
            Test.startTest();
            
            LicenseSet__c lic123 = new LicenseSet__c(Name='Test123', Price__c=10, Enterprise_Name__c=offr123.Id, Subscription_License_Term_Months__c = 23,Number_of_Licensed_Named_Users__c=25,Opportunity__c=testOppty123.Id, PGi_Contract__c=testContract123.Id);
            insert lic123;
            testContract123 = [SELECT Total_ACV__c FROM CONMAN_Contract__c WHERE Id =:testContract123.Id];
            system.assertequals(3000,testcontract123.Total_ACV__c);
    
            Test.stopTest();
    }*/
}