force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Subscription License Order</fullName>
                <default>true</default>
                <label>Subscription License Order</label>
            </value>
            <value>
                <fullName>Subscription License Agreement</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Rate Modification Amendment</fullName>
            </value>
            <value>
                <fullName>Agent Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Email Order</fullName>
            </value>
            <value>
                <fullName>Gateway Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Gateway Subscription License Order</fullName>
            </value>
            <value>
                <fullName>Master Services Agreement</fullName>
            </value>
            <value>
                <fullName>Related Document</fullName>
            </value>
            <value>
                <fullName>WebEx Agreement</fullName>
            </value>
            <value>
                <fullName>WebEx Amend</fullName>
            </value>
            <value>
                <fullName>Wholesale Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Services Agreement</fullName>
            </value>
            <value>
                <fullName>Local Affiliate Service Agreement</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>TPx Service Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Legal__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Legal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this Contract/Amendment requires Legal Approval.</description>
    <inlineHelpText>Whether or not this Contract/Amendment requires Legal Approval.</inlineHelpText>
    <label>Required Approval: Legal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <defaultValue>&quot;PGi Quote&quot;</defaultValue>
    <description>The title that appears at the top of the Contract Document</description>
    <inlineHelpText>The title that appears at the top of the Contract Document</inlineHelpText>
    <label>Contract Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/recordTypes/iContract.recordType-meta.xml
<RecordType>
    <fullName>iContract</fullName>
    <active>true</active>
    <description>NA Contract going through the iContract system</description>
    <label>NA Contract</label>
</RecordType>

force-app/main/default/classes/iContractConversion.cls
@RestResource(urlMapping='/iContractConversion/*')
global class iContractConversion {

    /* Given a PGi Contract ID and contractType this will update the Type
    */
    /* Given a PGi Contract ID, this will remove all of the products
     * and reset the Terms and Conditions to the defaults
    */
    @HttpPost
    global static String convert(String contractType) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;

        String contractIdRequest = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Id contractId;
        try { contractId = contractIdRequest; }
        catch (Exception e) {  return 'Invalid PGi Contract ID: ' + contractIdRequest; }

        /*try {*/
            CONMAN_Contract__c agreement =  [SELECT Id, Contract_Type__c FROM CONMAN_Contract__c WHERE Id = :contractId];
            boolean converting = agreement.Contract_Type__c != contractType;

            agreement.Contract_Type__c = contractType;
            if (converting) agreement.Title__c = 'PGi ' + contractType;
            if (contractType.equals('Amendment')) {
                agreement.Required_Approval_Legal__c = true;
                if (converting) agreement.Title__c += ' #X';
            } else if (contractType.equals('Subscription License Agreement')) {
                agreement.Required_Approval_Legal__c = true;
            } else {
                agreement.Required_Approval_Legal__c = false;
            }
            UPDATE agreement;

            if (converting) {
                iContract.handleTerms(contractId);
            }

            return iContract.SUCCESS;
        /*} catch (Exception e) {
            return iContract.formatException(e);
        }*/
    }
}