force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Auto_Renewal_Interval_months__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Interval_months__c</fullName>
    <label>Auto-Renewal Interval (months)</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/CEA_Date_Active__c.field-meta.xml
<CustomField>
    <fullName>CEA_Date_Active__c</fullName>
    <description>The date that shows the most recent Contract End/Anniversary Date. This shows the Original CEA Date before renewal and once renewed the current CEA Date.</description>
    <inlineHelpText>This shows the Original CEA Date before renewal and once renewed the current CEA Date. This will be set upon initial entry of the CEA Date - Original value. *For manual renewals, please set this to the new CEA Date for man. renewal.</inlineHelpText>
    <label>CEA Date - Active</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/CEA_Date_Prior_to_Renewal__c.field-meta.xml
<CustomField>
    <fullName>CEA_Date_Prior_to_Renewal__c</fullName>
    <description>The Contract End/Anniversary Date before the last renewal occurred.</description>
    <inlineHelpText>The Contract End/Anniversary Date before the last renewal occurred. This will be set automatically when auto-renewed. *For manual renewals please set this value to the old CEA Date - Original value.</inlineHelpText>
    <label>CEA Date - Prior to Renewal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Document_Status__c</fullName>
    <description>This is the replacement of the Q/C record&apos;s Contract Document Status field</description>
    <label>Contract Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Customer Signed</fullName>
            </value>
            <value>
                <fullName>Deactivated Company/No Termination Notice</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateQuoteCEAPriorDateBatch.cls
/*********************************************************************
Name : UpdateQuoteCEAPriorDateBatch
Created On : Mar 2, 2016
Created By : Archana Rajendran
Description : Batch Apex to update CEA Date Prior-to-Renewal and CEA Active Date 
**********************************************************************/
global class UpdateQuoteCEAPriorDateBatch implements Database.Batchable<sObject> 
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {   
        /*
String query = 'Select id,File_Store_Contract_Status__c,SC_Auto_renewal_Interval_in_months__c,CEA_Date_Prior_to_Renewal__c,CEA_Date_Active__c from quote where '+
'CEA_Date_Active__c < TODAY '+
'and SC_Auto_renewal_Interval_in_months__c != NULL '+
'and File_Store_Contract_Status__c = \'Active\''; */
        String query = 'Select id,Contract_Document_Status__c,Auto_Renewal_Interval_months__c,CEA_Date_Prior_to_Renewal__c,CEA_Date_Active__c from CONMAN_Contract__c where '+
            'CEA_Date_Active__c < TODAY '+
            'and Auto_Renewal_Interval_months__c != NULL '+
            'and Contract_Document_Status__c = \'Active\'';               
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<CONMAN_Contract__c> scope)
    {   
        for(CONMAN_Contract__c q:scope)
        {
            /* ORIGINAL
            q.CEA_Date_Prior_to_Renewal__c = q.CEA_Date_Active__c;
            date newdate = q.CEA_Date_Active__c;
            do {
            newdate = q.CEA_Date_Active__c.addmonths(integer.valueof(q.Auto_Renewal_Interval_months__c));
            q.CEA_Date_Active__c = newdate;
            } while (newdate <= system.today()); */
            
            // Only renew if the Active Date is in the past
            if (q.CEA_Date_Active__c <= System.today()) {
                q.CEA_Date_Prior_to_Renewal__c = q.CEA_Date_Active__c;
                
                // Skip those without renewal intervals
                if (q.Auto_Renewal_Interval_months__c == null || q.Auto_Renewal_Interval_months__c <= 0)
                    continue;
                
                Integer monthsOld = q.CEA_Date_Active__c.monthsBetween(System.today());
                Integer monthsRenew = Integer.valueof(q.Auto_Renewal_Interval_months__c);
                
                Integer renewalTimes;
                if (monthsOld <= 0) {
                    // If we're within a month of the Active Date,
                    // monthsOld will be 0 but we can trust that
                    // it's expired considering the <= today check
                    renewalTimes = 1;
                } else {
                    // Renew based on passed term lengths
                    renewalTimes = monthsOld / monthsRenew;
                    // If there's months left over (division remainder),
                    // add another term
                    if (Math.mod(monthsOld, monthsRenew) != 0)
                        renewalTimes += 1;
                }
                
                q.CEA_Date_Active__c = q.CEA_Date_Active__c.addMonths(renewalTimes * monthsRenew);
                
                // One last check to catch instances when the
                // difference is one whole term plus a few days old
                // e.g. 12m term on a 12m 15d old agreement
                // and monthsOld will only be 12
                if (q.CEA_Date_Active__c <= System.today())
                	q.CEA_Date_Active__c = q.CEA_Date_Active__c.addMonths(monthsRenew);
            }
        }
        update scope;
    }    
    global void finish(Database.BatchableContext BC)    
    {
        
    }
}