force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to set the relationship between Conman Contract and Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/CEA_Date_Active__c.field-meta.xml
<CustomField>
    <fullName>CEA_Date_Active__c</fullName>
    <description>The date that shows the most recent Contract End/Anniversary Date. This shows the Original CEA Date before renewal and once renewed the current CEA Date.</description>
    <inlineHelpText>This shows the Original CEA Date before renewal and once renewed the current CEA Date. This will be set upon initial entry of the CEA Date - Original value. *For manual renewals, please set this to the new CEA Date for man. renewal.</inlineHelpText>
    <label>CEA Date - Active</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/CEA_Date_Prior_to_Renewal__c.field-meta.xml
<CustomField>
    <fullName>CEA_Date_Prior_to_Renewal__c</fullName>
    <description>The Contract End/Anniversary Date before the last renewal occurred.</description>
    <inlineHelpText>The Contract End/Anniversary Date before the last renewal occurred. This will be set automatically when auto-renewed. *For manual renewals please set this value to the old CEA Date - Original value.</inlineHelpText>
    <label>CEA Date - Prior to Renewal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_UpdateQuoteCEAPriorDateBatch.cls
/*********************************************************************
Name : Test_UpdateQuoteCEAPriorDateBatch
Created On : Mar 09, 2016
Created By : Archana Rajendran
Description : Test Class for UpdateQuoteCEAPriorDateBatch 
**********************************************************************/

@isTest
private class Test_UpdateQuoteCEAPriorDateBatch {
     @testSetup static void setup() {
       PGITestUtilities.disableSalesWings();
    }
	
    static testmethod void test() 
    {
       Account acc = PGITestUtilities.getAccountDetails();
       insert acc;
       Contact con = PGITestUtilities.getContactDetails(Acc.id);
       insert con;
       Opportunity opp =  PGITestUtilities.getOpportunityDetails();
       opp.accountid = acc.id;
       insert opp;
       CONMAN_Contract__c testPGiContract = new CONMAN_Contract__c();
       testPGiContract.Opportunity__c = opp.Id;
       testPGiContract.Account_Name__c = acc.Id;
       insert testPGiContract;
       //Quote quote = PGITestUtilities.getQuoteDetails(Acc.id,Con.id,Opp.id);
       //quote.File_Store_Contract_Status__c='Active';
       //quote.SC_Auto_renewal_Interval_in_months__c=3;
       //quote.CEA_Date_Active__c =system.TODAY() - 2;
       //insert quote;
       /**/
       Test.startTest();
       UpdateQuoteCEAPriorDateBatch a = new UpdateQuoteCEAPriorDateBatch();
       Database.executeBatch(a);
       Test.stopTest();
       
       //Quote q1=[select id,CEA_Date_Prior_to_Renewal__c,CEA_Date_Active__c from quote where id =: quote.id];
       //System.assertEquals(q1.CEA_Date_Prior_to_Renewal__c,system.TODAY() - 2); 
       /**/
       
             
    }
}