force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to set the relationship between Conman Contract and Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Auto_Renewal_Interval_months__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renewal_Interval_months__c</fullName>
    <label>Auto-Renewal Interval (months)</label>
    <precision>16</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/CEA_Date_Active__c.field-meta.xml
<CustomField>
    <fullName>CEA_Date_Active__c</fullName>
    <description>The date that shows the most recent Contract End/Anniversary Date. This shows the Original CEA Date before renewal and once renewed the current CEA Date.</description>
    <inlineHelpText>This shows the Original CEA Date before renewal and once renewed the current CEA Date. This will be set upon initial entry of the CEA Date - Original value. *For manual renewals, please set this to the new CEA Date for man. renewal.</inlineHelpText>
    <label>CEA Date - Active</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/CEA_Date_Prior_to_Renewal__c.field-meta.xml
<CustomField>
    <fullName>CEA_Date_Prior_to_Renewal__c</fullName>
    <description>The Contract End/Anniversary Date before the last renewal occurred.</description>
    <inlineHelpText>The Contract End/Anniversary Date before the last renewal occurred. This will be set automatically when auto-renewed. *For manual renewals please set this value to the old CEA Date - Original value.</inlineHelpText>
    <label>CEA Date - Prior to Renewal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Document_Status__c</fullName>
    <description>This is the replacement of the Q/C record&apos;s Contract Document Status field</description>
    <label>Contract Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Customer Signed</fullName>
            </value>
            <value>
                <fullName>Deactivated Company/No Termination Notice</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateQuoteCEAPriorDateBatchTest.cls
@isTest
public with sharing class UpdateQuoteCEAPriorDateBatchTest {
    static testMethod void test(){
        Account accobj = new Account(Name = 'Test',Type = 'japan',website = 'http://google.com');
        Insert accobj;
        List<CONMAN_Contract__c > ccObjlist = new List<CONMAN_Contract__c > { new CONMAN_Contract__c(Account_Name__c = accobj.id,Contract_Document_Status__c = 'Active', Auto_Renewal_Interval_months__c = 12, CEA_Date_Prior_to_Renewal__c = Date.parse('11/20/2019'),
                                                                                                     CEA_Date_Active__c = Date.parse('11/10/2019')),
            new CONMAN_Contract__c(Account_Name__c = accobj.id,Contract_Document_Status__c = 'Active', Auto_Renewal_Interval_months__c = 0, CEA_Date_Prior_to_Renewal__c = Date.parse('10/18/2019'),
                                   CEA_Date_Active__c = Date.parse('11/10/2019'))};
                                       
                                       
                                       insert ccObjlist ;
        
        Test.startTest();
        UpdateQuoteCEAPriorDateScheduler sh1 = new UpdateQuoteCEAPriorDateScheduler ();
        String sch = '0 0 2 * * ?';
        system.schedule('UpdateQuoteCEAPriorDateBatch', sch, sh1);
        Test.stopTest();
        
         System.assertEquals(2, [SELECT COUNT() FROM CONMAN_Contract__c] );
       // System.assertEquals(Date.parse('11/10/2020'), [select id,CEA_Date_Active__c from CONMAN_Contract__c where Auto_Renewal_Interval_months__c =: 12].CEA_Date_Active__c );
    }
}