force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT</fullName>
            </value>
            <value>
                <fullName>ANY</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,FOXDEN_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Package__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>Package description. Up to 500 characters</description>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/provisioningEmailContext__c.field-meta.xml
<CustomField>
    <fullName>provisioningEmailContext__c</fullName>
    <description>Context to use while rendering the BBS Email Template</description>
    <label>Provisioning Email Context</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/provisioningEmailDescription__c.field-meta.xml
<CustomField>
    <fullName>provisioningEmailDescription__c</fullName>
    <description>A description of this package that can be used in a provisioning e-mail template</description>
    <label>Provisioning Email Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/QuantityEnabled__c.field-meta.xml
<CustomField>
    <fullName>QuantityEnabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>QuantityEnabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/package__c.field-meta.xml
<CustomField>
    <fullName>package__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Pkg.cls
public with sharing class Pkg extends AbstractRepository {

  public final static String table = 'Package__c';
  public final static String columns = 'id,name,billableType__c,description__c,provisioningEmailDescription__c,provisioningEmailContext__c,QuantityEnabled__c';

  /**
   * Validations
   */  
  public class builderValidator extends AbstractValidator {  
    
    public override void validate(SObject o) {  
      Package__c pkg = (Package__c)o;
      
    }        
  }
  
  /**
   * Queries
   */
  public List<Package__c> findAllPackages(){
    String columnsWithRelations = columns+innerSelectBuilder('RT_Products__r', Product.columns, 'order by name');
    return (List<Package__c>) Database.query(selectBuilder(table,columnsWithRelations,'order by name'));
  }
  
  public Package__c findById(Id packageId) {
    String columnsWithRelations = columns+innerSelectBuilder('RT_Products__r', Product.columns, 'order by name'); 
    return (Package__c) Database.query(selectBuilder(table,columnsWithRelations,'where id =: packageId limit 1'));
  }

  public Package__c findByName(String name) {
    String columnsWithRelations = columns+innerSelectBuilder('RT_Products__r', Product.columns, 'order by name'); 
    return (Package__c) Database.query(selectBuilder(table,columnsWithRelations,'where name =: name limit 1'));    
  }

  /**
   * Helper for Save
   */
  public Package__c savePackage(String name, String billableType, String description, String emailContext) {
    Package__c p =  (Package__c) new Pkg.builderValidator()
      .forObject(new Package__c())
      .set('name', name)
      .set('billableType__c', billableType)
      .set('description__c', description)
      .set('provisioningEmailContext__c', emailContext)
      .buildAndValidate()
      .save();
    return p;
  }
}