force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/package__c.field-meta.xml
<CustomField>
    <fullName>package__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/recurringCharge__c.field-meta.xml
<CustomField>
    <fullName>recurringCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Recurring Charge</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/scheduleName__c.field-meta.xml
<CustomField>
    <fullName>scheduleName__c</fullName>
    <formula>schedule__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Schedule Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/singleCharge__c.field-meta.xml
<CustomField>
    <fullName>singleCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Single Charge</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>AUDIO</fullName>
            </value>
            <value>
                <fullName>FOXDEN</fullName>
            </value>
            <value>
                <fullName>FOXDEN_CONNECT</fullName>
            </value>
            <value>
                <fullName>FOXDEN_CONNECT_HARDWARE</fullName>
            </value>
            <value>
                <fullName>HOSTING</fullName>
            </value>
            <value>
                <fullName>WEB</fullName>
            </value>
            <value>
                <fullName>S3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/useAssignedScheduleAsDefault__c.field-meta.xml
<CustomField>
    <fullName>useAssignedScheduleAsDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use the schedule assigned to this product as the default value in the drop down when selecting plan/products.</description>
    <label>Use Assigned Schedule As Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Product.cls
public with sharing class Product extends AbstractRepository {

  public final static String table = 'RT_Product__c';
  public final static String columns = 'id,name,package__c,recurringCharge__c,recurringChargeFrequency__c,schedule__c,scheduleName__c,singleCharge__c,useAssignedScheduleAsDefault__c,type__c';

  /**
   * Validations
   */  
  public class builderValidator extends AbstractValidator {  
    
    public override void validate(SObject o) {  
      RT_Product__c product = (RT_Product__c)o;
      
    }        
  } 

  /**
   * Queries
   */

  /**
   * Helper for Save
   */
  public RT_Product__c saveProduct(String name, Id packageId, Decimal recurringCharge, String recurringChargeFrequency, Id scheduleId, Decimal singleCharge, String type, boolean isDefault) {
    RT_Product__c p = (RT_Product__c) new Product.builderValidator()
      .forObject(new RT_Product__c())
      .set('name', name)
      .set('package__c', packageId)
      .set('recurringCharge__c', recurringCharge)
      .set('recurringChargeFrequency__c', recurringChargeFrequency)
      .set('schedule__c', scheduleId)
      .set('singleCharge__c', singleCharge)
      .set('type__c', type)
      .set('useAssignedScheduleAsDefault__c', isDefault)
      .buildAndValidate()
      .save();
    return p;
  }        
}