force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>Package description. Up to 500 characters</description>
    <label>Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Description</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testAbstractSObject.cls
@isTest
public with sharing class testAbstractSObject {

  static testMethod void testBadSaveWithDMLErrors() {
    //Try to save a schedule without the required description__c field
    try {
      new Schedule.builderValidator()
      .forObject(new Schedule__c())
      .set('name', 'fooSchedule')
      .save();
    }
    catch (ValidationException ve) {
      System.assert(ve!=null);
    }
  }  
    
  static testMethod void testBadSave() {
    //Try to save a bad plan 
    try {
      new Plan.builderValidator()
      .forObject(null)
      .save();      
    }
    catch (ValidationException ve) {
      System.assert(ve!=null);
    }    
  }
  
  static testMethod void testGetObject() {
    SObject so = new Pkg.builderValidator()
    .forObject(new Package__c())
    .getObject();
    
    System.assert(so != null);
  }
}