force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT</fullName>
            </value>
            <value>
                <fullName>ANY</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,FOXDEN_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/basePackage__c.field-meta.xml
<CustomField>
    <fullName>basePackage__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/quantityStartDate__c.field-meta.xml
<CustomField>
    <fullName>quantityStartDate__c</fullName>
    <label>quantityStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PlanQuantityHistory__c/PlanQuantityHistory__c.object-meta.xml
<CustomObject>
    <label>PlanQuantityHistory</label>
    <nameField>
        <label>PlanQuantityHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PlanQuantityHistorys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanQuantityHistory__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>PlanQuantityHistorys</relationshipLabel>
    <relationshipName>PlanQuantityHistorys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PlanQuantityHistory__c/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PlanQuantityHistory__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>startDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PlanAfterInsertAfterUpdateTest.cls
@IsTest
public class PlanAfterInsertAfterUpdateTest {
    @testsetup static void testPlanafterinsertandUpdate(){
        
        Account accObj = new Account(Name = 'TestAcc');
        Insert accObj;
        Package__c pkgObj = new Package__c(Name = 'Testpkg');
        Insert pkgObj;
        List<Plan__c> planList = new List<Plan__c>{new Plan__c(Name = 'TestPlan',quantity__c = 10,quantityStartDate__c = date.parse('11/26/2019'),
                                                              billableType__c = 'Account',account__c = accObj.Id,
                                                              basePackage__c = pkgObj.Id,startDate__c = date.parse('11/26/2019')) };
        Insert planList;
        Plan__c updatepkgObj  = new Plan__c(Id = planList[0].Id,quantity__c = 20);
        Update updatepkgObj;
    }
    static testmethod void testplan(){
        Test.startTest();
        System.assertEquals(10, [Select Id,quantity__c from PlanQuantityHistory__c limit 1].quantity__c);
        Test.stopTest();
    }
}