force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/provisioningEmailContext__c.field-meta.xml
<CustomField>
    <fullName>provisioningEmailContext__c</fullName>
    <description>Context to use while rendering the BBS Email Template</description>
    <label>Provisioning Email Context</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/provisioningEmailDescription__c.field-meta.xml
<CustomField>
    <fullName>provisioningEmailDescription__c</fullName>
    <description>A description of this package that can be used in a provisioning e-mail template</description>
    <label>Provisioning Email Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/basePackage__c.field-meta.xml
<CustomField>
    <fullName>basePackage__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/PlanAssignment__c.object-meta.xml
<CustomObject>
    <description>Assigned Products related to Access Codes.</description>
    <label>Plan Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>PlanAssignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SubscriptionEmailTemplateHelper.cls
public with sharing class SubscriptionEmailTemplateHelper {

  public String subId {get; set;}
  public Subscription subscriptionRepo = new Subscription();
  public PlanAssignment planAssignmentRepo = new PlanAssignment();
  public Pkg packageRepo = new Pkg();
  public Map<String,Object> defaultContext = new Map<String,Object>{
    'package' => new Map<String,Object>{'name' => 'Define package.name', 'numberSeats' => 0, 'headerText' => ''},
    'card' => new Map<String,Object>{'callMeAnchorText' => 'Define card.callMeAnchorText', 'callMeAnchorType' => 'define card.callMeAnchorType', 'callMeText' => 'Define card.callmeText', 'renderTollFreeLinkData' => false, 'renderTollFreeNumberData' => false, 'renderVOIPLinkData' => false, 'renderBroadcastAudioLinkData' => false},    
    'startButton' => new Map<String,Object>{'renderStartMeetingButton' => false, 'startMeetingButtonText' => 'Define startButton.startMeetingButtonText', 'renderScheduleWebinarButton' => false, 'renderScheduleWebinarText' => 'Define startButton.renderScheduleWebinarText'},
    'details' => new Map<String,Object>{'renderGetStarted' => false, 'renderInvite' => false, 'renderLearn' => false, 'renderPlanning' => false, 
      'getStarted' => new Map<String,Object>{'renderGetStartedCallMe' => false, 'renderDesktopApp' => false, 'renderMobileApps' => false, 'renderCalendar' => false, 'renderScheduleWebinar' => false, 'renderStartWebinar' => false, 'renderIncludeBA' => false},
      'license' => new Map<String,Object>{'renderTFTollVoipAvailable' => false, 'renderChargeDetails' => false, 'intTFText' => 'Toll-Free & International Audio Packages available', 'videoHeaderText' => 'Unlimited Video Conferencing', 'licenseTypeText' => '', 'renderMeetingSectionText' => false, 'renderWebinarSectionText' => false, 'renderPhoneSection' => true, 'renderAudioPorts' => false, 'renderUnlimitedPhoneIn' => true, 'renderSSSBA' => false, 'renderUnlimitedDialOut' => false, 'renderUnlimitedVOIP' => false, 'renderIncludedMinutes' => false, 'includedMinutes' => 0, 'renderPhonePlusSection' => false, 'renderTollFreeNumber' => false, 'renderChargesApply' => false, 'renderInternationalNumbersLink' => false, 'renderINTTFAudioPackagesAvailable' => false, 'renderTFAudioPackagesAvailable' => false, 'renderUnlimitedRecording' => true, 'renderUnlimitedMeetings' => true, 'renderUnlimitedVideo' => true}
    }
  };

  public String getProvisioningEmailDescription() {
    PlanAssignment__c pa = planAssignmentRepo.getCurrentPlanAssignmentBySObjectId(this.subId);
    if(pa==null)
      return 'N/A';

    Package__c pkg = packageRepo.findById(pa.Plan__r.basePackage__c);
    return pkg.provisioningEmailDescription__c;
  }

  public Map<String,Object> getContext() {
    Map<String, Object> m = new Map<String,Object>();

    PlanAssignment__c pa = planAssignmentRepo.getCurrentPlanAssignmentBySObjectId(this.subId);
    if(pa==null)
      return m;

    Package__c pkg = packageRepo.findById(pa.Plan__r.basePackage__c);
    if(pkg==null || pkg.provisioningEmailContext__c == null)
      return m;

    m = (Map<String, Object>) JSON.deserializeUntyped(pkg.provisioningEmailContext__c);
    return mergeMaps(defaultContext, m);
  }

  public Subscription__c getSubscription() {
    Subscription__c subscription = subscriptionRepo.findById(this.subId);
    return subscription;
  }

  //Merge two maps, m1 being the master with defaults to be overwritten.  m2 should be a subset of m1
  public Map<String, Object> mergeMaps(Map<String, Object> m1, Map<String, Object> m2) { 
    Map<String, Object> mergedMap = new Map<String,Object>();
    
    for(String key : m1.keySet()){
      Object masterValue = m1.get(key);
      
      if(masterValue instanceof Map<String,Object>) {
        if(!m2.containsKey(key)){
          mergedMap.put(key, masterValue);
        }
        else{
          mergedMap.put(key, (mergeMaps((Map<String,Object>) masterValue, (Map<String,Object>) m2.get(key))));        
        }
      }
      else{
        if(!m2.containsKey(key)){
          mergedMap.put(key, masterValue);
        }
        else{
          mergedMap.put(key, m2.get(key));
        }
      }
    }
    return mergedMap;
  } 
}