force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/package__c.field-meta.xml
<CustomField>
    <fullName>package__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testPlanRest.cls
@isTest(SeeAllData=true)
private with sharing class testPlanRest {  

  static{
    Pkg packageRepo = new Pkg();
    Schedule scheduleRepo = new Schedule();
    Product productRepo = new Product();
    String emailContext = '{"package":{"name":"Meeting Free Trial"}, "card":{"callMeAnchorText": "callme.readytalk.com", "callMeAnchorType": "callme", "callMeText": "Audio & Online Meetings", "renderVOIPLinkData": true }, "startButton":{"renderStartMeetingButton": true, "startMeetingButtonText": "Start My First Meeting Now"} }';
    Package__c pkg = packageRepo.savePackage('fooPackage', 'ACCESS_CODE', 'A test package', emailContext);
    Schedule__c schedule = scheduleRepo.saveSchedule('fooSchedule', 'A test schedule', 'Audio', Double.valueOf(100.0));
    RT_Product__c product = productRepo.saveProduct('fooProduct', pkg.Id, 49.00, 'INVOICE', schedule.Id, 0.00, 'WEB', true);    
    
   
    RestRequest req = new RestRequest(); 
    RestResponse res = new RestResponse();
    
    req.requestURI = '/services/apexrest/Plan';
    req.httpMethod = 'POST';
    RestContext.request = req;
    RestContext.response = res; 
  }  

  static testMethod void test_AddPlan_With_Invalid_Package() {
      Test.startTest();
    PlanRest.addPlan('fooAccountId', 'invalidPackage', '', '', '0');    
    String response = RestContext.response.responseBody.toString();
      Test.stopTest();
      
    System.assert(response.contains('error'));
  }
  static testMethod void test_AddPlan_With_Invalid_AccountId() {
      Test.startTest();
    PlanRest.addPlan('fooAccountId', 'fooPackage', '', '', '4');    
    String response = RestContext.response.responseBody.toString();
      Test.stopTest();
    System.assert(response.contains('error'));
      
  }

   static testMethod void test_AddPlan_With_Valid_Data() {
       Test.startTest();
    Account a = MockAccount.getNewAccount();
    
    PlanRest.addPlan(a.Id, 'fooPackage', '', '', '0'); 
   // PlanRest.addPlan(a.Id,pkg.Id,'fooPackage', today.format(), '', '',product );  
    String response = RestContext.response.responseBody.toString();
       Test.stopTest();
      //System.assert(!response.contains('error'));
  }
}