force-app/main/default/objects/Case_SLA_Exception_Rule_Conditions__c/Case_SLA_Exception_Rule_Conditions__c.object-meta.xml
<CustomObject>
    <label>Case SLA Exception Rule Conditions</label>
    <nameField>
        <label>Case SLA Exception Rule Conditions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case SLA Exception Rule Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_SLA_Exception_Rule_Conditions__c/fields/Case_SLA_Exception_Rules__c.field-meta.xml
<CustomField>
    <fullName>Case_SLA_Exception_Rules__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case SLA Exception Rules</label>
    <referenceTo>Case_SLA_Exception_Rules__c</referenceTo>
    <relationshipLabel>Case SLA Exception Rule Conditions</relationshipLabel>
    <relationshipName>Case_SLA_Exception_Rule_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_SLA_Exception_Rules__c/Case_SLA_Exception_Rules__c.object-meta.xml
<CustomObject>
    <label>Case SLA Exception Rules</label>
    <nameField>
        <label>Case SLA Exception Rules Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case SLA Exception Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseSLAExceptionRulesTriggerHandler.cls
/*
* Author : Anup
*/
public without sharing class CaseSLAExceptionRulesTriggerHandler {
    public void onBeforeDelete()
    {
        this.deleteChildRecords((List<Case_SLA_Exception_Rules__c>)Trigger.old);
    }
    // RT-586
    // it will delete all the Child object records related to Case_SLA_Exception_Rules__c object
    private void deleteChildRecords(List<Case_SLA_Exception_Rules__c> oldCaseSLAExpRuleRecords){
       List<Id> caseSLAExpRuleIds = new List<Id>();
        for(Case_SLA_Exception_Rules__c caseSLAExpRule : oldCaseSLAExpRuleRecords){
            caseSLAExpRuleIds.add(caseSLAExpRule.ID);
        }
        List<Case_SLA_Exception_Rule_Conditions__c> caseSLAExpRuleCondList = [SELECT Id, Case_SLA_Exception_Rules__c FROM Case_SLA_Exception_Rule_Conditions__c WHERE Case_SLA_Exception_Rules__c in : caseSLAExpRuleIds];
        delete caseSLAExpRuleCondList;
    }
}