force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/echosign_dev1__SIGN_Agreement__c.object-meta.xml
<CustomObject>
    <customHelpPage>echosign_dev1__EchosignHelp</customHelpPage>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/echosign_dev1__SIGN_Agreement__c/fields/echosign_dev1__StatusVisible__c.field-meta.xml
<CustomField>
    <fullName>echosign_dev1__StatusVisible__c</fullName>
    <formula>CASE(
TEXT(echosign_dev1__Status__c), 
&#39;Waiting for Counter-Signature&#39;, &#39;Out for Signature&#39;, 
&#39;Waiting for Counter-Approval&#39;, &#39;Out for Approval&#39;, 
&#39;Waiting for Counter-Acceptance&#39;, &#39;Out for Acceptance&#39;, 
&#39;Waiting for Counter-Form-Filling&#39;, &#39;Out for Form-Filling&#39;, 
&#39;Waiting for Counter-Delivery&#39;, &#39;Out for Delivery&#39;, 
&#39;Pre-Send&#39;, &#39;Not Yet Sent for Signature&#39;,
TEXT(echosign_dev1__Status__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel from Opportunity Owner&#39;s user record</description>
    <label>Owner&#39;s Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_s__c.field-meta.xml
<CustomField>
    <fullName>Competitor_s__c</fullName>
    <label>Competitor(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>8X8</fullName>
            </value>
            <value>
                <fullName>AAPT</fullName>
            </value>
            <value>
                <fullName>Airtel</fullName>
            </value>
            <value>
                <fullName>Amacus</fullName>
            </value>
            <value>
                <fullName>Arcano</fullName>
            </value>
            <value>
                <fullName>Arkadin</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Atlassian/Jira</fullName>
            </value>
            <value>
                <fullName>Bluejeans</fullName>
                <label>BlueJeans</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>British Telecom</label>
            </value>
            <value>
                <fullName>Broadsoft</fullName>
            </value>
            <value>
                <fullName>Budget Conference</fullName>
            </value>
            <value>
                <fullName>Chorus Call</fullName>
            </value>
            <value>
                <fullName>Cisco Teams</fullName>
            </value>
            <value>
                <fullName>CommuniCloud</fullName>
            </value>
            <value>
                <fullName>DSNL</fullName>
            </value>
            <value>
                <fullName>FreeConferenceCall</fullName>
            </value>
            <value>
                <fullName>Fuze Business</fullName>
                <label>Fuze</label>
            </value>
            <value>
                <fullName>Google+ Hangout</fullName>
                <label>Google Hangouts</label>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>GoToWebinar</fullName>
            </value>
            <value>
                <fullName>Intercall (West)</fullName>
            </value>
            <value>
                <fullName>Inxpo</fullName>
            </value>
            <value>
                <fullName>Join.me</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
                <label>Level 3 (CenturyLink)</label>
            </value>
            <value>
                <fullName>Microsoft Meeting Broadcast</fullName>
            </value>
            <value>
                <fullName>Microsoft Skype for Business</fullName>
            </value>
            <value>
                <fullName>Microsoft Teams</fullName>
            </value>
            <value>
                <fullName>NASDAQ OMX</fullName>
                <label>NASDAQ (West)</label>
            </value>
            <value>
                <fullName>ON24</fullName>
                <label>On24</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Differentiating_Win_Factors__c.field-meta.xml
<CustomField>
    <fullName>Differentiating_Win_Factors__c</fullName>
    <label>Differentiating Win Factors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incumbent__c.field-meta.xml
<CustomField>
    <fullName>Incumbent__c</fullName>
    <label>Incumbent</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>8X8</fullName>
            </value>
            <value>
                <fullName>AAPT</fullName>
            </value>
            <value>
                <fullName>Airtel</fullName>
            </value>
            <value>
                <fullName>Amacus</fullName>
            </value>
            <value>
                <fullName>Arcano</fullName>
            </value>
            <value>
                <fullName>Arkadin</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Atlassian/Jira</fullName>
            </value>
            <value>
                <fullName>Avaya</fullName>
            </value>
            <value>
                <fullName>Bluejeans</fullName>
                <label>BlueJeans</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>British Telecom</label>
            </value>
            <value>
                <fullName>BudgetConference</fullName>
            </value>
            <value>
                <fullName>Chorus Call</fullName>
            </value>
            <value>
                <fullName>Cisco Teams</fullName>
            </value>
            <value>
                <fullName>CommuniCloud</fullName>
            </value>
            <value>
                <fullName>DSNL</fullName>
            </value>
            <value>
                <fullName>FreeConferenceCall</fullName>
            </value>
            <value>
                <fullName>Fuze Business</fullName>
                <label>Fuze</label>
            </value>
            <value>
                <fullName>Google+ Hangout</fullName>
                <label>Google Hangouts</label>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>GoToWebinar</fullName>
            </value>
            <value>
                <fullName>Intercall (West)</fullName>
            </value>
            <value>
                <fullName>Inxpo</fullName>
            </value>
            <value>
                <fullName>Jive</fullName>
            </value>
            <value>
                <fullName>Join.me</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
                <label>Level 3 (CenturyLink)</label>
            </value>
            <value>
                <fullName>Microsoft Meeting Broadcast</fullName>
            </value>
            <value>
                <fullName>Microsoft Skype for Business</fullName>
            </value>
            <value>
                <fullName>Microsoft Teams</fullName>
            </value>
            <value>
                <fullName>Mitel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Won_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Won_Reason__c</fullName>
    <label>Primary Won Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-on or Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Support Model</fullName>
            </value>
            <value>
                <fullName>Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Relationship Loyalty</fullName>
            </value>
            <value>
                <fullName>Reliability of the Service</fullName>
            </value>
            <value>
                <fullName>Reseller Only - Undisclosed</fullName>
            </value>
            <value>
                <fullName>Superior Product Functionality</fullName>
            </value>
            <value>
                <fullName>Value for Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_Won_Reason__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Won_Reason__c</fullName>
    <label>Secondary Won Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-on or Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Support Model</fullName>
            </value>
            <value>
                <fullName>Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Relationship Loyalty</fullName>
            </value>
            <value>
                <fullName>Reliability of the Service</fullName>
            </value>
            <value>
                <fullName>Reseller Only - Undisclosed</fullName>
            </value>
            <value>
                <fullName>Superior Product Functionality</fullName>
            </value>
            <value>
                <fullName>Value for Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tertiary_Won_Reason__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Won_Reason__c</fullName>
    <label>Tertiary Won Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-on or Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Support Model</fullName>
            </value>
            <value>
                <fullName>Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Relationship Loyalty</fullName>
            </value>
            <value>
                <fullName>Reliability of the Service</fullName>
            </value>
            <value>
                <fullName>Reseller Only - Undisclosed</fullName>
            </value>
            <value>
                <fullName>Superior Product Functionality</fullName>
            </value>
            <value>
                <fullName>Value for Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendForESignatureController.cls
public with sharing class SendForESignatureController {
    @AuraEnabled
    public static Opportunity getOpportunityData(String oppId){
        Id profileId= userinfo.getProfileId();
        Opportunity oppRecord = new Opportunity();
        
        Set<String> profileIdSet = new Set<String>();
        for(Profile profileRec : [SELECT Id
                                  FROM Profile
                                  WHERE Name = 'System Administrator' OR Name = 'PGi Implementation Services']){
                                      profileIdSet.add(profileRec.Id);
                                  }
        if(profileIdSet.contains(profileId)){
            oppRecord = [SELECT StageName, Primary_Won_Reason__c, Secondary_Won_Reason__c, Tertiary_Won_Reason__c, Differentiating_Win_Factors__c,Incumbent__c,Competitor_s__c 
                         FROM Opportunity WHERE id =: OppId];
        }
        System.debug('>> oppRecord >>'+oppRecord);
        return oppRecord;
    }

    @AuraEnabled
    public static List<echosign_dev1__SIGN_Agreement__c> getSignAgreementData(String oppId){
        List<echosign_dev1__SIGN_Agreement__c> signObj = [SELECT id, Name, CreatedDate, ECHOSIGN_DEV1__STATUSVISIBLE__C 
                                                            FROM echosign_dev1__SIGN_Agreement__c 
                                                            WHERE ECHOSIGN_DEV1__OPPORTUNITY__C =: oppId and ECHOSIGN_DEV1__STATUSVISIBLE__C IN ('Draft', 'Pre-Send', 'Out for Signature', 'Waiting for Counter-Signature', 'Send in Progress', 'Waiting for Counter-Approval', 'Out for Approval', 'Created')];
        return signObj;
    }
    
    @AuraEnabled
    public static echosign_dev1__Agreement_Template__c getAgreementTemplateData(){
        Id userId = userinfo.getUserId();
        
        User userDetails =[SELECT Id, Name, Channel__c, User_Region__c, Country 
                            FROM User
                            WHERE Id=:userinfo.getUserId() ];
        System.debug('>> user details >>'+userDetails);
        String userChannel = userDetails.Channel__c;
        String userRegion ;//= userDetails.User_Region__c;
        String userCountry = userDetails.Country;
        
        if(userChannel == 'Partners' || userChannel == 'Carrier'){
            userRegion = 'Partners';
        }
        else{
            userRegion = 'EMEA';
        }
        echosign_dev1__Agreement_Template__c agreeTempObj = [SELECT Id, Name FROM echosign_dev1__Agreement_Template__c 
                                                    WHERE Name LIKE : '%'+ userRegion+'%' AND
                                                    echosign_dev1__Master_Object_Type__c = 'Opportunity'];
        System.debug('>> agreeTempObj >>'+agreeTempObj);
        return agreeTempObj;
    }
}