force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company_ID__c</fullName>
    <label>PGi Company ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Company__c/fields/PGi_Entity__c.field-meta.xml
<CustomField>
    <fullName>PGi_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Entity</label>
    <referenceTo>PGi_Entity__c</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Entity__c/PGi_Entity__c.object-meta.xml
<CustomObject>
    <label>PGi Entity</label>
    <nameField>
        <label>PGi Entity ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_PopulateParentCompanyonClients.cls
@isTest
public class Test_PopulateParentCompanyonClients{
    //static testMethod void validateparentcompany(){
    
    //    PGi_Entity__c ent = new PGi_Entity__c(name='ent1000');
    //    PGi_Company__c comp1 = new PGi_Company__c(name='comp1000',PGi_Entity__c=ent.id);
    //    PGi_Company__c comp2 = new PGi_Company__c(name='comp1001',PGi_Entity__c=ent.id);
    //    PGi_Company__c comp3 = new PGi_Company__c(name='comp1001',PGi_Entity__c=ent.id);
    //    insert ent;
    //    insert comp1;
    //    insert comp2;
    //    insert comp3;
            
    //    Test.startTest();
    //        PGi_Client__c cli1 = new PGi_Client__c(name = 'cli1000',PGi_Company_ID__c = 'comp10000'); 
    //        PGi_Client__c cli2 = new PGi_Client__c(name = 'cli1001',PGi_Company_ID__c = 'comp1000');
    //        PGi_Client__c cli3 = new PGi_Client__c(name = 'cli1002',PGi_Company_ID__c = 'comp1001');
    //        insert cli1;
    //        insert cli2;
    //        insert cli3;
    //        PGi_Client__c cli100 = [SELECT name,PGi_Company__c FROM PGi_Client__c WHERE name = 'cli1000'];
    //        PGi_Client__c cli101 = [SELECT name,PGi_Company__c FROM PGi_Client__c WHERE name = 'cli1001'];
    //        PGi_Client__c cli102 = [SELECT name,PGi_Company__c FROM PGi_Client__c WHERE name = 'cli1002'];
           
    //        system.assertequals(cli100.PGi_Company__c,NULL);
    //        system.assertequals(cli101.PGi_Company__c,comp1.id);
    //        system.assertequals(cli102.PGi_Company__c,NULL);
            
    //    Test.stopTest();
    //}
}