force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company_ID__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company_ID__c</fullName>
    <label>PGi Company ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PGIClientTriggerHandler.cls
public class PGIClientTriggerHandler extends TriggerHandler{
	public PGIClientTriggerHandler() {
		super('PGIClientTriggerHandler');
	}
	protected override void beforeInsert() {
		matchOnCompanyID();
	}
	protected override void beforeUpdate() {
		matchOnCompanyID();
	}
	
	private void matchOnCompanyID() {
		for(PGi_Client__c client: (List<PGi_Client__c>)Trigger.new){
			if(String.isNotBlank(client.PGi_Company_ID__c)) {
				if(relatedCompanyByCompanyName.get(client.PGi_Company_ID__c) != null) {
					if(relatedCompanyByCompanyName.get(client.PGi_Company_ID__c).size() == 1){
						//one match
						client.PGi_Company__c = relatedCompanyByCompanyName.get(client.PGi_Company_ID__c)[0].Id;
					} else {
						//multiple matches
					}
					
				} else {
					//no match
				}
			}
		}
	}

	private Map<String, List<PGi_Company__c>> relatedCompanyByCompanyName {
		get {
			if(relatedCompanyByCompanyName == null) {
				relatedCompanyByCompanyName = new Map<String, List<PGi_Company__c>>();
				for(PGi_Company__c company: [SELECT Id, Name FROM PGi_Company__c WHERE Name IN: companyNameSet]) {
					List<PGi_Company__c> companiesForName = new List<PGi_Company__c>();
					if(relatedCompanyByCompanyName.get(company.Name) != null) {
						companiesForName = relatedCompanyByCompanyName.get(company.Name);
					}
					companiesForName.add(company);
					relatedCompanyByCompanyName.put(company.Name, companiesForName);
				}
			}
			return relatedCompanyByCompanyName;
	} set;}
	
	private Set<String> companyNameSet {get{
		companyNameSet = new Set<String>();
		for(PGi_Client__c client: (List<PGi_Client__c>)Trigger.new){
			if(String.isNotBlank(client.PGi_Company_ID__c)) {
				companyNameSet.add(client.PGi_Company_ID__c);
			}
		}
		return companyNameSet;
	}set;}
}