force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Client__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>PGi Clients</relationshipLabel>
    <relationshipName>PGi_Clients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Company__c/fields/PGi_Entity__c.field-meta.xml
<CustomField>
    <fullName>PGi_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Entity</label>
    <referenceTo>PGi_Entity__c</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Conference__c/PGi_Conference__c.object-meta.xml
<CustomObject>
    <label>PGi Conference</label>
    <nameField>
        <label>PGi Conference ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Conferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Conference__c/fields/Client_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_ID__c</fullName>
    <label>PGi Client ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Conference__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>PGi Conferences</relationshipLabel>
    <relationshipName>PGi_Conferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Entity__c/PGi_Entity__c.object-meta.xml
<CustomObject>
    <label>PGi Entity</label>
    <nameField>
        <label>PGi Entity ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_PopulateParentClientonConferences.cls
@isTest
public class Test_PopulateParentClientonConferences{
    //static testMethod void validateparentclient(){
    
    //    PGi_Entity__c ent = new PGi_Entity__c(name='ent1000');
    //    PGi_Company__c comp = new PGi_Company__c(name='comp1000',PGi_Entity__c=ent.id);
    //    PGi_Client__c cli1 = new PGi_Client__c(name='cli1000',PGi_Company__c=comp.id);
    //    PGi_Client__c cli2 = new PGi_Client__c(name='cli1001',PGi_Company__c=comp.id);
    //    PGi_Client__c cli3 = new PGi_Client__c(name='cli1001',PGi_Company__c=comp.id);
        
    //    insert ent;
    //    insert comp;
    //    insert cli1;
    //    insert cli2;
    //    insert cli3;
            
    //    Test.startTest();
    //        PGi_Conference__c conf1 = new PGi_Conference__c(name = 'conf1000',Client_ID__c = 'cli10000'); 
    //        PGi_Conference__c conf2 = new PGi_Conference__c(name = 'conf1001',Client_ID__c = 'cli1000');
    //        PGi_Conference__c conf3 = new PGi_Conference__c(name = 'conf1002',Client_ID__c = 'cli1001');
    //        insert conf1;
    //        insert conf2;
    //        insert conf3;
    //        PGi_Conference__c conf100 = [SELECT name,PGi_Client__c FROM PGi_Conference__c WHERE name = 'conf1000'];
    //        PGi_Conference__c conf101 = [SELECT name,PGi_Client__c FROM PGi_Conference__c WHERE name = 'conf1001'];
    //        PGi_Conference__c conf102 = [SELECT name,PGi_Client__c FROM PGi_Conference__c WHERE name = 'conf1002'];
           
    //        system.assertequals(conf100.PGi_Client__c,NULL);
    //        system.assertequals(conf101.PGi_Client__c,cli1.id);
    //        system.assertequals(conf102.PGi_Client__c,NULL);
            
    //    Test.stopTest();
    //}
}