force-app/main/default/objects/Account/fields/ABM_PES_Last_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>ABM_PES_Last_Change_Date__c</fullName>
    <description>Date stamped when PES changes to x value.</description>
    <label>ABM | PES Last Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Cumulative_Total_Booked__c.field-meta.xml
<CustomField>
    <fullName>Cumulative_Total_Booked__c</fullName>
    <description>ASX Populated - Amount is the cumulative total booked since start for billing</description>
    <inlineHelpText>Cumulative amount booked by this account client</inlineHelpText>
    <label>Cumulative Total Booked</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Zendesk__createdUpdatedFlag__c.field-meta.xml
<CustomField>
    <fullName>Zendesk__createdUpdatedFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used in trigger to prevent looping of after insert and update. This flag is used to stop the account that came for creation to get updated again thereby preventing the loop</description>
    <label>createdUpdatedFlag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PGi_ServiceCatalogValidatorUtilityTest.cls
@isTest
public class PGi_ServiceCatalogValidatorUtilityTest {
    @testSetUp static void setup()
    {
        Account acc = new Account();
        acc.Name='Test1';
        Insert acc;
    }
    static testMethod void testvalidObjectName(){
        PGi_ServiceCatalogValidatorUtility obj = new PGi_ServiceCatalogValidatorUtility();
        System.assertEquals(false, obj.validObjectName('null'));
        System.assertEquals(true,obj.validObjectName('Account'));
    }
    static testMethod void testvalidFieldSet(){
        Account acc= [Select Id,Name from Account];
        PGi_ServiceCatalogValidatorUtility obj = new PGi_ServiceCatalogValidatorUtility();
        System.assertEquals(true, obj.validFieldSet('Account','Emergency_Account_Fields'));
        System.assertEquals(false, obj.validFieldSet('Account','test'));
        System.assertEquals(false, obj.validFieldSet('null','Name'));
    }
    static testMethod void testvalidField(){
        PGi_ServiceCatalogValidatorUtility obj = new PGi_ServiceCatalogValidatorUtility();
        System.assertEquals(true, obj.validField('Account','Name'));
        System.assertEquals(false, obj.validField('null','test'));
    }
    static testMethod void testvalidFieldInput(){
        PGi_ServiceCatalogValidatorUtility obj = new PGi_ServiceCatalogValidatorUtility();
        Datetime myDate =Date.today();
        String str=String.valueOf(myDate);
        obj.validFieldInput('Account','ABM_PES_Last_Change_Date__c',str);
        obj.validFieldInput('Account','Date_Provisioned__c',str);
        obj.validFieldInput('Account','Date_Provisioned__c','2019-11-12');
        System.assertEquals('true', obj.validFieldInput('Account','Name','Test1'));
        System.assertEquals('true', obj.validFieldInput('Account','Zendesk__createdUpdatedFlag__c','true'));
        System.assertEquals('true',  obj.validFieldInput('Account','Cumulative_Total_Booked__c','10'));
        System.assertEquals('true', obj.validFieldInput('Account','NumberOfEmployees','10'));
    }
    static testMethod void testvalidStaticResource(){
              PGi_ServiceCatalogValidatorUtility obj = new PGi_ServiceCatalogValidatorUtility();
        System.assertEquals(true, obj.validateStaticResource('A12_Alert','test'));
        System.assertEquals(false, obj.validateStaticResource('null','test'));
    }
}