force-app/main/default/objects/Account/fields/ABM_Last_PES__c.field-meta.xml
<CustomField>
    <fullName>ABM_Last_PES__c</fullName>
    <description>The previous predictive engagement score of the account.</description>
    <inlineHelpText>The previous predictive engagement score of the account.</inlineHelpText>
    <label>ABM | Last PES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABM_PES_Last_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>ABM_PES_Last_Change_Date__c</fullName>
    <description>Date stamped when PES changes to x value.</description>
    <label>ABM | PES Last Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_Address_Verification__c.field-meta.xml
<CustomField>
    <fullName>Bill_Address_Verification__c</fullName>
    <description>Date the customer&#39;s address was verified (mainly for tax purposes).</description>
    <label>Bill Address Verification</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Account_s_Agreement_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_s_Agreement_Name__c</fullName>
    <inlineHelpText>This value is populated by Sales Operations or Legal when the Account has been previously contracted under a different name.</inlineHelpText>
    <label>Account’s Agreement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Company_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_s_Name__c</fullName>
    <label>Company&#39;s Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Contract_Document_Status__c</fullName>
    <description>This is the replacement of the Q/C record&apos;s Contract Document Status field</description>
    <label>Contract Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Customer Signed</fullName>
            </value>
            <value>
                <fullName>Deactivated Company/No Termination Notice</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Superseded</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Source__c.field-meta.xml
<CustomField>
    <fullName>Contract_Source__c</fullName>
    <label>Contract Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Gateway</fullName>
            </value>
            <value>
                <fullName>Docusign</fullName>
            </value>
            <value>
                <fullName>Contract Document Generator</fullName>
            </value>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>iContract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contracted_Term__c.field-meta.xml
<CustomField>
    <fullName>Contracted_Term__c</fullName>
    <description>Length of the Contract/Amendment in months.</description>
    <inlineHelpText>Length of the Contract/Amendment in months.</inlineHelpText>
    <label>Contracted Term</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Sales_Ops_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Ops_Status__c</fullName>
    <description>Tracks the &quot;work&quot; of the Sales Ops team and is independent of Contract Status - Replacement of the QC field called QC Status</description>
    <label>Sales Ops Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Needs Review</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Contract Document Generated</fullName>
            </value>
            <value>
                <fullName>Contract Signed by Customer</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Pricing Approved - Internally Signed</fullName>
            </value>
            <value>
                <fullName>Quote- In Progress</fullName>
            </value>
            <value>
                <fullName>Ready for Contract</fullName>
            </value>
            <value>
                <fullName>Submitted - Price Approval</fullName>
            </value>
            <value>
                <fullName>Submitted Contract- Customer Approval</fullName>
            </value>
            <value>
                <fullName>Submitted Contract-Internal Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Service_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_Commencement_Date__c</fullName>
    <description>Date the Agreement will take effect, or empty if the signature date</description>
    <label>Service Commencement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/z_Source__c.field-meta.xml
<CustomField>
    <fullName>z_Source__c</fullName>
    <label>z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/recordTypes/iContract.recordType-meta.xml
<RecordType>
    <fullName>iContract</fullName>
    <active>true</active>
    <description>NA Contract going through the iContract system</description>
    <label>NA Contract</label>
</RecordType>

force-app/main/default/objects/Contact/fields/ECommerce_Convert__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECommerce Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/License_Profile__c.field-meta.xml
<CustomField>
    <fullName>License_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>License Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Number_of_Licensed_Named_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Licensed_Named_Users__c</fullName>
    <label>Number of Licensed Named Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Subscription_License_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Subscription_License_Term_Months__c</fullName>
    <label>Subscription License Term(Months)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Acct_Admin_Decison_Maker_Checked__c.field-meta.xml
<CustomField>
    <fullName>Acct_Admin_Decison_Maker_Checked__c</fullName>
    <inlineHelpText>Accounts are required to have a contact flagged as an Acct Admin and as a Decision Maker.  Fields are located at the contact level.</inlineHelpText>
    <label>Acct Admin/Decison Maker Checked?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Custom field used to map Lead Description to Opportunity Description. By default, SFDC only maps the Lead Description field to the Contact Description field. This will allow for it to also be mapped to the Opportunity via Lead Mapping. A workflow rule on Opportunity will then update the standard Opportunity Description field on the page layout from this custom field.</description>
    <label>Description__c</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This date indicates the date that an opportunity moved from qualified stage to a pipeline, closed won, or closed lost stage.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/z_Source__c.field-meta.xml
<CustomField>
    <fullName>z_Source__c</fullName>
    <label>z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityEventHandlerTest.cls
@isTest
private class OpportunityEventHandlerTest {
    @testSetup static void setup()
    {
        PGITestUtilities.disableSalesWings();
        Account act = new account(Name = 'Test32',ABM_Last_PES__c='testData',ABM_PES_Last_Change_Date__c =Date.today(),Bill_Address_Verification__c =Date.today().AddDays(2), Z_Source__c = 'eCommerce');
        insert act;
        
        System.assert(act.id <> null);
        
        Contact ct = new Contact();
        ct.FirstName = 'klnasknjaskldasd';
        ct.LastName  = 'efoijasjkndalkmsd';
        ct.Phone     = '3819405828';
        ct.Email     = 'knasdlkmsdklgasd@premierglobal.com';
        ct.accountId = act.id;
        ct.License_Profile__c = true;
        insert ct;
        
        Contact ct2 = new Contact();
        ct2.FirstName = 'cjnasdnkjaklwflkf';
        ct2.LastName  = 'njifasoinawlrkalsd';
        ct2.Phone     = '1950247284';
        ct2.Email     = 'efkjnsdlkmsalmd@premierglobal.com';
        ct2.accountId = act.id;
        ct2.License_Profile__c = true;
        insert ct2;
        
        Opportunity oppor = new Opportunity();
        oppor.name = 'Test oppor-1';
        oppor.stagename = 'Awareness';
        oppor.ECommerce_Convert__c=false;
        oppor.closeDate= system.today().addDays(100);
        oppor.ECommerce_Account_Number__c = 'Ecom-000000001';
        oppor.accountid = act.id;
        oppor.Z_Source__c = 'eCommerce';
        oppor.Acct_Admin_Decison_Maker_Checked__c = 'Yes';
        insert oppor;
        
        // Insert offerings
        Licenseset__c licSet        = new Licenseset__c();
        licSet.Description__c       = 'Lic Set - 1';
        licSet.End_Date__c          = system.today().adddays(100);
        licSet.Line_Number__c       = 1;
        licSet.Number_of_Licensed_Named_Users__c = 1;
        licSet.Order_Number__c      = 1;
        licSet.Price__c             = 12.22;
        licSet.SKU__c               = 'SKU-000000001';
        licSet.Start_Date__c        = system.today();
        licSet.Subscription_License_Term_Months__c = 12;
        licSet.name                 = 'Lic Set -1';
        licSet.Opportunity__c=oppor.Id;
        licSet.Z_Source__c = 'eCommerce';    
        insert licSet;
        Asset assetObj = new Asset();
        assetObj.Name='Test';
        assetObj.Opportunity__c = oppor.Id;
        assetObj.AccountId=act.Id;   
        assetObj.ContactId=ct2.Id;
        Insert assetObj;
        
    }
    
    static testMethod void testBeforeInsert() {
        Test.startTest();
        Licenseset__c licenceSetObj = [Select Id ,Opportunity__c from Licenseset__c];
        Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
        //Validate assert If required
        oppr.stagename = 'Closed Pending Approval';
        Update oppr;
        OpportunityEventHandler.skipExecution = false;
        oppr.ECommerce_Convert__c=true;
        oppr.stagename = 'Closed Won';
        Update oppr;
       Test.stopTest();
    }
    static testMethod void testAfterUpdate() {
        Test.startTest();
        Account a= [Select Id from Account Where Name='Test32'];
        Licenseset__c licenceSetObj = [Select Id ,Opportunity__c from Licenseset__c];
        Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(a.Id, oppr.Id);
        testContract.Contract_Source__c='iContract';
        testContract.Account_s_Agreement_Name__c='Test';
        testContract.Service_Commencement_Date__c=Date.today();
        testContract.Contracted_Term__c=null;
        Insert testContract;
        oppr.stagename = 'Closed Pending Approval';
        OpportunityEventHandler.skipExecution = false;
        oppr.ECommerce_Convert__c=true;
        Update oppr;
        oppr.stagename = 'Closed Won';
        Update oppr;
        CONMAN_Contract__c testContract1 =[Select Id,Account_s_Agreement_Name__c,Company_s_Name__c,Sales_Ops_Status__c,Contract_Document_Status__c from CONMAN_Contract__c Where Contract_Source__c='iContract'];
        System.debug('The CONMAN_Contract__c123'+testContract1);
        System.assertEquals(testContract.Account_s_Agreement_Name__c, testContract1.Account_s_Agreement_Name__c);
        System.assertEquals('Draft', testContract1.Sales_Ops_Status__c);
        System.assertEquals('Active', testContract1.Contract_Document_Status__c);
        Test.stopTest();
    }
    static testMethod void testAfterUpdateNull() {
        Test.startTest();
        Account a= [Select Id from Account Where Name='Test32'];
        Licenseset__c licenceSetObj = [Select Id ,Opportunity__c from Licenseset__c];
        Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
        echosign_dev1__SIGN_Agreement__c es = new echosign_dev1__SIGN_Agreement__c();
        es.echosign_dev1__Status__c = 'Signed';
        INSERT es;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(a.Id, oppr.Id);
        testContract.Contract_Source__c='iContract';
        testContract.Account_s_Agreement_Name__c=null;
        testContract.Service_Commencement_Date__c=Date.today();
        testContract.Contracted_Term__c=2;
        testContract.Related_Agreement__c=es.Id;
        testContract.Service_Commencement_Date__c=null;   
        Insert testContract;
        oppr.stagename = 'Closed Pending Approval';
        Update oppr;
        OpportunityEventHandler.skipExecution = false;
        oppr.stagename = 'Closed Won';
        oppr.ECommerce_Convert__c=true;
        Update oppr;
        CONMAN_Contract__c testContract1 =[Select Id,Account_s_Agreement_Name__c,Service_Commencement_Date__c,Auto_Renewal__c,Company_s_Name__c,Sales_Ops_Status__c,Contract_Document_Status__c from CONMAN_Contract__c Where Contract_Source__c='iContract'];
        System.assertEquals('Test32', testContract1.Company_s_Name__c);
        System.assertEquals(true, testContract1.Auto_Renewal__c);
        System.assertEquals(Date.today().format(), testContract1.Service_Commencement_Date__c.format());
        Test.stopTest();
    }
    static testMethod void testAfterUpdatevalidateRampDates() {
        Test.startTest();
        User u = [Select Id from User Where Id=:UserInfo.getUserId()];
        System.runAs(u){
            PermissionSet ps = new PermissionSet();
            ps.Name = 'Test';
            ps.Label = 'Test';
            insert ps;
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.AssigneeId = UserInfo.getUserId();
            psa.PermissionSetId = ps.Id;
            insert psa;
            SetupEntityAccess sea = new SetupEntityAccess();
            sea.ParentId = ps.Id;
            sea.SetupEntityId = [select Id from CustomPermission where DeveloperName = 'GCS_Read_Write_Ramp_Dates' limit 1].Id;
            insert sea;
            Account a= [Select Id from Account Where Name='Test32'];
            Licenseset__c licenceSetObj = [Select Id ,Opportunity__c from Licenseset__c];
            Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
            oppr.stagename = 'Closed Pending Approval';
            update oppr;
            // oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
            // System.assertNotEquals('Closed Won', oppr.StageName);
            // OpportunityEventHandler.skipExecution = false;
            // oppr.ECommerce_Convert__c=true;
            // oppr.stagename = 'Closed Won';
            // update oppr;
           Test.stopTest();
        }  
    }
    static testMethod void testAfterUpdatevalidateRampDatesException() {
        Test.startTest();
        User u = [Select Id from User Where Id=:UserInfo.getUserId()];
        System.runAs(u){
            try{
                PermissionSet ps = new PermissionSet();
                ps.Name = 'Test';
                ps.Label = 'Test';
                insert ps;
                PermissionSetAssignment psa = new PermissionSetAssignment();
                psa.AssigneeId = UserInfo.getUserId();
                psa.PermissionSetId = ps.Id;
                insert psa;
                SetupEntityAccess sea = new SetupEntityAccess();
                sea.ParentId = ps.Id;
                sea.SetupEntityId = [select Id from CustomPermission where DeveloperName = 'GCS_Read_Write_Ramp_Dates' limit 1].Id;
                insert sea;
                Account a= [Select Id from Account Where Name='Test32'];
                Licenseset__c licenceSetObj = [Select Id ,Opportunity__c from Licenseset__c];
                Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
                Product2 standardProduct = PGITestUtilities.getStdProduct();
                insert standardProduct;
                PricebookEntry standardPbe = PGITestUtilities.CreatePriceBookEntryForProduct(standardProduct);
                insert standardPbe;
                OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(oppr.Id, standardPbe.Id);
                oli.Existing_Service__c = false;
                insert oli; 
                oppr.stagename = 'Closed Pending Approval';
                Update oppr;
                OpportunityEventHandler.skipExecution = false;
                oppr.ECommerce_Convert__c=true;
                oppr.stagename = 'Closed Won';
                update oppr;
            }
            Catch(Exception e){
                // System.assert(e.getMessage().contains('Before setting Probability % to 80 or higher or Status to Closed Pending Approval, both Initial Bill Date and 100% Ramp Date on the product screen are required for any product that is not an Existing Service'));
                
            }
        }  
        Test.stopTest();
    }
    static testMethod void testUpdateOppFields() {
        Test.startTest();
        User u = [Select Id from User Where Id=:UserInfo.getUserId()];
        Set<Id> ownerId = new Set<Id>();
        ownerId.add(u.Id);
        System.runAs(u){
            Set<Id> closeOppId = new Set<Id>();
            
            List<Opportunity> oppList = new List<Opportunity>();
            Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
            oppr.stagename = 'Closed Pending Approval';
            oppr.OwnerId=u.Id;
            Update oppr;
            OpportunityEventHandler.skipExecution = false;
            oppr.ECommerce_Convert__c=true;
            oppr.stagename = 'Closed Won';
            update oppr;
            closeOppId.add(oppr.Id);
            oppList.add(oppr);   
            OpportunityEventHandler.UpdateOppFields(ownerId, oppList);    
            OpportunityEventHandler.addExistingOppLineItem(closeOppId);
           
        }
        Test.stopTest();
    } 
        static testMethod void testDeleteLicenseSet() {
            Test.startTest();
        Licenseset__c licenceSetObj = [Select Id ,Opportunity__c from Licenseset__c];
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
        oppList.add(oppr);
        OpportunityEventHandler.deleteOpporLicenseSets(oppList);
        Licenseset__c deletedliscSet = [SELECT Id, IsDeleted FROM Licenseset__c WHERE Z_Source__c = 'eCommerce' ALL ROWS];
        System.assertEquals(true, deletedliscSet.IsDeleted);
        Test.stopTest();
    }
    static testMethod void testDeleteAsset() {
        Test.startTest();
        Asset aseetObj = [Select Id,Opportunity__c from Asset];
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppr = [Select Id ,name,stagename,ECommerce_Convert__c,closeDate,ECommerce_Account_Number__c,Accountid,Z_Source__c,Acct_Admin_Decison_Maker_Checked__c from opportunity Where Name='Test oppor-1'];
        oppList.add(oppr);
        OpportunityEventHandler.deleteOpporLicenses(oppList);
        Asset deletedAsset = [SELECT Id, IsDeleted FROM Asset WHERE Name='Test' ALL ROWS];
        System.assertEquals(true, deletedAsset.IsDeleted);
        Test.stopTest();
    }
}