force-app/main/default/objects/Account/fields/ABM_Last_PES__c.field-meta.xml
<CustomField>
    <fullName>ABM_Last_PES__c</fullName>
    <description>The previous predictive engagement score of the account.</description>
    <inlineHelpText>The previous predictive engagement score of the account.</inlineHelpText>
    <label>ABM | Last PES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABM_PES_Last_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>ABM_PES_Last_Change_Date__c</fullName>
    <description>Date stamped when PES changes to x value.</description>
    <label>ABM | PES Last Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_Address_Verification__c.field-meta.xml
<CustomField>
    <fullName>Bill_Address_Verification__c</fullName>
    <description>Date the customer&#39;s address was verified (mainly for tax purposes).</description>
    <label>Bill Address Verification</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Acct_Admin_Decison_Maker_Checked__c.field-meta.xml
<CustomField>
    <fullName>Acct_Admin_Decison_Maker_Checked__c</fullName>
    <inlineHelpText>Accounts are required to have a contact flagged as an Acct Admin and as a Decision Maker.  Fields are located at the contact level.</inlineHelpText>
    <label>Acct Admin/Decison Maker Checked?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Existing_Service__c.field-meta.xml
<CustomField>
    <fullName>Existing_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enter 2 Products- 1st with the box checked for Existing Service, 2nd for New Service being added</inlineHelpText>
    <label>Existing Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/z_Source__c.field-meta.xml
<CustomField>
    <fullName>z_Source__c</fullName>
    <label>z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
            <value>
                <fullName>eCommerce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityProductExtensionTest.cls
@isTest
public class OpportunityProductExtensionTest {
    @testSetup static void setup(){
        Account act = new account(Name = 'Test32',ABM_Last_PES__c='testData',ABM_PES_Last_Change_Date__c =Date.today(),Bill_Address_Verification__c =Date.today().AddDays(2), Z_Source__c = 'eCommerce');
        insert act;
        Opportunity oppor = new Opportunity();
        oppor.name = 'Test oppor-1';
        oppor.stagename = 'Awareness';
        oppor.ECommerce_Convert__c=false;
        oppor.closeDate= system.today().addDays(100);
        oppor.ECommerce_Account_Number__c = 'Ecom-000000001';
        oppor.accountid = act.id;
        oppor.Z_Source__c = 'eCommerce';
        oppor.Acct_Admin_Decison_Maker_Checked__c = 'Yes';
        insert oppor;
        Product2 standardProduct = PGITestUtilities.getStdProduct();
        insert standardProduct;
        PricebookEntry standardPbe = PGITestUtilities.CreatePriceBookEntryForProduct(standardProduct);
        insert standardPbe;
        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(oppor.Id, standardPbe.Id);
        oli.Existing_Service__c = false;
        insert oli; 
    }
    static testMethod Void testOpprProdExtention(){
        Opportunity opp = [SELECT Id, RecordType.DeveloperName FROM Opportunity where name = 'Test oppor-1'];       
        String recordType =opp.RecordType.DeveloperName;
        OpportunityLineItem oppLineItem =[Select Id,OpportunityId from OpportunityLineItem Where Existing_Service__c = false]; 
        PageReference pageRef = Page.OpportunityProductViewPage;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.standardController(oppLineItem);
        OpportunityProductExtension obj = new OpportunityProductExtension(sc);
        Opportunity oppty =obj.oppty;
        String opptyRecordTypeName = obj.opptyRecordTypeName;
        List<Schema.FieldSetMember> fieldSet =obj.fieldSet;
        List<LayoutDescriberHelper.LayoutSection> layoutSections=obj.layoutSections;
        System.assertEquals(opp,oppty);
        System.assertEquals(recordType,opptyRecordTypeName);
    }

}