force-app/main/default/objects/Account/fields/ABM_Last_PES__c.field-meta.xml
<CustomField>
    <fullName>ABM_Last_PES__c</fullName>
    <description>The previous predictive engagement score of the account.</description>
    <inlineHelpText>The previous predictive engagement score of the account.</inlineHelpText>
    <label>ABM | Last PES</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ABM_PES_Last_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>ABM_PES_Last_Change_Date__c</fullName>
    <description>Date stamped when PES changes to x value.</description>
    <label>ABM | PES Last Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bill_Address_Verification__c.field-meta.xml
<CustomField>
    <fullName>Bill_Address_Verification__c</fullName>
    <description>Date the customer&#39;s address was verified (mainly for tax purposes).</description>
    <label>Bill Address Verification</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ECommerce_Convert__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECommerce Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Shows a lead record that relates to this contact</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Contacts</relationshipLabel>
    <relationshipName>Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/License_Profile__c.field-meta.xml
<CustomField>
    <fullName>License_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>License Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Cancelled or Lost Partner</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>End User - Agent</fullName>
            </value>
            <value>
                <fullName>End User - Carrier</fullName>
            </value>
            <value>
                <fullName>End User - Reseller</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>Managed</fullName>
            </value>
            <value>
                <fullName>Master Agent</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Prospecting</fullName>
            </value>
            <value>
                <fullName>Referral Customer</fullName>
            </value>
            <value>
                <fullName>Referral Partner</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Soundpath</fullName>
            </value>
            <value>
                <fullName>Sub Agent</fullName>
            </value>
            <value>
                <fullName>Sub-Reseller</fullName>
            </value>
            <value>
                <fullName>Territory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Custom field used to map Lead Description to Opportunity Description. By default, SFDC only maps the Lead Description field to the Contact Description field. This will allow for it to also be mapped to the Opportunity via Lead Mapping. A workflow rule on Lead will update this custom field from the standard Description field.</description>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DoNotSolicit__c.field-meta.xml
<CustomField>
    <fullName>DoNotSolicit__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Ecomm: used in back office for company create</description>
    <label>DoNotSolicit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <description>Source Value</description>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Number_of_Licensed_Named_Users__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Licensed_Named_Users__c</fullName>
    <label>Number of Licensed Named Users</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Subscription_License_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Subscription_License_Term_Months__c</fullName>
    <label>Subscription License Term(Months)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Acct_Admin_Decison_Maker_Checked__c.field-meta.xml
<CustomField>
    <fullName>Acct_Admin_Decison_Maker_Checked__c</fullName>
    <inlineHelpText>Accounts are required to have a contact flagged as an Acct Admin and as a Decision Maker.  Fields are located at the contact level.</inlineHelpText>
    <label>Acct Admin/Decison Maker Checked?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Custom field used to map Lead Description to Opportunity Description. By default, SFDC only maps the Lead Description field to the Contact Description field. This will allow for it to also be mapped to the Opportunity via Lead Mapping. A workflow rule on Opportunity will then update the standard Opportunity Description field on the page layout from this custom field.</description>
    <label>Description__c</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>This date indicates the date that an opportunity moved from qualified stage to a pipeline, closed won, or closed lost stage.</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PGI_Utility_Test.cls
@isTest (seealldata=true)
private class PGI_Utility_Test {
    static testMethod void testPgiUtility() {
        PGITestUtilities.disableSalesWings();
        Account act = new account(Name = 'Test32',ABM_Last_PES__c='testData',ABM_PES_Last_Change_Date__c =Date.today(),Bill_Address_Verification__c =Date.today().AddDays(2), Z_Source__c = 'eCommerce');
        insert act;
        
        System.assert(act.id <> null);
        
        Contact ct = new Contact();
        ct.FirstName = 'klnasknjaskldasd';
        ct.LastName  = 'efoijasjkndalkmsd';
        ct.Phone     = '3819405828';
        ct.Email     = 'knasdlkmsdklgasd@premierglobal.com';
        ct.accountId = act.id;
        ct.License_Profile__c = true;
        insert ct;
        
        Contact ct2 = new Contact();
        ct2.FirstName = 'cjnasdnkjaklwflkf';
        ct2.LastName  = 'njifasoinawlrkalsd';
        ct2.Phone     = '1950247284';
        ct2.Email     = 'efkjnsdlkmsalmd@premierglobal.com';
        ct2.accountId = act.id;
        ct2.License_Profile__c = true;
        insert ct2;
        Lead ld = new Lead(
            FirstName = 'cjnkdfjnklknasjknfawbjkd',
            LastName = 'cansknjaeflkwanjkd',
            Phone = '1592839429',
            Email = 'jknasnkjaskdjnlasd@pgi.com',
            //ECommerce_Account_Number__c = 'Ecom-000000001',
            ECommerce_Convert__c = false,
            LeadSource = 'ECommerce Customer',
            Company = 'cjknasnlklkmasdjkbasd',
            Status = 'Qualifying',
            Street = '1500 cnasdjknawlkf',
            City = 'SanJose',
            State = 'California',
            StateCode = 'CA',
            PostalCode = '25859',
            Country = 'United States',
            CountryCode = 'US',
            Business_Type__c = 1,
            DoNotSolicit__c = true,
            Z_Source__c = 'eCommerce',
            Account_Type__c = 'Affinity'
        );
        
        insert ld;
        Opportunity oppor = new Opportunity();
        oppor.name = 'Test oppor-1';
        oppor.stagename = 'Awareness';
        oppor.closeDate= system.today().addDays(100);
        oppor.ECommerce_Account_Number__c = 'Ecom-000000001';
        oppor.accountid = act.id;
        oppor.Z_Source__c = 'eCommerce';
        oppor.Acct_Admin_Decison_Maker_Checked__c = 'Yes';
        insert oppor;
        // Insert offerings
        Licenseset__c licSet        = new Licenseset__c();
        licSet.Description__c       = 'Lic Set - 1';
        licSet.End_Date__c          = system.today().adddays(100);
        licSet.Lead__c              = ld.id;
        licSet.Line_Number__c       = 1;
        licSet.Number_of_Licensed_Named_Users__c = 1;
        licSet.Order_Number__c      = 1;
        licSet.Price__c             = 12.22;
        licSet.SKU__c               = 'SKU-000000001';
        licSet.Start_Date__c        = system.today();
        licSet.Subscription_License_Term_Months__c = 12;
        licSet.name                 = 'Lic Set -1';
        licSet.Opportunity__c=oppor.Id;
        licSet.Z_Source__c = 'eCommerce';    
        insert licSet;
        
        Set<String> fieldsToRemove = new  Set<String>();
        fieldsToRemove.add('ABM_Last_PES__c');
        List<Account> accList = new List<Account>();
        accList.add(act);
        PGI_Utility obj = new PGI_Utility();
        PGI_Utility.removeFields(accList,fieldsToRemove);
        Account a = [Select ABM_Last_PES__c from Account Where Name='Test32'];
        System.debug('The return list'+PGI_Utility.removeFields(accList,fieldsToRemove));
        system.assertEquals(Date.today().AddDays(2), PGI_Utility.findMinimumDate(accList,'Bill_Address_Verification__c'));
        system.assertEquals(Date.today(), PGI_Utility.findMaximumDate(accList,'ABM_PES_Last_Change_Date__c'));
        Date d= Date.today().addMonths(1);
        system.assertEquals(Date.newInstance(d.year(), d.month(), 1), PGI_Utility.startOfNextMonth(Date.today()));
        Date d1= Date.today();
        Integer daysInMonth = Date.daysInMonth(d1.year(), d1.month());
        system.assertEquals(Date.newInstance(d1.year(), d1.month(), daysInMonth), PGI_Utility.endOfMonth(Date.today()));
        system.assertEquals(null, PGI_Utility.startOfNextMonth(null));
        system.assertEquals(null, PGI_Utility.endOfMonth(null));
        system.assertEquals(null, PGI_Utility.startOfMonth(null));
        List<Licenseset__c> licensesetList = new List<Licenseset__c>();
        licensesetList.add(licSet);
        
        List<Asset> assetLst =new List<Asset>();
        assetLst.add(PGI_Utility.createOpporAsset(licensesetList)[0]);
       //System.debug('123'+PGI_Utility.createOpporAsset(licensesetList));
        system.assertEquals('Lic Set -1', assetLst[0].Name);
        List<opportunity> opprLst = new List<opportunity>();
        opprLst.add(oppor);
        Map<Id,Id> ldOpprIdMap = new Map<Id,Id>();
        ldOpprIdMap.put(ld.Id, oppor.Id);
        //PGI_Utility.createOpporLicenseSet(ldOpprIdMap);
        User currentUser = PGI_Utility.currentUser;
        Integer currentHourInGMT =PGI_Utility.hourInMT;
        list<Licenseset__c> licSetLst = new list<Licenseset__c>();
        licSetLst.add( PGI_Utility.createOpporLicenseSet(ldOpprIdMap)[0]);
        system.assertEquals(oppor.Id, licSetLst[0].opportunity__c);
    }
    
}