force-app/main/default/objects/Account/fields/Account_Codes__c.field-meta.xml
<CustomField>
    <fullName>Account_Codes__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Requires chairperson to enter an account (billing) code on the bridge prior to starting an audio call.</inlineHelpText>
    <label>Account Code Prompt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/App_Share_Allowed__c.field-meta.xml
<CustomField>
    <fullName>App_Share_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Provides chairperson (and co-presenters) with access to “Share Desktop,” “Share Applications,” and “Grant Control” options.</inlineHelpText>
    <label>App Share Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Auto_Delete_Slides__c.field-meta.xml
<CustomField>
    <fullName>Auto_Delete_Slides__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checked, presentation slides will be automatically deleted at the end of a web meeting.</inlineHelpText>
    <label>Auto Delete Slides</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Copresenter_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Copresenter_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Allows chairperson to promote participant/s to presenter status.</inlineHelpText>
    <label>Copresenter Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Entry_Announcement__c.field-meta.xml
<CustomField>
    <fullName>Entry_Announcement__c</fullName>
    <inlineHelpText>Announces a participant entering an audio conference via a tone or the participant’s name.</inlineHelpText>
    <label>Entry Announcement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tone</fullName>
                <default>true</default>
                <label>Tone</label>
            </value>
            <value>
                <fullName>Silence</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/International_Dial_Out_Allowed__c.field-meta.xml
<CustomField>
    <fullName>International_Dial_Out_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>International Dial Out Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Moderator_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Moderator_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If unchecked, the chairperson will not be able to launch Conference Controls from CC (Will not be able to host an on-demand web meeting or manage an audio conference using the Conference Controls).</inlineHelpText>
    <label>Conference Controls Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Quickstart__c.field-meta.xml
<CustomField>
    <fullName>Quickstart__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allows an audio conference to start without the chairperson. Participants will be placed directly into the meeting without the need for the chairperson to log in.</inlineHelpText>
    <label>Quickstart Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Recording_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Will slow down provisioning when updated.  Needs to be updated with non-patria user name</description>
    <inlineHelpText>Allows chairperson to record audio or audio/web conference.</inlineHelpText>
    <label>Recording Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Recording_Editing_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Recording_Editing_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Allow recordings to be edited</description>
    <inlineHelpText>Allows chairperson to edit audio and web recordings in Conference Center.</inlineHelpText>
    <label>Recording Editing Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Security_Option__c.field-meta.xml
<CustomField>
    <fullName>Security_Option__c</fullName>
    <inlineHelpText>Requires chairperson and participants to enter a security code on the bridge to gain access to an audio conference.</inlineHelpText>
    <label>Security Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Security</fullName>
                <default>true</default>
                <label>No Security</label>
            </value>
            <value>
                <fullName>Optional Security</fullName>
            </value>
            <value>
                <fullName>Mandatory Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Slide_Presentation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Slide_Presentation_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Allows chairperson (and co-presenter) to upload/push slides and insert/push polls.</inlineHelpText>
    <label>Slide Presentation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Video_Conferencing_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Video_Conferencing_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Provides chairperson and co-presenters with the ability to share four video feeds simultaneously.</inlineHelpText>
    <label>Video Conferencing Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Web_Conf_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Web_Conf_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Allows chairperson to host a web conference via Conference Controls. If unchecked, user only has audio privileges in Conference Controls.</inlineHelpText>
    <label>Web Conf Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account_Code_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Account_Code_Prompt__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Requires chairperson to enter an internal code (billing code/client matter code) on the bridge prior to starting an audio conference.</inlineHelpText>
    <label>Account Code Prompt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/App_Share_Allowed__c.field-meta.xml
<CustomField>
    <fullName>App_Share_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Provides chairperson (and co-presenters) with access to “Share Desktop,” “Share Applications,” and “Grant Control” options.</inlineHelpText>
    <label>App Share Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Auto_Delete_Slides__c.field-meta.xml
<CustomField>
    <fullName>Auto_Delete_Slides__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If checked, presentation slides will be automatically deleted when the web moderator is closed.</inlineHelpText>
    <label>Auto Delete Slides</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Entry_Announcement__c.field-meta.xml
<CustomField>
    <fullName>Entry_Announcement__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Audio feature alerts chairperson when participants enter an audio conference (tone, silence or a name announcement). This sends an email to Level 3 to have them change it on the bridge.</inlineHelpText>
    <label>Entry Announcement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tone</fullName>
            </value>
            <value>
                <fullName>Silence</fullName>
            </value>
            <value>
                <fullName>Name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/International_Dial_Out_Allowed__c.field-meta.xml
<CustomField>
    <fullName>International_Dial_Out_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If checked, allows chairperson to dial-out to Int’l participants from the audio bridge.</inlineHelpText>
    <label>International Dial Out Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Moderator_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Moderator_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If unchecked, the chairperson will not be able to launch Conference Controls from CC (Will not be able to host an on-demand web meeting or manage an audio conference using the Conference Controls).</inlineHelpText>
    <label>Conference Controls Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Quickstart__c.field-meta.xml
<CustomField>
    <fullName>Quickstart__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Provides chairperson with the OPTION to enable/disable Quickstart via the bridge. If enabled, participants will be placed directly into an audio conference without the chairperson logging in.</inlineHelpText>
    <label>Quickstart Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Recording_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Recording_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Allows chairperson to record audio or audio/web conference.</inlineHelpText>
    <label>Recording Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Recording_Editing_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Recording_Editing_Allowed__c</fullName>
    <defaultValue>true</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If it&#39;s okay for the recording editor to be used on this subscription&#39;s recordings, check this box.</description>
    <inlineHelpText>Allows chairperson to edit audio and web recordings in Conference Center.</inlineHelpText>
    <label>Recording Editing Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Security_Passcode__c.field-meta.xml
<CustomField>
    <fullName>Security_Passcode__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Requires chairperson and participants to enter a security code on the bridge to gain access to an audio conference.</inlineHelpText>
    <label>Security Option</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No security</fullName>
            </value>
            <value>
                <fullName>Optional security</fullName>
            </value>
            <value>
                <fullName>Mandatory security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Slide_Presentation_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Slide_Presentation_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Allows chairperson (and co-presenter) to upload/push slides and insert/push polls.</inlineHelpText>
    <label>Slide Presentation Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Video_Conferencing_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Video_Conferencing_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Provides chairperson and co-presenters with the ability to share four video feeds simultaneously.</inlineHelpText>
    <label>Video Conferencing Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Web_Conference_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Web_Conference_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Allows chairperson to host a web conference via Conference Controls. If unchecked, user only has audio privileges in Conference Controls.</inlineHelpText>
    <label>Web Conference Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>If there was an error in provisioning the subscription, then it is of this record type</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/AccountCascadeSettingsController.cls
public with sharing class AccountCascadeSettingsController extends BaseController {

  public Account a {get; set;}
  
  public Boolean accountCodePrompt {get; set;}
  public Boolean appShareAllowed {get; set;}
  public Boolean archivePeriod {get; set;}
  public Boolean autoDeleteSlides {get; set;}
  public Boolean conferenceControlsAllowed {get; set;}
  public Boolean coPresenterAllowed {get; set;}
  public Boolean entryAnnouncement {get; set;}
  public Boolean internationalDialoutAllowed {get; set;}
  public Boolean grantControlAllowed {get; set;}
  public Boolean numberOfAudioPorts {get; set;}
  public Boolean podcasting {get; set;}
  public Boolean quickstartAllowed {get; set;}
  public Boolean recordingAllowed {get; set;}
  public Boolean recordingEditingAllowed {get; set;}
  public Boolean securityOption {get; set;}
  public Boolean slidePresentationAllowed {get; set;}
  public Boolean voipAllowed {get; set;}
  public Boolean videoConferencingAllowed {get; set;}
  public Boolean webConfAllowed {get; set;}
  
  public List<ErrorMessage> errorMessages;
  
  public AccountCascadeSettingsController(ApexPages.StandardController controller) {
    if(getPageID() != null)
      this.a = (Account) RTDatabaseUtils.getEntireSObject(new Account(), getPageID());
  }

  public PageReference cascadeSettings() {     
    try {
      List<Subscription__c> subscriptions = (List<Subscription__c>) RTDatabaseUtils.getSObjectList(new Subscription__c(), 'where Provision__c = true and Inactive__c = false and Contact__r.Account.id = \''+this.a.id+'\'');
      
      for(Subscription__c sub : subscriptions) {
        sub.Recording_Allowed__c = this.recordingAllowed==true ? this.a.Recording_Allowed__c : sub.Recording_Allowed__c;
        sub.Recording_Editing_Allowed__c = this.recordingEditingAllowed ? this.a.Recording_Editing_Allowed__c : sub.Recording_Editing_Allowed__c;
        sub.Account_Code_Prompt__c = this.accountCodePrompt ? this.a.Account_Codes__c : sub.Account_Code_Prompt__c;
        sub.Security_Passcode__c = this.securityOption ? this.a.Security_Option__c : sub.Security_Passcode__c;
        sub.Quickstart__c = this.quickstartAllowed ? this.a.Quickstart__c : sub.Quickstart__c;
        sub.International_Dial_Out_Allowed__c = this.internationalDialoutAllowed ? this.a.International_Dial_Out_Allowed__c : sub.International_Dial_Out_Allowed__c;
        sub.Entry_Announcement__c = this.entryAnnouncement ? this.a.Entry_Announcement__c : sub.Entry_Announcement__c;
        sub.Moderator_Allowed__c = this.conferenceControlsAllowed ? this.a.Moderator_Allowed__c : sub.Moderator_Allowed__c;
        sub.Web_Conference_Allowed__c = this.webConfAllowed ? this.a.Web_Conf_Allowed__c : sub.Web_Conference_Allowed__c;
        sub.Video_Conferencing_Allowed__c = this.videoConferencingAllowed ? this.a.Video_Conferencing_Allowed__c : sub.Video_Conferencing_Allowed__c;
        sub.Slide_Presentation_Allowed__c = this.slidePresentationAllowed ? this.a.Slide_Presentation_Allowed__c : sub.Slide_Presentation_Allowed__c;
        sub.App_Share_Allowed__c = this.appShareAllowed ? this.a.App_Share_Allowed__c : sub.App_Share_Allowed__c;
        sub.Auto_Delete_Slides__c = this.autoDeleteSlides ? this.a.Auto_Delete_Slides__c : sub.Auto_Delete_Slides__c;
        sub.Copresenter_Allowed__c = this.coPresenterAllowed ? this.a.Copresenter_Allowed__c : sub.Copresenter_Allowed__c;
        sub.Archive_Period__c = this.archivePeriod ? this.a.Archive_Period__c : sub.Archive_Period__c;
        sub.Remote_Control_Allowed__c = this.grantControlAllowed ? this.a.Remote_Control_Allowed__c : sub.Remote_Control_Allowed__c;
        sub.Audio_Subscription_Size__c = this.numberOfAudioPorts ? this.a.Audio_Subscription_Size__c : sub.Audio_Subscription_Size__c;
        sub.Podcasting__c = this.podcasting ? this.a.Podcast__c : sub.Podcasting__c;
        sub.voipAllowed__c = this.voipAllowed ? this.a.voipAllowed__c : sub.voipAllowed__c;
      }
      
      //Perform the update; add any to the errorMessages list
      this.errorMessages = new List<ErrorMessage>();
      Database.SaveResult[] updateResults = Database.update(subscriptions,false);
      Integer index = 0;
      for(Database.SaveResult updateResult : updateResults) {
        if(!updateResult.isSuccess()) {
          ErrorMessage message = new ErrorMessage();
          message.setId(subscriptions.get(index).Id);
          message.setMessage('Access Code: '+subscriptions.get(index).name+' Message: '+updateResult.getErrors()[0].getMessage());
          this.errorMessages.add(message);
        }
        index++;
      }
      
      //If there are error messages, then stay on the page
      if(!errorMessages.isEmpty())
        return null;
    }
    catch(Exception ex){
      //If there are error messages, then stay on the page
      this.errorMessages = new List<ErrorMessage>();
      ErrorMessage message = new ErrorMessage();
      message.setMessage(ex.getMessage() +' '+ex.getStackTraceString());
      this.errorMessages.add(message);
      return null;
    }
    
    //Update was a success, got back to the account view
    return gotoView(this.a);
  }
  
  public void setErrorMessages(List<ErrorMessage> errorMessages) {
    this.errorMessages = errorMessages;
  }
  
  public List<ErrorMessage> getErrorMessages() {    
    return this.errorMessages;
  }

  public virtual override PageReference cancel() {
    return gotoView(this.a.id);
  }  

}