force-app/main/default/objects/Account/fields/AutoRenewalEmail__c.field-meta.xml
<CustomField>
    <fullName>AutoRenewalEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For every access code subscribed to an annual plan, send the Contact an email, 30 days prior to the plan start date, indicating that their subscription will be automatically renewed.</description>
    <label>Automated Renewal Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>this are are the product they purchased and maps to product line</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premier Edition</fullName>
            </value>
            <value>
                <fullName>Marketing Premier Edition</fullName>
            </value>
            <value>
                <fullName>SocialBridge</fullName>
            </value>
            <value>
                <fullName>Marketers</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Team Edition</fullName>
            </value>
            <value>
                <fullName>Team Plus Edition</fullName>
            </value>
            <value>
                <fullName>Marketing Professional</fullName>
            </value>
            <value>
                <fullName>Community Edition</fullName>
            </value>
            <value>
                <fullName>Company Plan</fullName>
            </value>
            <value>
                <fullName>Free Edition</fullName>
            </value>
            <value>
                <fullName>Group Edition</fullName>
            </value>
            <value>
                <fullName>Professional Edition</fullName>
            </value>
            <value>
                <fullName>Team Plan</fullName>
            </value>
            <value>
                <fullName>Workgroup Edition</fullName>
            </value>
            <value>
                <fullName>Self Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/NegotiatedProduct__c.object-meta.xml
<CustomObject>
    <description>Configured Components under Products assigned to an Account.</description>
    <label>Negotiated Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NegotiatedProduct__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RT Product</label>
    <referenceTo>RT_Product__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>Negotiated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/PlanAssignment__c.object-meta.xml
<CustomObject>
    <description>Assigned Products related to Access Codes.</description>
    <label>Plan Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/fields/accessCode__c.field-meta.xml
<CustomField>
    <fullName>accessCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>PlanAssignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>Plan_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>PlanAssignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/RecurringChargeOverride__c.object-meta.xml
<CustomObject>
    <label>Recurring Charge Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Charge Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringChargeOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Recurring Charge Overrides</relationshipLabel>
    <relationshipName>RecurringChargeOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/fields/recurringCharge__c.field-meta.xml
<CustomField>
    <fullName>recurringCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Recurring Charge</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/fields/recurringChargeFrequency__c.field-meta.xml
<CustomField>
    <fullName>recurringChargeFrequency__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Recurring Charge Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ANNUALLY</fullName>
            </value>
            <value>
                <fullName>INVOICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/recurringCharge__c.field-meta.xml
<CustomField>
    <fullName>recurringCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Recurring Charge</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>HYPERLINK(Contact__r.Account.Id, Contact__r.Account.Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscriber Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlanRenewalEmailerSchedulable.cls
global with sharing class PlanRenewalEmailerSchedulable implements Schedulable {
    
  global void execute(SchedulableContext context) {
    runRenewal();
  }    
      
  public List<Messaging.SingleEmailMessage> runRenewal() {
    System.debug('runRenewal method called');
    List<Messaging.SingleEmailMessage> msgList = new List<Messaging.SingleEmailMessage>();
    List<Plan__c> plans = getAnnualAccessCodePlansDueForRenewal(getAutoRenewalAccounts());
    List<PlanAssignment__c> planAssignments = getActiveContactsByPlan(plans);
    EmailTemplate template = [SELECT id from EmailTemplate where developerName = 'Subscription_Renewal'];
    for (PlanAssignment__c planAss : planAssignments) {
      Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
      msg.setTemplateId(template.Id);
      msg.setTargetObjectId(planAss.accessCode__r.Contact__c);
      msg.setSenderDisplayName('ReadyTalk Provisioning');
      msg.setWhatId(planAss.plan__r.Id);
      msg.setUseSignature(false);
      msg.setReplyTo('noreply@pgi.com');
      msgList.add(msg);
    }
    Messaging.sendEmail(msgList, true);
    return msgList;
  }
    
  private List<Plan__c> getAnnualAccessCodePlansDueForRenewal(List<String> accountIds) {
    List<Plan__c> plans = [select Id, name, (select Id, name, product__r.recurringChargeFrequency__c, product__r.recurringCharge__c from NegotiatedProducts__r) 
      from Plan__c where billableType__c = 'ACCESS_CODE' and startDate__c < TODAY
      and DAY_IN_YEAR(startDate__c) = :Date.today().addDays(30).dayOfYear()
      and (endDate__c = null or endDate__c > :Date.today().addDays(30))
      and account__r.Id in :accountIds];
      
    Map<String, RecurringChargeOverride__c> rcoMap = getRecurringChargeOverrides();
    List<Plan__c> validPlans = new List<Plan__c>();
    for (Plan__c plan : plans) {
      System.debug('plan name = ' + plan.Name);
      for (NegotiatedProduct__c np : plan.NegotiatedProducts__r) {
        System.debug('np.name = ' + np.Name);
        System.debug('np.product__r.recurringChargeFrequency__c = ' +  np.product__r.recurringChargeFrequency__c + ' ' + np.product__r.Id);
        if (rcoMap.containsKey(np.Id)) {
          System.debug('np.Id has rco');
          if (rcoMap.get(np.Id).recurringChargeFrequency__c == 'ANNUALLY' && rcoMap.get(np.Id).recurringCharge__c > 0) {
            System.debug('Plan rco frequency is annual and charge is > 0');
            validPlans.add(plan);
          }
          continue;
        }
        if (np.product__r.recurringChargeFrequency__c == 'ANNUALLY' && np.product__r.recurringCharge__c > 0) {
          System.debug('Plan is annual and charge is > 0');
          validPlans.add(plan);
          continue;
        }
      }
    }
    return validPlans;
  }

  private Map<String, RecurringChargeOverride__c> getRecurringChargeOverrides() {
    Map<String, RecurringChargeOverride__c> rcoMap = new Map<String, RecurringChargeOverride__c>();
    List<RecurringChargeOverride__c> overrides = (List<RecurringChargeOverride__c>) Database.query('select Id, negotiatedProduct__r.Id, recurringCharge__c, recurringChargeFrequency__c from RecurringChargeOverride__c');
    for (RecurringChargeOverride__c rco : overrides) {
      rcoMap.put(rco.negotiatedProduct__r.Id, rco);
    }
    return rcoMap;
  }
    
  private List<String> getAutoRenewalAccounts() {
    List<String> accountIds = new List<String>();
    List<Account> accounts = [select id from Account where AutoRenewalEmail__c = true];
    for (Account account : accounts) {
      System.debug('account with sfId: ' + account.Id + ' is on Auto Renewal');
      accountIds.add(account.Id);
    }
    return accountIds;
  }
  
  private List<PlanAssignment__c> getActiveContactsByPlan(List<Plan__c> plans) {
    List<String> planIds = new List<String>();
    for (Plan__c plan : plans) {
      planIds.add(plan.Id);
    }
    List<PlanAssignment__c> planAssignments = [SELECT Id, accessCode__r.inactive__c, accessCode__r.Contact__c, plan__r.Id FROM PlanAssignment__c 
      where (endDate__c = null OR endDate__c > :Date.today().addDays(30)) and accessCode__r.inactive__c = false and Plan__c in :planIds];
    return planAssignments;
  }
}