force-app/main/default/objects/Account/fields/AutoRenewalEmail__c.field-meta.xml
<CustomField>
    <fullName>AutoRenewalEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For every access code subscribed to an annual plan, send the Contact an email, 30 days prior to the plan start date, indicating that their subscription will be automatically renewed.</description>
    <label>Automated Renewal Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>this are are the product they purchased and maps to product line</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premier Edition</fullName>
            </value>
            <value>
                <fullName>Marketing Premier Edition</fullName>
            </value>
            <value>
                <fullName>SocialBridge</fullName>
            </value>
            <value>
                <fullName>Marketers</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Team Edition</fullName>
            </value>
            <value>
                <fullName>Team Plus Edition</fullName>
            </value>
            <value>
                <fullName>Marketing Professional</fullName>
            </value>
            <value>
                <fullName>Community Edition</fullName>
            </value>
            <value>
                <fullName>Company Plan</fullName>
            </value>
            <value>
                <fullName>Free Edition</fullName>
            </value>
            <value>
                <fullName>Group Edition</fullName>
            </value>
            <value>
                <fullName>Professional Edition</fullName>
            </value>
            <value>
                <fullName>Team Plan</fullName>
            </value>
            <value>
                <fullName>Workgroup Edition</fullName>
            </value>
            <value>
                <fullName>Self Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/NegotiatedProduct__c.object-meta.xml
<CustomObject>
    <description>Configured Components under Products assigned to an Account.</description>
    <label>Negotiated Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NegotiatedProduct__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RT Product</label>
    <referenceTo>RT_Product__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>Negotiated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <description>Default configuration and pricing of products that we sell; e.g. Web Meeting Pro (25)</description>
    <label>Package</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT</fullName>
            </value>
            <value>
                <fullName>ANY</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>ACCOUNT,SEAT,FOXDEN_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/basePackage__c.field-meta.xml
<CustomField>
    <fullName>basePackage__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/billableType__c.field-meta.xml
<CustomField>
    <fullName>billableType__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Billable Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNT</fullName>
            </value>
            <value>
                <fullName>ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE</fullName>
            </value>
            <value>
                <fullName>SEAT,ACCESS_CODE,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT,FOXDEN_USER</fullName>
            </value>
            <value>
                <fullName>SEAT</fullName>
            </value>
            <value>
                <fullName>S3_USER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/quantityStartDate__c.field-meta.xml
<CustomField>
    <fullName>quantityStartDate__c</fullName>
    <label>quantityStartDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/RecurringChargeOverride__c.object-meta.xml
<CustomObject>
    <label>Recurring Charge Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Charge Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringChargeOverride__c/fields/baseProductRecurringCharge__c.field-meta.xml
<CustomField>
    <fullName>baseProductRecurringCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Product Recurring Charge</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Recurring Charge Overrides</relationshipLabel>
    <relationshipName>RecurringChargeOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/fields/recurringCharge__c.field-meta.xml
<CustomField>
    <fullName>recurringCharge__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Recurring Charge</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SingleChargeOverride__c/SingleChargeOverride__c.object-meta.xml
<CustomObject>
    <label>Single Charge Override</label>
    <nameField>
        <label>Single Charge Overrides Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Single Charge Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SingleChargeOverride__c/fields/baseProductSingleCharge__c.field-meta.xml
<CustomField>
    <fullName>baseProductSingleCharge__c</fullName>
    <label>Base Product Single Charge</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SingleChargeOverride__c/fields/endDate__c.field-meta.xml
<CustomField>
    <fullName>endDate__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SingleChargeOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Single Charge Overrides</relationshipLabel>
    <relationshipName>SingleChargeOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SingleChargeOverride__c/fields/singleCharge__c.field-meta.xml
<CustomField>
    <fullName>singleCharge__c</fullName>
    <label>Single Charge</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SingleChargeOverride__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OverridesTotalDTOTest.cls
@isTest
public class OverridesTotalDTOTest {
    //test addRecurringCharge
    static testmethod void testaddRecurringCharge(){
         Account accObj = new Account(Name = 'TestAcc',AutoRenewalEmail__c = true);
        Insert accObj;
        
        Package__c pkgObj = new Package__c(Name = 'Testpkg');
       	Insert pkgObj;
        
        List<Plan__c> planList = new List<Plan__c>{
            new Plan__c(Name = 'TestPlan',quantity__c = 10,quantityStartDate__c = Date.today().addDays(-3),
                        billableType__c = 'ACCESS_CODE',account__c = accObj.Id,basePackage__c = pkgObj.Id,
                        startDate__c = Date.today().addDays(-3), endDate__c = null) }; 
                            Insert planList;
        
         NegotiatedProduct__c npObj = new NegotiatedProduct__c(Name = 'TestNegstPrdt',account__c = accObj.Id,plan__c = planList[0].Id);  //, product__c = rtpObj.Id);
        Insert npObj;
        List<RecurringChargeOverride__c> rcoobjList = new List<RecurringChargeOverride__c>{
            new RecurringChargeOverride__c(Name = 'test0',baseProductRecurringCharge__c = 10, 
                                           negotiatedProduct__c = npObj.Id,recurringCharge__c = 0, startDate__c = date.today()),
                new RecurringChargeOverride__c(Name = 'test1',baseProductRecurringCharge__c = 10, 
                                           negotiatedProduct__c = npObj.Id, recurringCharge__c = 10, startDate__c = date.today()) };
                    INSERT rcoobjList;
        
      Test.startTest();
        OverridesTotalDTO obj = new OverridesTotalDTO();
        obj.addRecurringCharge(rcoobjList[0]);
        obj.addRecurringCharge(rcoobjList[1]);
        System.assertEquals(10.00, [SELECT id,recurringCharge__c FROM RecurringChargeOverride__c WHERE name = 'test1'].recurringCharge__c);
        Test.stopTest();
    }
    //test addSingleCharge
    static testmethod void testaddSingleCharge(){
        
         Account accObj = new Account(Name = 'TestAcc',AutoRenewalEmail__c = true);
        Insert accObj;
        
        Package__c pkgObj = new Package__c(Name = 'Testpkg');
       	Insert pkgObj;
        
        List<Plan__c> planList = new List<Plan__c>{
            new Plan__c(Name = 'TestPlan',quantity__c = 10,quantityStartDate__c = Date.today().addDays(-3),
                        billableType__c = 'ACCESS_CODE',account__c = accObj.Id,basePackage__c = pkgObj.Id,
                        startDate__c = Date.today().addDays(-3), endDate__c = null) }; 
                            Insert planList;
        
         NegotiatedProduct__c npObj = new NegotiatedProduct__c(Name = 'TestNegstPrdt',account__c = accObj.Id,plan__c = planList[0].Id);  //, product__c = rtpObj.Id);
        Insert npObj;
        
        List<SingleChargeOverride__c> scoobjList = new List<SingleChargeOverride__c>{
            new SingleChargeOverride__c(Name = 'test0',baseProductSingleCharge__c = 10,singleCharge__c = 0, 
                                           negotiatedProduct__c = npObj.Id, startDate__c = date.today()),
                new SingleChargeOverride__c(Name = 'test1',baseProductSingleCharge__c = 10, singleCharge__c = 10,
                                           negotiatedProduct__c = npObj.Id, startDate__c = date.today()) };
                    INSERT scoobjList;
        
      Test.startTest();
        OverridesTotalDTO obj = new OverridesTotalDTO();
        obj.addSingleCharge(scoobjList[0]);
        obj.addSingleCharge(scoobjList[1]);
        System.assertEquals(10.00, [SELECT id,singleCharge__c FROM SingleChargeOverride__c WHERE name = 'test1'].singleCharge__c);
       Test.stopTest();
    }
}