force-app/main/default/objects/Account/fields/BBS_InvoiceFrequency__c.field-meta.xml
<CustomField>
    <fullName>BBS_InvoiceFrequency__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Invoice Frequency</description>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY</fullName>
                <default>true</default>
                <label>MONTHLY</label>
            </value>
            <value>
                <fullName>WEEKLY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/BBS_L3ServiceProvider__c.field-meta.xml
<CustomField>
    <fullName>BBS_L3ServiceProvider__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Service provider used to provision with L(3)</description>
    <label>L3 ServiceProvider</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>247</fullName>
            </value>
            <value>
                <fullName>558</fullName>
            </value>
            <value>
                <fullName>645</fullName>
            </value>
            <value>
                <fullName>737</fullName>
            </value>
            <value>
                <fullName>755</fullName>
                <default>true</default>
                <label>755</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Toll_Free_Number__c.field-meta.xml
<CustomField>
    <fullName>Toll_Free_Number__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Toll Free Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3039993333</fullName>
            </value>
            <value>
                <fullName>8667401260</fullName>
                <default>true</default>
                <label>8667401260</label>
            </value>
            <value>
                <fullName>8009257671</fullName>
            </value>
            <value>
                <fullName>8772948214</fullName>
            </value>
            <value>
                <fullName>8008301513</fullName>
            </value>
            <value>
                <fullName>8006499919</fullName>
            </value>
            <value>
                <fullName>8663654411</fullName>
            </value>
            <value>
                <fullName>8006617007</fullName>
            </value>
            <value>
                <fullName>8006772898</fullName>
            </value>
            <value>
                <fullName>8009371839</fullName>
            </value>
            <value>
                <fullName>8553484177</fullName>
            </value>
            <value>
                <fullName>8775574194</fullName>
            </value>
            <value>
                <fullName>8554304241</fullName>
            </value>
            <value>
                <fullName>8553554218</fullName>
            </value>
            <value>
                <fullName>8555594243</fullName>
            </value>
            <value>
                <fullName>8772217520</fullName>
            </value>
            <value>
                <fullName>8007229903</fullName>
            </value>
            <value>
                <fullName>8553914244</fullName>
            </value>
            <value>
                <fullName>8006054285</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testAccountProvisionController.cls
@isTest
private class testAccountProvisionController {
    
    static testMethod Id createacc(){
        Account a = new Account(Name='Test0',Status__c = 'New',BBS_L3ServiceProvider__c = null,BBS_InvoiceFrequency__c = null,
                               Toll_Free_Number__c = null);
        INSERT a;
        RTDatabaseUtils.getEntireSObject(new Account(), a.Id);
        return a.Id;
    }
    
  //private static ApexPages.StandardController controller = new ApexPages.StandardController(RTDatabaseUtils.getEntireSObject(new Account(), MockAccount.getNewAccount().id));
  private static ApexPages.StandardController controller = new ApexPages.StandardController(RTDatabaseUtils.getEntireSObject(new Account(), createacc()));

  //AccountProvisionController.AccountProvisionController
  static testMethod void testConstruct() {
    AccountProvisionController c = new AccountProvisionController(controller);
    c.getAccountId();
    System.assert(c != null);
  }

  //AccountProvisionController.getAudioSchedulesByType
  static testMethod void testGetAudioSchedulesByType() {
      Test.startTest();
      Schedule scheduleRepo = new Schedule();
        scheduleRepo.findAllSchedulesByType('Audio');
      Test.stopTest();
    System.assert(AccountProvisionController.getAudioSchedulesByType('Audio')!=null);
  }  

  //AccountProvisionController.getStatusMessage
  static testMethod void testGetStatusMessage() {
      Account acc = new Account();
      acc.Name='Test';
      acc.Status__c= null;
      insert acc;
      //RTDatabaseUtils.getEntireSObject(new Account(), acc.Id);
      AccountProvisionController.getStatusMessage(acc.Id);
 }

  //AccountProvisionController.Provision
  static testMethod void testProvision() {
    Account a = (Account)controller.getRecord();

    //Create a new schedule
    Schedule scheduleRepo = new Schedule();
    Schedule__c audioSchedule = scheduleRepo.saveSchedule('Audio: Test Schedule', 'A test audio schedule', 'Audio', Double.valueOf(1.0));
    Schedule__c webSchedule = scheduleRepo.saveSchedule('Web: Test Schedule', 'A test web schedule', 'Web', Double.valueOf(2.0));
    Schedule__c hostingSchedule = scheduleRepo.saveSchedule('Hosting: Test Schedule', 'A test hosting schedule', 'Hosting', Double.valueOf(3.0));

    System.assert(AccountProvisionController.provision(a.Id, audioSchedule.name, audioSchedule.Id, webSchedule.name, webSchedule.Id, hostingSchedule.name, hostingSchedule.Id) == true);
  }
}