force-app/main/default/objects/Account/fields/Biling_Contact__c.field-meta.xml
<CustomField>
    <fullName>Biling_Contact__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Name of billing contact person.</description>
    <label>Billing Contact Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Email__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Billing Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/corpLicBillingFrequency__c.field-meta.xml
<CustomField>
    <fullName>corpLicBillingFrequency__c</fullName>
    <description>Corporate Billing Frequency</description>
    <label>Corporate License Billing Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/corpLicRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>corpLicRenewalDate__c</fullName>
    <description>Corporate License Expiration Date</description>
    <inlineHelpText>This field will be populated after the first bill run, for Corp Licenses billed annually.</inlineHelpText>
    <label>Corporate License Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/corpLicStartDate__c.field-meta.xml
<CustomField>
    <fullName>corpLicStartDate__c</fullName>
    <description>Corporate License Start Date</description>
    <label>Corporate License Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/corporateLicenseRate__c.field-meta.xml
<CustomField>
    <fullName>corporateLicenseRate__c</fullName>
    <description>Corporate License Rate</description>
    <label>Corporate License Price</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/corporateLicenseType__c.field-meta.xml
<CustomField>
    <fullName>corporateLicenseType__c</fullName>
    <description>Corporate License Type</description>
    <label>Corporate License Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Corporate License</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Types__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Types__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Invoice Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Summary</fullName>
                <default>true</default>
                <label>Account Summary</label>
            </value>
            <value>
                <fullName>Department Summary</fullName>
            </value>
            <value>
                <fullName>Access Code Summary</fullName>
            </value>
            <value>
                <fullName>Access Code Detail</fullName>
            </value>
            <value>
                <fullName>Conference Detail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rate_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rate_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Date these shown rates began to apply to this account</description>
    <inlineHelpText>This date shows when the rates for on-demand/per-minute audio and web rates, event and Custom Int&#39;l Audio Schedule rates begin to apply to this account.</inlineHelpText>
    <label>Rate Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reservationless_Web__c.field-meta.xml
<CustomField>
    <fullName>Reservationless_Web__c</fullName>
    <defaultValue>0.20</defaultValue>
    <description>Cost of reservationless web per minute for this account.</description>
    <inlineHelpText>Per-Minute (On-Demand) web conferencing price.</inlineHelpText>
    <label>Web Conferencing</label>
    <precision>13</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Toll_Free_Number__c.field-meta.xml
<CustomField>
    <fullName>Toll_Free_Number__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Toll Free Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3039993333</fullName>
            </value>
            <value>
                <fullName>8667401260</fullName>
                <default>true</default>
                <label>8667401260</label>
            </value>
            <value>
                <fullName>8009257671</fullName>
            </value>
            <value>
                <fullName>8772948214</fullName>
            </value>
            <value>
                <fullName>8008301513</fullName>
            </value>
            <value>
                <fullName>8006499919</fullName>
            </value>
            <value>
                <fullName>8663654411</fullName>
            </value>
            <value>
                <fullName>8006617007</fullName>
            </value>
            <value>
                <fullName>8006772898</fullName>
            </value>
            <value>
                <fullName>8009371839</fullName>
            </value>
            <value>
                <fullName>8553484177</fullName>
            </value>
            <value>
                <fullName>8775574194</fullName>
            </value>
            <value>
                <fullName>8554304241</fullName>
            </value>
            <value>
                <fullName>8553554218</fullName>
            </value>
            <value>
                <fullName>8555594243</fullName>
            </value>
            <value>
                <fullName>8772217520</fullName>
            </value>
            <value>
                <fullName>8007229903</fullName>
            </value>
            <value>
                <fullName>8553914244</fullName>
            </value>
            <value>
                <fullName>8006054285</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Toll_Number__c.field-meta.xml
<CustomField>
    <fullName>Toll_Number__c</fullName>
    <label>Toll Number</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Toll_Free_Number__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>3039993333</fullName>
            </value>
            <value>
                <fullName>3032480285</fullName>
                <default>true</default>
                <label>3032480285</label>
            </value>
            <value>
                <fullName>6477233976</fullName>
            </value>
            <value>
                <fullName>6477233989</fullName>
            </value>
            <value>
                <fullName>6477236906</fullName>
            </value>
            <value>
                <fullName>6477237255</fullName>
            </value>
            <value>
                <fullName>3032489658</fullName>
            </value>
            <value>
                <fullName>9139049824</fullName>
            </value>
            <value>
                <fullName>9139049837</fullName>
            </value>
            <value>
                <fullName>9139049321</fullName>
            </value>
            <value>
                <fullName>9139049338</fullName>
            </value>
            <value>
                <fullName>9139049392</fullName>
            </value>
            <value>
                <fullName>9139049364</fullName>
            </value>
            <value>
                <fullName>9139049397</fullName>
            </value>
            <value>
                <fullName>2122313834</fullName>
            </value>
            <value>
                <fullName>9139049834</fullName>
            </value>
            <value>
                <fullName>9139049398</fullName>
            </value>
            <value>
                <fullName>2122313858</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Web_Rate_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Web_Rate_Start_Date__c</fullName>
    <defaultValue>DATE(YEAR(TODAY()),MONTH(TODAY()),1)</defaultValue>
    <description>Web subscription rate start date. (limited/web meeting, unlimited/webinar)</description>
    <label>Web Rate Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Web_Sub_Bill_Period__c.field-meta.xml
<CustomField>
    <fullName>Web_Sub_Bill_Period__c</fullName>
    <description>This is the billing period for web subscriptions. If billed
      annual then Subscription prices are per year. If monthly, then the
      price is a monthly price.</description>
    <label>Web Subscription Bill Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
                <default>true</default>
                <label>Monthly</label>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Web_Sub_Default_Type__c.field-meta.xml
<CustomField>
    <fullName>Web_Sub_Default_Type__c</fullName>
    <description>What is the default web subscription type for this account.</description>
    <label>Web Subscription Default Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None (Per-Minute Rates Apply)</fullName>
                <default>true</default>
                <label>None (Per-Minute Rates Apply)</label>
            </value>
            <value>
                <fullName>Web Meeting Pro (25)</fullName>
            </value>
            <value>
                <fullName>Web Meeting Pro (150)</fullName>
            </value>
            <value>
                <fullName>Webinar (150)</fullName>
            </value>
            <value>
                <fullName>Webinar (500)</fullName>
            </value>
            <value>
                <fullName>Webinar (3000)</fullName>
            </value>
            <value>
                <fullName>Web Meeting</fullName>
            </value>
            <value>
                <fullName>Unlimited Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MockAccount.cls
public class MockAccount {
    
    public String Status = 'New';
    public String Name = 'Mock Account Object';
    public String AccountNumber = '12345';    
    public String CorporateLicenseType;
    public Date CorporateLicenseStartDate;
    public String CorporateLicenseBillingFrequency;
    public Decimal CorporateLicenseRate;
    public Date CorporateLicenseRenewalDate;
    public Id OwnerId = MockUser.getNewUser().Id;
    public String WebSubDefaultType = 'None (Per-Minute Rates Apply)';
    public Date WebRateStartDate = Date.newInstance(3010, 1, 1);
    public Date AudioRateStartDate = Date.newInstance(2010, 1, 1);
    public String WebSubBillPeriod = 'Monthly';
    public Decimal ReservationlessWeb = 0.150;
    public DateTime DateProvisioned = DateTime.newInstance(Date.newInstance(2010, 1, 1), Time.newInstance(0, 0, 0, 0));
    public String State = 'CO';
    public String StreetAddress1 = '123 Sesame Street';
    public String BillingCity = 'Denver';
    public String BillingZip = '80202';
    public String BillingContactName = 'Fred';
    public String BillingContactEmail = 'fred@readytalk.com';
    public String invoiceTypes = 'Account Summary';
        
    private void setupAccount(Account a) {
        a.Status__c = Status;
        a.Name = Name;
        a.AccountNumber = '12345';
        a.Web_Sub_Bill_Period__c = WebSubBillPeriod;
        a.corporateLicenseType__c = CorporateLicenseType;
        a.corpLicStartDate__c = CorporateLicenseStartDate;
        a.corpLicBillingFrequency__c = CorporateLicenseBillingFrequency;
        a.corporateLicenseRate__c = CorporateLicenseRate;
        //a.corpLicRenewalDate__c = CorporateLicenseRenewalDate;
        a.OwnerId = OwnerId;
        a.Web_Sub_Default_Type__c = WebSubDefaultType;
        a.Rate_Start_Date__c = AudioRateStartDate;
        a.Web_Rate_Start_Date__c = WebRateStartDate;
        a.Web_Sub_Bill_Period__c = WebSubBillPeriod;
        a.Date_Provisioned__c = DateProvisioned;
        a.Reservationless_Web__c = ReservationlessWeb;
        //a.Billing_State__c= State;
        //a.Billing_Street_Address_1__c = StreetAddress1;
        //a.Billing_City__c = BillingCity;
        //a.Billing_Zip__c = BillingZip;
        a.Biling_Contact__c = BillingContactName;
        a.Billing_Contact_Email__c = BillingContactEmail;
        a.Invoice_Types__c = invoiceTypes;
        a.Toll_Free_Number__c = '8009371839';
        a.Toll_Number__c = '8009371839';
        RecordType accntRecordtype = [SELECT Id,Name FROM RecordType WHERE sObjectType = 'Account' AND Name LIKE '%ReadyTalk%' LIMIT 1];
        a.RecordTypeId = accntRecordtype.Id;
    }
       
    public static Account getNewAccount() {
        Account a = new Account();
        MockAccount ma = new MockAccount();
        ma.setupAccount(a);
        Database.insert(a);
        return a;
    }
    
    public Account getAccount() {
        Account a = new Account();
        setupAccount(a);        
        Database.insert(a);        
        return a;
    }
}