force-app/main/default/objects/Account/fields/Billed_Revenue_Last_13_Months__c.field-meta.xml
<CustomField>
    <fullName>Billed_Revenue_Last_13_Months__c</fullName>
    <inlineHelpText>Total amount of billed revenue over the past 13 month&apos;s from all premier companies (PGi Companies object) associated to this Account.  Although the currency may show differently, this amount is always in USD.</inlineHelpText>
    <label>Billed Revenue - Last 13 Months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Parent_Billed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Billed_Revenue__c</fullName>
    <inlineHelpText>Total amount of billed revenue over the past 13 month&apos;s from all premier companies (PGi Companies object) associated to this Account only where this Account is set as the Ultimate Parent.</inlineHelpText>
    <label>Ultimate Parent Billed Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to set the relationship between Conman Contract and Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Contracts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>PGi_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Company__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Companies (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>PGi_Companies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountUltimateParentBilledRevBatchTest.cls
@isTest
private class AccountUltimateParentBilledRevBatchTest {
	static Account testUltimateParentAccount {get;set;}
	static Account testAccountChild {get;set;}
	static Account testAccountGrandChild {get;set;}
	static Account testAccountGreatGrandChild {get;set;}

	static PGi_Company__c testPGiCompany {get;set;}
	static CONMAN_Contract__c testPGiContract {get;set;}
	
	
	static testMethod void testScheduleBatch() {
		Test.startTest();
		AccountUltimateParentBilledRevenueBatch ultimateParentBatch = new AccountUltimateParentBilledRevenueBatch();
		String sch = '0 0 23 * * ?'; 
		System.schedule('Test Account Ultimate Parent Revenue Batch', sch, ultimateParentBatch);
		Test.stopTest();
	}

	static testMethod void testRunBatchNow() {
		Init();

		Test.startTest();
		Database.executeBatch(new AccountUltimateParentBilledRevenueBatch());
		Test.stopTest();

		System.assertEquals(50, [SELECT Id, Ultimate_Parent_Billed_Revenue__c FROM Account WHERE Id = :testUltimateParentAccount.Id].Ultimate_Parent_Billed_Revenue__c);
		System.assertEquals([SELECT Id, Ultimate_Parent_Account__c FROM Account WHERE Id = :testAccountChild.Id].Ultimate_Parent_Account__c, testUltimateParentAccount.Id);		
		System.assertEquals([SELECT Id, Ultimate_Parent_Account__c FROM Account WHERE Id = :testAccountGrandChild.Id].Ultimate_Parent_Account__c, testUltimateParentAccount.Id);
		System.assertEquals([SELECT Id, Ultimate_Parent_Account__c FROM Account WHERE Id = :testAccountGreatGrandChild.Id].Ultimate_Parent_Account__c, testUltimateParentAccount.Id);
	}

	static void Init() {
		testUltimateParentAccount = PGITestUtilities.createAccount(false);
		testUltimateParentAccount.Billed_Revenue_Last_13_Months__c = 5;
		insert testUltimateParentAccount;
		testAccountChild = PGITestUtilities.createAccount(false);
		testAccountChild.Billed_Revenue_Last_13_Months__c = 10;
		testAccountChild.ParentId = testUltimateParentAccount.Id;
		insert testAccountChild;
		testAccountGrandChild = PGITestUtilities.createAccount(false);
		testAccountGrandChild.Billed_Revenue_Last_13_Months__c = 15;
		testAccountGrandChild.ParentId = testAccountChild.Id;
		insert testAccountGrandChild;
		testAccountGreatGrandChild = PGITestUtilities.createAccount(false);
		testAccountGreatGrandChild.Billed_Revenue_Last_13_Months__c = 20;
		testAccountGreatGrandChild.ParentId = testAccountGrandChild.Id;
		insert testAccountGreatGrandChild;

		testPGiCompany = PGITestUtilities.createCompany(PGITestUtilities.createEntity(true), false);
		testPGiCompany.RelatedAccount__c = testAccountChild.Id;
		insert testPGiCompany;

		testPGiContract = PGITestUtilities.createConManContract(testAccountChild, PGITestUtilities.createOpportunity(testAccountChild, true), false);
		testPGiContract.Account_Name__c = testAccountChild.Id;
		insert testPGiContract;
	}
}