force-app/main/default/objects/Account/fields/Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Start_Date__c</fullName>
    <description>First Month we starting billing customer</description>
    <label>Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FilterField__c/FilterField__c.object-meta.xml
<CustomObject>
    <label>FilterField</label>
    <nameField>
        <displayFormat>FF-{000000}</displayFormat>
        <label>FilterField Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FilterFields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FilterField__c/fields/Field__c.field-meta.xml
<CustomField>
    <fullName>Field__c</fullName>
    <label>Field</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FilterField__c/fields/FilterObject__c.field-meta.xml
<CustomField>
    <fullName>FilterObject__c</fullName>
    <label>FilterObject</label>
    <referenceTo>FilterObject__c</referenceTo>
    <relationshipLabel>FilterFields</relationshipLabel>
    <relationshipName>FilterFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FilterField__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FilterObject__c/FilterObject__c.object-meta.xml
<CustomObject>
    <label>FilterObject</label>
    <nameField>
        <label>FilterObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FilterObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DataRetentionServiceTest.cls
@isTest 
public class DataRetentionServiceTest {
    
    public static testMethod void disassociateContactRelatedCasesTest(){
        
        List<Contact> contacts = new List<Contact>();
        for(Integer i=0 ;i <5;i++)
        {
            Contact contObj = new Contact();
            contObj.LastName ='TestContName'+i;
            contacts.add(contObj);
        }
        insert contacts;
        
         Test.startTest();
        List<Case> caseList = new List<Case>();
        for(Integer i=0 ;i <5;i++)
        {
            Case caseObj = new Case();
            caseObj.ContactId = contacts[i].id;
            caseList.add(caseObj);
        }
        insert caseList;

        DataRetentionService.disassociateContactRelatedCases(contacts);
        DataRetentionService.disassociateCaseContacts(caseList);
        System.assertEquals(Null, [SELECT Id, ContactId FROM Case LIMIT 1].ContactId);
        Test.stopTest();
    }
    
    public static testMethod void disassociateAccountRelatedCasesTest(){
        List<Account> accounts = new List<Account>();
        for(Integer i=0;i <5;i++)
        {
            Account accObj = new Account();
            accObj.Name ='TestAccName'+i;
            accounts.add(accObj);
        }
        insert accounts;
         
        Test.startTest();
        List<Case> caseList = new List<Case>();
        for(Integer i=0 ;i <5;i++)
        {
            Case caseObj = new Case();
            caseObj.AccountId = accounts[i].id;
            caseList.add(caseObj);
        }
        insert caseList;
         DataRetentionService.disassociateAccountRelatedCases(accounts);
        DataRetentionService.disassociateCaseAccounts(caseList);
        System.assertEquals(Null, [SELECT Id, AccountId FROM Case LIMIT 1].AccountId);
        Test.stopTest();
    }
    
    public static testMethod void buildRetentionQueryTest(){
         Test.startTest();
        List<FilterObject__c> lstFtObj= new List<FilterObject__c>();
        for(Integer i=0 ;i <5;i++)
        {
            FilterObject__c foobj = new FilterObject__c();
            foobj.Name ='TestFOName'+i;
            foobj.Status__c='Active';
            foobj.Object__c = 'Account';
            lstFtObj.add(foobj);
        }
        insert lstFtObj;
        
        
        List<FilterField__c> lstFFObj = new List<FilterField__c>();
        lstFFObj.add(new FilterField__c(FilterObject__c = lstFtObj[0].id,Value__c= 'test',Field__c = 'Name',Operator__c = 'Includes' ));
        lstFFObj.add(new FilterField__c(FilterObject__c = lstFtObj[1].id,Value__c= '11/25/2019',Field__c = 'Billing_Start_Date__c',Operator__c = 'Greater Than Or Equal' ));
        lstFFObj.add(new FilterField__c(FilterObject__c = lstFtObj[2].id,Value__c= '100',Field__c = 'AnnualRevenue',Operator__c = 'Greater Than' ));
         insert lstFFObj;
		
        String filterObjectName = 'Account';
        for(Integer i=0 ;i <2;i++)
        {
        DataRetentionService.buildRetentionQuery(lstFtObj[i].Id);
        DataRetentionService.validQuery(filterObjectName,lstFFObj);
        DataRetentionService.validateFields(lstFFObj);
            
        }
    
        System.assertEquals(true, DataRetentionService.validObjectName(filterObjectName));
        Test.stopTest();
    }
       
}