force-app/main/default/objects/Account/fields/Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Start_Date__c</fullName>
    <description>First Month we starting billing customer</description>
    <label>Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commission_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Commission_Start_Date__c</fullName>
    <label>Commission Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/NetSuite_Financial__c.object-meta.xml
<CustomObject>
    <description>Posting transactions from NetSuite including Cash Sales, Invoices, Customer Payments, Credit Memos, Cash Refunds, Journal Entries, etc.</description>
    <label>Financial</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NetSuite_Financial__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Displays account name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Revenue_Total__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Total__c</fullName>
    <inlineHelpText>Total commissionable revenue (Invoice Total minus FUSF) for the invoice period.</inlineHelpText>
    <label>Revenue Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Date of transaction in NetSuite.</description>
    <inlineHelpText>Accounting posting date.</inlineHelpText>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testFinancialActions.cls
@isTest
public class testFinancialActions {
    
  static testMethod void testFinancialTriggerWithInsert() {
    // dummy test to fire trigger action.
    NetSuite_Financial__c financial = new NetSuite_Financial__c();
    financial.Transaction_Date__c = Date.today();
    financial.Name = '1234';
    financial.Account__c = MockAccount.getNewAccount().Id;
    insert financial;
    
    System.assert(true);
  }
    
  static testMethod void testInsertStartDatesWithRevenue () {
	Account acct = MockAccount.getNewAccount();
    System.assert(acct.Billing_Start_Date__c == null);
    System.assert(acct.Commission_Start_Date__c == null);
    NetSuite_Financial__c financial = new NetSuite_Financial__c();
    financial.Transaction_Date__c = Date.today();
    financial.Name = '1234';
    financial.Account__c = acct.Id;
    financial.Revenue_Total__c = 20.40;
    insert financial;
    acct = [select Id, Billing_Start_Date__c, Commission_Start_Date__c from Account where Id = :acct.Id];
    System.assert(acct.Billing_Start_Date__c == Date.today());
    System.assert(acct.Commission_Start_Date__c == Date.today());
  }

  static testMethod void testInsertStartDatesWithoutRevenue () {
	Account acct = MockAccount.getNewAccount();
    System.assert(acct.Billing_Start_Date__c == null);
    System.assert(acct.Commission_Start_Date__c == null);
    NetSuite_Financial__c financial = new NetSuite_Financial__c();
    financial.Transaction_Date__c = Date.today();
    financial.Name = '1234';
    financial.Account__c = acct.Id;
    insert financial;
    acct = [select Id, Billing_Start_Date__c, Commission_Start_Date__c from Account where Id = :acct.Id];
    System.assert(acct.Billing_Start_Date__c == Date.today());
    System.assert(acct.Commission_Start_Date__c == null);
  }

  static testMethod void testInsertStartDatesWhenDatesAlreadyExist () {
	Account acct = MockAccount.getNewAccount();
    acct.Billing_Start_Date__c = Date.today() -3;
    acct.Commission_Start_Date__c = Date.today() - 2;
	update acct;      
    NetSuite_Financial__c financial = new NetSuite_Financial__c();
    financial.Transaction_Date__c = Date.today();
    financial.Name = '1234';
    financial.Revenue_Total__c = 20.40;
    financial.Account__c = acct.Id;
    insert financial;
    acct = [select Id, Billing_Start_Date__c, Commission_Start_Date__c from Account where Id = :acct.Id];
    System.assert(acct.Billing_Start_Date__c == Date.today() - 3);
    System.assert(acct.Commission_Start_Date__c == Date.today() - 2);
  }

}