force-app/main/default/objects/Account/fields/Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Start_Date__c</fullName>
    <description>First Month we starting billing customer</description>
    <label>Billing Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Commission_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Commission_Start_Date__c</fullName>
    <label>Commission Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/NetSuite_Financial__c.object-meta.xml
<CustomObject>
    <description>Posting transactions from NetSuite including Cash Sales, Invoices, Customer Payments, Credit Memos, Cash Refunds, Journal Entries, etc.</description>
    <label>Financial</label>
    <nameField>
        <label>Transaction Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financials</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NetSuite_Financial__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <inlineHelpText>Displays account name.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Financials</relationshipLabel>
    <relationshipName>Financials</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Revenue_Total__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Total__c</fullName>
    <inlineHelpText>Total commissionable revenue (Invoice Total minus FUSF) for the invoice period.</inlineHelpText>
    <label>Revenue Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NetSuite_Financial__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <description>Date of transaction in NetSuite.</description>
    <inlineHelpText>Accounting posting date.</inlineHelpText>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FinancialActions.cls
public class FinancialActions { 
  /**
  * SFB-1520 Billing Start Date and Commission Start Date on Account
  */
  public static void insertStartDates(List<NetSuite_Financial__c> financialsIn) {
    Set<Id> financialIds = new Set<Id>();

    for(NetSuite_Financial__c financial : financialsIn){
      financialIds.add(financial.Id);
    }

    List<NetSuite_Financial__c> financials = (List<NetSuite_Financial__c>)[select Id, Revenue_Total__c, Account__r.Billing_Start_Date__c,
        Account__r.Commission_Start_Date__c, Transaction_Date__c from NetSuite_Financial__c where Id in :financialIds];

    //Modify the values
    for(NetSuite_Financial__c financial : financials){
      System.debug('financial.Id = ' + financial.Id);
      if (financial.Account__r.Billing_Start_Date__c == null) {
        Account account = new Account();
        account.Id = financial.Account__c;
        account.Billing_Start_Date__c = financial.Transaction_Date__c;
        update(account);
      }
      if (financial.Account__r.Commission_Start_Date__c == null && financial.Revenue_Total__c != null && financial.Revenue_Total__c > 0) {
        Account account = new Account();
        account.Id = financial.Account__c;
        account.Commission_Start_Date__c = financial.Transaction_Date__c;
        update(account);
      } 
    }
  }
}