force-app/main/default/objects/Account/fields/Billed_Revenue_Last_13_Months__c.field-meta.xml
<CustomField>
    <fullName>Billed_Revenue_Last_13_Months__c</fullName>
    <inlineHelpText>Total amount of billed revenue over the past 13 month&apos;s from all premier companies (PGi Companies object) associated to this Account.  Although the currency may show differently, this amount is always in USD.</inlineHelpText>
    <label>Billed Revenue - Last 13 Months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Company__c/fields/Last_13_Months_Billed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Last_13_Months_Billed_Revenue__c</fullName>
    <label>Last 13 Month&apos;s Billed Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountSummaryBatch.cls
/*******************************************************************************************
Name : AccountSummaryBatch
Created On : March 2018
Created By : Timothy Barsotti
Description : Batch Apex to summarize the revenue associated to an account
********************************************************************************************/
public without sharing class AccountSummaryBatch implements Database.Batchable<sObject>, Schedulable {
	public void execute(SchedulableContext sc) {
		Database.ExecuteBatch(new AccountSummaryBatch(), 100);
	}
    public Database.QueryLocator start(Database.BatchableContext bc){
    	String query = 'SELECT Id, Billed_Revenue_Last_13_Months__c FROM Account';
    	return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<Account> scope){
        List<Account> acctList = [SELECT Id, Billed_Revenue_Last_13_Months__c, (SELECT Id, Last_13_Months_Billed_Revenue__c FROM PGi_Companies__r) FROM Account WHERE Id IN: scope];
    	List<Account> toUpdate = new List<Account>();
    	for(Account acct: acctList) {
    		Decimal revenue = 0;
    		for(PGI_Company__c comp: acct.PGi_Companies__r) {
    			if(comp.Last_13_Months_Billed_Revenue__c != null){
    				revenue += comp.Last_13_Months_Billed_Revenue__c;
    			}
    		}
    		if(acct.Billed_Revenue_Last_13_Months__c != revenue) {
    			acct.Billed_Revenue_Last_13_Months__c = revenue;
    			toUpdate.add(acct);
    		}
    	}
    	Database.update(toUpdate, false);
    }
    public void finish(Database.BatchableContext bc){

    }
}