force-app/main/default/objects/Account/fields/Billed_Revenue_Last_13_Months__c.field-meta.xml
<CustomField>
    <fullName>Billed_Revenue_Last_13_Months__c</fullName>
    <inlineHelpText>Total amount of billed revenue over the past 13 month&apos;s from all premier companies (PGi Companies object) associated to this Account.  Although the currency may show differently, this amount is always in USD.</inlineHelpText>
    <label>Billed Revenue - Last 13 Months</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Count_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Leads__c</fullName>
    <label>Count of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Duns_Number__c.field-meta.xml
<CustomField>
    <fullName>Duns_Number__c</fullName>
    <description>Used in PopulateParentAccount Trigger</description>
    <externalId>true</externalId>
    <label>ADMIN Duns Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/DuplicateDetectedforParentLookup__c.field-meta.xml
<CustomField>
    <fullName>DuplicateDetectedforParentLookup__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duplicate Detected for Parent Lookup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account_MQA__c.field-meta.xml
<CustomField>
    <fullName>Global_Account_MQA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global Account MQA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Global_Account_MQA_Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Global_Account_MQA_Assignment_date__c</fullName>
    <label>Global Account MQA Assignment date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/of_Tickets_Last_5_Days__c.field-meta.xml
<CustomField>
    <fullName>of_Tickets_Last_5_Days__c</fullName>
    <label># of Tickets Last 5 Days</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Potiential_Duplicate_via_DUNS__c.field-meta.xml
<CustomField>
    <fullName>Potiential_Duplicate_via_DUNS__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auto checked by the Account Trigger to auto match a Parent Account.  If multiple matches are found for the Parent account then they will be marked as TRUE for potential duplicate.</description>
    <label>Potiential Duplicate via DUNS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>For both manual and automatic selection of an Account record related to this lead.</inlineHelpText>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Zendesk__organization__c.field-meta.xml
<CustomField>
    <fullName>Zendesk__organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel from Opportunity Owner&#39;s user record</description>
    <label>Owner&#39;s Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Converted_from_MQA__c.field-meta.xml
<CustomField>
    <fullName>Converted_from_MQA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converted from MQA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Company__c/fields/Last_13_Months_Billed_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Last_13_Months_Billed_Revenue__c</fullName>
    <label>Last 13 Month&apos;s Billed Revenue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zendesk__Zendesk_Ticket__c/Zendesk__Zendesk_Ticket__c.object-meta.xml
<CustomObject>
    <description>Custom object to store Zendesk Support tickets (mostly closed ones) on salesforce</description>
    <label>Zendesk Support Ticket</label>
    <nameField>
        <label>Zendesk Support Ticket</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zendesk Support Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zendesk__Zendesk_Ticket__c/fields/Zendesk__Organization__c.field-meta.xml
<CustomField>
    <fullName>Zendesk__Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Zendesk_Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Zendesk__Zendesk_Ticket__c/fields/Zendesk__Ticket_Form_Id__c.field-meta.xml
<CustomField>
    <fullName>Zendesk__Ticket_Form_Id__c</fullName>
    <label>Ticket Form Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@isTest
public class AccountTriggerHandlerTest {
	private static Account queriedAccount;
	@isTest
	public static void testParent() {
		
	}

	@isTest
	public static void testMapZoomCountries() {

	}
//moved to batch job
	//static testMethod void testPGi_Account_Billed_Revenue_Last_13_Mont() {

	//	//
 //       // SELECT Last_13_Months_Billed_Revenue__c , RelatedAccount__c FROM PGi_Company__c WHERE isDeleted = false ORDER BY Id DESC NULLS LAST
 //       //
 //       //
 //       // PGi_Company__c > Last_13_Months_Billed_Revenue__c 
 //       //
 //       //
 //       // CURRENCY to rollup into Account.Billed_Revenue_Last_13_Months__c
 //       //

 //       Account testAcct = new Account(); 
 //       testAcct.Name = 'test';
 //       insert testAcct;

 //       List<PGi_Company__c> testRecords = new List<PGi_Company__c>();
 //       for(Integer i = 0, j = 0; i < 3; i++) {
        
 //           testRecords.add(new PGi_Company__c(RelatedAccount__c = testAcct.Id, Last_13_Months_Billed_Revenue__c = 10));
 //       }   
 //       insert testRecords;

 //       Test.startTest();

 //       System.assertEquals([SELECT Billed_Revenue_Last_13_Months__c FROM Account WHERE Id = :testAcct.Id].Billed_Revenue_Last_13_Months__c, 30);

 //       Test.stopTest();
	//}

	static testMethod void testNumberofZenDeskTicketsSubmitted_Last_5_Days() {
		//
        // SELECT Zendesk__Ticket_Form_Id__c , Zendesk__Organization__c FROM Zendesk__Zendesk_Ticket__c WHERE isDeleted = false
        //
        //
        // Account.of_Tickets_Last_5_Days__c
        //
        //
        // Zendesk__Zendesk_Ticket__c > Zendesk__Ticket_Form_Id__c 
        //

        Account testAcct = new Account(); 
        testAcct.Name = 'test';
        insert testAcct;

        List<Zendesk__Zendesk_Ticket__c> testRecords = new List<Zendesk__Zendesk_Ticket__c>();
        for(Integer i = 0, j = 0; i < 3; i++) {
        
            testRecords.add(new Zendesk__Zendesk_Ticket__c(Zendesk__Organization__c = testAcct.Id, Zendesk__Ticket_Form_Id__c = i));
        }   
        insert testRecords;

        Test.startTest();

        System.assertEquals([SELECT of_Tickets_Last_5_Days__c FROM Account WHERE Id = :testAcct.Id].of_Tickets_Last_5_Days__c, 3);

        Test.stopTest();
	}

	// static testMethod void testAccount_Count_of_Leads() {
    //     //
    //     // SELECT IsDeleted, Account__c FROM Lead WHERE isDeleted = false
    //     //
    //     //
    //     // Account.Count_of_Leads__c
    //     //

    //     Account testAcct = new Account(); 
    //     testAcct.Name = 'test';
    //     insert testAcct;

    //     List<Lead> testRecords = new List<Lead>();
    //     for(Integer i = 0, j = 0; i < 3; i++) {
        
    //         testRecords.add(new Lead(Account__c = testAcct.Id, LastName = 'test', Company = 'test', Email = 'test@test.com'));
    //     }   
    //     insert testRecords;

    //     Test.startTest();

    //     System.assertEquals([SELECT Count_of_Leads__c FROM Account WHERE Id = :testAcct.Id].Count_of_Leads__c, 3);

    //     Test.stopTest();
    // }
	
	@isTest
	public static void testSameAsUltimate() {
		DandBCompany ultimateDb = PGITestUtilities.createDandBCompany('123', '123', true);
		Account a = PGITestUtilities.createAccount(false);
		a.DandBCompanyId = ultimateDb.Id;
		a.DUNSNumber = '123';
		a.DUNS_Number__c = '123';
		//a.Channel__c = 'Marketing';
		a.RecordTypeId = AccountTriggerHandler.PGIRecordTypeId;
		insert a;
		queriedAccount = [SELECT Id, ParentId FROM Account];
		System.assert(queriedAccount.ParentId == null);
		AccountTriggerHandler.parentsChecked = new Set<Id>();
		update a;
		queriedAccount = [SELECT Id, ParentId FROM Account];
		System.assert(queriedAccount.ParentId == null);

	}
	@isTest
	public static void testDuplicateParent() {
		DandBCompany ultimateDb = PGITestUtilities.createDandBCompany('123', '123', true);
		DandBCompany childDb = PGITestUtilities.createDandBCompany('321', '123', true);
		Account parentAcct = PGITestUtilities.createAccount(false);
		parentAcct.DandBCompanyId = ultimateDb.Id;
		parentAcct.DUNS_Number__c = '123';
		parentAcct.DUNSNumber = '123';
		//parentAcct.Channel__c = 'Marketing';
		parentAcct.RecordTypeId = AccountTriggerHandler.PGIRecordTypeId;
		insert parentAcct;

		Account dupeParentAcct = PGITestUtilities.createAccount(false);
		dupeParentAcct.DandBCompanyId = ultimateDb.Id;
		dupeParentAcct.DUNS_Number__c = '123';
		dupeParentAcct.DUNSNumber = '123';
		//dupeParentAcct.Channel__c = 'Marketing';
		dupeParentAcct.RecordTypeId = AccountTriggerHandler.PGIRecordTypeId;
		insert dupeParentAcct;
		queriedAccount = [SELECT Id, Potiential_Duplicate_via_DUNS__c, DuplicateDetectedforParentLookup__c FROM Account WHERE Id =: dupeParentAcct.Id];
		System.assert(queriedAccount.Potiential_Duplicate_via_DUNS__c == true, 'failed to set potential duplicate');
		System.assert(queriedAccount.DuplicateDetectedforParentLookup__c == true, 'failed to set potential duplicate parent');
		Account childAcct = PGITestUtilities.createAccount(false);
		childAcct.DandBCompanyId = childDb.Id;
		childAcct.DUNSNumber = '321';
		childAcct.DUNS_Number__c = '321';
		//childAcct.Channel__c = 'Marketing';
		childAcct.RecordTypeId = AccountTriggerHandler.PGIRecordTypeId;
		insert childAcct;
		queriedAccount = [SELECT Id, ParentId, Potiential_Duplicate_via_DUNS__c, DuplicateDetectedforParentLookup__c FROM Account WHERE Id =: childAcct.Id];
		System.assert(queriedAccount.Potiential_Duplicate_via_DUNS__c == false, 'set as potential duplicate');
		System.assert(queriedAccount.DuplicateDetectedforParentLookup__c == true, 'failed to set potential duplicate parent');

		System.assert(queriedAccount.ParentId == null, 'set parent!!');

		delete dupeParentAcct;

		AccountTriggerHandler.parentsChecked = new Set<Id>();
		update childAcct;
		queriedAccount = [SELECT Id, ParentId, Potiential_Duplicate_via_DUNS__c, DuplicateDetectedforParentLookup__c FROM Account WHERE Id =: childAcct.Id];
		System.assert(queriedAccount.ParentId == parentAcct.Id, 'failed to set parent!!');
		System.assert(queriedAccount.Potiential_Duplicate_via_DUNS__c == false, 'set as potential duplicate');
		System.assert(queriedAccount.DuplicateDetectedforParentLookup__c == false, 'set potential duplicate parent');
	}
    
  /*  @isTest
    public static void testSetConvertedMQAFieldOnOpportunity(){
          PGITestUtilities.disableSalesWings();
          Account a1 = PGITestUtilities.createAccount(false);
          a1.Global_Account_MQA__c=true;
          a1.Global_Account_MQA_Assignment_date__c=Date.today().addDays(-2);
          Account a2 = PGITestUtilities.createAccount(false);
          a2.Global_Account_MQA__c=true;
          a2.Global_Account_MQA_Assignment_date__c=Date.today().addDays(4);        
          insert new List<Account>{a1, a2};
              
         Opportunity o1a1=PGITestUtilities.createOpportunity(a1, false); 
         o1a1.CreatedDate=Date.today();
         Opportunity o2a2=PGITestUtilities.createOpportunity(a2, false); 
         o2a2.CreatedDate=Date.today();
         insert new List<Opportunity>{o1a1,o2a2};
             
         Opportunity o=[SELECT Id,Converted_from_MQA__c FROM Opportunity WHERE Id=:o1a1.Id];    
         System.assertEquals(false,o.Converted_from_MQA__c);    
    } */
}