force-app/main/default/objects/Account/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
The date and time this account was made inactive.</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <description>Person&#39;s ID who marks this account as inactive.</description>
    <label>Deleted By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Provisioned__c.field-meta.xml
<CustomField>
    <fullName>Provisioned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to provision the account.</description>
    <label>Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Date/time the contact is marked as deleted (therefore, inactive in SF &amp; deleted with GX).</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Corporate Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting/Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Customer Service/Care/Support</fullName>
            </value>
            <value>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </value>
            <value>
                <fullName>HR Generalist</fullName>
            </value>
            <value>
                <fullName>HR Recruiting</fullName>
            </value>
            <value>
                <fullName>Investor Relations</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Department_Parent__c.field-meta.xml
<CustomField>
    <fullName>Department_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
This is the department that this contact is directly related with.</description>
    <label>Billing Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Contact</relationshipLabel>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <description>Name of person who deleted the account (not really deleted, just inactivated)</description>
    <label>Deleted By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Provisioned__c.field-meta.xml
<CustomField>
    <fullName>Provisioned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>This object handles departments (children of accounts) so accounts will not have children accounts.</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <label>Deleted By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <label>Pending</label>
</RecordType>

force-app/main/default/classes/ContactRepositoryTest.cls
@isTest
public class ContactRepositoryTest {
    @testSetup static void setup() {
        Account ac = new Account();
        ac.Name='Ac1';
        insert ac;
        Department__c departMentObj = new Department__c();
        departMentObj.Name = 'Testdept';
        departMentObj.Parent_Account__c = ac.id;
        departMentObj.Inactive__c = false;
        departMentObj.Status__c = 'error';
        Insert departMentObj;
        Contact con=new Contact();
        con.Department_Parent__c = departMentObj.Id;
        con.Inactive__c = false;
        con.Inactivated_By__c = 'TestUser';
        con.Provisioned__c = true;
        con.Status__c = 'Pending';
        con.Date_Deleted__c = Date.today();
        con.AccountId=ac.Id;
        con.LastName= 'test';
        con.FirstName='test';
        con.Phone= '9887678558';
        con.Email= 'hsk@test.com';
        insert con;
    }
    static  testmethod void testContactRepositoryById(){
        Account accObj =[Select Id,Name from Account Where Name='Ac1'];
        List<Id> deptListId = new List<Id>();
        Department__c deptObj = [Select Id from Department__c Where Status__c = 'error'];
        deptListId.add(deptObj.Id);
        Contact contactObj = [Select id,name,Account.Id,Department_Parent__c,Inactive__c, Inactivated_By__c, Provisioned__c, Status__c, Date_Deleted__c from Contact];
        ContactRepository obj = new ContactRepository();
        obj.getContactsByAccountId(accObj.Id);
        List<contact> contactMatchAccLst = obj.getContactsByAccountId(accObj.Id);
        System.assertEquals(contactObj.Name, contactMatchAccLst[0].Name);
        List<contact> contactMatchDeptLst = obj.getContactsWhereDepartmentInList(deptListId);
        System.assertEquals(contactObj.Account.Id, contactMatchDeptLst[0].Account.Id);
    }
    static  testmethod void testContactCascadeDelete(){
        Account accObj =[Select Id,Name from Account Where Name='Ac1'];
        Contact contactObj = [Select id,name,Account.Id,Department_Parent__c,Inactive__c, Inactivated_By__c, Provisioned__c, Status__c, Date_Deleted__c from Contact];
        contactObj.Inactive__c = true;
        contactObj.Status__c = 'Deleting';
        Update contactObj;
        List<contact> conList = new List<Contact>();
        conList.add(contactObj);
        ContactRepository obj = new ContactRepository();
        obj.cascadeDelete(contactObj);  
        contact conReturnObj = [Select id,name,Account.Id,Department_Parent__c,Inactive__c, Inactivated_By__c, Provisioned__c, Status__c, Date_Deleted__c from Contact];
        System.assertEquals(true, conReturnObj.Inactive__c);
        System.assertEquals(accObj.Id, conReturnObj.Account.Id); 
    }
    static  testmethod void testContactDel(){
        Contact contactObj = [Select id,name,Account.Id,Department_Parent__c,Inactive__c, Inactivated_By__c, Provisioned__c, Status__c, Date_Deleted__c from Contact];
        contactObj.Inactive__c = false;
        contactObj.Status__c = 'Deleting';
        contactObj.Inactivated_By__c=null;
        contactObj.Date_Deleted__c=null;
        Update contactObj;
        List<contact> conList = new List<Contact>();
        conList.add(contactObj);
        ContactRepository obj = new ContactRepository();
        Obj.del(conList);
        Contact contactReturnObj = [Select Inactive__c,Status__c,Inactivated_By__c,Date_Deleted__c from contact];
        System.assertEquals(true, contactReturnObj.Inactive__c);
        System.assertEquals('Delete', contactReturnObj.Status__c);
    }
}