force-app/main/default/objects/Account/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
The date and time this account was made inactive.</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <description>Person&#39;s ID who marks this account as inactive.</description>
    <label>Deleted By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Provisioned__c.field-meta.xml
<CustomField>
    <fullName>Provisioned__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this to provision the account.</description>
    <label>Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Date/time the contact is marked as deleted (therefore, inactive in SF &amp; deleted with GX).</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department_Parent__c.field-meta.xml
<CustomField>
    <fullName>Department_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
This is the department that this contact is directly related with.</description>
    <label>Billing Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Contact</relationshipLabel>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <description>Name of person who deleted the account (not really deleted, just inactivated)</description>
    <label>Deleted By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Provisioned__c.field-meta.xml
<CustomField>
    <fullName>Provisioned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactRepository.cls
public with sharing class ContactRepository extends AbstractRepository {

  public final static String table = 'Contact';
  public final static String columns = 'id,name,Account.Id,Department_Parent__c,Inactive__c, Inactivated_By__c, Provisioned__c, Status__c, Date_Deleted__c';

  /**
   * Validations
   */    
  public class builderValidator extends AbstractValidator {     
  } 

  /**
   * Queries
   */
  public List<Contact> getContactsByAccountId(Id accountId){
    return (List<Contact>) Database.query(selectBuilder(table,columns, 'where Account.Id = :accountId and Provisioned__c = true and (Inactive__c = false or Status__c = \'Error\')'));
  }
  
  public List<Contact> getContactsWhereDepartmentInList(List<Id> departmentIds){
    return (List<Contact>) Database.query(selectBuilder(table,columns, 'where Provisioned__c = true and Department_Parent__c in :departmentIds and (Inactive__c = false or Status__c = \'Error\')'));
  }  

  /**
   * Helpers for deletes
   * Executed when someone initiates a delete action for a single contact (i.e. delete button on contact page)
   */
  public void cascadeDelete(Contact contact){
    List<Contact> contacts = new List<Contact>();
    contacts.add(contact);

    try{
      cascadeDelete(contacts);
    }
    catch(Exception e){
      throw new ConstructableException('Sorry, unable to complete deletion of this contact because '+e.getMessage());      
    }

  } 

  //Executed when a list of contacts needs to be deleted (i.e. delete all contacts under an Account/Department)
  public void cascadeDelete(List<Contact> contacts){
    for(Contact contact : contacts){
      //A little trickery - we will make this contact look active again (Inactive__c true).
      //The delete will occur in the final method of a batch job (after all of it's subscriptions are deleted)

      //If this contact is marked as Inactive__c and Status__c is Deleting it will attempt to fire an outbound message, we don't want that here.
      if(contact.Inactive__c == true && contact.Status__c=='Deleting')
        contact.Inactive__c = false;
    }

    //Get all of the subscriptions hanging off of these contacts and delete them (via batch)
    //The Finish method of the Batch Executor will delete all of the Contacts    
    BatchSObjectDelete batchDelete = new BatchSObjectDelete();
    batchDelete.sObjectName = 'Contact';
    batchDelete.action = 'DeleteContacts';
    batchDelete.subscriptionsDeleted = false; 
    batchDelete.subscriptions = BatchSObjectDelete.getSubscriptionsFromContactList(contacts);    
    batchDelete.contacts = contacts;    
    Database.executeBatch(batchDelete);
  }

  //Executed from Finish methods on Batch Deletes
  public void del(List<Contact> contacts){
    for(Contact contact : contacts){
      //Mark Contact as deleted (Inactive__c) now
      if(contact.Inactive__c == false)
        contact.Inactive__c = true;

      //Mark contact inactivated by user
      if(contact.Inactivated_By__c == null)
        contact.Inactivated_By__c = Userinfo.getUserName();

      //Mark contact deleted date
      if(contact.Date_Deleted__c == null) 
        contact.Date_Deleted__c = Datetime.now();

      //Mark the Status__c as Delete so that we don't end up in an infinite loop
      contact.Status__c = 'Delete';
    }

    try{
      update(contacts);
    }
    catch(Exception e){
      throw new ConstructableException('Sorry, unable to complete deletion of this contact because '+e.getMessage());      
    }    
  }
}