force-app/main/default/objects/Account/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
The date and time this account was made inactive.</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/defaultPlan__c.field-meta.xml
<CustomField>
    <fullName>defaultPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the default Plan for this Account</description>
    <label>Default Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Date/time the contact is marked as deleted (therefore, inactive in SF &amp; deleted with GX).</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/isDefault__c.field-meta.xml
<CustomField>
    <fullName>isDefault__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is the default plan used (for plan&apos;s on this Account).</description>
    <label>isDefault</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/S3User__c/S3User__c.object-meta.xml
<CustomObject>
    <label>Replay User</label>
    <nameField>
        <label>Replay User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replay Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S3User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Replay Username (Email)</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/S3UserController.cls
global with sharing class S3UserController extends BaseController {

  Contact c;
  S3User__c user {get; set;}
  public String planId {get; set;}
  public Boolean isDelete;
  public String planStartDate {
    set;
    get {
      if(planStartDate == null)
        planStartDate = Date.today().format();
      return planStartDate;
    }
  }  

  public S3UserController(ApexPages.StandardController controller) {    
    S3User__c user = (S3User__c)controller.getRecord();    
    
    if(user!=null){    
      this.user = user;
    }    

    if(ApexPages.currentPage().getParameters().get('delID') != null){
      this.isDelete = true;
    }
    else{
      try{
        this.c = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), getRetURL(), ',Account.Status__c,Account.defaultPlan__c,Account.Id');
        if(this.user != null && this.user.email__c == null){
          this.user.email__c = c.email;
        }
      }
      catch(Exception e){
        throw new ValidationException('You cannot create a S3 User object without a reference to a Contact.  Use the New S3 User button from a Contact record.');
      }      
    }
  }

  public S3UserController(){    
  }

  public PageReference save() {
    SavePoint sp = Database.setSavePoint();
    Id userId = null;

    try {
      Database.UpsertResult result = Database.upsert(this.user);
      if(!result.isSuccess())
        throw new ValidationException('Unable to save, please try again.');

      userId = result.getId();

      //Save the Plan Assignment record
      //Name field: (avoid a lookup by adding name to the id field; same with endDate Looks like: id:name:endDate)
      //Validate the planStartDate first
      if (this.planStartDate == null || this.planStartDate == '')
        throw new ValidationException('Plan start date cannot be empty');

      //Validate planId
      if (this.planId == null)
        throw new ValidationException('Unable to provision.  An assigned plan is required to provision a S3 User.');

      PlanAssignment planAssignmentRepository = new PlanAssignment();
      planAssignmentRepository.savePlanAssignment(this.planId.split(':')[1], this.planId.split(':')[0], 'S3User__c', userId, this.planStartDate, this.planId.split(':')[2]);  
    } 
    catch (Exception ex) {
      ApexPages.addMessages(ex);
      Database.rollback(sp);
      return null;
    }

    return gotoView(userId);
  }

  @RemoteAction
  public static void customDelete(String userId){
    S3User s3UserRepository = new S3User();    
    S3User__c user = s3UserRepository.findById(userId);

    user.Inactive__c = true;

    //If it was already marked w/ a delete date, don't change it
    if(user.Date_Deleted__c == null) 
      user.Date_Deleted__c = Datetime.now();

    //If it was already deleted, don't put it back into a deleting status.
    if(user.Status__c != 'Delete') 
      user.Status__c = 'Deleting';
  
    try{
      update(user);    
    }
    catch(Exception e){
      throw new ValidationException('Sorry, unable to complete deletion of this S3 user because '+e.getMessage());      
    }
  }

  /**
   * Get the Account Level Plans (where today is in the plans start/end range) as SelectOption objects
   */
  public List<SelectOption> getAccountLevelPlans() {
    List<SelectOption> options = new List<SelectOption>();
    Plan planRepository = new Plan();
    List<Plan__c> accountPlans = planRepository.getPlansByAccountIdAndBillableTypeWhereAccessCodeInRange(this.c.Account.Id, 'S3_USER', Date.today());

    for (Plan__c plan : accountPlans) {
      if (plan.isDefault__c != null && plan.isDefault__c && options.size() > 0)
        options.add(0, new SelectOption(plan.Id + ':' + plan.Name + ':' + RTUtils.formatDateSafe(plan.endDate__c, null), plan.Name + ': ' + RTUtils.formatDateSafe(plan.startDate__c, 'No start') + ' - ' + RTUtils.formatDateSafe(plan.endDate__c, '∞')));
      else
        options.add(new SelectOption(plan.Id + ':' + plan.Name + ':' + RTUtils.formatDateSafe(plan.endDate__c, null), plan.Name + ': ' + RTUtils.formatDateSafe(plan.startDate__c, 'No start') + ' - ' + RTUtils.formatDateSafe(plan.endDate__c, '∞')));
    }

    return options;
  }  

  public S3User__c getUser(){
    return this.user;
  }

  public String getUserId(){
    return this.user.Id;
  }

  public String getContactId(){
    if(this.c != null)
      return this.c.Id;
    else
      return null;
  }

  public Boolean getIsDelete(){
    return this.isDelete;
  }
}