force-app/main/default/objects/Account/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
The date and time this account was made inactive.</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Date/time the contact is marked as deleted (therefore, inactive in SF &amp; deleted with GX).</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department_Parent__c.field-meta.xml
<CustomField>
    <fullName>Department_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
This is the department that this contact is directly related with.</description>
    <label>Billing Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Contact</relationshipLabel>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testContactController.cls
@isTest
private class testContactController {
    @testSetup static void setup() {
        PGITestUtilities.disableSalesWings();
    }
    static {
        ApexPages.currentPage().getParameters().put('id', MockAccount.getNewAccount().id);
    }
    
    static testMethod void testConstruct() {
        ContactController c = new ContactController();
        System.assert(c!=null);
        
        ApexPages.currentPage().getParameters().put('id', MockDepartment.getNewDepartment().id);
        c = new ContactController();
        System.assert(c!=null);
        
        ApexPages.currentPage().getParameters().put('id', MockAccount.getNewAccount().id);
        c = new ContactController();
        System.assert(c!=null);
        
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);
        c = new ContactController();
        System.assert(c!=null);        
    }
    
    static testMethod void testSave() {
        ContactController c = new ContactController();
        System.assert(c.save()==null);
    }
    
    static testMethod void testSaveThenNew() {
        ContactController c = new ContactController();
        System.assert(c.saveThenNew()!=null);
    } 
    
    /*static testMethod void testCustomDelete() {
ApexPages.currentPage().getParameters().put('id', '/'+MockContact.getNewContact().id);
ApexPages.currentPage().getParameters().put('delID', '/'+MockContact.getNewContact().id);
ApexPages.currentPage().getParameters().put('retURL', '/'+MockContact.getNewContact().id);
ContactController c = new ContactController();
c.init();
System.assert(1==1);
}  */
    
    static testMethod void testCancelDelete() {
        ContactController c = new ContactController();
        System.assert(c.cancelDelete()!=null);
    }  
    //new
    static testMethod void testInit() {
        ApexPages.currentPage().getParameters().put('retURL', '/'+MockContact.getNewContact().id);
        ContactController c = new ContactController();
        System.assert(c.init()==null);
    }  
    static testMethod void testInitWithContact() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);
        ApexPages.currentPage().getParameters().put('retURL', '/'+MockContact.getNewContact().id);
        ContactController c = new ContactController();
        c.init();
    } 
    //new
    /*static testMethod void testcontroller() {
ApexPages.currentPage().getParameters().put('Id', '/'+MockContact.getNewContact().id);
ContactController c = new ContactController();
System.assert(c.init()==null);
}*/
    
    
    static testMethod void testGetContact() {
        ContactController c = new ContactController();
        c.setContact(new Contact());
        System.assert(c.getContact()!=null);
    }  
    
    static testMethod void testGetAdministratorInformationTitle() {
        ContactController c = new ContactController();
        System.assert(c.getAdministratorInformationTitle()!=null);
    }  
    
    static testMethod void testSetWaitDialogContent() {
        ContactController c = new ContactController();
        c.setWaitDialogContent();
        System.assert(c.getWaitDialog()!=null);
    } 
    static testMethod void testrestoreDateNull() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);   
        ContactController c = new ContactController();
        String Id =ApexPages.currentPage().getParameters().get('delID');  
        Contact contactObj =[Select Account.Id,Status__c from Contact where Id=:ApexPages.currentPage().getParameters().get('delID')];
        contactObj.Status__c='Delete'; 
        Update contactObj;
        Account accountObj =[Select Status__c from Account Where Id=:contactObj.AccountId];
        accountObj.Status__c='Active'; 
        Update accountObj;  
        ContactController.restore(Id);
        System.assertEquals('Contact must have a Date Deleted value set before restoring.',ContactController.restore(Id));
    }
    static testMethod void testrestoreDate() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);   
        ContactController c = new ContactController();
        String Id =ApexPages.currentPage().getParameters().get('delID');  
        Contact contactObj =[Select Account.Id,Status__c from Contact where Id=:ApexPages.currentPage().getParameters().get('delID')];
        contactObj.Status__c='Delete'; 
        contactObj.Date_Deleted__c=Date.today().addDays(-31);
        Update contactObj;
        Account accountObj =[Select Status__c from Account Where Id=:contactObj.AccountId];
        accountObj.Status__c='Active'; 
        Update accountObj;  
        System.assertEquals('Cannot restore Contacts that were deleted more than 30 days ago.',ContactController.restore(Id));
    }
    static testMethod void testrestore() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);   
        ContactController c = new ContactController();
        String Id =ApexPages.currentPage().getParameters().get('delID');  
        Contact contactObj =[Select Account.Id,Status__c from Contact where Id=:ApexPages.currentPage().getParameters().get('delID')];
        contactObj.Status__c='Delete'; 
        contactObj.Date_Deleted__c=Date.today();   
        Update contactObj;
        Account accountObj =[Select Status__c from Account Where Id=:contactObj.AccountId];
        accountObj.Status__c='Active'; 
        Update accountObj; 
        ContactController.restore(Id);
        Contact objContact =[Select Inactive__c,Status__c From Contact];
        System.assertEquals(false, objContact.Inactive__c);
        System.assertEquals('Restoring', objContact.Status__c);
    }
    
    static testMethod void testrestoreAccountException() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);   
        ContactController c = new ContactController();
        String Id =ApexPages.currentPage().getParameters().get('delID');  
        System.assertEquals('Related Account must be in an Active status before restoring.',ContactController.restore(Id)); 
    }
    static testMethod void testrestoreDeptValidation() {
        ApexPages.currentPage().getParameters().put('id', MockDepartment.getNewDepartment().id);
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);   
        ContactController c = new ContactController();
        String Id =ApexPages.currentPage().getParameters().get('delID');  
        Id deptId = ApexPages.currentPage().getParameters().get('id');
        Contact contactObj =[Select Account.Id,Status__c from Contact where Id=:ApexPages.currentPage().getParameters().get('delID')];
        contactObj.Status__c='Delete'; 
        contactObj.Department_Parent__c=deptId;
        contactObj.Date_Deleted__c=Date.today();   
        Update contactObj;
        Account accountObj =[Select Status__c from Account Where Id=:contactObj.AccountId];
        accountObj.Status__c='Active'; 
        Update accountObj; 
        System.assertEquals('Related Department must be in an Active status before restoring.',ContactController.restore(Id)); 
    }
    static testMethod void testrestoreStatusException() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);   
        ContactController c = new ContactController();
        String Id =ApexPages.currentPage().getParameters().get('delID');  
        Contact contactObj =[Select Account.Id,Status__c from Contact where Id=:ApexPages.currentPage().getParameters().get('delID')];
        contactObj.Date_Deleted__c=Date.today();
        Update contactObj;
        Account accountObj =[Select Status__c from Account Where Id=:contactObj.AccountId];
        accountObj.Status__c='Active';
        update accountObj;
        System.assertEquals('Contact must be in a Delete satus before restoring.',ContactController.restore(Id));
    }
    static testMethod void testcustomDelete() {
        ApexPages.currentPage().getParameters().put('delID', MockContact.getNewContact().id);  
        ContactController c = new ContactController();
        c.customDelete();
        Contact objContact =[Select Inactive__c,Status__c From Contact];
        System.assertEquals(true, objContact.Inactive__c);
        System.assertEquals('Deleting', objContact.Status__c);
    } 
    static testMethod void testcustomDeleteElse() {
        ContactController c = new ContactController();
        System.assert(c.customDelete()==null);
    } 
}