force-app/main/default/objects/Account/fields/defaultPlan__c.field-meta.xml
<CustomField>
    <fullName>defaultPlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A reference to the default Plan for this Account</description>
    <label>Default Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/PlanAssignment__c.object-meta.xml
<CustomObject>
    <description>Assigned Products related to Access Codes.</description>
    <label>Plan Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>PlanAssignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If &quot;Active,&quot; indicates that the access code is activated on audio and web systems.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>SendProvisioningEmail</fullName>
            </value>
            <value>
                <fullName>BillingDeleteError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>If there was an error in provisioning the subscription, then it is of this record type</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/SubscriptionRest.cls
@RestResource(urlMapping = '/Subscription/*')
global with sharing class SubscriptionRest{            

  @HttpPost
  global static void save(){        
    RestContext.response.addHeader('Content-Type', 'application/json');
    RestRequest req = RestContext.request;

    SavePoint sp = Database.setSavePoint();
    Account a = null;
    String planName = null;
    Plan planRepository = null;
    PlanAssignment planAssignmentRepository = null;
    Id subscriptionId = null;

    try{    
      String body = req.requestBody.toString();
      Map<String, Object> bodyMap = new Map<String,Object>();  
      bodyMap = (Map<String, Object>) JSON.deserializeUntyped(body);      

      String contactId = (String) bodyMap.get('contactId');
      planName = (String) bodyMap.get('planName');
      Map<String, Object> accessCode = (Map<String, Object>) bodyMap.get('accessCode');      

      planRepository = new Plan();
      planAssignmentRepository = new PlanAssignment();
      Subscription subscriptionRepository = new Subscription();      
      Subscription__c sub = new Subscription__c();

      //Build a new Subscription__c object from the incoming accessCode (if there is one)
      if(accessCode != null){
        AbstractValidator builder = new Subscription.builderValidator().forObject(new Subscription__c());
        for(String key : accessCode.keySet()){
          builder.set(key, accessCode.get(key));
        }

        sub = (Subscription__c) builder.buildAndValidate().getObject();
      }

      //Save the Subscription__c record
      Contact c = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), contactId, ',Account.Status__c,Account.defaultPlan__c,Account.Id');
      a = (Account) RTDatabaseUtils.getEntireSObject(new Account(), c.AccountId);    
      subscriptionId = RTAccessCodeUtils.saveAndProvisionSubscription(sub, c, a, true);
    }  
    catch(Exception ex){
      Database.rollback(sp);
      RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new ErrorResponse(new List<ErrorResponse.Error>{new ErrorResponse.Error(ex.getMessage())})));
      return;
    }

    sp = Database.setSavePoint();
    try{    
      //Save the PlanAssignment__c record
      List<Plan__c> availableAccountPlans = new List<Plan__c>();
      if(planName != null)
        availableAccountPlans = planRepository.getPlansByAccountIdAndName(a.Id, planName);
      else
        availableAccountPlans = planRepository.getPlansByAccountIdAndIsDefault(a.Id);

      if(availableAccountPlans == null || availableAccountPlans.size() < 1){
        RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new ErrorResponse(new List<ErrorResponse.Error>{new ErrorResponse.Error('No available plan to assign to this access code.')})));  
        return;
      }

      planAssignmentRepository.savePlanAssignment(availableAccountPlans.get(0).Name, availableAccountPlans.get(0).Id, 'Subscription__c', subscriptionId, Date.today(), availableAccountPlans.get(0).endDate__c);

      RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new ValidResponse(new AddSubscriptionData(subscriptionId))));
    }
    catch(Exception ex){
      Database.rollback(sp);
      RestContext.response.responseBody = Blob.valueOf(JSON.serialize(new ErrorResponse(new List<ErrorResponse.Error>{new ErrorResponse.Error(ex.getMessage())})));
    }
  }

  public class AddSubscriptionData{
    public String subscriptionId;

    public AddSubscriptionData(String subscriptionId){
      this.subscriptionId = subscriptionId;
    }
  }   
}