force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NetSuite_Id__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Id__c</fullName>
    <label>NetSuite Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NetSuite_Pull__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Pull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Pull</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Admin__c.field-meta.xml
<CustomField>
    <fullName>Account_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Use patria_lanfranchi@ecovate.com login if need to bulk update this field</description>
    <inlineHelpText>If checked, this is the primary contact for this account.</inlineHelpText>
    <label>Account Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NetSuite_Locked__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NetSuite_Push__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Push__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Push</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NS_Sync__c.field-meta.xml
<CustomField>
    <fullName>NS_Sync__c</fullName>
    <label>NetSuite Sync</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PGi_Contact.recordType-meta.xml
<RecordType>
    <fullName>PGi_Contact</fullName>
    <active>true</active>
    <label>PGi Contact</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/ReadyTalk_Contact.recordType-meta.xml
<RecordType>
    <fullName>ReadyTalk_Contact</fullName>
    <active>true</active>
    <label>ReadyTalk Contact</label>
</RecordType>

force-app/main/default/classes/ContactActionsTest.cls
@isTest
public class ContactActionsTest {
    static testMethod void testonContactDelete(){
        Id pgiRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PGi_Contact').getRecordTypeId();
        Account acc = new Account();
        acc.Name='test';
        Insert acc;
        Contact contactObj = new Contact(Lastname = 'testcon',AccountId = acc.Id,RecordTypeId = pgiRT,Account_Admin__c=true,Email='test@Contact.com',Status__c='Delete');
		Insert contactObj;  
    }
    static testMethod void testonContactDeleteInactive(){
        Id readyTalkRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ReadyTalk_Contact').getRecordTypeId();
        Account acc = new Account();
        acc.Name='test';
        Insert acc;
        Contact contactObj = new Contact(Lastname = 'testcon',Celigo_Update__c=true,AccountId = acc.Id,RecordTypeId = readyTalkRT,Account_Admin__c=true,Email='test@Contact.com');
		Insert contactObj;  
        contact conObj=[Select Id,NetSuite_Id__c,NetSuite_Locked__c,NS_Sync__c,NetSuite_Push__c,NetSuite_Pull__c from contact];
        System.assertEquals(false, conObj.NetSuite_Locked__c);
        System.assertEquals(false, conObj.NetSuite_Push__c);
        System.assertEquals(false, conObj.NetSuite_Pull__c);
    }
    static testMethod void testonContactDeleteStatus(){
        Id readyTalkRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ReadyTalk_Contact').getRecordTypeId();
        Account acc = new Account();
        acc.Name='test';
        Insert acc;
        Contact contactObj = new Contact(Lastname = 'testcon',Inactive__c=true,Status__c='Delete',AccountId = acc.Id,RecordTypeId = readyTalkRT,Account_Admin__c=true,Email='test@Contact.com');
		Insert contactObj;  
        contact conObj=[Select Id,NetSuite_Id__c,NetSuite_Locked__c,NS_Sync__c,NetSuite_Push__c,NetSuite_Pull__c from contact];
        System.assertEquals(false, conObj.NetSuite_Locked__c);
        System.assertEquals(false, conObj.NetSuite_Push__c);
        System.assertEquals(false, conObj.NetSuite_Pull__c);
    }
    static testMethod void testonContactDeleteSameStatus(){
        Id readyTalkRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ReadyTalk_Contact').getRecordTypeId();
        Account acc = new Account();
        acc.Name='test';
        Insert acc;
        Contact contactObj = new Contact(Lastname = 'testcon',Inactive__c=true,AccountId = acc.Id,RecordTypeId = readyTalkRT,Account_Admin__c=true,Email='test@Contact.com');
		Insert contactObj; 
        contact conObj=[Select Id,NetSuite_Id__c,NetSuite_Locked__c,NS_Sync__c,NetSuite_Push__c,NetSuite_Pull__c from contact];
        System.assertEquals(false, conObj.NetSuite_Locked__c);
        System.assertEquals(false, conObj.NetSuite_Push__c);
        System.assertEquals(false, conObj.NetSuite_Pull__c);
    }
    static testMethod void testonContactDeleteAllFalse(){
        Id readyTalkRT = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('ReadyTalk_Contact').getRecordTypeId();
        Account acc = new Account();
        acc.Name='test';
        Insert acc;
        Contact contactObj = new Contact(Lastname = 'testcon',Inactive__c=true,AccountId = acc.Id,RecordTypeId = readyTalkRT,Account_Admin__c=true,Email='test@Contact.com');
		Insert contactObj; 
        contactObj.Status__c='Pending';
        Update contactObj;
        contact conObj=[Select Id,NetSuite_Id__c,NetSuite_Locked__c,NS_Sync__c,NetSuite_Push__c,NetSuite_Pull__c from contact];
        System.assertEquals(false, conObj.NetSuite_Locked__c);
        System.assertEquals(false, conObj.NetSuite_Push__c);
        System.assertEquals(false, conObj.NetSuite_Pull__c);
    }
}