force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Suspend_Account__c.field-meta.xml
<CustomField>
    <fullName>Suspend_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the account has not paid its bills, etc, this should be checked.</description>
    <inlineHelpText>If checked, indicates that all active subscribers&#39; access codes have been deactivated until balance due is paid.</inlineHelpText>
    <label>Suspend Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If &quot;Active,&quot; indicates that the access code is activated on audio and web systems.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>SendProvisioningEmail</fullName>
            </value>
            <value>
                <fullName>BillingDeleteError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Deleted.recordType-meta.xml
<RecordType>
    <fullName>Deleted</fullName>
    <active>true</active>
    <description>Use this record type when the subscription is deleted</description>
    <label>Deleted</label>
</RecordType>

force-app/main/default/objects/Subscription__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>If there was an error in provisioning the subscription, then it is of this record type</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/AccountController.cls
public with sharing class AccountController extends BaseController {

  Account a;
  String deleteID;
  WaitDialog dialog;
  Integer subscriptionCount;

  /**
   * Default Constructor
   */
  public AccountController(ApexPages.StandardController controller) {
    //Delete
    this.deleteID = ApexPages.currentPage().getParameters().get('delID');
    

    //Delete Account
    if (this.deleteID != null) {
      this.a = (Account) RTDatabaseUtils.getEntireSObject(new Account(), this.deleteID);
      setWaitDialogContent();
    }
  }
  public PageReference init() {
    String retUrl = ApexPages.currentPage().getParameters().get('retURL');
    if(ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypeIds.contains(this.a.RecordTypeId)) {
        return null;
    } else {
        delete a;
        return new PageReference(retUrl);
    } 
  }
  /**
   * Setter for the wait dialog content.
   */
  public void setWaitDialogContent() {
    this.dialog = new WaitDialog();
    if (this.deleteID != null && this.subscriptionCount == null) {
      getWaitDialog().setHeader('Question...');
      getWaitDialog().setStatus('This will delete this account along with all departments, contacts and subscriptions associated with it. Are you sure you want to do this?');
      getWaitDialog().setButton('Delete');
      getWaitDialog().setClickCommand('preDelete()');
      getWaitDialog().setCancelButton('Cancel');
      getWaitDialog().setShouldRenderCancelButton(true);
      getWaitDialog().setCancelClickCommand('cancelDelete()');
      getWaitDialog().setShouldRender(true);
    }

    if (this.deleteID != null && this.subscriptionCount != null && ((this.subscriptionCount <= RTConfig.LIMIT_NUMBER_SUBSCRIPTIONS || getIsAdministrator()) || (this.subscriptionCount > RTConfig.LIMIT_NUMBER_SUBSCRIPTIONS && ValidateAccountFields.timeFrameOKToBulkDelete))) {
      getWaitDialog().setHeader('Question...');
      getWaitDialog().setStatus('Please describe the reason for deleting this account.');
      getWaitDialog().setButton('Continue');
      getWaitDialog().setClickCommand('customDelete()');
      getWaitDialog().setCancelButton('Cancel');
      getWaitDialog().setCancelClickCommand('cancelDelete()');
      getWaitDialog().setShouldRenderCancelButton(true);
      getWaitDialog().setShouldRenderForm(true);
      getWaitDialog().setShouldRender(true);
    }

    if (this.deleteID != null && this.subscriptionCount != null && this.subscriptionCount > RTConfig.LIMIT_NUMBER_SUBSCRIPTIONS && !ValidateAccountFields.timeFrameOKToBulkDelete) {
      getWaitDialog().setHeader('Error: Too many subscriptions...');
      getWaitDialog().setStatus('Due to the number of subscriptions to be deleted (' + this.subscriptionCount + '), this action must be performed after working hours (after 4PM MT).');
      getWaitDialog().setButton('OK');
      getWaitDialog().setClickCommand('cancelDelete()');
      getWaitDialog().setShouldRender(true);
    }

    if (this.deleteID != null && this.a.Suspend_Account__c == true) {
      getWaitDialog().setHeader('Error...');
      getWaitDialog().setStatus('This account is in suspended status and cannot be deleted.  Contact SF/Billing Team in order to delete this account.');
      getWaitDialog().setButton('OK');
      getWaitDialog().setClickCommand('cancelDelete()');
      getWaitDialog().setShouldRenderCancelButton(false);
      getWaitDialog().setShouldRender(true);
    }
  }

  public void preDelete() {
    this.subscriptionCount = 0;
    //Abstract to RTAccountUtils.getSubscriptionCount()

    //Subscriptions
    List<Subscription__c> subscriptions = [select id, inactive__c from Subscription__c where Contact__r.Account.id = : getAccount().id and inactive__c = false];
    this.subscriptionCount += subscriptions.size();

    setWaitDialogContent();
  }

  public PageReference customDelete() {
    this.a.Inactive__c = true;
    this.a.Status__c = 'Deleting';

    update(this.a);

    AccountRepository accountRepository = new AccountRepository();
    accountRepository.cascadeDelete(this.a);
    return gotoView(this.a);
  }

  public PageReference cancelDelete() {
    return gotoView(this.a.id);
  }

  /**
   * Returns the wait dialog
   */
  public WaitDialog getWaitDialog() {
    return this.dialog;
  }

  public Account getAccount() {
    return this.a;
  }
}