force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Corporate Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting/Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Customer Service/Care/Support</fullName>
            </value>
            <value>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </value>
            <value>
                <fullName>HR Generalist</fullName>
            </value>
            <value>
                <fullName>HR Recruiting</fullName>
            </value>
            <value>
                <fullName>Investor Relations</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>This object handles departments (children of accounts) so accounts will not have children accounts.</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CascadeAccountOwner.cls
public class CascadeAccountOwner implements Queueable{
  private String objectType;
  private Id accountId;
  private Id oldAccountOwnerId;
  private Id newAccountOwnerId;

  public CasCadeAccountOwner(String objectType, Id accountId, Id oldAccountOwnerId, Id newAccountOwnerId){
    this.objectType = objectType;
    this.accountId = accountId;
    this.oldAccountOwnerId = oldAccountOwnerId;
    this.newAccountOwnerId = newAccountOwnerId;
  }

  public void execute(QueueableContext context) {            
    if(this.objectType.equals('Subscription__c')){
      updateSubscriptions();
      System.enqueueJob(new CascadeAccountOwner('Department__c', this.accountId, this.oldAccountOwnerId, this.newAccountOwnerId));
    }
    else if(this.objectType.equals('Department__c')){
      updateDepartments();
      System.enqueueJob(new CascadeAccountOwner('Contact', this.accountId, this.oldAccountOwnerId, this.newAccountOwnerId));
    }
    else if(this.objectType.equals('Contact')){
      updateContacts();
    }
    else if(this.objectType.equals('Execute')){
      System.enqueueJob(new CascadeAccountOwner('Subscription__c', this.accountId, this.oldAccountOwnerId, this.newAccountOwnerId));
    }
    else{
      System.debug('Invalid objectType '+this.objectType+' passed to CascadeAccountOwner.');
    }
  }

  private void updateSubscriptions(){
    String query = 'select id, inactive__c, OwnerId, contact__r.Account.id from Subscription__c where contact__r.Account.id = \'' + this.accountId + '\'' +
      ' and inactive__c=false';

    List<Subscription__c> objects = Database.query(query);
    List<Subscription__c> updates = new List<Subscription__c>();

    for(Subscription__c o : objects){      
      o.Ownerid=this.newAccountOwnerId;
      updates.add(o);
    }

    try{
      update updates;
    }
    catch(Exception e){

    }
  }

  private void updateDepartments(){
    String query = 'select id, inactive__c, OwnerId, Parent_Account__r.id from Department__c where Parent_Account__r.id = \'' + this.accountId + '\'' +
      ' and inactive__c=false';
    List<Department__c> objects = Database.query(query);
    List<Department__c> updates = new List<Department__c>();

    for(Department__c o : objects){
      o.Ownerid=this.newAccountOwnerId;
      updates.add(o);      
    }

    try{
      update updates;
    }
    catch(Exception e){

    }
  }

  private void updateContacts(){
    String query = 'select id, inactive__c, OwnerId, Contact.Account.id from Contact where Contact.Account.id = \'' + this.accountId + '\'' +
      ' and inactive__c=false';

    List<Contact> objects = Database.query(query);
    List<Contact> updates = new List<Contact>();

    for(Contact o : objects){      
      o.Ownerid=this.newAccountOwnerId;
      updates.add(o);      
    }

    try{
      update updates;
    }
    catch(Exception e){

    }
  }
}