force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountRepositoryTest.cls
@isTest
public class AccountRepositoryTest {
    static testMethod void testCustomDelete() {
        List<Account> accList = new List<Account>{new Account(Name = 'testAcc'),
            new Account(Name = 'testAcc00',Inactive__c = true,Status__c='Deleting'),
            new Account(Name = 'testAcc11',Status__c = 'Delete',Inactive__c = true) };
        insert accList;
        
        Test.startTest();
        AccountRepository a = new AccountRepository();
        a.findById(accList[0].Id);
        a.cascadeDelete(accList[1]);
       //  Database.SaveResult srList = Database.update(accList[2], false);
        a.del(accList[2]);
        Test.stopTest();
        System.assertEquals(0, [select id,Status__c from account where Status__c = 'Delete'].size());
    }
}