force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/FoxDen_Box__c.object-meta.xml
<CustomObject>
    <description>FoxDen box includes ChromeBox, Microphone/Speaker, and Camera</description>
    <label>FoxDen Box</label>
    <nameField>
        <displayFormat>FoxDenBox-{00000}</displayFormat>
        <label>FoxDen Box Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FoxDen Boxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_Box__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for the account this FoxDen Box belongs to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FoxDen Boxes</relationshipLabel>
    <relationshipName>FoxDen_Boxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Id__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Id__c</fullName>
    <description>The UUID of the beacon</description>
    <label>Beacon Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Major_Value__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Major_Value__c</fullName>
    <label>Beacon Major Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Minor_Value__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Minor_Value__c</fullName>
    <label>Beacon Minor Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A flag indicating whether or not this box is active</description>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Kiosk_Email__c.field-meta.xml
<CustomField>
    <fullName>Kiosk_Email__c</fullName>
    <label>Kiosk Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Kiosk Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>Kit ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status_Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FoxDenBox.cls
public with sharing class FoxDenBox extends AbstractRepository {

  public final static String table = 'FoxDen_Box__c';
  public final static String columns = 'id,name,Account__c,Auth0_User_Id__c,Beacon_Id__c,Beacon_Major_Value__c,Beacon_Minor_Value__c,Inactive__c,Kiosk_Email__c,Password__c,sku__c,Status__c,Status_Description__c';

  /**
   * Validations
   */    
  public class builderValidator extends AbstractValidator {      
    public override void validate(SObject o) {  
      FoxDen_Box__c box = (FoxDen_Box__c)o;      
      this.accountHasFoxDenAccountLicense(box);      
    }

    public void accountHasFoxDenAccountLicense(FoxDen_Box__c box){
      if(box.Account__c == null)
        return;
      else{
        Plan planRepository = new Plan();
        List<Plan__c> plans = planRepository.getPlansByAccountIdAndName(box.Account__c, 'FoxDen Connect In-Room System');
        if(plans == null || plans.size() < 1)
          throw new ValidationException('A FoxDen - Connect In-Room System plan needs to be added to this account before assigning a FoxDen Box');
      }
    }
  }
  
  /**
   * Queries
   */  
  public FoxDen_Box__c findById(Id boxId) {    
    return (FoxDen_Box__c) Database.query(selectBuilder(table,columns,'where id = :boxId limit 1'));
  }

  public List<FoxDen_Box__c> getFoxDenBoxesInSet(List<Id> s){
    List<FoxDen_Box__c> boxes = (List<FoxDen_Box__c>) Database.query(selectBuilder(table,columns,'where id in : s'));
    return boxes;    
  }

  /*
  * Returns FoxDen boxes that are unassigned (NOTE: Limits to 30 ATM)
  */
  public List<FoxDen_Box__c> getFoxDenBoxesWhereAccountIdIsNullAndActive(){
    List<FoxDen_Box__c> boxes = (List<FoxDen_Box__c>) Database.query(selectBuilder(table,columns,'where account__c = null and Inactive__c = false and Status__c = \'Active\' order by CreatedDate asc limit 30'));
    return boxes;
  }

  public FoxDen_Box__c assignBox(Id accountId, FoxDen_Box__c foxDenBox) { 
    FoxDen_Box__c box = (FoxDen_Box__c) new FoxDenBox.builderValidator()
      .forObject(foxDenBox)
      .set('account__c', accountId)
      .buildAndValidate()
      .getObject();   
    return box;
  }  
}