force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
If the account is inactive (ie deleted, but not deleted from the db), this should be checked.</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Individual_ID__c.field-meta.xml
<CustomField>
    <fullName>Individual_ID__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
This is the unique ID for this contact in billing.</description>
    <externalId>true</externalId>
    <label>Individual ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MockContact.cls
public class MockContact {
    
    public String Status = 'New';
    public Account acct = MockAccount.getNewAccount();
    public Id AccountId = acct.id;
    public String LastName = 'Mock Last Name';
    public String FirstName = 'Mock First Name';
    public String MailingAddress1 = '123 Main St.';
    public String MailingAddress2 = 'Unit 350';
    public String MailingCity = 'Denver';
    public String MailingStateCode = 'CO';
    public String MailingState = 'Colorado';
    public String MailingCountry = 'United States';
    public String MailingCountryCode = 'US';
    public String MailingZip = '80202';
    public Id OwnerId = MockUser.getNewUser().Id;
    public boolean Inactive = false;
    public String email = 'qa@readytalk.com';
    
    public void setupContact(Contact c) {
        c.Status__c = Status;     
        c.AccountId = AccountId;
        c.Account = acct;
        c.LastName = LastName;
        c.FirstName = FirstName;
        c.OwnerId = OwnerId;
        c.inactive__c = Inactive;
        c.MailingStreet = MailingAddress1;
        //c.Mailing_Address_2__c = MailingAddress2;
        c.MailingCity = MailingCity;
        c.MailingState = MailingState;
        c.MailingStateCode = MailingStateCode;
        c.MailingPostalCode = MailingZip;
        c.MailingCountry = MailingCountry;
        c.MailingCountryCode = MailingCountryCode;
        c.Email = email;     
        c.Individual_ID__c = '1234'; 
    }
       
    public static Contact getNewContact() {        
        Contact c = new Contact();
        MockContact mc = new MockContact();
        mc.setupContact(c);
        Database.insert(c);      
        return c;
    }
    
    public Contact getContact() {
        Contact c = new Contact();
        setupContact(c);        
        Database.insert(c);        
        return c;
    }
}