force-app/main/default/objects/Account/fields/Invoice_Types__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Types__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Invoice Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Summary</fullName>
                <default>true</default>
                <label>Account Summary</label>
            </value>
            <value>
                <fullName>Department Summary</fullName>
            </value>
            <value>
                <fullName>Access Code Summary</fullName>
            </value>
            <value>
                <fullName>Access Code Detail</fullName>
            </value>
            <value>
                <fullName>Conference Detail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Webcasting_Rates__c/Event_Webcasting_Rates__c.object-meta.xml
<CustomObject>
    <label>Event &amp; Webcasting Rates</label>
    <nameField>
        <displayFormat>Rate{000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event &amp; Webcasting Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RTEvent__c/RTEvent__c.object-meta.xml
<CustomObject>
    <description>Primary ReadyTalk Events record.</description>
    <label>RT Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTEvent__c/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipName>R00N50000001bJrhEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RT Events</relationshipLabel>
    <relationshipName>R00N50000001bEk2EAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Bill_to_Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Bill_to_Access_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Insert access code that should be billed for event services.</description>
    <inlineHelpText>Insert access code that should be billed for event services.</inlineHelpText>
    <label>Bill to Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>RT Events (Bill to Access Code)</relationshipLabel>
    <relationshipName>RT_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Broadcast_Audio_Event_Duration2__c.field-meta.xml
<CustomField>
    <fullName>Broadcast_Audio_Event_Duration2__c</fullName>
    <label>Broadcast Audio Event Duration*</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Broadcast_Audio_Event_Participants__c.field-meta.xml
<CustomField>
    <fullName>Broadcast_Audio_Event_Participants__c</fullName>
    <description>Number of participants utilizing BA for an event.</description>
    <inlineHelpText>Enter number of participants utilizing Broadcast Audio for this event.</inlineHelpText>
    <label>Broadcast Audio Event Participants</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Coordinator_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Coordinator_Notes_New__c</fullName>
    <label>Coordinator Notes - New</label>
    <length>62487</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Displays date of event.</inlineHelpText>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Event_Manager_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager_Notes_New__c</fullName>
    <label>Event Manager Notes - New</label>
    <length>62487</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Event_Webcasting_Rates__c.field-meta.xml
<CustomField>
    <fullName>Event_Webcasting_Rates__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event &amp; Webcasting Rates</label>
    <referenceTo>Event_Webcasting_Rates__c</referenceTo>
    <relationshipLabel>RT Events</relationshipLabel>
    <relationshipName>RT_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/eventManager__c.field-meta.xml
<CustomField>
    <fullName>eventManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Event Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RT_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Select the status of the event.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>DUPLICATE</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
            <value>
                <fullName>Waiting to Close</fullName>
            </value>
            <value>
                <fullName>Waiting on Recording Edits</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Total_lines_reserved__c.field-meta.xml
<CustomField>
    <fullName>Total_lines_reserved__c</fullName>
    <description>Total number of International Toll Free Speaker and Participant dial in #&apos;s</description>
    <inlineHelpText>Total ITF lines requested (Spkr &amp; Part)</inlineHelpText>
    <label>Total ITF lines reserved</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <description>This field should be removed as soon as possible so it doesn&apos;t confuse people.</description>
    <label>Access Code Old Field</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>HYPERLINK(Contact__r.Account.Id, Contact__r.Account.Name, &quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subscriber Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Coordinator_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Coordinator_Notes_New__c</fullName>
    <label>Coordinator Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Event_Manager_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager_Notes_New__c</fullName>
    <label>Event Manager Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If &quot;Active,&quot; indicates that the access code is activated on audio and web systems.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>SendProvisioningEmail</fullName>
            </value>
            <value>
                <fullName>BillingDeleteError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RTEventTriggerTest.cls
@IsTest
public without sharing class RTEventTriggerTest {
  @TestSetup
  static void makeData(){
    Test.startTest();
      
      Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = new User(
            ProfileId = pf.Id,
            LastName = 'test User',
            Email = 'test.FromTestCEmailComposer.com@pgi.com',
            Username = 'test.FromTestCEmailComposer01.com@pgi.com' ,
            CompanyName = 'RT',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            EmployeeNumber = 'one'
       );
       insert u;
       System.runAs(u) {
        PGITestUtilities.disableSalesWings();
       }
      Test.stopTest();
  }
  private static void init() {
    EventDate = Date.newInstance(3010, 1, 1);
    billToSub = MockSubscription.getNewSubscription();
    ac = MockSubscription.getNewSubscription();
    duration = 100;
    participants = 100;
  }
    public static Date EventDate;
    private static Subscription__c billToSub;
    private static Subscription__c ac;
    private static Integer duration;
    private static Integer participants;
        
    private static void setupRTEvent(RTEvent__c e) {
      User usr = [SELECT Id, Username, LastName FROM User WHERE UserName = 'test.FromTestCEmailComposer01.com@pgi.com' AND IsActive = true];
      e.Event_Date__c = EventDate;
      e.Access_Code__c = ac.Id;
      e.Bill_to_Access_Code__c = billToSub.Id;
      e.Bill_to_Access_Code__r = billToSub;
      e.Broadcast_Audio_Event_Duration2__c = duration;
      e.Broadcast_Audio_Event_Participants__c = participants;
      e.Total_lines_reserved__c = 10;

      e.Coordinator_Notes_New__c = 'Test Coordinator_Notes_New__c Description';
      e.Event_Manager_Notes_New__c = 'Test Event_Manager_Notes_New__c Description';
      e.status__c = 'CANCELLED';
      e.eventManager__c = UserInfo.getUserId();

    }
    @IsTest 
    public static void testRateAssociation() {
      init();
      Test.startTest();
      Account acct = new Account();
	    acct.Name = 'test';
	    //acct.Billing_State__c = 'CO';
	    acct.Invoice_Types__c = 'Account Summary';
	    acct.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypes[0].Id;
      insert new List<Account>{acct};
	    //test update
	    RTEvent__c updateEvent = getNewRTEvent(true);
	    updateEvent = [SELECT Event_Webcasting_Rates__c FROM RTEvent__c WHERE Id =: updateEvent.Id];
	    System.assert(updateEvent.Event_Webcasting_Rates__c == null);
	    updateEvent.Account__c = acct.Id;
	    update updateEvent;
	    updateEvent = [SELECT Event_Webcasting_Rates__c FROM RTEvent__c WHERE Id =: updateEvent.Id];
	    updateEvent.Event_Webcasting_Rates__c = null;
	    update updateEvent;
	    updateEvent = [SELECT Event_Webcasting_Rates__c FROM RTEvent__c WHERE Id =: updateEvent.Id];
	    System.assert(updateEvent.Event_Webcasting_Rates__c != null);
	    //test insert
	    RTEvent__c insertEvent = getNewRTEvent(false);
	    insertEvent.Account__c = acct.Id;
      insertEvent.eventManager__c = UserInfo.getUserId();
	    insert insertEvent;
	    insertEvent = [SELECT Event_Webcasting_Rates__c FROM RTEvent__c WHERE Id =: insertEvent.Id];
      System.assert(insertEvent.Event_Webcasting_Rates__c != null);
      
      // Event evnt = new Event();
      // evnt.WhatId = insertEvent.Id;
      // evnt.DurationInMinutes = 4;
      // evnt.ActivityDate = date.newInstance(2020, 3, 10);
      // evnt.ActivityDateTime = datetime.newInstance(2020, 3, 10, 16, 30, 0);
      // insert evnt;
      Test.stopTest();
    }

    public static RTEvent__c getNewRTEvent(Boolean doInsert) {
      RTEvent__c e = new RTEvent__c();
      setupRTEvent(e);
      if(doInsert) {
      	Database.insert(e);
      }
      return e;
    }

    @IsTest 
    public static void test() {
      init();
      Test.startTest();
       Account acc = new Account();
        acc.Name = 'Test Account';
        insert acc;

        Profile pf = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
      //   User u = new User(
      //       ProfileId = pf.Id,
      //       LastName = 'test.FromTestCEmailComposer01.com@pgi.com New',
      //       Email = 'test.FromTestCEmailComposer.com@pgi.com',
      //       Username = 'test.FromTestCEmailComposer01.com@pgi.com' ,
      //       CompanyName = 'RT',
      //       Title = 'title',
      //       Alias = 'alias',
      //       TimeZoneSidKey = 'America/Los_Angeles',
      //       EmailEncodingKey = 'UTF-8',
      //       LanguageLocaleKey = 'en_US',
      //       LocaleSidKey = 'en_US',
      //       EmployeeNumber = 'one'
      //     );
      //  insert u;
      User usr = [SELECT Id, Username, LastName FROM User WHERE UserName = 'test.FromTestCEmailComposer01.com@pgi.com' AND IsActive = true];

        RTEvent__c insertEventNew = new RTEvent__c();
        insertEventNew.Account__c = acc.Id;
        insertEventNew.Coordinator_Notes_New__c = 'Test Description';
        insertEventNew.Event_Manager_Notes_New__c = 'Test Description';
        insertEventNew.status__c = 'CANCELLED';
        insertEventNew.eventManager__c = usr.Id;
        insert insertEventNew;
       
        // insertEventNew.eventManager__c = UserInfo.getUserId();
        insertEventNew.status__c = 'Closed';
        update insertEventNew;

        Event evnt = new Event();
        evnt.WhatId = insertEventNew.Id;
        evnt.DurationInMinutes = 4;
        evnt.ActivityDate = date.newInstance(2020, 3, 10);
        evnt.ActivityDateTime = datetime.newInstance(2020, 3, 10, 16, 30, 0);
        insert evnt;
    }
}