force-app/main/default/objects/Account/fields/Invoice_Types__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Types__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Invoice Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account Summary</fullName>
                <default>true</default>
                <label>Account Summary</label>
            </value>
            <value>
                <fullName>Department Summary</fullName>
            </value>
            <value>
                <fullName>Access Code Summary</fullName>
            </value>
            <value>
                <fullName>Access Code Detail</fullName>
            </value>
            <value>
                <fullName>Conference Detail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Webcasting_Rates__c/Event_Webcasting_Rates__c.object-meta.xml
<CustomObject>
    <label>Event &amp; Webcasting Rates</label>
    <nameField>
        <displayFormat>Rate{000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event &amp; Webcasting Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Webcasting_Rates__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventWebcastingRateTest.cls
@isTest
public class EventWebcastingRateTest {
	@isTest
	public static void testDuplicates() {
	    Account testWithDuplicate = new Account();
	    testWithDuplicate.Name = 'test';
	    //testWithDuplicate.Billing_State__c = 'CO';
	    testWithDuplicate.Invoice_Types__c = 'Account Summary';
	    testWithDuplicate.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypes[0].Id;

	    Account testWithoutDuplicate = new Account();
	    testWithoutDuplicate.Name = 'test';
	    //testWithoutDuplicate.Billing_State__c = 'CO';
	    testWithoutDuplicate.Invoice_Types__c = 'Account Summary';
	    testWithoutDuplicate.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypes[0].Id;
	    insert new List<Account>{testWithDuplicate, testWithoutDuplicate};

	    delete [SELECT Id FROM Event_Webcasting_Rates__c WHERE Related_Account__c =: testWithoutDuplicate.Id];
	    //reset the trigger handler
	    EventWebcastingRateTriggerHandler.existingWebcastingRates = null;
	    Event_Webcasting_Rates__c rate1 = new Event_Webcasting_Rates__c(Related_Account__c = testWithoutDuplicate.Id);

	    Event_Webcasting_Rates__c rate2 = new Event_Webcasting_Rates__c(Related_Account__c = testWithDuplicate.Id);

	    Database.insert(new List<Event_Webcasting_Rates__c>{rate1, rate2}, false);

	    System.assert([SELECT Id FROM Event_Webcasting_Rates__c].size() == 2);
	}
}