force-app/main/default/objects/Account/fields/NetSuite_Pull__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Pull__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Pull</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Celigo_Sync_Helper__c.field-meta.xml
<CustomField>
    <fullName>Celigo_Sync_Helper__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Celigo Sync Helper</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NS_Sync__c.field-meta.xml
<CustomField>
    <fullName>NS_Sync__c</fullName>
    <label>NetSuite Sync</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_to_NetSuite__c.field-meta.xml
<CustomField>
    <fullName>Send_to_NetSuite__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send to NetSuite</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CeligoSyncPoller.cls
public with sharing abstract class CeligoSyncPoller {
	
	private Boolean showLoader = true;
    private Boolean showError = false;
    
    public abstract String getMessage();
    public abstract String getErrorMessage();
    
    public Boolean getShowLoader(){
		return showLoader;
	}
	public void setShowLoader(Boolean showLoader){
		this.showLoader = showLoader;
	}
	
	public Boolean getShowError(){
		return showError;
	}
	public void setShowError(Boolean showError){
		this.showError = showError;
	}
    
	public PageReference redirect(String recordId){
		PageReference ref = new PageReference('/'+recordId);
		ref.setRedirect(true);
		return ref;
	}
	
	public Opportunity getOpportunityById(String id){
        return [
            select Id, Celigo_Sync_Helper__c, Send_to_NetSuite__c, NS_Sync__c
            from Opportunity
            where Id =: id
        ];
    }
    
    public Account getAccountById(String id){
        return [
            select Id, NetSuite_Pull__c
            from Account
            where Id =: id
        ];
    }
}