force-app/main/default/objects/Account/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>this are are the product they purchased and maps to product line</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Premier Edition</fullName>
            </value>
            <value>
                <fullName>Marketing Premier Edition</fullName>
            </value>
            <value>
                <fullName>SocialBridge</fullName>
            </value>
            <value>
                <fullName>Marketers</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>Team Edition</fullName>
            </value>
            <value>
                <fullName>Team Plus Edition</fullName>
            </value>
            <value>
                <fullName>Marketing Professional</fullName>
            </value>
            <value>
                <fullName>Community Edition</fullName>
            </value>
            <value>
                <fullName>Company Plan</fullName>
            </value>
            <value>
                <fullName>Free Edition</fullName>
            </value>
            <value>
                <fullName>Group Edition</fullName>
            </value>
            <value>
                <fullName>Professional Edition</fullName>
            </value>
            <value>
                <fullName>Team Plan</fullName>
            </value>
            <value>
                <fullName>Workgroup Edition</fullName>
            </value>
            <value>
                <fullName>Self Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/NegotiatedProduct__c.object-meta.xml
<CustomObject>
    <description>Configured Components under Products assigned to an Account.</description>
    <label>Negotiated Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NegotiatedProduct__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/fields/product__c.field-meta.xml
<CustomField>
    <fullName>product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RT Product</label>
    <referenceTo>RT_Product__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>Negotiated_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/account__c.field-meta.xml
<CustomField>
    <fullName>account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NegotiatedProduct.cls
public with sharing class NegotiatedProduct extends AbstractRepository {

  public final static String table = 'NegotiatedProduct__c';
  public final static String columns = 'id,name,account__c,plan__c,product__c';
  
  /**
   * Validations
   */
  public class builderValidator extends AbstractValidator {  
    
    public override void validate(SObject o) {  
      NegotiatedProduct__c np = (NegotiatedProduct__c)o;

      this.notBlank(np.name, NegotiatedProduct__c.name.getDescribe().getLabel());
    }        
  } 
  
  /**
   * Queries
   */  
  public NegotiatedProduct__c getById(Id npId) {
    String columnsWithRelations = columns+relationBuilder('product__r', Product.columns)+relationBuilder('plan__r', Plan.columns)+',product__r.schedule__r.Name, product__r.schedule__r.scheduleType__c, account__r.id, account__r.parentID';
    return (NegotiatedProduct__c) Database.query(selectBuilder(table,columnsWithRelations,'where id = :npId limit 1'));
  }

  public List<NegotiatedProduct__c> getByPlanId(Id planId){
    List<NegotiatedProduct__c> negotiatedProducts = (List<NegotiatedProduct__c>) Database.query(selectBuilder(table,columns,'where plan__c =: planId'));
    return negotiatedProducts;
  }
  
  /**
   * Helper for save
   */
  public NegotiatedProduct__c saveNegotiatedProduct(String name, Id productId, Id planId, Id accountId) {
    NegotiatedProduct__c np = (NegotiatedProduct__c) new NegotiatedProduct.builderValidator()
      .forObject(new NegotiatedProduct__c())
      .set('name', name)
      .set('product__c', productId)
      .set('plan__c', planId)
      .set('account__c', accountId)
      .buildAndValidate()
      .save();
    return np;
  }    
}