force-app/main/default/objects/Account/fields/Provisioning_Email_Template_Override__c.field-meta.xml
<CustomField>
    <fullName>Provisioning_Email_Template_Override__c</fullName>
    <description>Override Provisioning Email Template name. Select &quot;None&quot; if you want the standard rules to be used</description>
    <inlineHelpText>None to use standard email template rules, or select to OVERRIDE</inlineHelpText>
    <label>Provisioning Email Template Override</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Provisioning: BBS</fullName>
                <default>true</default>
                <label>Provisioning: BBS</label>
            </value>
            <value>
                <fullName>Provisioning: Dominion Email</fullName>
            </value>
            <value>
                <fullName>Provisioning: Partner Email</fullName>
            </value>
            <value>
                <fullName>Provisioning: BBS Audio Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/PlanAssignment__c.object-meta.xml
<CustomObject>
    <description>Assigned Products related to Access Codes.</description>
    <label>Plan Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>Plan_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/RTEvent__c.object-meta.xml
<CustomObject>
    <description>Primary ReadyTalk Events record.</description>
    <label>RT Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTEvent__c/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipName>R00N50000001bJrhEAE</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Coordinator_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Coordinator_Notes_New__c</fullName>
    <label>Coordinator Notes - New</label>
    <length>62487</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Event_Manager_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager_Notes_New__c</fullName>
    <label>Event Manager Notes - New</label>
    <length>62487</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <description>This field should be removed as soon as possible so it doesn&apos;t confuse people.</description>
    <label>Access Code Old Field</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Coordinator_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Coordinator_Notes_New__c</fullName>
    <label>Coordinator Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Event_Manager_Notes_New__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager_Notes_New__c</fullName>
    <label>Event Manager Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SubscriptionActions.cls
public class SubscriptionActions {

  /**
  * Update plan assignments when a Subscription__c record is updated.
  */
  public static void updatePlanAssignments(Map<Id, Subscription__c> newSubsMap, Map<Id, Subscription__c> oldSubsMap){
    //Perform 1 SOQL query that retrieves PlanAssignments for every Subscription__c in newsubs
    Set<Id> newSubIds = newSubsMap.keySet();
    PlanAssignment planAssignmentRepository = new PlanAssignment();
    List<PlanAssignment__c> planAssignments = planAssignmentRepository.getWhereSObjectIdInSet(newSubIds);

    //Update all of the planAssignments
    Database.update(planAssignments);
  }

  /**
  * Update all related RTEvent Coordinator_Notes_New__c and Event_Manager_Notes_New__c when a Subscription__c record is updates
  */
  public static void updateRTEventNotes(Map<Id, Subscription__c> newSubsMap, Map<Id, Subscription__c> oldSubsMap){
    Set<Id> newSubIds = newSubsMap.keySet();

    if(newSubIds.size() > 0){
      //Get all of the RTEvent__c objects under this subscription(s)
      List<RTEvent__c> events = (List<RTEvent__c>) [select Coordinator_Notes_New__c, Event_Manager_Notes_New__c, Access_Code__c from RTEvent__c where Access_Code__c in :newSubIds];
      
      //Modify the values
      for(RTEvent__c event : events){
        event.Coordinator_Notes_New__c = newSubsMap.get(event.Access_Code__c).Coordinator_Notes_New__c;
        event.Event_Manager_Notes_New__c = newSubsMap.get(event.Access_Code__c).Event_Manager_Notes_New__c;
      }

      //Update all of the events
      Database.update(events);
    }
  }

  /**
  * Determines whether or not subscriptions need to get a provisioning email
  */
  public static boolean sendProvisioningEmailIfNeeded(Subscription__c newSub, Subscription__c oldSub) {
    if(ProvisioningEmailHelper.needsProvisioningEmail(newSub, oldSub)) {
      Contact contact = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), newSub.Contact__c, ',Account.Id');
      Account acct = (Account) RTDatabaseUtils.getEntireSObject(new Account(), contact.Account.Id);
      
      String templateDevName = 'Provisioning_BBS';
      if(acct.Provisioning_Email_Template_Override__c != null) {
        EmailTemplate template = [SELECT Id, DeveloperName from EmailTemplate where Name = :acct.Provisioning_Email_Template_Override__c];
        if(template != null) {
          templateDevName = template.DeveloperName;
        } else {
          newSub.addError('Invalid Provisioning Email Template specified for Account.');
        }
      }
    
      return ProvisioningEmailHelper.sendProvisioningEmail(newSub, templateDevName);
    } else {
      return false;
    }
  }  
}