force-app/main/default/objects/Account/fields/Send_Provisioning_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Provisioning_Email__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Email sent to user with account information (toll free number, toll number, access code, passcode) and links to RT website to download V-Card, print details or order a wallet card.</inlineHelpText>
    <label>Send Provisioning Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/FoxDen_User__c.object-meta.xml
<CustomObject>
    <description>A similar object to access code, but for FoxDen.</description>
    <label>FoxDen User</label>
    <nameField>
        <label>FoxDen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxDen Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FoxDen Users</relationshipLabel>
    <relationshipName>FoxDen_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/PasswordChangeTicket__c.field-meta.xml
<CustomField>
    <fullName>PasswordChangeTicket__c</fullName>
    <description>Initial change password link generated on complete</description>
    <inlineHelpText>Initial change password link (expires)</inlineHelpText>
    <label>PasswordChangeTicket</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/ProvisioningEmailSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisioningEmailSent__c</fullName>
    <label>Provisioning Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/S3User__c/S3User__c.object-meta.xml
<CustomObject>
    <label>Replay User</label>
    <nameField>
        <label>Replay User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replay Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S3User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Replay Users</relationshipLabel>
    <relationshipName>Replay_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/PasswordChangeTicket__c.field-meta.xml
<CustomField>
    <fullName>PasswordChangeTicket__c</fullName>
    <description>Password Change Ticket request result from Auth0</description>
    <label>PasswordChangeTicket</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/ProvisioningEmailSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisioningEmailSent__c</fullName>
    <label>Provisioning Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Add_l_Provisioning_Email_Addresses__c.field-meta.xml
<CustomField>
    <fullName>Add_l_Provisioning_Email_Addresses__c</fullName>
    <inlineHelpText>Separate add&#39;l email addresses with a semi-colon, comma or hard return.</inlineHelpText>
    <label>Add&#39;l Provisioning Email Addresses</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Add_l_Provisioning_Emails__c.field-meta.xml
<CustomField>
    <fullName>Add_l_Provisioning_Emails__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Also send a provisioning email to additional recipients listed below (regardless of &quot;Send Provisioning Email&quot; checkbox)</description>
    <label>Send Copy of Provisioning Emails</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ProvisioningEmailSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisioningEmailSent__c</fullName>
    <description>Date and time a provisioning email was sent</description>
    <inlineHelpText>Date a provisioning email was sent.</inlineHelpText>
    <label>Provisioning Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Send_Provisioning_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Provisioning_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If checked, chairperson will receive a provisioning email (audio/web access information) upon activation.</inlineHelpText>
    <label>Send Provisioning Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>If &quot;Active,&quot; indicates that the access code is activated on audio and web systems.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>SendProvisioningEmail</fullName>
            </value>
            <value>
                <fullName>BillingDeleteError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Subscription_Email__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Email__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Subscription Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <description>When subscription is provisioned, it is of this record type</description>
    <label>Active</label>
</RecordType>

force-app/main/default/classes/ProvisioningEmailHelper.cls
public with sharing class ProvisioningEmailHelper {

  // if the AC is Active and a provisioning email hasn't been sent before, and Send Prov email checkbox is selected, 
  // then we need to send an email
  public static boolean needsProvisioningEmail(Subscription__c newVersion, Subscription__c oldVersion) {
    if (newVersion.Status__c == 'Active' 
      && (newVersion.Send_Provisioning_Email__c || newVersion.Add_l_Provisioning_Emails__c)
      && newVersion.ProvisioningEmailSent__c == null) {
        return true;
    }
    return false;
  }

  // Should abstract this later...
  public static boolean needsFoxDenProvisioningEmail(FoxDen_User__c newVersion, FoxDen_User__c oldVersion) {
    if(newVersion.Status__c == 'Active' && newVersion.ProvisioningEmailSent__c == null && newVersion.Password__c != null) {
      return true;
    }
    return false;
  }  

  // Should abstract this later...
  public static boolean needsS3ProvisioningEmail(S3User__c newVersion, S3User__c oldVersion) {
    if(newVersion.Status__c == 'Active' && newVersion.ProvisioningEmailSent__c == null && newVersion.Password__c != null && newVersion.PasswordChangeTicket__c != null) {
      return true;
    }
    return false;
  }    

  // Should abstract this later...
  public static boolean sendFoxDenProvisioningEmail(FoxDen_User__c foxDenUser, String templateUniqueName) {
    Contact contact = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), foxDenUser.Contact__c, ',Account.Id');
    Messaging.reserveSingleEmailCapacity(1);
    EmailTemplate template = [SELECT id from EmailTemplate where developerName = :templateUniqueName];
    Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
    msg.setTemplateId(template.Id);
    msg.setTargetObjectId(contact.Id);
    msg.setSenderDisplayName('FoxDen');
    msg.setWhatId(foxDenUser.Id);
    msg.setUseSignature(true);
    msg.setReplyTo('support@foxden.io');
    msg.setSaveAsActivity(true);
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] {msg}, true);
    return true;
  }

    // Should abstract this later...
  public static boolean sendS3ProvisioningEmail(S3User__c s3User, String templateUniqueName) {
    Contact contact = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), s3User.Contact__c, ',Account.Id');
    Messaging.reserveSingleEmailCapacity(1);
    EmailTemplate template = [SELECT id from EmailTemplate where developerName = :templateUniqueName];
    Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
    msg.setTemplateId(template.Id);
    msg.setTargetObjectId(contact.Id);
    msg.setSenderDisplayName('ReadyTalk Illuminate');
    msg.setWhatId(s3User.Id);
    msg.setUseSignature(true);
    msg.setReplyTo('support@readytalk.com');
    msg.setSaveAsActivity(true);
    Messaging.sendEmail(new Messaging.SingleEmailMessage[] {msg}, true);
    return true;
  }

  public static boolean sendProvisioningEmail(Subscription__c subscription, String templateUniqueName) {
    Contact contact = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), subscription.Contact__c, ',Account.Id');

    Messaging.reserveSingleEmailCapacity(1);
    
    EmailTemplate template = [SELECT id from EmailTemplate where developerName = :templateUniqueName];
    System.debug('Sending provisioning email template: ' + template.Id);
  
    List<String> addlEmails = new List<String>();
    if (subscription.Add_l_Provisioning_Emails__c) {
      addlEmails = splitAdditionalEmailAddresses(subscription.Add_l_Provisioning_Email_Addresses__c);
    }
    String currentContactEmail = null;
    Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();
    msg.setTemplateId(template.Id);
    msg.setTargetObjectId(contact.Id);
    // msg.setSenderDisplayName('ReadyTalk Provisioning');
    msg.setOrgWideEmailAddressId('0D21B000000L0pu');
    msg.setWhatId(subscription.Id);
    msg.setUseSignature(true);
    msg.setReplyTo('provisioning@readytalk.com');
    msg.setSaveAsActivity(true);
    try {
      if (subscription.Send_Provisioning_Email__c) {
        if (!subscription.Subscription_Email__c.equals(contact.Email.trim())) {
          if(addlEmails.size() > 0)
            addlEmails.add(0, subscription.Subscription_Email__c);
          else
            addlEmails.add(subscription.Subscription_Email__c);
        }
      } else if (addlEmails.size() > 0) {
        // Salesforce requires that we set the TargetObjectId which it uses to set the toAddress to the contact.Email
        // In the case where the sub email is different from the contact or when we are only sending addl emails,
        // we set the contact email to the first email in the list and then set it back
        currentContactEmail = contact.Email;
        String newEmail = addlEmails.remove(0);
        contact.Email = newEmail;
        Update(contact);
      }
      if (addlEmails.size() > 0) {
        msg.setToAddresses(addlEmails);
      }
    
      Messaging.sendEmail(new Messaging.SingleEmailMessage[] {msg}, true);
    } finally {
      if (currentContactEmail != null) {
        contact.Email = currentContactEmail;
        Update(contact);
      }
    }

    subscription.ProvisioningEmailSent__c = Datetime.now();

    return true;
  }

  public static String[] splitAdditionalEmailAddresses(String addresses) {
    String cleaned = addresses.normalizeSpace();
    String[] simpleSplit = cleaned.split('[;,\\s\\n\\r\\t]', -1);
    String[] cleanedSplit = new List<String>();
    for (String current : simpleSplit) {
      if (current != null && current.length()>0) {
        cleanedSplit.add(current);
      }
    }
    return cleanedSplit;
  }
}