force-app/main/default/objects/Account/fields/SFDC_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account_ID__c</fullName>
    <description>External ID to Inetgrate with TESLA System. TEsla system also host this field and will be in Synch with Salesforce.</description>
    <displayFormat>{0}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Unique Salesforce Refrerence ID and this will be refrenced in TESLA system.</inlineHelpText>
    <label>SFDC Account ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to set the relationship between Conman Contract and Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/PGi_Entity__c.field-meta.xml
<CustomField>
    <fullName>PGi_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Entity</label>
    <referenceTo>PGi_Entity__c</referenceTo>
    <relationshipLabel>PGi Contracts</relationshipLabel>
    <relationshipName>PGi_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Contracts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>PGi_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>SFDC-OPP-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>AT&amp;T SHELL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EMEA - TP Direct</fullName>
            </value>
            <value>
                <fullName>Event Center - Slide Assist</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>ON24 Forced Conv</fullName>
            </value>
            <value>
                <fullName>PGi Consolidated Billing</fullName>
            </value>
            <value>
                <fullName>PWN</fullName>
            </value>
            <value>
                <fullName>Ready Talk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SFDC_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account_ID__c</fullName>
    <formula>Account.SFDC_Account_ID__c</formula>
    <label>SFDC Account ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Company__c/fields/CorpCustSFAccountID__c.field-meta.xml
<CustomField>
    <fullName>CorpCustSFAccountID__c</fullName>
    <label>CorpCust SF Account ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/DirectSFOpptyID__c.field-meta.xml
<CustomField>
    <fullName>DirectSFOpptyID__c</fullName>
    <label>CorpCust SF Oppty ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/PGi_Entity__c.field-meta.xml
<CustomField>
    <fullName>PGi_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Entity</label>
    <referenceTo>PGi_Entity__c</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/PGi_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>PGi_Entity_ID__c</fullName>
    <externalId>true</externalId>
    <label>PGi Entity ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/PrimarySalesRep__c.field-meta.xml
<CustomField>
    <fullName>PrimarySalesRep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/RelatedAccount__c.field-meta.xml
<CustomField>
    <fullName>RelatedAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Companies</relationshipLabel>
    <relationshipName>PGi_Companies</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/Sales_Rep_s_Email__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_s_Email__c</fullName>
    <label>Sales Rep&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/SF_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Account_ID__c</fullName>
    <label>SF Account ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/SF_Opportunity_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Opportunity_ID__c</fullName>
    <label>SF Opportunity ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Companies (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>PGi_Companies1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Entity__c/PGi_Entity__c.object-meta.xml
<CustomObject>
    <label>PGi Entity</label>
    <nameField>
        <label>PGi Entity ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
    <label>DB Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <color>#009900</color>
                <label>NA</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
                <label>APAC</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <color>#990000</color>
                <label>LA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PgiCompanyTriggerHandler_Test.cls
/**
* @Test Class Name : PgiCompanyTriggerHandler_Test
* @Class Name : PgiCompanyTriggerHandler
*/
@isTest
private class PgiCompanyTriggerHandler_Test
{
    
    @testSetup static void setup() {    
        User Objuser = PGITestUtilities.getTestUser();
        insert Objuser;
        System.runAs(objuser) {
            Account account = PGITestUtilities.getAccountDetails();
            insert account;
            
            Account account1 = PGITestUtilities.getAccountDetails();
            account1.Ultimate_Parent_Account__c = account.Id;
            insert account1;
            
            
            
            Opportunity opportunity = PGITestUtilities.getOpportunityDetails();
            Insert opportunity;
            //Opportunity opportunity1 = PGITestUtilities.getOpportunityDetails();
            //Insert opportunity1;
            PGi_Company__c pgiComapny = PGITestUtilities.getPGiCompany(account.Id);
            pgiComapny.CorpCustSFAccountID__c = account.Id;
            pgiComapny.PGi_Entity_ID__c = 'sam';
            pgiComapny.DirectSFOpptyID__c = opportunity.Id;
            pgiComapny.RelatedAccount__c = account.Id;
            pgiComapny.Ultimate_Parent_Account__c = account1.Id;
            pgiComapny.PrimarySalesRep__c = Objuser.Id;
            //pgiComapny.SF_Opportunity_ID__c = opportunity.Id;
            insert pgiComapny;
            AccountTeamMember accountTeamMember = new AccountTeamMember();
            accountTeamMember.AccountId = account.Id;
            accountTeamMember.UserId = Objuser.Id;
            accountTeamMember.teammemberrole='Sales Engineer';
            INSERT accountTeamMember;
            System.assertEquals(pgiComapny.RelatedAccount__c, account.Id);
        }
    }
    
    @isTest static void pgiInsertWithSFDCId() 
    {  
        Account getaccount = [SELECT Id,SFDC_Account_ID__c FROM Account][0];
        Opportunity getOpportunity = [SELECT Id,Opportunity_Number__c FROM Opportunity][0];
        
        CONMAN_Contract__c pgiContract = new CONMAN_Contract__c();
        pgiContract.Opportunity__c = getOpportunity.Id;
        pgiContract.Account_Name__c = getaccount.Id;
        Insert pgiContract;
        
        System.debug('getOpportunity>>>>>>>>>> '+getOpportunity);
        PGi_Company__c pgiComapny = [SELECT Id,PGi_Entity_ID__c,SF_Account_ID__c,RelatedAccount__c FROM PGi_Company__c][0];
        pgiComapny.CorpCustSFAccountID__c = null;
        pgiComapny.SF_Account_ID__c = getaccount.SFDC_Account_ID__c;
        pgiComapny.SF_Opportunity_ID__c = getOpportunity.Opportunity_Number__c;
        pgiComapny.DirectSFOpptyID__c = null;
        pgiComapny.PGi_Entity_ID__c = '1234';
        UPDATE pgiComapny;
        //138-144
        /* PGi_Company__c pgiComapny1 = new PGi_Company__c();
pgiComapny1.SF_Account_ID__c = null;
pgiComapny1.Region__c = 'USA';
Insert pgiComapny1;*/
        
        System.assertEquals(pgiComapny.RelatedAccount__c, getaccount.Id);
    }
    
    @isTest static void pgiInsertWithREmptySFDCId() 
    {  
        //set emai9l of user with company
        User Objuser1 = PGITestUtilities.getTestUser();
        Objuser1.Email = 'cf@pgi.com';
        Objuser1.IsActive = true;
        Objuser1.Username = 'cf001@fr.com';
        INSERT Objuser1;
        System.runAs(objuser1) {
            PGi_Company__c pgiComapny = [SELECT Id,DirectSFOpptyID__c,Sales_Rep_s_Email__c,SF_Account_ID__c,RelatedAccount__c FROM PGi_Company__c][0];
            pgiComapny.SF_Account_ID__c = null;
            pgiComapny.Sales_Rep_s_Email__c = 'cf@pgi.com';
            pgiComapny.Region__c = 'USA';
            UPDATE pgiComapny;
        }
        // System.debug('Is active ...................>>>>>'+Objuser.IsActive);
    }
    @isTest static void pgiInsertWithREmptySFDCId1() 
    {
        //AccountTeamMember accountTeamMember = [Select Id,AccountId,UserId from AccountTeamMember where  teammemberrole = 'Sales Engineer'];
        //System.debug(')))))))))))))))))))))))))--------->>>>>>'+accountTeamMember);
        //AccountTeamMember accountTeamMember = PGITestUtilities.getAccountTeamMembe(getaccount.Id , Objuser1.Id);
        //insert accountTeamMember;
    }
    @isTest static void pgiInsertWithREmptySFDCId2() 
    {
        Account getaccount = [SELECT Id,SFDC_Account_ID__c FROM Account][0];
        Opportunity opportunity = new Opportunity();
        
        PGi_Company__c pgiComapny = [SELECT Id,Sales_Rep_s_Email__c,SF_Account_ID__c,RelatedAccount__c FROM PGi_Company__c][0];        
        pgiComapny.DirectSFOpptyID__c = opportunity.Id;
        UPDATE pgiComapny;   
        CONMAN_Contract__c pgiContract = new CONMAN_Contract__c();
        pgiContract.Account_Name__c = getaccount.Id;
        pgiContract.Opportunity__c = opportunity.Id;
        INSERT pgiContract;
    }
     @isTest static void pgiInsertWithREmptySFDCId3() 
     {
         PGI_Entity__c pgiEntity = new PGI_Entity__c();    
         pgiEntity.Name = 'sam';
         Insert pgiEntity;
         PGi_Company__c pgiComapny1 = [SELECT Id,PGi_Entity_ID__c,PGI_Entity__c FROM PGi_Company__c][0];
         pgiComapny1.PGi_Entity_ID__c = 'sam';
         pgiComapny1.PGi_Entity__c = pgiEntity.Id;
         UPDATE pgiComapny1;
     }
     @isTest static void pgiInsertWithREmptySFDCId4() 
     {
        /* //325
         Account getaccount = [SELECT Id,SFDC_Account_ID__c FROM Account][0];
         //getaccount.SFDC_Account_ID__c = getaccount.Id;
          UPDATE getaccount;
         PGi_Company__c pgiComapny1 = [SELECT Id,PGi_Entity_ID__c,SF_Account_ID__c FROM PGi_Company__c][0];
         pgiComapny1.SF_Account_ID__c = getaccount.Id;
         UPDATE pgiComapny1;*/
     }
}