force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileEpic__c/AgileEpic__c.object-meta.xml
<CustomObject>
    <label>Agile Epic</label>
    <nameField>
        <label>Agile Epic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agile Epics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileEpic__c/fields/EpicColor__c.field-meta.xml
<CustomField>
    <fullName>EpicColor__c</fullName>
    <label>Epic Color</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Black</fullName>
                <color>#000000</color>
                <label>Black</label>
            </value>
            <value>
                <fullName>Blue</fullName>
                <color>#0B6FCE</color>
                <label>Blue</label>
            </value>
            <value>
                <fullName>Gray</fullName>
                <color>#999999</color>
                <label>Gray</label>
            </value>
            <value>
                <fullName>Green</fullName>
                <color>#78C953</color>
                <label>Green</label>
            </value>
            <value>
                <fullName>Orange</fullName>
                <color>#FF6600</color>
                <label>Orange</label>
            </value>
            <value>
                <fullName>Pink</fullName>
                <color>#CC33CC</color>
                <label>Pink</label>
            </value>
            <value>
                <fullName>Purple</fullName>
                <color>#641CCF</color>
                <label>Purple</label>
            </value>
            <value>
                <fullName>Red</fullName>
                <color>#FF0000</color>
                <label>Red</label>
            </value>
            <value>
                <fullName>Teal</fullName>
                <color>#00CCCC</color>
                <label>Teal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/AgileSprint__c.object-meta.xml
<CustomObject>
    <label>Agile Sprint</label>
    <nameField>
        <label>Agile Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agile Sprints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgileSprint__c/fields/AssociatedGroup__c.field-meta.xml
<CustomField>
    <fullName>AssociatedGroup__c</fullName>
    <label>Associated Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BI Operations</fullName>
            </value>
            <value>
                <fullName>BP.com</fullName>
            </value>
            <value>
                <fullName>Care Systems</fullName>
            </value>
            <value>
                <fullName>Mediation</fullName>
            </value>
            <value>
                <fullName>Salesforce: CRM Ops &amp; Dev</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AgileSprint__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AssGroupToAgileStatus__mdt/AssGroupToAgileStatus__mdt.object-meta.xml
<CustomObject>
    <description>Store the AgileStatus for Particular Associated group</description>
    <label>AssGroupToAgileStatus</label>
    <pluralLabel>AssGroupToAgileStatus</pluralLabel>
</CustomObject>

force-app/main/default/objects/AssGroupToAgileStatus__mdt/fields/AgileStatus__c.field-meta.xml
<CustomField>
    <fullName>AgileStatus__c</fullName>
    <description>Store the status for particular associated group</description>
    <label>AgileStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AssGroupToAgileStatus__mdt/fields/GroupName__c.field-meta.xml
<CustomField>
    <fullName>GroupName__c</fullName>
    <description>Store the group name of the AgileSprint</description>
    <label>GroupName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AgileEpic__c.field-meta.xml
<CustomField>
    <fullName>AgileEpic__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agile Epic</label>
    <referenceTo>AgileEpic__c</referenceTo>
    <relationshipLabel>Related Cases</relationshipLabel>
    <relationshipName>Related_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/AgileSprint__c.field-meta.xml
<CustomField>
    <fullName>AgileSprint__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agile Sprint</label>
    <referenceTo>AgileSprint__c</referenceTo>
    <relationshipLabel>Related Cases</relationshipLabel>
    <relationshipName>Related_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/AgileStatus__c.field-meta.xml
<CustomField>
    <fullName>AgileStatus__c</fullName>
    <label>Agile Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>To Do</fullName>
                <default>true</default>
                <label>To Do</label>
            </value>
            <value>
                <fullName>Dev</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Peer Reviewed</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Deployed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/AgileTester__c.field-meta.xml
<CustomField>
    <fullName>AgileTester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agile Tester</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Agile_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Agent working the case.</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/GeneralDetails__c.field-meta.xml
<CustomField>
    <fullName>GeneralDetails__c</fullName>
    <label>General Details</label>
    <length>30000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/KanbanOrder__c.field-meta.xml
<CustomField>
    <fullName>KanbanOrder__c</fullName>
    <label>KanbanOrder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Precision__c.field-meta.xml
<CustomField>
    <fullName>Precision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Precision</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/kanbanActiveSprintTest.cls
@IsTest
public with sharing class kanbanActiveSprintTest {
    public kanbanActiveSprintTest() {

    }
    @TestSetup
    static void setData(){
        Account acc = new Account(Name = 'Test Account');
        insert acc;
        Contact con = new Contact(LastName = 'Test contact');
        insert con;
        AgileSprint__c agileSprit = new AgileSprint__c();
        agileSprit.Name = 'ActiveSprint';
        agileSprit.AssociatedGroup__c = 'Mediation';
        agileSprit.Status__c ='Active';
        insert agileSprit;
        Case caseObj = new Case(
                                Subject = 'Case Subject',
                                ContactId = con.ID,
                                AccountId = acc.Id,
                                Status = 'Working',
                                Precision__c = 1.0,
                                Origin = 'Phone',
                                AgileSprint__c = agileSprit.Id,
                                AgileStatus__c = 'To Do'
                            );
        insert caseObj;
        Case caseObj1 = new Case(
                                Subject = 'Case Subject',
                                ContactId = con.ID,
                                AccountId = acc.Id,
                                Status = 'Working',
                                Precision__c = 1.0,
                                Origin = 'Phone',
                                AgileSprint__c = agileSprit.Id,
                                AgileStatus__c = 'To Do'
                            );
        insert caseObj1;
        Case caseObj2 = new Case(
                                Subject = 'Case Subject',
                                ContactId = con.ID,
                                AccountId = acc.Id,
                                Status = 'Working',
                                Precision__c = 1.0,
                                Origin = 'Phone',
                                AgileSprint__c = agileSprit.Id,
                                AgileStatus__c = 'To Do'
                            );
        insert caseObj2;
    }
    @isTest
    public static void testGetActiveAgiles(){
        Test.startTest();
        String objName = 'Case';
        String[] objFields = new String[]{'Precision__c','CaseNumber','KanbanOrder__c','GeneralDetails__c','AgileStatus__c','AgileSprint__c','Assigned_To__c	','Assigned_To__r.Name','AgileTester__c','AgileTester__r.Name','AgileEpic__c','AgileEpic__r.Name','AgileEpic__r.EpicColor__c','AgileSprint__r.Name','AgileSprint__r.AssociatedGroup__c'};

        // String[] objFields ;// {"Precision__c","CaseNumber",'KanbanOrder__c','GeneralDetails__c'};//= 'AssociatedGroup__c';
        String kanbanField = 'AgileSprint__c';
        Boolean isForBackLog = true;
        String selectedGroup = 'Mediation';
        String field = 'Precision__c';
        Boolean order = true;
        kanbanActiveSprint.getActiveAgiles(objName, objFields, kanbanField, isForBackLog, selectedGroup,field,order);
        Boolean isForBackLog1 = false;
        kanbanActiveSprint.getActiveAgiles(objName, objFields, kanbanField, isForBackLog1, selectedGroup,field,false);
        System.assertEquals(1, [SELECT Id, Name 
                                FROM AgileSprint__c 
                                WHERE AssociatedGroup__c =:selectedGroup AND (Status__c = 'Not Started' OR Status__c = 'Active')
                                ORDER BY StartDate__c ASC].Size());
        Test.stopTest();
    }
    
    @isTest
    public static void testGetPickListValuesIntoList(){
        Test.startTest();
        kanbanActiveSprint.getPickListValuesIntoList('AgileSprint__c', 'AssociatedGroup__c');
        System.assertEquals(5, kanbanActiveSprint.getPickListValuesIntoList('AgileSprint__c', 'AssociatedGroup__c').Size());
        Test.stopTest();
    }
    // @isTest
    // public static void testGetallSprint(){
    //     kanbanActiveSprint.getallSprint();
    //     System.assertEquals(1, kanbanActiveSprint.getallSprint().Size());
    // }
    @isTest
    public static void testUpdateStatus(){
        Test.startTest();
        kanbanActiveSprint.updateStatus('ActiveSprint', 'Start', 'Mediation');
        kanbanActiveSprint.updateStatus('ActiveSprint', 'Complete', 'Mediation');
        kanbanActiveSprint.updateStatus('ActiveSprint', 'name', 'Mediation');
        System.assertEquals(1, [SELECT Id,Name,AssociatedGroup__c,Status__c FROM AgileSprint__c].Size());
        Test.stopTest();
    }
    @isTest
    public static void testGetAgileStatusToGroup(){
        Test.startTest();
        kanbanActiveSprint.getAgileStatusToGroup();
        System.assertEquals(5, [SELECT Id,GroupName__c,AgileStatus__c FROM AssGroupToAgileStatus__mdt].Size());
        Test.stopTest();
    }
    @isTest
    public static void testGetAgileNameToStatus(){
        Test.startTest();
        kanbanActiveSprint.getAgileNameToStatus();
        System.assertEquals(1, [SELECT Id,Name,AssociatedGroup__c,Status__c FROM AgileSprint__c].Size());
        Test.stopTest();
    }
    @isTest
    public static void testGetGroupToStatus(){
        Test.startTest();
        kanbanActiveSprint.getGroupToStatus();
        List<sObject> records = new List<sObject>();
        List<sObject> backlogCases = new List<sObject>();
        List<String> pickVals = new List<String>();
        
        // kanbanActiveSprint.kanbanWrap obj = new kanbanActiveSprint.kanbanWrap(records,pickVals,backlogCases);
        System.assertEquals(1, [SELECT Id,Name,AssociatedGroup__c,Status__c FROM AgileSprint__c WHERE  Status__c ='Active'].Size());
        Test.stopTest();
    }
    @isTest
    public static void testSetPrecision(){
        Test.startTest();
        // AgileSprint__c agileSprit = new AgileSprint__c();
        // agileSprit.Name = 'ActiveSprint';
        // agileSprit.AssociatedGroup__c = 'Mediation';
        // agileSprit.Status__c ='Active';
        // insert agileSprit;

        List<Case> caseLst = [SELECT Id, Precision__c, CaseNumber, KanbanOrder__c, GeneralDetails__c, AgileStatus__c, AgileSprint__c, Assigned_To__c, AgileTester__c, AgileEpic__c,AgileSprint__r.Name, AgileSprint__r.AssociatedGroup__c
                              FROM Case 
                              WHERE Subject = 'Case Subject'];
       
        String sprintName = '';
        // String sprintName = 'ActiveSprint';
        Id caseId = caseLst[2].Id;
        // kanbanActiveSprint.setPrecision(caseLst, '' ,caseId);
        kanbanActiveSprint.setPrecision(caseLst, sprintName, caseId,true,2);
        Case objCase = [Select Precision__c from Case where Id =:caseId];
        System.assertEquals(objCase.Precision__c, 2);
        System.assertNotEquals(objCase.Precision__c, caseLst[0].Precision__c);
        // kanbanActiveSprint.setPrecision(caseLst, sprintName, caseId);
       Test.stopTest();
    }
    @isTest
    public static void testSetPrecisionElse(){
        Test.startTest();
        AgileSprint__c agileSprit = new AgileSprint__c();
        agileSprit.Name = 'ActiveSprint';
        agileSprit.AssociatedGroup__c = 'Salesforce: CRM Ops & Dev';
        agileSprit.Status__c ='Active';
        insert agileSprit;
        List<Case> caseLst = [SELECT Id, Precision__c, CaseNumber, KanbanOrder__c, GeneralDetails__c, AgileStatus__c, AgileSprint__c, Assigned_To__c, AgileTester__c, AgileEpic__c,AgileSprint__r.Name, AgileSprint__r.AssociatedGroup__c
                              FROM Case 
                              WHERE Subject = 'Case Subject'];
        Id caseId = caseLst[0].Id;
        String sprintName = 'ActiveSprint';
        try{
            kanbanActiveSprint.setPrecision(caseLst, sprintName, caseId,true,null);
        }catch(Exception e){}
        Case objCase = [Select Precision__c from Case where Id =:caseId];
        System.assertEquals(objCase.Precision__c, 2);
        System.assertNotEquals(objCase.Precision__c, caseLst[0].Precision__c);
        
        Test.stopTest();
    }                           
    @isTest
    public static void testGetUpdateStage(){
        Test.startTest();
        Case cse = new Case();
        List<Case> caseLst = [SELECT Id, Subject,Precision__c,Status FROM Case WHERE Subject = 'Case Subject'];
        String sprintName = 'ActiveSprint';
        Id recId = caseLst[0].Id;
        String kanbanField = 'AgileSprint__c';
        String kanbanNewValue = 'ActiveSprint' ;
        Boolean isForBackLog = true;
        String groupselected = 'Mediation';
        kanbanActiveSprint.getUpdateStage(recId, kanbanField, kanbanNewValue, isForBackLog,groupselected);
        System.assertEquals('Success', kanbanActiveSprint.getUpdateStage(recId, kanbanField, kanbanNewValue, isForBackLog,groupselected));
        Test.stopTest();
    }
}