force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/Product_Engagement_Request__c.object-meta.xml
<CustomObject>
    <label>Product Engagement Request</label>
    <nameField>
        <displayFormat>PER-{0000}</displayFormat>
        <label>Product Engagement Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Engagement Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Business_Customer_Value__c.field-meta.xml
<CustomField>
    <fullName>Business_Customer_Value__c</fullName>
    <label>Customer Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Customer_Engagement_Request__c.field-meta.xml
<CustomField>
    <fullName>Customer_Engagement_Request__c</fullName>
    <label>Customer Engagement Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Specific Request</fullName>
            </value>
            <value>
                <fullName>Feature Acceleration Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Client</fullName>
            </value>
            <value>
                <fullName>Existing Client</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Key_Internal_or_External_Drivers__c.field-meta.xml
<CustomField>
    <fullName>Key_Internal_or_External_Drivers__c</fullName>
    <label>Key Internal or External Drivers</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/PGi_Product__c.field-meta.xml
<CustomField>
    <fullName>PGi_Product__c</fullName>
    <label>PGi Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audio</fullName>
            </value>
            <value>
                <fullName>BackOffice / MiddleTier</fullName>
            </value>
            <value>
                <fullName>Billing / Reporting</fullName>
            </value>
            <value>
                <fullName>Central Desktop</fullName>
            </value>
            <value>
                <fullName>Convergence</fullName>
            </value>
            <value>
                <fullName>Event Conferencing</fullName>
            </value>
            <value>
                <fullName>GlobalMeet Desktop</fullName>
            </value>
            <value>
                <fullName>GlobalMeet Mobile</fullName>
            </value>
            <value>
                <fullName>GlobalMeet Tools</fullName>
            </value>
            <value>
                <fullName>GlobalMeet Web (5.x)</fullName>
            </value>
            <value>
                <fullName>GlobalMeet Webcast</fullName>
            </value>
            <value>
                <fullName>GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Identity</fullName>
            </value>
            <value>
                <fullName>MS / Cisco / Adobe</fullName>
            </value>
            <value>
                <fullName>OnNet</fullName>
            </value>
            <value>
                <fullName>Op Assist</fullName>
            </value>
            <value>
                <fullName>Portal/Hub/Provisioning</fullName>
            </value>
            <value>
                <fullName>Production Applications</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Systems Architecture</fullName>
            </value>
            <value>
                <fullName>UCaaS</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Please_describe_in_detail_the__c.field-meta.xml
<CustomField>
    <fullName>Please_describe_in_detail_the__c</fullName>
    <inlineHelpText>Please describe in detail the description of the feature request.</inlineHelpText>
    <label>Description of Feature Request</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Product Engagement Requests</relationshipLabel>
    <relationshipName>Product_Engagement_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Engagement_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending PM Approval</fullName>
            </value>
            <value>
                <fullName>PM Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Exec. Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Closed Completed</fullName>
            </value>
            <value>
                <fullName>Closed Rejected</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
                <isActive>false</isActive>
                <label>Pending Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_ToValidateApprovals.cls
@isTest

public class Test_ToValidateApprovals{

static testMethod void tovalidateapprovals() {

Account acc1 = new Account();
        acc1.Name = 'Acc123456789';
        acc1.BillingCountryCode = 'US';
        acc1.BillingStateCode = 'CA';
        acc1.BillingStreet = 'Street1';
        acc1.BillingPostalCode = '12345';
insert acc1;

Product_Engagement_Request__c per123 = new Product_Engagement_Request__c();
per123.Customer_Type__c = 'Existing Client';
per123.Customer_Engagement_Request__c = 'Customer Specific Request';
per123.PGi_Product__c = 'imeet';
per123.Related_Account__c = acc1.id;
per123.Status__c='New';
per123.Please_describe_in_detail_the__c = 'test';
per123.Business_Customer_Value__c = 'test';
per123.Key_Internal_or_External_Drivers__c = 'test';
insert per123;

Test.StartTest();
per123.Please_describe_in_detail_the__c = 'updated';

update per123;

Test.StopTest();

}
}