force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/FoxDen_User__c.object-meta.xml
<CustomObject>
    <description>A similar object to access code, but for FoxDen.</description>
    <label>FoxDen User</label>
    <nameField>
        <label>FoxDen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxDen Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FoxDen Users</relationshipLabel>
    <relationshipName>FoxDen_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>FoxDen Email address</description>
    <inlineHelpText>This is the email address the user will use as their login for FoxDen. This must be a unique email from any other FoxDen user.</inlineHelpText>
    <label>FoxDen Username (Email)</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/ProvisioningEmailSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisioningEmailSent__c</fullName>
    <label>Provisioning Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FoxDenUserAfterInsertAfterUpdateTest.cls
@isTest//Insted Used FoxDenUserActionsTest
public class FoxDenUserAfterInsertAfterUpdateTest {
   /* @testSetup static void setup() {
        Account acc = new Account();
        acc.Name = 'testAcc';
        INSERT acc;
        Contact c = new Contact();
        c.AccountId=acc.Id;
        c.LastName = 'test Contact';
        INSERT c;
        
        FoxDen_User__c FUser = new FoxDen_User__c();
        FUser.Contact__c = c.Id;
        FUser.Email__c = 'vijay@raagvitech.com';
        FUser.Name = 'test';
        FUser.Status__c = 'Active';
        FUser.ProvisioningEmailSent__c = Date.newInstance(2019, 11, 19);
        FUser.Password__c = 'test1';
        INSERT FUser;       
    }*/
    
    /*static testMethod void testUpdate(){
        // FoxDen_User__c objFoxDenOld = [SELECT Id,Status__c,Name,Password__c,ProvisioningEmailSent__c FROM FoxDen_User__c WHERE Name ='test' LIMIT 1];
        FoxDen_User__c objFoxDenNew = [SELECT Id,Status__c,Name,Password__c,ProvisioningEmailSent__c FROM FoxDen_User__c WHERE Name ='test' LIMIT 1];
        // System.debug('objFoxDenOld>>>>'+objFoxDenOld);
        //objFoxDenNew.Status__c = 'Active';
        objFoxDenNew.ProvisioningEmailSent__c = null;
        objFoxDenNew.Password__c = 'testPassword';
        UPDATE objFoxDenNew;
    }*/
    /*static testMethod void testUpdate1(){
        // FoxDen_User__c objFoxDenOld = [SELECT Id,Status__c,Name,Password__c,ProvisioningEmailSent__c FROM FoxDen_User__c WHERE Name ='test' LIMIT 1];
        FoxDen_User__c objFoxDenNew = [SELECT Id,Status__c,Contact__c,Name,Password__c,ProvisioningEmailSent__c FROM FoxDen_User__c WHERE Name ='test' LIMIT 1];
        System.debug('The Error'+objFoxDenNew);
        objFoxDenNew.ProvisioningEmailSent__c = null;
        objFoxDenNew.Password__c = 'test1';
        UPDATE objFoxDenNew;
    }*/
}