force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Locations__c.field-meta.xml
<CustomField>
    <fullName>Locations__c</fullName>
    <label>Locations</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Test</fullName>
            </value>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Company ID.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/Locations__c.object-meta.xml
<CustomObject>
    <description>List of Company Locations</description>
    <label>Locations</label>
    <nameField>
        <label>Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Locations__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Mexico</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Norway</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>South Korea</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Current_assigned_headcount__c.field-meta.xml
<CustomField>
    <fullName>Current_assigned_headcount__c</fullName>
    <label>Current assigned headcount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Facility_Access_control_type__c.field-meta.xml
<CustomField>
    <fullName>Facility_Access_control_type__c</fullName>
    <label>Facility: Access control type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Card access - card issued by landlord/vendor</fullName>
            </value>
            <value>
                <fullName>Card access - card issued by PGi</fullName>
            </value>
            <value>
                <fullName>Escort Only</fullName>
            </value>
            <value>
                <fullName>Guard/Escort must unlock doors</fullName>
            </value>
            <value>
                <fullName>Sign for key with facility Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Facility_Entrance_has_camera__c.field-meta.xml
<CustomField>
    <fullName>Facility_Entrance_has_camera__c</fullName>
    <label>Facility: Entrance has camera?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes - monitored by personnel</fullName>
            </value>
            <value>
                <fullName>Yes - recorded only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Facility_Guard_Hours__c.field-meta.xml
<CustomField>
    <fullName>Facility_Guard_Hours__c</fullName>
    <label>Facility: Guard Hours</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 hrs/day x 365 days/yr</fullName>
            </value>
            <value>
                <fullName>Facility is not guarded</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Facility_Usage_Select_all_that_apply__c.field-meta.xml
<CustomField>
    <fullName>Facility_Usage_Select_all_that_apply__c</fullName>
    <label>Facility Usage (Select all that apply)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PCI Infrastructure</fullName>
            </value>
            <value>
                <fullName>Data Center (Unmanned)</fullName>
            </value>
            <value>
                <fullName>Audio Conference Co-Location Facility (VoIP)</fullName>
            </value>
            <value>
                <fullName>Call Center</fullName>
            </value>
            <value>
                <fullName>Office space for non-call center personnel</fullName>
            </value>
            <value>
                <fullName>Data Center (Manned)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Maximum_worker_capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_worker_capacity__c</fullName>
    <label>Maximum worker capacity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Rack_Room_Access_control_type__c.field-meta.xml
<CustomField>
    <fullName>Rack_Room_Access_control_type__c</fullName>
    <label>Rack/Room: Access control type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Card access - card issued by landlord/vendor</fullName>
            </value>
            <value>
                <fullName>Card access - card issued by PGi</fullName>
            </value>
            <value>
                <fullName>Escort only</fullName>
            </value>
            <value>
                <fullName>Guard/Escort must unlock cage, doors, and/or racks</fullName>
            </value>
            <value>
                <fullName>Sign for key with facility Security</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Rack_Room_Entrance_has_camera__c.field-meta.xml
<CustomField>
    <fullName>Rack_Room_Entrance_has_camera__c</fullName>
    <label>Rack/Room: Entrance has camera?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes - monitored by personnel</fullName>
            </value>
            <value>
                <fullName>Yes - recorded only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Locations__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Locations__c/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/PIDR__c/PIDR__c.object-meta.xml
<CustomObject>
    <label>Personal Information Data Request</label>
    <nameField>
        <displayFormat>PIDR-{00000}</displayFormat>
        <label>PIDR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Information Data Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PIDR__c/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipName>GDPR_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PIDR__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Employee_Location__r.Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
    <label>DB Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <color>#009900</color>
                <label>NA</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
                <label>APAC</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <color>#990000</color>
                <label>LA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PIDRTriggerHandlerTest.cls
@isTest(seeAllData = false)
public class PIDRTriggerHandlerTest {
    
    public static List<PIDR__c> PIDRListtoInsert;
    public static Id pidrCustomerRT = Schema.SObjectType.PIDR__c.getRecordTypeInfosByName().get('Customer Request Record Type').getRecordTypeId();
    public static Id pidrEmployeeRT = Schema.SObjectType.PIDR__c.getRecordTypeInfosByName().get('Employee Request Record Type').getRecordTypeId();
    
    @testSetup static void setup() {

        Profile p = [Select Id from Profile where Name='System Administrator'];
        User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ',
                         Email = 'test@pgi.com', 
                         Username = 'tes'+DateTime.now().getTime()+'t@pgi.com', 
                         EmailEncodingKey = 'UTF-8', 
                         Alias = 'Test', 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US',
                         EmployeeNumber='12345',
                         ProfileId = p.Id
                        ); 
        insert uu;
        System.runAs(uu){
            PGITestUtilities.disableSalesWings();
            
            List<PGi_Company__c> pgiCompanyList = new List<PGi_Company__c>{new PGI_Company__c(Name='test01', Region__c='EMEA'),
                new PGI_Company__c(Name='test02', Region__c='USA'),
                new PGI_Company__c(Name='test03', Region__c='APAC'),
                new PGI_Company__c(Name='test04', Region__c='EMEA'),
                new PGI_Company__c(Name='test05', Region__c='NA')};
                    INSERT pgiCompanyList;
            
            Locations__c empLoc = new Locations__c(City__c='abc',Country__c='xyz'   ,Current_assigned_headcount__c=2,Facility_Access_control_type__c='Escort Only',
                                                   Facility_Entrance_has_camera__c='Yes',Facility_Guard_Hours__c='24 hrs/day x 365 days/yr',Facility_Usage_Select_all_that_apply__c='Data Center (Unmanned)',
                                                   Maximum_worker_capacity__c=5,Rack_Room_Access_control_type__c='Escort only',Rack_Room_Entrance_has_camera__c='Yes - monitored by personnel',Region__c='APAC',
                                                   State_Province__c='yyyyy',Status__c='Active',Street__c='abc',Zip_Postal_Code__c='abcdef' );
            INSERT empLoc;
            PIDR__c pidr = new PIDR__c(RecordTypeId=pidrCustomerRT, Status__c='closed', PGi_Company__c=pgiCompanyList[0].Id,Data_Type__c='Account',Data_Details__c='date_02',
                                       First_Name__c='Jon', Last_Name__c='lincon', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test02@gmail.com', Phone__c='7418529635');		
            INSERT pidr;  
        }
    }
    public static void getcase(){
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            PIDR__c pidro = [SELECT Id,Status__c FROM PIDR__c WHERE Status__c ='closed'];  
            Account ac = new Account(Name='Ac1',BillingCountry='India',BillingStreet='xyz');
            insert ac;
            Contact con=new Contact(AccountId=ac.Id,LastName= 'test',FirstName='test',Phone= '9887678558',Email= 'hsk@test.com');
            insert con;
            Case caseObj1 = new Case(ContactId = con.Id,AccountId = ac.Id,Status = 'Working',Origin = 'Phone',Personal_Information_Data_Request__c=pidro.Id);
            insert caseObj1;
            Case caseObj = new Case(ContactId = con.Id,AccountId = ac.Id,Status = 'Working',Origin = 'Phone',Personal_Information_Data_Request__c=pidro.Id);
            insert caseObj; 
        }
    }
    @IsTest 
    private static void validateQueues(){
        Set<String> allQueues = new Set<String>();
        allQueues.addAll(PIDRTriggerHandler.nameToGroupforCustomersMap.keySet());
        allQueues.addAll(PIDRTriggerHandler.nameToGroupforEmployeesMap.keySet());
        allQueues.addAll(PIDRTriggerHandler.nameToGroupforCaseOwnerIdMap.keySet());
        List<QueueSObject> sObjectQueueList = [SELECT Id, Queue.Name FROM QueueSObject WHERE SobjectType = 'Case' AND Queue.Name IN: allQueues];
        for(QueueSobject q: sObjectQueueList) {
            allQueues.remove(q.Queue.Name);
        }
        System.assert(allQueues.isEmpty(), 'Missing Queue:' + allQueues);
    }
    @IsTest static void testPIDRTrigger(){
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            Locations__c location = [SELECT City__c,Status__c FROM Locations__c];
            PIDRListtoInsert = new List<PIDR__c>{
                new PIDR__c(RecordTypeId=pidrEmployeeRT, Status__c='Approved',Employee_Location__c=location.Id, 
                            First_Name__c='test_FN01', Last_Name__c='test_LN01', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test01@gmail.com'),
                    new PIDR__c(RecordTypeId=pidrEmployeeRT, Status__c='Approved', 
                                First_Name__c='test_FN02', Last_Name__c='test_LN02', Request_Type__c='Port', Employee_Status__c='Former', Phone__c='9879878529')};
                                    
                                    INSERT PIDRListtoInsert;    
        }
    }
    @isTest static void test1(){
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            //List<Group> grpcusLst =[Select Id,Name From Group Where Type='Regular'];
            //List<Group> grpCaseLst =[Select Id,Name From Group Where Type='Queue'];
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name, Region__c FROM PGi_Company__c];
            
            PIDR__c pidr = new PIDR__c(RecordTypeId=pidrCustomerRT, Status__c='Approved', PGi_Company__c=pgiCompanyList[0].Id,Data_Type__c='Account',Data_Details__c='date_02',
                                       First_Name__c='test_FN03', Last_Name__c='test_LN03', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test02@gmail.com', Phone__c='7418529635');
            
            INSERT pidr;
            Group ObjGroup =[Select Id,Name from group where Type='Queue' and Name='PGi-Case-EU-Branding&Conf Email' limit 1];
        List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: ObjGroup.Id];
        System.assertEquals(ObjGroup.Id, lstcase[0].OwnerId);
             
        }
    }
    @IsTest static void test2() {
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name, Region__c FROM PGi_Company__c];
            
            PIDRListtoInsert = new List<PIDR__c>{
                new PIDR__c(RecordTypeId=pidrCustomerRT, Status__c='Approved',PGi_Company__c=pgiCompanyList[1].Id,Data_Type__c='All',Data_Details__c='Testing', 
                            First_Name__c='test_FN04', Last_Name__c='test_LN04', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test03@gmail.com', Phone__c='9638527415'),
                    new PIDR__c(RecordTypeId=pidrEmployeeRT, Status__c='Approved',PGi_Company__c=pgiCompanyList[2].Id,Data_Type__c='All',Data_Details__c='Testing', 
                                First_Name__c='test_FN05', Last_Name__c='test_LN05', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test03@gmail.com', Phone__c='9638527415')
                    };
                        INSERT PIDRListtoInsert;
            List<String> lstGroupName = new List<String>{'PGi-Case-AP-Facilities'};
                List<Group> lstGroup = [Select Id,Name from group where Type='Queue' AND Name IN :lstGroupName];
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: lstGroup[0].Id];
            System.assertEquals(lstGroup[0].Id, lstcase[0].OwnerId);
        }   
    }
    @isTest static void test3() {
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name, Region__c FROM PGi_Company__c];
            
            PIDRListtoInsert = new List<PIDR__c>{
                new PIDR__c(RecordTypeId=pidrEmployeeRT, Status__c='Approved',PGi_Company__c=pgiCompanyList[3].Id,Data_Type__c='All',Data_Details__c='Testing', 
                            First_Name__c='test_FN06', Last_Name__c='test_LN06', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test03@gmail.com', Phone__c='9638527415'),
                    new PIDR__c(RecordTypeId=pidrEmployeeRT, Status__c='Approved',PGi_Company__c=pgiCompanyList[4].Id,Data_Type__c='All',Data_Details__c='Testing', 
                                First_Name__c='test_FN07', Last_Name__c='test_LN07', Request_Type__c='Port', Employee_Status__c='Current', Email_Address__c='test03@gmail.com', Phone__c='9638527415')};
                                    INSERT PIDRListtoInsert;
            List<String> lstGroupName = new List<String>{'PGi-Case-EU-Employee Serv','PGi-Case-EU-Facilities','PGi-Case-NA-Facilities'};
                List<Group> lstGroup = [Select Id,Name from group where Type='Queue' AND Name IN :lstGroupName]; 
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: lstGroup[0].Id];
            System.assertEquals(lstGroup[0].Id, lstcase[0].OwnerId);
            List<case> lstcase1 = [Select Id,OwnerId from Case where OwnerId =: lstGroup[1].Id];
            System.assertEquals(lstGroup[1].Id, lstcase1[0].OwnerId);  
            List<case> lstcase2 = [Select Id,OwnerId from Case where OwnerId =: lstGroup[2].Id];
            System.assertEquals(lstGroup[2].Id, lstcase2[0].OwnerId);
        }
    }
    @isTest static void testUpdate(){        
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name FROM PGi_Company__c];
            PIDR__c pidro = [SELECT Id,Status__c FROM PIDR__c WHERE Status__c ='closed'];
            pidro.RecordTypeId=pidrCustomerRT;
            pidro.PGi_Company__c=pgiCompanyList[0].Id;
            pidro.Status__c = 'Approved';       
            UPDATE pidro;    
            Group ObjGroup =[Select Id,Name from group where Type='Queue' AND Name='PGi-Case-EU-Branding&Conf Email'];
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: ObjGroup.Id];
            System.assertEquals(ObjGroup.Id, lstcase[0].OwnerId); 
        }
    }
    @isTest static void testUpdate2()
    { 
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name FROM PGi_Company__c];
            PIDR__c pidro = [SELECT Id,Status__c FROM PIDR__c WHERE Status__c ='closed'];
            pidro.RecordTypeId = pidrEmployeeRT;
            pidro.PGi_Company__c=pgiCompanyList[2].Id;
            pidro.Status__c = 'Approved';       
            UPDATE pidro;    
            Group ObjGroup =[Select Id,Name from group where Type='Queue' AND Name='PGi-Case-AP-Facilities'];
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: ObjGroup.Id];
            System.assertEquals(ObjGroup.Id, lstcase[0].OwnerId);
        }
    }
    @isTest static void testUpdate3()
    { 
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name FROM PGi_Company__c];
            PIDR__c pidro = [SELECT Id,Status__c FROM PIDR__c WHERE Status__c ='closed'];
            pidro.RecordTypeId = pidrEmployeeRT;
            pidro.PGi_Company__c = pgiCompanyList[3].Id;
            pidro.Status__c = 'Approved';       
            UPDATE pidro;   
            List<String> lstGroupName = new List<String>{'PGi-Case-EU-Employee Serv','PGi-Case-EU-Facilities'};
                List<Group> lstGroup = [Select Id,Name from group where Type='Queue' AND Name IN :lstGroupName];
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: lstGroup[0].Id];
            System.assertEquals(lstGroup[0].Id, lstcase[0].OwnerId);
            List<case> lstcase1 = [Select Id,OwnerId from Case where OwnerId =: lstGroup[1].Id];
            System.assertEquals(lstGroup[1].Id, lstcase1[0].OwnerId);
        }
    }
    @isTest static void testUpdateCaseDuplicate()
    { 
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name FROM PGi_Company__c];
            getcase();
            PIDR__c pidro = [SELECT Id,Status__c FROM PIDR__c WHERE Status__c ='closed'];
            pidro.RecordTypeId = pidrEmployeeRT;
            pidro.PGi_Company__c = pgiCompanyList[3].Id;
            pidro.Status__c = 'Approved';       
            UPDATE pidro;   
            List<String> lstGroupName = new List<String>{'PGi-Case-EU-Employee Serv','PGi-Case-EU-Facilities'};
                List<Group> lstGroup = [Select Id,Name from group where Type='Queue' AND Name IN :lstGroupName];
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: lstGroup[0].Id];
            System.assertEquals(0, lstcase.size());
            List<case> lstcase1 = [Select Id,OwnerId from Case where OwnerId =: lstGroup[1].Id];
            System.assertEquals(0, lstcase1.size());
        }
    }
    @isTest static void testUpdate4()
    { 
        User u =[SELECT Id from User Where Email = 'test@pgi.com'];
        System.runAs(u){
            List<PGi_Company__c> pgiCompanyList = [SELECT Id,Name FROM PGi_Company__c];
            PIDR__c pidro = [SELECT Id,Status__c FROM PIDR__c WHERE Status__c ='closed'];
            pidro.RecordTypeId = pidrEmployeeRT;
            pidro.PGi_Company__c = pgiCompanyList[4].Id;
            pidro.Status__c = 'Approved';       
            UPDATE pidro;     
            Group ObjGroup =[Select Id,Name from group where Type='Queue' AND Name='PGi-Case-NA-Facilities'];
            List<case> lstcase = [Select Id,OwnerId from Case where OwnerId =: ObjGroup.Id];
            System.assertEquals(ObjGroup.Id, lstcase[0].OwnerId);
        }  
    }
}