force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Product_Family_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Family_Interest__c</fullName>
    <label>Product Family Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automated Audio</fullName>
            </value>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Operator Assisted</fullName>
            </value>
            <value>
                <fullName>Skype for Business</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
            <value>
                <fullName>Unified Communications</fullName>
            </value>
            <value>
                <fullName>Webcast</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <inlineHelpText>Select what Region should have visibility to the campaign when doing a search.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Global_Contact_MQL__c.field-meta.xml
<CustomField>
    <fullName>Global_Contact_MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global Contact MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CampaignMemberTriggerHandlerTest.cls
@isTest
public class CampaignMemberTriggerHandlerTest {
@isTest
    public static void setContactMql() {
        PGITestUtilities.disableSalesWings();
        Account a3 = PGITestUtilities.createAccount(false);
        Insert a3;
        Contact c1a1 =new Contact();
        c1a1.AccountId=a3.Id;
        c1a1.LastName='opptyContact1';
        c1a1.Status__c = 'Active';
        Insert c1a1;
        Campaign camp = new Campaign();
        camp.Type='Email';
        camp.Name='Test';
        camp.CurrencyIsoCode='USD';
        camp.Product_Family_Interest__c ='Collaboration';
        camp.Region__c='APAC';
        Insert camp;
        CampaignMember newMember =new CampaignMember(ContactId = c1a1.id, status='Sent', campaignid = camp.id);
        insert newMember;
        //  System.assertEquals(true, [Select Id,Global_Contact_MQL__c from contact Where Id=:c1a1.Id].Global_Contact_MQL__c);
    }
}