force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Used to tag a contact with a particular marketing campaign.</description>
    <label>Campaign Code</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Form_Submissions__c.field-meta.xml
<CustomField>
    <fullName>Form_Submissions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Submissions</label>
    <referenceTo>Form_Submissions__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Global_Contact_MQL__c.field-meta.xml
<CustomField>
    <fullName>Global_Contact_MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global Contact MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Global_Contact_MQL_Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Global_Contact_MQL_Assignment_date__c</fullName>
    <label>Global Contact MQL Assignment date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketing_Program__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Program__c</fullName>
    <label>Marketing Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Madison Logic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NetSuite_Locked__c.field-meta.xml
<CustomField>
    <fullName>NetSuite_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NetSuite Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Form_Submissions__c/Form_Submissions__c.object-meta.xml
<CustomObject>
    <description>This is a new table that will serve as a log for all form completions. Fields will be populated through API connection.</description>
    <label>Form Submissions</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Form Submissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Submissions__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Code</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Form_Submissions__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/FoxDen_User__c.object-meta.xml
<CustomObject>
    <description>A similar object to access code, but for FoxDen.</description>
    <label>FoxDen User</label>
    <nameField>
        <label>FoxDen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxDen Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FoxDen Users</relationshipLabel>
    <relationshipName>FoxDen_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>FoxDen Email address</description>
    <inlineHelpText>This is the email address the user will use as their login for FoxDen. This must be a unique email from any other FoxDen user.</inlineHelpText>
    <label>FoxDen Username (Email)</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>If you do not see a match please go in and add a contact to the account related to this opportunity.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Won</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHandlerTest.cls
/*
* Test class for ContactTriggerHandler
*/
@isTest
public class ContactTriggerHandlerTest {
    @isTest
    public static void SystemAdminUnitTest() {
        Test.startTest();
        PGITestUtilities.disableSalesWings();
        Account a1 = PGITestUtilities.createAccount(false);
        Account a2 = PGITestUtilities.createAccount(false);        
        insert new List<Account>{a1, a2};
            
            Contact c1a1 = PGITestUtilities.createContact(a1, false);
        // c1a1.AccountId = a1.Id;
        c1a1.Campaign_Code__c = 'test123';
        c1a1.Marketing_Program__c='testasd';
        // c1a1.NetSuite_Locked__c=false;
        c1a1.NetSuite_Locked__c= true;
        c1a1.Celigo_Update__c=false;
        c1a1.RecordTypeId='0121B000001q5WXQAY';
        Contact c2a1 = PGITestUtilities.createContact(a1, false);
        c2a1.Campaign_Code__c='test123';
        c2a1.Marketing_Program__c='testasd';
        c2a1.NetSuite_Locked__c=true;
        c2a1.Celigo_Update__c=true;
        Contact c3a1 = new Contact();
        c3a1.LastName = 'Test Con';
        c3a1.Campaign_Code__c='test123';
        c3a1.Marketing_Program__c='testasd';
        c3a1.NetSuite_Locked__c=true;
        c3a1.Celigo_Update__c=true;
        insert new List<Contact>{c1a1, c2a1, c3a1};
            
            Contact contactObj=[SELECT id,Celigo_Update__c FROM Contact WHERE id=:c1a1.Id];
        System.assertEquals(false, contactObj.Celigo_Update__c);
        Test.stopTest();
        /* 	Contact testContact = new Contact();
testContact.AccountId = testAccount.Id;
testContact.FirstName = 'Test';
testContact.Campaign_Code__c='test123';
testContact.Marketing_Program__c='testasd';
testContact.LastName = 'Test';
testContact.NetSuite_Locked__c=false;
testContact.Celigo_Update__c=false;
testContact.RecordTypeId='0121B000001q5WXQAY';
insert testContact; */
        
        
    }
    @isTest
    public static void testMQLOnOpportunity() {
        Test.startTest();
        PGITestUtilities.disableSalesWings();
        Account a1 = PGITestUtilities.createAccount(false);
        Account a2 = PGITestUtilities.createAccount(false);        
        insert new List<Account>{a1, a2};
            
        Contact c1a1 = PGITestUtilities.createContact(a1, false);
        // c1a1.Form_Submissions__c = frmSubmission.Id;
        c1a1.Campaign_Code__c='test123';
        c1a1.Marketing_Program__c='testasd';
        // c1a1.NetSuite_Locked__c =true;
        c1a1.NetSuite_Locked__c=false;
        c1a1.Celigo_Update__c=false;
        c1a1.RecordTypeId='0121B000001q5WXQAY';
        Contact c2a1 = PGITestUtilities.createContact(a1, false);
        c2a1.Campaign_Code__c='test123';
        c2a1.Marketing_Program__c='testasd';
        c2a1.NetSuite_Locked__c=true;
        c2a1.Celigo_Update__c=true;
        insert new List<Contact>{c1a1, c2a1};
            
            Contact contactObj=[SELECT id,Celigo_Update__c FROM Contact WHERE id=:c1a1.Id];
        System.assertEquals(false, contactObj.Celigo_Update__c);
        Test.stopTest();
        /* 	Contact testContact = new Contact();
testContact.AccountId = testAccount.Id;
testContact.FirstName = 'Test';
testContact.Campaign_Code__c='test123';
testContact.Marketing_Program__c='testasd';
testContact.LastName = 'Test';
testContact.NetSuite_Locked__c=false;
testContact.Celigo_Update__c=false;
testContact.RecordTypeId='0121B000001q5WXQAY';
insert testContact; */
        
        
    }
    
    @isTest
    public static void testCascadeFoxDenUser() {
        Test.startTest();
        PGITestUtilities.disableSalesWings();
        Account a1 = PGITestUtilities.createAccount(false);
        Account a2 = PGITestUtilities.createAccount(false);        
        insert new List<Account>{a1, a2};
            
            Contact c1a1 = PGITestUtilities.createContact(a1, false);
        c1a1.Global_Contact_MQL__c=true;
        c1a1.Global_Contact_MQL_Assignment_date__c=System.now();
        c1a1.Status__c = 'Active';
        Contact c2a1 = PGITestUtilities.createContact(a1, false);
        c2a1.Status__c = 'Active';
        c2a1.Global_Contact_MQL__c=true;
        c2a1.Global_Contact_MQL_Assignment_date__c=System.now();
        Contact c3a2 = PGITestUtilities.createContact(a2, false);
        c3a2.Global_Contact_MQL__c=true;
        c3a2.Global_Contact_MQL_Assignment_date__c=System.now();
        Contact c4a2 = PGITestUtilities.createContact(a2, false);
        c4a2.Status__c = 'Active';
        c4a2.Global_Contact_MQL__c=true;
        c4a2.Global_Contact_MQL_Assignment_date__c=System.now();
        insert new List<Contact>{c1a1, c2a1, c3a2, c4a2};
            
            Opportunity o1a1=PGITestUtilities.createOpportunity(a1, false); 
        o1a1.CreatedDate=System.now();
        Opportunity o2a2=PGITestUtilities.createOpportunity(a2, false); 
        o2a2.CreatedDate=System.now();
        insert new List<Opportunity>{o1a1,o2a2};
            
            FoxDen_User__c fc1a1 = new FoxDen_User__c(Contact__c = c1a1.Id, Status__c = 'Active', Email__c = c1a1.Email);
        //   FoxDen_User__c fc2a1 = new FoxDen_User__c(Contact__c = c2a1.Id, Status__c = 'Active', Email__c = c2a1.Email);
        FoxDen_User__c fc3a2 = new FoxDen_User__c(Contact__c = c3a2.Id, Status__c = 'Active', Email__c = c3a2.Email);
        //  FoxDen_User__c fc4a2 = new FoxDen_User__c(Contact__c = c4a2.Id, Status__c = 'Active', Email__c = c4a2.Email);
        insert new List<FoxDen_User__c>{fc1a1,fc3a2};
            
            //    c4a2.Status__c = 'Inactive';
            //    update c4a2;
            
            //   o2a2.CloseDate=Date.today().addDays(13);
            //   update o2a2;
            
            //  FoxDen_User__c fu = [SELECT Id, Status__c FROM FoxDen_User__c WHERE Id =: fc4a2.Id];
            //  System.assertEquals(c4a2.Status__c, fu.Status__c);
            
            FoxDen_User__c fu2 = [SELECT Id, Status__c FROM FoxDen_User__c WHERE Id =: fc1a1.Id];
        System.assertEquals(c1a1.Status__c, fu2.Status__c);
        Test.stopTest();
    } 
    
    @isTest
    public static void testSetConvertedMQLOnOpportunity() {
        Test.startTest();
        PGITestUtilities.disableSalesWings();
        Account a3 = PGITestUtilities.createAccount(false);
        Account a4 = PGITestUtilities.createAccount(false);        
        insert new List<Account>{a3, a4};
            
        
      
        
        Contact c1a1 =new Contact();
        c1a1.AccountId=a3.Id;
        c1a1.LastName='opptyContact1';
        c1a1.Status__c = 'Active';
        Contact c2a1 = new Contact();
        c2a1.AccountId=a3.Id;
        c2a1.LastName='opptyContact2';
        c2a1.Status__c = 'Active';
        insert new List<Contact>{c1a1, c2a1};
        Form_Submissions__c formSub1=new Form_Submissions__c();
        formSub1.Contact_Id__c =c1a1.id;
        formSub1.Email__c='testForm@fs.com';
        Insert formSub1;   
        c2a1.Email='Test123@pgi.com';
        Update c1a1;

        // System.assertEquals(true, [Select Id,Global_Contact_MQL__c from contact Where Id=:c1a1.Id].Global_Contact_MQL__c);
        Test.stopTest();
    } 

    // @isTest
    // public static void test() {
    //     Test.startTest();
    //     Contact con = new Contact();
    //     con.LastName = 'Test Contact';
    //     con.NetSuite_Locked__c = true;
    //     Contact con1 = new Contact();
    //     con1.LastName = 'Test Contact';
    //     con1.NetSuite_Locked__c = true;
    //     insert new List<Contact>{con, con1};
    //     Test.stopTest();
    // }
}