force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Not Provisioned</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Not active</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/FoxDen_Box__c.object-meta.xml
<CustomObject>
    <description>FoxDen box includes ChromeBox, Microphone/Speaker, and Camera</description>
    <label>FoxDen Box</label>
    <nameField>
        <displayFormat>FoxDenBox-{00000}</displayFormat>
        <label>FoxDen Box Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FoxDen Boxes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_Box__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field for the account this FoxDen Box belongs to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>FoxDen Boxes</relationshipLabel>
    <relationshipName>FoxDen_Boxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Id__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Id__c</fullName>
    <description>The UUID of the beacon</description>
    <label>Beacon Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Major_Value__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Major_Value__c</fullName>
    <label>Beacon Major Value</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Beacon_Minor_Value__c.field-meta.xml
<CustomField>
    <fullName>Beacon_Minor_Value__c</fullName>
    <label>Beacon Minor Value</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Kiosk_Email__c.field-meta.xml
<CustomField>
    <fullName>Kiosk_Email__c</fullName>
    <label>Kiosk Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Kiosk Password</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/sku__c.field-meta.xml
<CustomField>
    <fullName>sku__c</fullName>
    <label>Kit ID</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FoxDen_Box__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testFoxDenBox.cls
@isTest
private class testFoxDenBox {
 
    static testMethod void testConstruct() {
        Account acc = PGITestUtilities.createAccount(true);
        // INSERT acc;
       FoxDenBox FBox = new FoxDenBox();
        FoxDen_Box__c testFoxDen = new FoxDen_Box__c();
        testFoxDen.Beacon_Minor_Value__c = 3;
        testFoxDen.Account__c = acc.Id;
        testFoxDen.Beacon_Id__c = 'test';
        testFoxDen.Beacon_Major_Value__c = 7;
        testFoxDen.Kiosk_Email__c = 'vijay@test.com';
        testFoxDen.Password__c = 'testPass';
        testFoxDen.sku__c = 'testUniqueKey';
        testFoxDen.Status__c = 'Active';
        INSERT testFoxDen;
        Id BoxId = testFoxDen.Id;
        
		//FBox.accountHasFoxDenAccountLicense(testFoxDen);
        FBox.findById(BoxId);
        FBox.getFoxDenBoxesWhereAccountIdIsNullAndActive();
        
    }    
   
}