force-app/main/default/objects/Account/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Related_Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Ultimate_Parent_Account__c</fullName>
    <formula>Account_Name__r.Ultimate_Parent_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Related Ultimate Parent Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>PGi Contracts (Ultimate Parent Account)</relationshipLabel>
    <relationshipName>PGi_Contracts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PGiContractAccountUltimateParentBatch.cls
public without sharing class PGiContractAccountUltimateParentBatch implements Database.Batchable<sObject> {
	public Database.QueryLocator start(Database.BatchableContext bc) {
    	String query = 'SELECT Id, Ultimate_Parent_Account__c, Related_Ultimate_Parent_Account__c FROM CONMAN_Contract__c';
    	return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<CONMAN_Contract__c> scope) {
        List<CONMAN_Contract__c> updatePGiContracts = new List<CONMAN_Contract__c>();
    	for(CONMAN_Contract__c pgiContract : scope) {
    		if(pgiContract.Ultimate_Parent_Account__c != null && pgiContract.Related_Ultimate_Parent_Account__c != null) {
    			if(pgiContract.Ultimate_Parent_Account__c != pgiContract.Related_Ultimate_Parent_Account__c) {
    				updatePGiContracts.add(pgiContract);
    			}
    		}
    	}
    	if(!updatePGiContracts.isEmpty()) {
    		LoggerUtil.handleSaveResults('Failed to update PGi Contract Account Ultimate Parent Batch', Database.update(updatePGiContracts, false));
    	}
        LoggerUtil.commitLogs();    
    }
    public void finish(Database.BatchableContext bc) {

    }
}