force-app/main/default/objects/Account/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Follow_Up_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Email_Address__c</fullName>
    <inlineHelpText>Separate additional email addresses with a comma.</inlineHelpText>
    <label>Follow-Up Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Corporate Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accounting/Finance</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
            <value>
                <fullName>Customer Service/Care/Support</fullName>
            </value>
            <value>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </value>
            <value>
                <fullName>HR Generalist</fullName>
            </value>
            <value>
                <fullName>HR Recruiting</fullName>
            </value>
            <value>
                <fullName>Investor Relations</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ECommerce_Convert__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Convert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ECommerce Convert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <description>this is for EMEA to use for email marketing</description>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>This object handles departments (children of accounts) so accounts will not have children accounts.</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_SLA_Management__c/Email_SLA_Management__c.object-meta.xml
<CustomObject>
    <label>Email SLA Management</label>
    <nameField>
        <displayFormat>SLA-{000000}</displayFormat>
        <label>Email SLA Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email SLA Management</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_SLA_Management__c/fields/Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Email_Template__c</fullName>
    <description>API Name of the email template used for this from address</description>
    <inlineHelpText>API Name of the email template used for this from address</inlineHelpText>
    <label>Dedicated Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ChannelType__c.field-meta.xml
<CustomField>
    <fullName>ChannelType__c</fullName>
    <inlineHelpText>Default value is Direct.  Do not change unless you work in the Partners channel.</inlineHelpText>
    <label>x-Channel Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affinity</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
                <default>true</default>
                <label>Direct</label>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>End User - Agent</fullName>
            </value>
            <value>
                <fullName>End User - Distributor</fullName>
            </value>
            <value>
                <fullName>End User - Reseller</fullName>
            </value>
            <value>
                <fullName>Marketing Alliance</fullName>
            </value>
            <value>
                <fullName>Master Agent</fullName>
            </value>
            <value>
                <fullName>Reseller</fullName>
            </value>
            <value>
                <fullName>Soundpath</fullName>
            </value>
            <value>
                <fullName>Sub Agent</fullName>
            </value>
            <value>
                <fullName>Sub-Reseller</fullName>
            </value>
            <value>
                <fullName>Tier 1</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Corporate Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>C-Level/VP/Director</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Investor Relations</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Marketing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Telecom</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>HR Generalist</fullName>
            </value>
            <value>
                <fullName>HR Recruiting</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Customer Service/Care/Support</fullName>
            </value>
            <value>
                <fullName>Accounting/Finance</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DoNotSolicit__c.field-meta.xml
<CustomField>
    <fullName>DoNotSolicit__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Ecomm: used in back office for company create</description>
    <label>DoNotSolicit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <description>used to set the preferred language for the lead</description>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Initial Product of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audio: GlobalMeet Audio</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Audio for Skype for Business</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Webcast Managed Event</fullName>
            </value>
            <value>
                <fullName>Audio: Op. Assisted: Premium Event</fullName>
            </value>
            <value>
                <fullName>Audio: Op. Assisted: Standard Auditorium</fullName>
            </value>
            <value>
                <fullName>Bundle: GlobalMeet</fullName>
            </value>
            <value>
                <fullName>Bundle: GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Web: Cisco WebEx</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Active Host</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webcast</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webcast Managed Event</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Web for Microsoft Lync</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Web: iMeet Central</fullName>
            </value>
            <value>
                <fullName>Web: UCaaS</fullName>
            </value>
            <value>
                <fullName>Web: vCube</fullName>
            </value>
            <value>
                <fullName>Web: Webcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <description>Source Value</description>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailComposerTest.cls
@isTest
public class EmailComposerTest {
    @testSetup static void methodName() {
        
        
        Profile p = [Select Id from Profile where Name='System Administrator'];
        
        User uu=new User(firstname = 'ABC', 
                         lastName = 'XYZ',
                         Email = 'test.FromTestCEmailComposer.com@pgi.com', 
                         Username = 'test.FromTestCEmailComposer567.com@pgi.com', 
                         EmailEncodingKey = 'UTF-8', 
                         Alias = 'Test', 
                         TimeZoneSidKey = 'America/Los_Angeles', 
                         LocaleSidKey = 'en_US', 
                         LanguageLocaleKey = 'en_US',
                         EmployeeNumber='12345',
                         ProfileId = p.Id,
                         IsActive =True
                        ); 
        insert uu; 
        System.runAs(uu){
        PGITestUtilities.disableSalesWings();
        Id pgi_ClientESRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('PGi_Client_External_Support').getRecordTypeId();
        Id outboundCaseRTId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Outbound_Email_Support').getRecordTypeId();
        Account accountObj= new Account();
        accountObj.Name='Test';
        Insert accountObj;
        Contact contactObj= new Contact();
        contactObj.AccountId=accountObj.Id;
        contactObj.Email='Test@eX.com';
        contactObj.LastName='Test';
        contactObj.FirstName='Testfn';
        contactObj.Language_Preference__c='EN';
        contactObj.Title='test';
        Insert contactObj;
        Email_SLA_Management__c objEmailSla = new Email_SLA_Management__c();
        objEmailSla.Origin__c='Email';
        objEmailSla.Email_Template__c='pgiTemplate';
        objEmailSla.From_Address__c='Ecampl123e@ex.com';
        Insert objEmailSla;
         Lead l    =    new Lead(
                            FirstName = 'Test',
                            LastName = 'Owner',
                            //Topic__c = 'Test',
                            Phone = '2222012011',
                            Email = 'LeadQueueOwner@pgi.com',
                            ECommerce_Account_Number__c = 'Ecom-000000001',
                            ECommerce_Convert__c = false,
                            LeadSource = 'ECommerce Customer',
                            Company = 'Pfiz I',
                            ChannelType__c = 'Direct',
                            Status = 'Qualifying',
                            Street = '1500 Main Street',
                            City = 'SanJose',
                            StateCode = 'CA',
                            PostalCode = '95802',
                            CountryCode = 'US',
                            Business_Type__c = 1,
                            DoNotSolicit__c = true,
                            Z_Source__c = 'eCommerce',
                            Department__c = 'Sales',
                            Product_Interest__c='Web: GlobalMeet'
                        );

            insert l;
        
            Case objCase = new Case(
                Subject = 'TestEmail',
                ContactId=contactObj.Id,
                Follow_Up_Email_Address__c='Ecample@ex.com',
                RecordTypeId = pgi_ClientESRTId
            );
            INSERT objCase;
            Case objCse1 = new Case(
                Subject = 'EmailTest',
                OwnerId = uu.Id,
                RecordTypeId = outboundCaseRTId
            );
            INSERT objCse1;
            Case objCase1 = new Case(
                Subject = 'TestEmail1',
                Origin='Email',
                Follow_Up_Email_Address__c='Ecample1@ex.com',
                ParentId =objCase.Id,
                ContactId=contactObj.Id,
                RecordTypeId = outboundCaseRTId
            );
            Insert objCase1;
            EmailTemplate validEmailTemplate = new EmailTemplate();
            validEmailTemplate.isActive = true;
            validEmailTemplate.Name = 'name';
            validEmailTemplate.DeveloperName = 'pgiTemplate';
            validEmailTemplate.TemplateType = 'text';
            validEmailTemplate.FolderId = uu.Id;
            validEmailTemplate.Body='Test123';
            validEmailTemplate.HtmlValue='Test456';
            insert validEmailTemplate;
            
        }
    }
    static testMethod void testforNullCase(){
        User userObj = [Select Id from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            Case caseObj = new Case();
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('inConsole', null);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();   
            
            String selectedTemplateStr =emailComposerObj.selectedTemplate;
            String ccAddressStr =emailComposerObj.ccAddress;
            ccAddressStr='test@test.com';
            String bccAddressStr =emailComposerObj.bccAddress;
            bccAddressStr='test@test1.com';
            Boolean initialized =emailComposerObj.initialized;
            System.assertEquals(true, initialized);
            String replyMailId = emailComposerObj.replyMailId;
            System.assertEquals(null, replyMailId);
            test.stopTest();
        }
    }
    static testMethod void testforPGiExternalSupport(){
        User userObj = [Select Id from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            emailSLAObj.From_Address__c='pgisfnoreply@pgi.com';
            update emailSLAObj;
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', 'Example@replyMailId.com');
            pageRef.getParameters().put('fwdMailId', 'Example@fwdMailId.com');
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer();
            emailComposerObj.init();
            
            Boolean initialized =emailComposerObj.initialized;
            System.assertEquals(false, initialized);
            case passedInFrom = emailComposerObj.passedInFrom;
            // System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            emailComposerObj.composeEmail();
            emailComposerObj.send();
            emailComposerObj.selectTemplate();
            emailComposerObj.validParent();
            //emailComposerObj.rerenderTemplate();
            List<SelectOption> statusPicklist =emailComposerObj.statusPicklist;
            EmailMessage emailMsgObj =emailComposerObj.em;
            List<SelectOption> objList =emailComposerObj.fromAddressOptions;
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            emailComposerObj.cancel();
            test.stopTest();
            
        }   
    }
    static testMethod void testForOutboundEmailSupport(){
        User userObj = [Select Id from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,Origin,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            objEmailMsg.ToAddress = 'Ecample@ex.com';
            objEmailMsg.BccAddress = 'Ecample1@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text';    
            objEmailMsg.MessageDate = datetime.now();
            insert objEmailMsg;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            
            emailComposerObj.init();
            case passedInFrom = emailComposerObj.passedInFrom;
            
            emailComposerObj.composeEmail();
            emailComposerObj.validateParentCase();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            emailComposerObj.setInConsole();
            String subject = emailComposerObj.subject;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            System.assertEquals(caseObj.Origin, passedInFrom.Origin);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testContactToIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Contact contactObj =[Select Id,Email,FirstName,LastName from contact where FirstName='Testfn'];
            contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = contactObj.Id; // user id of the sender
            emr.relationType = 'ToAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.validParent();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testContactBccIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Contact contactObj =[Select Id,Email,FirstName,LastName from contact where FirstName='Testfn'];
            contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = contactObj.Id; // user id of the sender
            emr.relationType = 'BccAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer();
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.validParent();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testContactCcIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Contact contactObj =[Select Id,Email,FirstName,LastName from contact where FirstName='Testfn'];
            contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = contactObj.Id; // user id of the sender
            emr.relationType = 'CcAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.validParent();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testUserToIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Contact contactObj =[Select Id,Email,FirstName,LastName from contact where FirstName='Testfn'];
            contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = userObj.Id; // user id of the sender
            emr.relationType = 'ToAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
                pageRef.getParameters().put('composeEmail', 'true');
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.validParent();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testUserCcIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Contact contactObj =[Select Id,Email,FirstName,LastName from contact where FirstName='Testfn'];
            contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ParentId,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = userObj.Id; // user id of the sender
            emr.relationType = 'CcAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.validParent();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
            emailComposerObj.doNothing();
        }   
    }
    static testMethod void testUserBccIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Contact contactObj =[Select Id,Email,FirstName,LastName from contact where FirstName='Testfn'];
            contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = userObj.Id; // user id of the sender
            emr.relationType = 'BccAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer();
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.validParent();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testForDiffertAddress(){
        User userObj = [Select Id from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            objEmailMsg.ToAddress = 'Ecample@ex.com';
            objEmailMsg.BccAddress = 'Ecample1@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text';    
            objEmailMsg.MessageDate = datetime.now();
            insert objEmailMsg;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            emailSLAObj.From_Address__c='Ecample1@ex.com';
            update emailSLAObj;
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            // EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            // System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
        }   
    }
    static testMethod void testCheckIfFwdMailId(){
        User userObj = [Select Id from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            objEmailMsg.ToAddress = 'Ecample@ex.com';
            objEmailMsg.BccAddress = 'Ecample1@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text';    
            objEmailMsg.MessageDate = datetime.now();
            insert objEmailMsg;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            emailSLAObj.From_Address__c='Ecample1@ex.com';
            update emailSLAObj;
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.send();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            // EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            system.debug('--emailTemplate---->'+emailComposerObj);
            // System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
        }  
    }
    static testMethod void testleadBccIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Lead leadObj =[Select Id,Email,FirstName,LastName from Lead where FirstName='Test'];
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = leadObj.Id; // user id of the sender
            emr.relationType = 'BccAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.send();
            emailComposerObj.validParent();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testleadToIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Lead leadObj =[Select Id,Email,FirstName,LastName from Lead where FirstName='Test'];
            //contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            //String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = leadObj.Id; // user id of the sender
            emr.relationType = 'ToAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.send();
            emailComposerObj.validParent();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
        }   
    }
    static testMethod void testleadccIds(){
        User userObj = [Select Id,FirstName,LastName,Email from User Where Email = 'test.FromTestCEmailComposer.com@pgi.com' LIMIT 1];
        System.runAs(userObj){
            List<Id> contactIdList=new List<Id>();
            Lead leadObj =[Select Id,Email,FirstName,LastName from Lead where FirstName='Test'];
            //contactIdList.add(contactObj.Id);
            Case caseObj=[Select Id,Subject,ContactId,Follow_Up_Email_Address__c,RecordTypeId from Case where Subject = 'TestEmail1']; 
            EmailTemplate emailTemplate = [Select Id,isActive,Name,DeveloperName,TemplateType,FolderId,Body,HtmlValue from EmailTemplate Where Name = 'name']; 
            EmailMessage objEmailMsg = new EmailMessage();
            objEmailMsg.Status='3';
            objEmailMsg.ParentId = caseObj.Id;
            objEmailMsg.Subject = 'subject';
            
            objEmailMsg.BccAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.htmlBody = 'This has body';
            objEmailMsg.TextBody = 'This has body of text'; 
            objEmailMsg.MessageDate = datetime.now();
            //String[] toIds = new String[]{contactObj.Id};
            objEmailMsg.ToAddress = 'Ecample@ex.com;test@ex.com';
            objEmailMsg.CcAddress = 'Ecample1@ex.com;test@ex.com';
            objEmailMsg.FromAddress = 'Ecampl123e@ex.com';
            insert objEmailMsg;
            EmailMessageRelation emr = new EmailMessageRelation();
            emr.emailMessageId = objEmailMsg.id;
            emr.relationId = leadObj.Id; // user id of the sender
            emr.relationType = 'CcAddress';
            insert emr;
            Email_SLA_Management__c emailSLAObj =[Select Id,Origin__c,Email_Template__c,From_Address__c from Email_SLA_Management__c where Origin__c='Email'];
            test.startTest();
            PageReference pageRef = Page.SendAnEmail;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('Id', caseObj.Id);
            pageRef.getParameters().put('inConsole', 'true');
            pageRef.getParameters().put('toAll', 'Example@taAll.com');
            pageRef.getParameters().put('replyMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('fwdMailId', String.valueOf(objEmailMsg.Id));
            pageRef.getParameters().put('selectedTemplate', String.valueOf(emailTemplate.Id));
            ApexPages.StandardController sc = new ApexPages.StandardController(caseObj);
            EmailComposer emailComposerObj = new EmailComposer(); 
            //emailComposerObj.validate();
            //emailComposerObj.passedInFrom=caseObj1;
             emailComposerObj.resetForm();
            emailComposerObj.init();
            emailComposerObj.composeEmail();
            emailComposerObj.send();
            emailComposerObj.validParent();
            Contact theContact = emailComposerObj.theContact;
            System.assertEquals(caseObj.ContactId, theContact.Id);
            case passedInFrom = emailComposerObj.passedInFrom;
            System.assertEquals(caseObj.Follow_Up_Email_Address__c, passedInFrom.Follow_Up_Email_Address__c);
            EmailTemplate theEmailTemplate =emailComposerObj.theEmailTemplate;
            System.assertEquals(emailTemplate.Id, theEmailTemplate.Id);
            test.stopTest();
           
        }   
    }

}