force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact_Toll_Free_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Toll_Free_Number__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Conference toll-free phone number assigned to this customer.</inlineHelpText>
    <label>Toll Free Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>8667401260</fullName>
                <default>true</default>
                <label>8667401260</label>
            </value>
            <value>
                <fullName>3039993333</fullName>
            </value>
            <value>
                <fullName>8772948214</fullName>
            </value>
            <value>
                <fullName>8006499919</fullName>
            </value>
            <value>
                <fullName>8008301513</fullName>
            </value>
            <value>
                <fullName>8009257671</fullName>
            </value>
            <value>
                <fullName>8663654411</fullName>
            </value>
            <value>
                <fullName>8006617007</fullName>
            </value>
            <value>
                <fullName>8006772898</fullName>
            </value>
            <value>
                <fullName>8009371839</fullName>
            </value>
            <value>
                <fullName>8553484177</fullName>
            </value>
            <value>
                <fullName>8775574194</fullName>
            </value>
            <value>
                <fullName>8554304241</fullName>
            </value>
            <value>
                <fullName>8555594243</fullName>
            </value>
            <value>
                <fullName>8772217520</fullName>
            </value>
            <value>
                <fullName>8007229903</fullName>
            </value>
            <value>
                <fullName>8553914244</fullName>
            </value>
            <value>
                <fullName>8006054285</fullName>
            </value>
            <value>
                <fullName>8553554218</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PasscodeController.cls
global with sharing class PasscodeController {  
  private static final String SYNC_PASSCODE_ENDPOINT = 'https://provision.ecovate.com/bbs-provisioning/rest/accessCode/syncPasscode';
  private final Id subscriptionId;
  private static final Subscription subscriptionRepo = new Subscription();
  
  public PasscodeController(ApexPages.StandardController controller) {
    Subscription__c s = (Subscription__c)controller.getRecord();    

    if(s!=null)
      this.subscriptionId = s.id;
    else
      this.subscriptionId = ApexPages.currentPage().getParameters().get('id');
  }

  /**
  * Remote action to call out to the syncPasscode endpoint
  */
  @RemoteAction
  global static Map<String, Object> getPasscode(String subscriptionId) {
    Subscription__c s = subscriptionRepo.findById(subscriptionId);

    if(s==null)
      throw new ValidationException('Inavlid Access Code');

    Http h = new Http();
    HttpRequest req = new HttpRequest();
    req.setEndpoint(SYNC_PASSCODE_ENDPOINT+'?tf='+s.Contact_Toll_Free_Number__c+'&ac='+s.Name);
    req.setMethod('GET'); 

    HttpResponse res = h.send(req);
    return (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
  }
      
  public Id getSubscriptionId() {
    return this.subscriptionId;
  }
    
}