force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Audio_subscription_size__c.field-meta.xml
<CustomField>
    <fullName>Audio_subscription_size__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Indicates the number of audio ports available for this access code during an audio conference.</inlineHelpText>
    <label>Number of Audio Ports</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>50</fullName>
            </value>
            <value>
                <fullName>100</fullName>
            </value>
            <value>
                <fullName>150</fullName>
                <default>true</default>
                <label>150</label>
            </value>
            <value>
                <fullName>300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Last_Change_Date_for_Audio_Ports__c.field-meta.xml
<CustomField>
    <fullName>Last_Change_Date_for_Audio_Ports__c</fullName>
    <label>Last Change Date for Audio Ports</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Last_Number_of_Audio_Ports__c.field-meta.xml
<CustomField>
    <fullName>Last_Number_of_Audio_Ports__c</fullName>
    <label>Last Number of Audio Ports</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/ProvisioningEmailSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisioningEmailSent__c</fullName>
    <description>Date and time a provisioning email was sent</description>
    <inlineHelpText>Date a provisioning email was sent.</inlineHelpText>
    <label>Provisioning Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Revert_Last_Subscription_Values__c.field-meta.xml
<CustomField>
    <fullName>Revert_Last_Subscription_Values__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Revert Last Subscription Values</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubscriptionTriggerHandler.cls
public class SubscriptionTriggerHandler extends TriggerHandler {
  public SubscriptionTriggerHandler() {
    super('SubscriptionTriggerHandler');
  }
    protected override void beforeUpdate() {
        SubscriptionBeforeInsertBeforeUpdate();
        checkAudioPortChange();
    }
    protected override void afterInsert() {
        SubscriptionAfterInsertAfterUpdate();
    }
    protected override void afterUpdate() {
     	  SubscriptionAfterInsertAfterUpdate();
    }

    private void checkAudioPortChange() {
      for(Subscription__c sub: (List<Subscription__c>)Trigger.new) {
        Subscription__c oldSub = (Subscription__c)Trigger.oldMap.get(sub.Id);
        if(sub.Revert_Last_Subscription_Values__c == true) {
            sub.Revert_Last_Subscription_Values__c = false;
            sub.Audio_subscription_size__c = sub.Last_Number_of_Audio_Ports__c;
            sub.Last_Change_Date_for_Audio_Ports__c = null;
            sub.Last_Number_of_Audio_Ports__c = null;
        } else if(isChanged('Audio_subscription_size__c', sub)) {
          if(sub.Audio_subscription_size__c != sub.Last_Number_of_Audio_Ports__c) {
            sub.Last_Number_of_Audio_Ports__c = oldSub.Audio_subscription_size__c;
            sub.Last_Change_Date_for_Audio_Ports__c = System.today();
          } else {
            sub.Revert_Last_Subscription_Values__c = false;
            sub.Last_Change_Date_for_Audio_Ports__c = null;
            sub.Last_Number_of_Audio_Ports__c = null;
          }
        }
      }
    }

    private void SubscriptionBeforeInsertBeforeUpdate() {
    	Map<Id, Subscription__c> newSubsMap = (Map<Id,Subscription__c>)Trigger.newMap;
    	Map<Id, Subscription__c> oldSubsMap = (Map<Id,Subscription__c>)Trigger.oldMap;
    	Set<Id> newSubIds = newSubsMap.keySet();
    	for(Id updatedSub : newSubIds) {
      		System.debug('Checking if we should send an email... sub id ' + updatedSub);
      		try {
        		Boolean emailSent = SubscriptionActions.sendProvisioningEmailIfNeeded(newSubsMap.get(updatedSub), oldSubsMap.get(updatedSub));
        		if(emailSent) {
          			System.debug('Provisioning email sent for Suscription ' + updatedSub);
          			newSubsMap.get(updatedSub).ProvisioningEmailSent__c = Datetime.now();
        		}
      		} catch(EmailException e) {
        		for(Integer i = 0 ; i < e.getNumDml(); i++) {
          			newSubsMap.get(updatedSub).addError(' Please correct provisioning email address. ' + e.getDmlMessage(i));
        		}
        		return;

      		} catch (Exception e) {
        		newSubsMap.get(updatedSub).addError( ' ' + e.getMessage());
        		return;
      		}
    	}
    }

    private void SubscriptionAfterInsertAfterUpdate() {
    	//Update Plan Assignments after update
    	SubscriptionActions.updatePlanAssignments((Map<Id,Subscription__c>)Trigger.newMap, (Map<Id,Subscription__c>)Trigger.oldMap);
    	SubscriptionActions.updateRTEventNotes((Map<Id,Subscription__c>)Trigger.newMap, (Map<Id,Subscription__c>)Trigger.oldMap);
    }
}