force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Passcode__c.field-meta.xml
<CustomField>
    <fullName>Passcode__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>4-9 digit private passcode used by chairperson to launch and audio/web conferences.</inlineHelpText>
    <label>Passcode</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testValidateSubscriptionFields.cls
@isTest
private class testValidateSubscriptionFields {
    private static List<Subscription__c> newList;
    private static List<Subscription__c> oldList;
    
    static {
        PGITestUtilities.disableSalesWings();
        MockSubscription mock = new MockSubscription();
        mock.Promotion = '30 day free web trial';
        mock.WebSubDefaultType = 'Web Meeting';
        mock.BillingID = 123456;
        
        MockSubscription badMock = new MockSubscription();
        badMock.WebStartDate = Date.newInstance(1960, 1, 2); 
        badMock.BillingID = 123456;

        newList = new List<Subscription__c>();
        newList.add((Subscription__c) RTDatabaseUtils.getEntireSObject(new Subscription__c(), mock.getSubscription().id));
        //newList.add((Subscription__c) RTDatabaseUtils.getEntireSObject(new Subscription__c(), badMock.getSubscription().id));

        oldList = new List<Subscription__c>();
        oldList.add(MockSubscription.getNewSubscription());        
    }
    
    /*
    static testMethod void testValidateWebRateStartDate() {
        System.assert(ValidateSubscriptionFields.validateWebRateStartDate(newList, oldList) == true);
    }
    
    static testMethod void testValidateFreeTrial() {
        System.assert(ValidateSubscriptionFields.validateFreeTrial(newList, oldList) == true);
    }
    */
    
    static testMethod void testValidPasscodes(){
      String beginningPasscode = newList[0].passcode__c;
      newList[0].passcode__c = '123589';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '1221';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '0199';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '9900';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '0128';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '3789';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '1112';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '2212';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '0003';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
      newList[0].passcode__c = '0998';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == true);
 
      newList[0].passcode__c = newList[0].name.substring(4);
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = newList[0].name.substring(3);
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = newList[0].name;
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '1111';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '2222';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '3333';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '4444';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '5555';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '6666';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '7777';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '8888';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '9999';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '0000';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '0123';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '3456';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '6789';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '012345678';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '9876';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '3210';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);
      newList[0].passcode__c = '5432';
      System.assert(ValidateSubscriptionFields.validatePasscode(newList) == false);

      newList[0].passcode__c = beginningPasscode;
    }
}