force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testAccountActions.cls
@isTest
private class testAccountActions {
  static testMethod void testOnAccountOwnerChanged() {    
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
    Subscription__c s = MockSubscription.getNewSubscription();
    Contact c = (Contact) RTDataBaseUtils.getEntireSObject(new Contact(), s.contact__c);
    Account a = (Account) RTDataBaseUtils.getEntireSObject(new Account(), c.AccountId);
    a.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypes[0].Id;
    a.OwnerId = MockUser.getSoapUser().Id;
    update(a);
    System.assert(1==1);
  }

  static testMethod void testUpdateCustomFields() {
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
    Account newAccount = new Account();
    newAccount.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypes[0].Id;
    newAccount.BillingStreet = '101 Main St.';
    newAccount.BillingCity = 'Denver';
    newAccount.BillingCountry = 'USA';
    newAccount.BillingState = 'Colorado';
    newAccount.BillingPostalCode = '80202';
    

    Account[] newObj = new List<Account>();
    newObj.add(newAccount);

    Account oldAccount = new Account();
    oldAccount.RecordTypeId = ReadyTalkRecordTypeHelper.readyTalkAccountRecordTypes[0].Id;
    oldAccount.BillingStreet = '101 Main St.';
    oldAccount.BillingCity = 'Denver';
    oldAccount.BillingCountry = 'USA';
    oldAccount.BillingState = 'Colorado';
    oldAccount.BillingPostalCode = '80202';


    Account[] oldObj = new List<Account>();
    oldObj.add(oldAccount);

    AccountActions.syncAddressFields(newObj, oldObj);

    //System.assert('United States'.equals(newObj[0].BillingCountry));
    System.assert('Denver'.equals(newObj[0].BillingCity));
    System.assert('101 Main St.'.equals(newObj[0].BillingStreet));
    System.assert('Colorado'.equals(newObj[0].BillingState));
    System.assert('80202'.equals(newObj[0].BillingPostalCode));

  }
}