force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Parent_Ind_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Ind_ID__c</fullName>
    <description>Billing Individual id of this subscription&#39;s contact</description>
    <label>Parent Ind ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Provision__c.field-meta.xml
<CustomField>
    <fullName>Provision__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Provision</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/testAccountCascadeSettingsController.cls
@isTest
private class testAccountCascadeSettingsController {
  private static ApexPages.StandardController controller;
  static {
    PGITestUtilities.disableSalesWings();
    Subscription__c s = MockSubscription.getNewSubscription();
    s.Provision__c = true;
    s.Parent_Ind_ID__c = 'foo';
    update s;
    Contact c = (Contact) RTDatabaseUtils.getEntireSObject(new Contact(), s.contact__c, ',Contact.Account.Id');
    Account a = (Account) RTDatabaseUtils.getEntireSObject(new Account(), c.Account.Id);
    ApexPages.currentPage().getParameters().put('id', a.Id);
    controller = new ApexPages.StandardController(a);
  }

  static testMethod void testConstruct() {
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
    AccountCascadeSettingsController a = new AccountCascadeSettingsController(controller);
    
    System.assert(a!=null);
  }
  
  static testMethod void testGetErrorMessages() {
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
    AccountCascadeSettingsController a = new AccountCascadeSettingsController(controller);
    
    System.assert(a.getErrorMessages() == null);
  }

  static testMethod void testCascade() {
 
    AccountCascadeSettingsController a = new AccountCascadeSettingsController(controller);
      a.accountCodePrompt=true;
      a.appShareAllowed=true;
      a.archivePeriod=true;
      a.autoDeleteSlides=true;
      a.conferenceControlsAllowed=true;
      a.coPresenterAllowed=true;
      a.entryAnnouncement=true;
      a.grantControlAllowed=true;
      a.internationalDialoutAllowed=true;
      a.numberOfAudioPorts=true;
      a.podcasting=true;
      a.quickstartAllowed=true;
      a.recordingAllowed=true;
      a.recordingEditingAllowed=true;
      a.securityOption=true;
      a.slidePresentationAllowed=true;
      a.videoConferencingAllowed=true;
      a.voipAllowed=true;
      a.webConfAllowed=true;
    a.cascadeSettings();
    a.cancel();
     
    System.assert(1==1);
  }
}