force-app/main/default/objects/Problem_Review_Ticket__c/Problem_Review_Ticket__c.object-meta.xml
<CustomObject>
    <label>Problem Review Ticket</label>
    <nameField>
        <displayFormat>PRT-{00000}</displayFormat>
        <label>Problem Review #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Problem Review Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Problem_Review_Ticket__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <label>Assignment Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>PGi-RFC-EU-Branding&amp;Conf Email</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Audio Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Business Intelligence (BI)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-GM Tools &amp; Integration Proj</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-GM Web Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-InfoSec</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-QA</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-QA/DEV Lab</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 2-Integrations</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Audio Applications</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Database Operations</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Network</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SaaS Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SAN Admin</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Systems Admin</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Systems Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Telco</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Voice Delivery</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Database Development</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-INTL-Corp IT</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-INTL-Tier 1-Deskside Support</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-NA-Corp IT</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-NA-Tier 1-CARE (Call Delivery)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-NA-Tier 3-Production Sys Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProblemReviewTicketTriggerHandler.cls
public class ProblemReviewTicketTriggerHandler extends TriggerHandler{
	public ProblemReviewTicketTriggerHandler() {
		super('ProblemReviewTicketTriggerHandler');
	}
    protected override void beforeInsert() {
        setOwnerFromAssignmentGroup();
    }
    protected override void beforeUpdate() {
        setOwnerFromAssignmentGroup();
    }
    private void setOwnerFromAssignmentGroup() {
		for(Problem_Review_Ticket__c rfc: (List<Problem_Review_Ticket__c>)Trigger.new) {
			if(isChanged('Assignment_Group__c', rfc) && !String.isBlank(rfc.Assignment_Group__c)) {
				if(rfcQueueByName.get(rfc.Assignment_Group__c) != null) {
					rfc.OwnerId = rfcQueueByName.get(rfc.Assignment_Group__c);
				}
			}
		}
	}

	private static Map<String, Id> rfcQueueByName {get {
		if(rfcQueueByName == null) {
			rfcQueueByName = new Map<String, Id>();
			for(QueueSobject q: [SELECT QueueId, Queue.DeveloperName, Queue.Name FROM QueueSobject WHERE SobjectType = 'Problem_Review_Ticket__c']){
				rfcQueueByName.put(q.Queue.Name, q.QueueId);
			}	
		}
		return rfcQueueByName;
	} set;}
}