force-app/main/default/objects/Implementation_Services__c/Implementation_Services__c.object-meta.xml
<CustomObject>
    <label>Implementation Services</label>
    <nameField>
        <displayFormat>IST-{000000}</displayFormat>
        <label>Implementation Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Services__c/fields/Cancelled_Notes__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Notes__c</fullName>
    <label>Cancelled Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Date_of_Stage_Off_Hold__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Stage_Off_Hold__c</fullName>
    <label>Date of Stage Off Hold</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Date_of_Stage_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Stage_On_Hold__c</fullName>
    <label>Date of Stage On Hold</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/End_Nurture__c.field-meta.xml
<CustomField>
    <fullName>End_Nurture__c</fullName>
    <label>End Nurture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Implementation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Implementation_Services_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Implementation_Stage__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Stage__c</fullName>
    <label>Implementation Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-contract</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No IS Assigned</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
                <isActive>false</isActive>
                <label>Adoption</label>
            </value>
            <value>
                <fullName>Bill Review</fullName>
                <isActive>false</isActive>
                <label>Bill Review</label>
            </value>
            <value>
                <fullName>Configuration</fullName>
                <isActive>false</isActive>
                <label>Configuration</label>
            </value>
            <value>
                <fullName>Discovery</fullName>
                <isActive>false</isActive>
                <label>Discovery</label>
            </value>
            <value>
                <fullName>Hand-off</fullName>
                <isActive>false</isActive>
                <label>Hand-off</label>
            </value>
            <value>
                <fullName>Initial Communication</fullName>
                <isActive>false</isActive>
                <label>Initial Communication</label>
            </value>
            <value>
                <fullName>Launched</fullName>
                <isActive>false</isActive>
                <label>Launched</label>
            </value>
            <value>
                <fullName>Onboarding</fullName>
                <isActive>false</isActive>
                <label>Onboarding</label>
            </value>
            <value>
                <fullName>Pilot Team</fullName>
                <isActive>false</isActive>
                <label>Pilot Team</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Implementation</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Enterprise Setup</fullName>
            </value>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>New Reseller</fullName>
            </value>
            <value>
                <fullName>Partner End Customer</fullName>
            </value>
            <value>
                <fullName>Small Projects</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/IST_Completed_Status__c.field-meta.xml
<CustomField>
    <fullName>IST_Completed_Status__c</fullName>
    <inlineHelpText>Used to track the final status of an implementation.  Please select Completed or Cancelled to completely close this implementation record.</inlineHelpText>
    <label>Implementation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No IS Assigned</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Disengaged</fullName>
            </value>
            <value>
                <fullName>On-Track</fullName>
            </value>
            <value>
                <fullName>Off-Track</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/IST_Status__c.field-meta.xml
<CustomField>
    <fullName>IST_Status__c</fullName>
    <label>Implementation Stage (legacy)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-contract</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Initial Communication</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Bill Review</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
            </value>
            <value>
                <fullName>Hand-off</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No IS Assigned</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Pilot Team</fullName>
            </value>
            <value>
                <fullName>Launched</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/On_Hold_Notes__c.field-meta.xml
<CustomField>
    <fullName>On_Hold_Notes__c</fullName>
    <label>On-Hold Notes</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_1_Pause_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_1_Pause_Date__c</fullName>
    <label>Phase 1 (Plan) Pause Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_1_Pause_Days__c.field-meta.xml
<CustomField>
    <fullName>Phase_1_Pause_Days__c</fullName>
    <label>Phase 1 (Plan) Pause Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_1_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_1_Start_Date__c</fullName>
    <label>Phase 1 (Plan) Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_2_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_2_End_Date__c</fullName>
    <label>Phase 2 (Build) End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_2_Pause_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_2_Pause_Date__c</fullName>
    <label>Phase 2 (Build) Pause Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_2_Pause_Days__c.field-meta.xml
<CustomField>
    <fullName>Phase_2_Pause_Days__c</fullName>
    <label>Phase 2 (Build) Pause Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_2_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_2_Start_Date__c</fullName>
    <label>Phase 2 (Build) Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_3_Pause_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_3_Pause_Date__c</fullName>
    <label>Phase 3 (Train) Pause Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_3_Pause_Days__c.field-meta.xml
<CustomField>
    <fullName>Phase_3_Pause_Days__c</fullName>
    <label>Phase 3 (Train) Pause Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Phase_3_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Phase_3_Start_Date__c</fullName>
    <label>Phase 3 (Train) Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Related_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Related_Opportunity__c</fullName>
    <label>Related Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Implementation Services</relationshipLabel>
    <relationshipName>Implementation_Services</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Start_Nurture__c.field-meta.xml
<CustomField>
    <fullName>Start_Nurture__c</fullName>
    <label>Start Nurture</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Total_of_Days_on_Hold__c.field-meta.xml
<CustomField>
    <fullName>Total_of_Days_on_Hold__c</fullName>
    <label>Total # of Days on Hold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Products_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Products_of_Interest__c</fullName>
    <inlineHelpText>Prospect product interests.</inlineHelpText>
    <label>Products of Interest</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acteva Integration</fullName>
            </value>
            <value>
                <fullName>Act-on</fullName>
            </value>
            <value>
                <fullName>Eloqua Integration</fullName>
            </value>
            <value>
                <fullName>Foxden</fullName>
            </value>
            <value>
                <fullName>Google Calendar Gadget</fullName>
            </value>
            <value>
                <fullName>Hosted Voice</fullName>
            </value>
            <value>
                <fullName>Hubspot Integration</fullName>
            </value>
            <value>
                <fullName>Illuminate Replay</fullName>
            </value>
            <value>
                <fullName>International Audio</fullName>
            </value>
            <value>
                <fullName>Kapost Integration</fullName>
            </value>
            <value>
                <fullName>Managed Event Services</fullName>
            </value>
            <value>
                <fullName>Marketo Integration</fullName>
            </value>
            <value>
                <fullName>Microsoft Dynamics</fullName>
            </value>
            <value>
                <fullName>Mobile Apps</fullName>
            </value>
            <value>
                <fullName>Op-Assisted Audio</fullName>
            </value>
            <value>
                <fullName>Outlook Plug-in</fullName>
            </value>
            <value>
                <fullName>Pardot Integration</fullName>
            </value>
            <value>
                <fullName>PSTN Audio/Skype for Business</fullName>
            </value>
            <value>
                <fullName>Recording &amp; Archiving</fullName>
            </value>
            <value>
                <fullName>Reservationless Audio</fullName>
            </value>
            <value>
                <fullName>RTD</fullName>
            </value>
            <value>
                <fullName>Salesforce Integration</fullName>
            </value>
            <value>
                <fullName>Simulive</fullName>
            </value>
            <value>
                <fullName>Video Conferencing</fullName>
            </value>
            <value>
                <fullName>VoIP</fullName>
            </value>
            <value>
                <fullName>Webcasting</fullName>
            </value>
            <value>
                <fullName>Web Conferencing</fullName>
            </value>
            <value>
                <fullName>Webinar Packages</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ImplementationServiceTriggerTest.cls
@IsTest
public class ImplementationServiceTriggerTest {
    @testSetup static void methodName() {
        Account acc= new Account();
        acc.Name='TestAccountSetImplementationOwnerOnOpportunity';
        acc.BillingCountryCode = 'US';
        acc.BillingStateCode = 'AL';
        acc.BillingPostalCode = '35630';
        acc.BillingStreet = '110 abc street';
        insert acc;
        
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'test1';
        opp1.AccountId = acc.Id;
        opp1.CloseDate = system.today();
        opp1.StageName = 'Awareness';
        opp1.CurrencyIsoCode = 'USD';
        opp1.Products_of_Interest__c = 'Foxden';
        insert opp1;
        
        Product2 standardProduct = PGITestUtilities.getStdProduct();
        insert standardProduct;
        PricebookEntry standardPbe = PGITestUtilities.CreatePriceBookEntryForProduct(standardProduct);
        insert standardPbe;
        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(opp1.Id, standardPbe.Id);
        insert oli; 
    }
    @IsTest
    public static void testImplementationServiceTrigger() {
        Opportunity opp1 =[Select Id,Name,AccountId,CloseDate,StageName,CurrencyIsoCode,Products_of_Interest__c from Opportunity where Name = 'test1'];
        Implementation_Services__c ImpSer = new Implementation_Services__c();
        ImpSer.IST_Status__c='Open';
        ImpSer.Implementation_Stage__c = 'Plan';
        ImpSer.Related_Opportunity__c=opp1.id;
        ImpSer.Implementation_Type__c ='Small Business <2K MMR';      
        //ImpSer.Implementation_Owner__c = u.Id;
        insert ImpSer;
        ImpSer.Implementation_Stage__c = 'On Hold';
        ImpSer.On_Hold_Notes__c = 'On Hold';
        update ImpSer;
        ImpSer = [SELECT Id,Date_of_Stage_Off_Hold__c,Date_of_Stage_On_Hold__c FROM Implementation_Services__c];
        System.assertEquals(null, ImpSer.Date_of_Stage_Off_Hold__c);
        System.assertEquals(System.today().format(), ImpSer.Date_of_Stage_On_Hold__c.format());
        ImpSer.Implementation_Stage__c = 'Plan';
        update ImpSer;
        ImpSer = [SELECT Id,Date_of_Stage_Off_Hold__c,Total_of_Days_on_Hold__c FROM Implementation_Services__c];
        System.assertEquals(0, ImpSer.Total_of_Days_on_Hold__c);
        System.assertEquals(System.today().format(), ImpSer.Date_of_Stage_Off_Hold__c.format());
        ImpSer.Implementation_Stage__c = 'On Hold';
        update ImpSer;   
        ImpSer.Implementation_Stage__c = 'Plan';
        ImpSer.Phase_1_Start_Date__c = System.today();
        ImpSer.Phase_1_Pause_Date__c = null;
        ImpSer.Phase_1_Pause_Days__c = null;
        ImpSer.Total_of_Days_on_Hold__c = 1;
        update ImpSer;
        ImpSer.IST_Completed_Status__c = 'Cancelled';
        ImpSer.Cancelled_Notes__c = 'Cancelled';
        update ImpSer;
        ImpSer.IST_Completed_Status__c = 'Nuture';
        update ImpSer;
        ImpSer = [SELECT Id, Phase_1_Pause_Date__c, Phase_2_Pause_Date__c, Phase_3_Pause_Date__c FROM Implementation_Services__c];
        System.assertNotEquals(null, ImpSer.Phase_1_Pause_Date__c);
        System.assertNotEquals(null, ImpSer.Phase_2_Pause_Date__c);
        System.assertNotEquals(null, ImpSer.Phase_3_Pause_Date__c);
    }
    @IsTest
    public static void testImplementationServiceTrigger1() {
        Opportunity opp1 =[Select Id,Name,AccountId,CloseDate,StageName,CurrencyIsoCode,Products_of_Interest__c from Opportunity where Name = 'test1'];
        Implementation_Services__c ImpSer = new Implementation_Services__c();
        ImpSer.IST_Status__c='Open';
        ImpSer.Implementation_Stage__c = 'Plan';
        ImpSer.Related_Opportunity__c=opp1.id;
        ImpSer.Implementation_Type__c ='Small Business <2K MMR';      
        //ImpSer.Implementation_Owner__c = u.Id;
        insert ImpSer;
        ImpSer.Implementation_Stage__c = 'On Hold';
        ImpSer.On_Hold_Notes__c = 'On Hold';
        update ImpSer;
        ImpSer = [SELECT Id,Date_of_Stage_Off_Hold__c,Date_of_Stage_On_Hold__c FROM Implementation_Services__c];
        System.assertEquals(null, ImpSer.Date_of_Stage_Off_Hold__c);
        System.assertEquals(System.today().format(), ImpSer.Date_of_Stage_On_Hold__c.format());
        ImpSer.Implementation_Stage__c = 'Plan';
        ImpSer.IST_Completed_Status__c='Open';   
        ImpSer.Total_of_Days_on_Hold__c = 0;
        ImpSer.Phase_1_Start_Date__c = System.today();
        ImpSer.Phase_1_Pause_Date__c = null;
        ImpSer.Phase_1_Pause_Days__c = null;  
        update ImpSer;  
        ImpSer = [SELECT Id,Phase_1_Pause_Days__c FROM Implementation_Services__c];
        System.assertEquals(0, ImpSer.Phase_1_Pause_Days__c);
        ImpSer.Implementation_Stage__c = 'On Hold';
        update ImpSer;
        ImpSer.Implementation_Stage__c = 'Build';
        ImpSer.IST_Completed_Status__c='Open';   
        ImpSer.Total_of_Days_on_Hold__c = 0;
        ImpSer.Phase_1_Start_Date__c = null;
        ImpSer.Phase_2_Start_Date__c = System.today();
        ImpSer.Phase_2_Pause_Date__c = null;
        ImpSer.Phase_2_Pause_Days__c = null;
        update ImpSer;  
        ImpSer = [SELECT Id,Phase_2_Pause_Days__c FROM Implementation_Services__c];
        System.assertEquals(0, ImpSer.Phase_2_Pause_Days__c);
        ImpSer.Implementation_Stage__c = 'On Hold';
        update ImpSer;
        ImpSer.Implementation_Stage__c = 'Train';
        ImpSer.IST_Completed_Status__c='Open';   
        ImpSer.Total_of_Days_on_Hold__c = 0;
        ImpSer.Phase_1_Start_Date__c = null;
        ImpSer.Phase_2_Start_Date__c = null;    
        ImpSer.Phase_3_Start_Date__c = System.today();
        ImpSer.Phase_3_Pause_Days__c = null;
        ImpSer.Phase_3_Pause_Date__c = null;
        update ImpSer;  
        ImpSer = [SELECT Id,Phase_3_Pause_Days__c FROM Implementation_Services__c];
        System.assertEquals(0, ImpSer.Phase_3_Pause_Days__c);
    }
    @IsTest
    public static void istCountDown() {
        Opportunity opp1 =[Select Id,Name,AccountId,CloseDate,StageName,CurrencyIsoCode,Products_of_Interest__c from Opportunity where Name = 'test1'];
        Implementation_Services__c ImpSer = new Implementation_Services__c();
        ImpSer.IST_Status__c='Open';
        ImpSer.Implementation_Stage__c = 'Plan';
        ImpSer.IST_Completed_Status__c = 'Open';
        ImpSer.Related_Opportunity__c=opp1.id;
        ImpSer.Implementation_Type__c ='Small Business <2K MMR';      
        //ImpSer.Implementation_Owner__c = u.Id;
        insert ImpSer;
        ImpSer.IST_Completed_Status__c='Nurture';
        Update ImpSer;
        ImpSer = [SELECT Id,Start_Nurture__c FROM Implementation_Services__c];
        System.assertEquals(System.today().format(), ImpSer.Start_Nurture__c.format());	
        ImpSer.IST_Completed_Status__c='Open';
        Update ImpSer;
        ImpSer = [SELECT Id,End_Nurture__c FROM Implementation_Services__c];
        System.assertEquals(System.today().format(), ImpSer.End_Nurture__c.format());
        ImpSer.Implementation_Stage__c = 'Train';
        ImpSer.Phase_1_Start_Date__c = System.today();
        ImpSer.Phase_1_Pause_Date__c = null;   
        update ImpSer;
        ImpSer = [SELECT Id,Phase_1_Pause_Date__c FROM Implementation_Services__c];
        System.assertEquals(System.today().format(), ImpSer.Phase_1_Pause_Date__c.format());
        ImpSer.Implementation_Stage__c = 'Build';
        ImpSer.Phase_2_Start_Date__c = null;
        ImpSer.IST_Completed_Status__c = 'Open';   
        update ImpSer;
        ImpSer = [SELECT Id,Phase_2_Start_Date__c,Phase_2_End_Date__c FROM Implementation_Services__c];
        System.assertEquals(System.today().format(), ImpSer.Phase_2_Start_Date__c.format());
        System.assertEquals(Date.today().addDays(28).format(), ImpSer.Phase_2_End_Date__c.format());
        ImpSer.Implementation_Stage__c = 'Train';
        ImpSer.Phase_2_Start_Date__c = System.today();
        ImpSer.Phase_2_Pause_Date__c = null;   
        update ImpSer;
        ImpSer = [SELECT Id,Phase_2_Pause_Date__c FROM Implementation_Services__c];
        System.assertEquals(System.today().format(), ImpSer.Phase_2_Pause_Date__c.format());
        ImpSer.Implementation_Stage__c = 'Build';
        ImpSer.Phase_3_Start_Date__c = System.today();
        ImpSer.Phase_3_Pause_Date__c = null;   
        update ImpSer;
        ImpSer = [SELECT Id,Phase_3_Pause_Date__c FROM Implementation_Services__c];
        System.assertEquals(System.today().format(), ImpSer.Phase_3_Pause_Date__c.format());
        ApexPages.StandardController sc = new ApexPages.StandardController(ImpSer);	
        ISTCountdownTimer ext = new ISTCountdownTimer(sc);
        ISTCountdownTimer.refreshTimers(ImpSer.Id);
        
    }
}