force-app/main/default/objects/Implementation_Services__c/Implementation_Services__c.object-meta.xml
<CustomObject>
    <label>Implementation Services</label>
    <nameField>
        <displayFormat>IST-{000000}</displayFormat>
        <label>Implementation Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Services__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>TEXT( Implementation_Owner__r.Channel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner&#39;s Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Implementation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Implementation_Services_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Owner_Region__c</fullName>
    <formula>TEXT( Implementation_Owner__r.User_Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner&apos;s Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel from Opportunity Owner&#39;s user record</description>
    <label>Owner&#39;s Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Competitor_s__c.field-meta.xml
<CustomField>
    <fullName>Competitor_s__c</fullName>
    <label>Competitor(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>8X8</fullName>
            </value>
            <value>
                <fullName>AAPT</fullName>
            </value>
            <value>
                <fullName>Airtel</fullName>
            </value>
            <value>
                <fullName>Amacus</fullName>
            </value>
            <value>
                <fullName>Arcano</fullName>
            </value>
            <value>
                <fullName>Arkadin</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Atlassian/Jira</fullName>
            </value>
            <value>
                <fullName>Bluejeans</fullName>
                <label>BlueJeans</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>British Telecom</label>
            </value>
            <value>
                <fullName>Broadsoft</fullName>
            </value>
            <value>
                <fullName>Budget Conference</fullName>
            </value>
            <value>
                <fullName>Chorus Call</fullName>
            </value>
            <value>
                <fullName>Cisco Teams</fullName>
            </value>
            <value>
                <fullName>CommuniCloud</fullName>
            </value>
            <value>
                <fullName>DSNL</fullName>
            </value>
            <value>
                <fullName>FreeConferenceCall</fullName>
            </value>
            <value>
                <fullName>Fuze Business</fullName>
                <label>Fuze</label>
            </value>
            <value>
                <fullName>Google+ Hangout</fullName>
                <label>Google Hangouts</label>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>GoToWebinar</fullName>
            </value>
            <value>
                <fullName>Intercall (West)</fullName>
            </value>
            <value>
                <fullName>Inxpo</fullName>
            </value>
            <value>
                <fullName>Join.me</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
                <label>Level 3 (CenturyLink)</label>
            </value>
            <value>
                <fullName>Microsoft Meeting Broadcast</fullName>
            </value>
            <value>
                <fullName>Microsoft Skype for Business</fullName>
            </value>
            <value>
                <fullName>Microsoft Teams</fullName>
            </value>
            <value>
                <fullName>NASDAQ OMX</fullName>
                <label>NASDAQ (West)</label>
            </value>
            <value>
                <fullName>ON24</fullName>
                <label>On24</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Differentiating_Win_Factors__c.field-meta.xml
<CustomField>
    <fullName>Differentiating_Win_Factors__c</fullName>
    <label>Differentiating Win Factors</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_Status__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Status__c</fullName>
    <label>Forecast Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Early Stage</fullName>
            </value>
            <value>
                <fullName>Best Case</fullName>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
            <value>
                <fullName>Commit</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incumbent__c.field-meta.xml
<CustomField>
    <fullName>Incumbent__c</fullName>
    <label>Incumbent</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>8X8</fullName>
            </value>
            <value>
                <fullName>AAPT</fullName>
            </value>
            <value>
                <fullName>Airtel</fullName>
            </value>
            <value>
                <fullName>Amacus</fullName>
            </value>
            <value>
                <fullName>Arcano</fullName>
            </value>
            <value>
                <fullName>Arkadin</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Atlassian/Jira</fullName>
            </value>
            <value>
                <fullName>Avaya</fullName>
            </value>
            <value>
                <fullName>Bluejeans</fullName>
                <label>BlueJeans</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>British Telecom</label>
            </value>
            <value>
                <fullName>BudgetConference</fullName>
            </value>
            <value>
                <fullName>Chorus Call</fullName>
            </value>
            <value>
                <fullName>Cisco Teams</fullName>
            </value>
            <value>
                <fullName>CommuniCloud</fullName>
            </value>
            <value>
                <fullName>DSNL</fullName>
            </value>
            <value>
                <fullName>FreeConferenceCall</fullName>
            </value>
            <value>
                <fullName>Fuze Business</fullName>
                <label>Fuze</label>
            </value>
            <value>
                <fullName>Google+ Hangout</fullName>
                <label>Google Hangouts</label>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>GoToWebinar</fullName>
            </value>
            <value>
                <fullName>Intercall (West)</fullName>
            </value>
            <value>
                <fullName>Inxpo</fullName>
            </value>
            <value>
                <fullName>Jive</fullName>
            </value>
            <value>
                <fullName>Join.me</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
                <label>Level 3 (CenturyLink)</label>
            </value>
            <value>
                <fullName>Microsoft Meeting Broadcast</fullName>
            </value>
            <value>
                <fullName>Microsoft Skype for Business</fullName>
            </value>
            <value>
                <fullName>Microsoft Teams</fullName>
            </value>
            <value>
                <fullName>Mitel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NoISTNeeded__c.field-meta.xml
<CustomField>
    <fullName>NoISTNeeded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only IST members can see and select this field, only select it AFTER you have audited the Opportunity and find it as not needing an Implementation request.</inlineHelpText>
    <label>No IST Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Owner_Region__c</fullName>
    <label>Owner&#39;s Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Won_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Won_Reason__c</fullName>
    <label>Primary Won Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-on or Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Support Model</fullName>
            </value>
            <value>
                <fullName>Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Relationship Loyalty</fullName>
            </value>
            <value>
                <fullName>Reliability of the Service</fullName>
            </value>
            <value>
                <fullName>Reseller Only - Undisclosed</fullName>
            </value>
            <value>
                <fullName>Superior Product Functionality</fullName>
            </value>
            <value>
                <fullName>Value for Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Care - CEM</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Finance&amp;Pricing</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>IST Team</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Service &amp; Care</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Region__c.field-meta.xml
<CustomField>
    <fullName>User_Region__c</fullName>
    <label>User Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityImplementationAutomationTest.cls
@isTest
private class OpportunityImplementationAutomationTest 
{
    @testSetup static void setup() 
    {
        Profile profileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User usr = new User(LastName = 'LIVESTON', 
                            FirstName='JASON',
                            Alias = 'jliv',
                            Email = 'bellemay@pgi.com',
                            Username = 'bellemay@sfdc01.com',
                            CommunityNickname = 'bellemay',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            EmployeeNumber='12345',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            LocaleSidKey = 'en_US',
                            User_Region__c ='NA'
                           );
        Insert usr;
       User usr1 = new User(LastName = 'test Class user', 
                            FirstName='JASON',
                            Alias = 'test',
                            Email = 'testclassDeveloperUserFake@pgi.com',
                            Username = 'testclassDeveloperUserFakePgi@sfdc01.com',
                            CommunityNickname = 'ComtestPBGI',
                            ProfileId = profileId.id,
                            TimeZoneSidKey = 'GMT',
                            LanguageLocaleKey = 'en_US',
                            EmailEncodingKey = 'UTF-8',
                            EmployeeNumber='12345',
                            LocaleSidKey = 'en_US',
                            User_Region__c ='APAC',
                            Channel__c = 'APAC'
                           );
        Insert usr1;
        System.runAs(usr1) {
        RecordType recordtype =[select Id from Recordtype WHERE name ='PGi Opportunity' and sObjectType  = 'Opportunity' ];
        List<Opportunity> lstoppty = new List<Opportunity>{new Opportunity(Name = 'test' , CloseDate = system.today() , RecordTypeId = recordtype.id , Owner_Region__c = 'NA' , Stagename = 'Awareness' , Forecast_Status__c = 'Commit' , CurrencyIsoCode = 'USD' , Probability = 0 , 
                                        NoISTNeeded__c = false , Competitor_s__c ='Airtel' , Incumbent__c ='Arkadin' , Differentiating_Win_Factors__c ='abc' , Primary_Won_Reason__c ='Pricing Structure'),
            new Opportunity(Name = 'test 1',CloseDate = system.today(),Owner_Region__c ='EMEA',Stagename = 'Purchase',Forecast_Status__c='Commit',CurrencyIsoCode = 'USD',Probability = 0,Competitor_s__c ='Airtel',Incumbent__c='Arkadin',Differentiating_Win_Factors__c ='abc',Primary_Won_Reason__c ='Pricing Structure'),
            new Opportunity(Name = 'test 2',CloseDate = system.today(),Owner_Region__c ='APAC',Stagename = 'Purchase',Forecast_Status__c='Commit',CurrencyIsoCode = 'USD',Probability = 0,Competitor_s__c ='Airtel',Incumbent__c='Arkadin',Differentiating_Win_Factors__c ='abc',Primary_Won_Reason__c ='Pricing Structure')};
        Insert lstoppty; 
        }
        
    }
    public static testMethod void TestGoToOpportunityLink(){
        test.starttest(); 
        OpportunityImplementationAutomation notificationcnt = new OpportunityImplementationAutomation();
        system.assert(notificationcnt.GoToOpportunityLink()!=null);
        /*Cover wrapper code*/
        notificationcnt.ViewData();
        notificationcnt.CreateImpSerRecord();
        notificationcnt.getSortDirection();
        notificationcnt.setSortDirection('name');
        notificationcnt.setSortDirection('ASC');
        notificationcnt.GoToOpportunityLink();
        notificationcnt.NoISTNeeded();
        
        
        User u3 =[Select Id,FirstName,User_Region__c,Channel__c from User where User_Region__c ='NA' AND Email = 'bellemay@pgi.com'];
        system.runas(U3) {
            /*Cover wrapper code*/
            OpportunityImplementationAutomation notificationcnt2=new OpportunityImplementationAutomation();
            system.assert(notificationcnt2.GoToOpportunityLink()!=null);
            
            notificationcnt2.ViewData();
            for(OpportunityImplementationAutomation.oOpportunity obj : notificationcnt2.OpportunityList ){
                obj.selected = true;
            }
            notificationcnt2.CreateImpSerRecord();
            notificationcnt2.getSortDirection();
            notificationcnt2.setSortDirection('name');
        }
        List<Implementation_Services__c> objImplemServic = [Select Implementation_Owner__c,Implementation_Type__c,IST_Status__c,IST_Completed_Status__c,Related_Opportunity__c from Implementation_Services__c];
        Opportunity obj =[Select Id,Name,NoISTNeeded__c from Opportunity where Name = 'test'];
        System.assertEquals(obj.Id,  objImplemServic[0].Related_Opportunity__c);
        System.assertEquals('N/A',objImplemServic[0].Implementation_Type__c);
        System.assertEquals('No IS Assigned',objImplemServic[0].IST_Status__c);
        System.assertEquals('No IS Assigned',objImplemServic[0].IST_Completed_Status__c);
        test.stoptest();
        
    }
      public static testMethod void TestGoToOpportunityLink1(){
         OpportunityImplementationAutomation notificationcnt1 = new OpportunityImplementationAutomation();
        system.assert(notificationcnt1.GoToOpportunityLink()!=null);
        User U1 = [Select Id,User_Region__c,Channel__c from User where Email = 'testclassDeveloperUserFake@pgi.com' LIMIT 1];
        System.debug('------------->'+U1.User_Region__c);
        system.runas(U1) {
            /*Cover wrapper code*/
            
            notificationcnt1.ViewData();
            for(OpportunityImplementationAutomation.oOpportunity obj : notificationcnt1.OpportunityList ){
                obj.selected = true;
            }
            notificationcnt1.CreateImpSerRecord();
            notificationcnt1.getSortDirection();
            notificationcnt1.setSortDirection('name');
            //notificationcnt1.setSortDirection('ASC');
            //notificationcnt1.GoToOpportunityLink();
        }
    }
}