force-app/main/default/objects/Implementation_Services__c/Implementation_Services__c.object-meta.xml
<CustomObject>
    <label>Implementation Services</label>
    <nameField>
        <displayFormat>IST-{000000}</displayFormat>
        <label>Implementation Services Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementation Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Services__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>TEXT( Implementation_Owner__r.Channel__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner&#39;s Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Implementation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Implementation_Services_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Implementation_Type__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Direct Implementation</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Enterprise Setup</fullName>
            </value>
            <value>
                <fullName>New Agent</fullName>
            </value>
            <value>
                <fullName>New Reseller</fullName>
            </value>
            <value>
                <fullName>Partner End Customer</fullName>
            </value>
            <value>
                <fullName>Small Projects</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/IST_Completed_Status__c.field-meta.xml
<CustomField>
    <fullName>IST_Completed_Status__c</fullName>
    <inlineHelpText>Used to track the final status of an implementation.  Please select Completed or Cancelled to completely close this implementation record.</inlineHelpText>
    <label>Implementation Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>No IS Assigned</fullName>
            </value>
            <value>
                <fullName>Nurture</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Disengaged</fullName>
            </value>
            <value>
                <fullName>On-Track</fullName>
            </value>
            <value>
                <fullName>Off-Track</fullName>
            </value>
            <value>
                <fullName>Standby</fullName>
            </value>
            <value>
                <fullName>Unresponsive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/IST_Status__c.field-meta.xml
<CustomField>
    <fullName>IST_Status__c</fullName>
    <label>Implementation Stage (legacy)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-contract</fullName>
            </value>
            <value>
                <fullName>Discovery</fullName>
            </value>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>Build</fullName>
            </value>
            <value>
                <fullName>Initial Communication</fullName>
            </value>
            <value>
                <fullName>Train</fullName>
            </value>
            <value>
                <fullName>Bill Review</fullName>
            </value>
            <value>
                <fullName>Adoption</fullName>
            </value>
            <value>
                <fullName>Hand-off</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>No IS Assigned</fullName>
            </value>
            <value>
                <fullName>Configuration</fullName>
            </value>
            <value>
                <fullName>Pilot Team</fullName>
            </value>
            <value>
                <fullName>Launched</fullName>
            </value>
            <value>
                <fullName>Onboarding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Services__c/fields/Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Owner_Region__c</fullName>
    <formula>TEXT( Implementation_Owner__r.User_Region__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner&apos;s Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Calculated from the total of the Product TCV associated with this Opportunity (excludes uncommitted audio revenue).</description>
    <inlineHelpText>Calculated from the total of the Product TCV associated with this Opportunity (excludes uncommitted audio revenue).</inlineHelpText>
    <label>Total TCV</label>
    <summarizedField>OpportunityLineItem.Value_Over_Term__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.isReportable_Text__c</field>
        <operation>equals</operation>
        <value>Valid</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel from Opportunity Owner&#39;s user record</description>
    <label>Owner&#39;s Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/CountofISTRecords__c.field-meta.xml
<CustomField>
    <fullName>CountofISTRecords__c</fullName>
    <label>Count of IST Records</label>
    <summaryForeignKey>Implementation_Services__c.Related_Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast_Status__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Status__c</fullName>
    <label>Forecast Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Early Stage</fullName>
            </value>
            <value>
                <fullName>Best Case</fullName>
            </value>
            <value>
                <fullName>Upside</fullName>
            </value>
            <value>
                <fullName>Commit</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Implementation_Review_Request__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Review_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Select this to ask the Implementation Services team to become involved with this Opp.</inlineHelpText>
    <label>Implementation Review/Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MRR_Total__c.field-meta.xml
<CustomField>
    <fullName>MRR_Total__c</fullName>
    <formula>IF(RecordTypeId = &apos;0121B000001hgTt&apos; &amp;&amp; ISPICKVAL(MRR__c,&quot;Yes&quot;), (TPSummaryofAnnualizedProducts__c/12) + TPSummaryofNonAnnualizedProducts__c,
IF(RecordTypeId = &apos;0121B000001q5Wh&apos; &amp;&amp; NOT(ISPICKVAL(Service_Term__c, &quot;1 Time Event&quot;)), Amount/12,
IF(RecordTypeId = &apos;0121B000001q5Wi&apos; &amp;&amp; NOT(ISPICKVAL(Service_Term__c, &quot;1 Time Event&quot;)), Amount/12,
Total_MRR_Formula__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NoISTNeeded__c.field-meta.xml
<CustomField>
    <fullName>NoISTNeeded__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Only IST members can see and select this field, only select it AFTER you have audited the Opportunity and find it as not needing an Implementation request.</inlineHelpText>
    <label>No IST Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>SFDC-OPP-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Owner_Region__c.field-meta.xml
<CustomField>
    <fullName>Owner_Region__c</fullName>
    <label>Owner&#39;s Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Annual_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Annual_Value__c</fullName>
    <inlineHelpText>Calculated from the total of all Product Annual Value&apos;s associated with this opportunity.</inlineHelpText>
    <label>Total ACV</label>
    <summarizedField>OpportunityLineItem.Annual_Value__c</summarizedField>
    <summaryFilterItems>
        <field>OpportunityLineItem.isReportable_Text__c</field>
        <operation>equals</operation>
        <value>Valid</value>
    </summaryFilterItems>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_GM_IM_Licenses__c.field-meta.xml
<CustomField>
    <fullName>Total_GM_IM_Licenses__c</fullName>
    <formula>Total_GM_Licenses__c + Total_IM_Licenses__c  + 
Total_Audio_Licenses__c</formula>
    <inlineHelpText>Shows Total GM, IM and GM Audio licenses</inlineHelpText>
    <label>Total # Licenses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Care - CEM</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Finance&amp;Pricing</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>IST Team</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Service &amp; Care</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Region__c.field-meta.xml
<CustomField>
    <fullName>User_Region__c</fullName>
    <label>User Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityImplementationAutomation.cls
public with sharing class OpportunityImplementationAutomation {
    
    //public String OpportunityName { get; set; }
    //public String OpportunityID { get; set; }
    public list<Opportunity> SearchedOpportunities {get; set;}
    public List<oOpportunity> OpportunityList {get; set;}
    public Integer NumberofClosedOpportunities {get; set;}

   // public List<Implementation_Services__c> ImplementationInsertList {get;set;}
    public boolean Flag=false;
    public String OpportunityRefID;
    private String sortDirection = 'ASC';
    private String sortExp = 'name';
    private List<Opportunity> SortListOpportunity;
    private String currentUserRegion;
    private String currentUserChannel;
    private String oppChannelCanada = '%' + PGIAppConstants.USER_CHANNEL_CANADA;
    
    public static String strQueryFields='Select ' /*Count_of_Quote__c,'*/+
                                                  'owner.name,account.type,account.name,'+
                                                  'type,forecast_status__c,Total_GM_IM_Licenses__c,Opportunity_Number__c,'+
                                                  'id,Implementation_Review_Request__c,'+
                                                  'Name,AccountId,OwnerId,Owner_Region__c,'+
                                                  'Channel__c,StageName,CloseDate,Amount__c,'+
                                                  'Total_Annual_Value__c,isClosed ' + //,MRR_Total__c '+
                                                  'from Opportunity '+
                                                  'where ';

    public static String strQueryFilters = ' and NoISTNeeded__c = false and recordtype.name like \'%PGi%\' AND Owner.Name <> \'eCommerce Customer\' '
                                                    + 'AND stagename <> \'Closed Lost\' AND '+ 
                                                    +' CountofISTRecords__c=0 AND ' +
                                                  '(((stagename = \'Purchase\' OR Forecast_Status__c = \'Commit\') AND closedate >= 2018-12-31) OR '+
                                                  '(closedate >= 2018-12-31 AND stagename in (\'Closed Won\',\'Closed Won - Implementation\',\'Closed Won - Implementation Complete\'))) ';
    // **** Constructor******
    
    public OpportunityImplementationAutomation() {
        User currentUser = [Select Id, User_Region__c, Channel__c From User Where Id=:Userinfo.getUserId()];
        currentUserRegion = currentUser.User_Region__c;
        currentUserChannel = currentUser.Channel__c;
        if (currentUserRegion == 'NA')
        {
            SearchedOpportunities =Database.query( strQueryFields+'Owner_Region__c=\''+ currentUserRegion +'\''+ strQueryFilters +' limit 50');


//          
//                                    where 
//                                    recordtype.name like '%PGi%' AND Owner.Name <> 'eCommerce Customer' AND Owner_Region__c=:currentUserRegion  AND NoISTNeeded__c = False AND CountofISTRecords__c=0 AND stagename <> 'Closed Lost' AND 
//                                    (((stagename = 'Purchase' OR Forecast_Status__c = 'Commit') AND closedate >= 2018-12-31) OR
//                                     (closedate >= 2018-12-31 AND stagename in ('Closed Won','Closed Won - Implementation','Closed Won - Implementation Complete'))) LIMIT 50];
        }
        else
        {
            SearchedOpportunities =Database.query(strQueryFields +'Owner_Region__c IN (\'APAC\',\'EMEA\')'+strQueryFilters + ' limit 50');

            //NumberofClosedOpportunities = [SELECT count() FROM Opportunity WHERE isClosed = true];
        }
        Integer count = 0;
        if(SearchedOpportunities.size() >0) {
            OpportunityList = new List<oOpportunity>();
            for(Opportunity c: SearchedOpportunities ) {
                // As each Opportunity is processed we create a new oOpportunity object and add it to the OpportunityList
                OpportunityList.add(new oOpportunity(c));
                if(c.isClosed == true){
                   count += 1; 
                }
            }  Flag=true; NumberofClosedOpportunities = count;
        }
    }
    
    public String sortExpression
    {
        get
        {  //system.debug('..sortExp..'+sortExp);
         
         return sortExp;
        }
        set
        {
            //if the column is clicked on then switch between Ascending and Descending modes
            //system.debug('..value..'+value);
            if (value == sortExp)
                sortDirection = (sortDirection == 'ASC')? 'DESC' : 'ASC';
            else
                sortDirection = 'ASC';
            sortExp = value;
        }
    }  
    
    public String getSortDirection()
    {
        //if not column is selected 
        if (sortExpression == null || sortExpression == '')
            return 'ASC';
        else
            return sortDirection;
    }  
    
    public void setSortDirection(String value)
    {  
        sortDirection = value;
    } 
    
    //************ method that is called when user clicks on column to sort
    public pagereference ViewData() 
    { //build the full sort expression

        string sortFullExp = sortExpression  + ' ' + sortDirection;
        //System.debug('sortFullExp>>>>>>>> '+sortFullExp);
        string ISTEligible='yes';
        
        //if (PGIAppConstants.USER_REGIONS[1].equals(currentUserRegion))
        if(currentUserRegion == 'NA')
        {
            
            SearchedOpportunities =Database.query( strQueryFields+'Owner_Region__c=\''+ currentUserRegion +'\''+ strQueryFilters +
                                                  'order by '+ sortFullExp + ' limit 50');
        }
        else
        {
            SearchedOpportunities =Database.query(strQueryFields +'Owner_Region__c IN (\'APAC\',\'EMEA\')'+strQueryFilters+
                                                  'order by ' + sortFullExp + ' limit 50');
        }
        
        OpportunityList = new List<oOpportunity>();
        
        for(Opportunity c: SearchedOpportunities ) 
        {
            OpportunityList.add(new oOpportunity(c));
        }
        
        return null; 
    }
    
    
    // **** Opportunity Wrapper Class***
    
    public class oOpportunity {
        public Opportunity con {get; set;}
        public Boolean selected {get; set;}

        
        //This is the contructor method. When we create a new oOpportunity object we pass a Opportunity that is set to the con property. We also set the selected value to false
        public oOpportunity(Opportunity c) {
            con = c;
            selected = false;
        }
    }
    //**** Class to create a child implementation record for the selected opportunity. On click of New Automated Button
    
    
    
    public PageReference CreateImpSerRecord() {
        
        List<Opportunity> selectedOpportunitys = new List<Opportunity>();
        
        //We will cycle through our list of oOpportunitys and will check to see if the selected property is set to true, if it is we add the Opportunity to the selectedOpportunitys list
        
        if(Flag==true) {
            
            for(oOpportunity cCon:OpportunityList) {
                if(cCon.selected == true) {
                    selectedOpportunitys.add(cCon.con);
                }
            }
            
            
            // Now we have our list of selected Opportunitys and can perform any type of logic we want, sending emails, updating a field on the Opportunity, etc
            //System.debug('These are the selected Opportunitys...');
            for(Opportunity con: selectedOpportunitys) {
                //system.debug(con);
            }
            
            //system.debug('------selectedOpportunitys------'+selectedOpportunitys);  
            
            if(selectedOpportunitys.size()>0)
            {  //system.debug('### -- Got some selected records' );
             
             for(Opportunity oo: selectedOpportunitys)
             {  
                 Implementation_Services__c Imp =new Implementation_Services__c();
                 
                 //Imp.Implementation_Owner__c='005e0000001YTG5';
                 Imp.Implementation_Owner__c='005a000000AoISB';
                 Imp.Implementation_Type__c='N/A';
                 Imp.IST_Status__c=  'No IS Assigned';
                 Imp.IST_Completed_Status__c ='No IS Assigned';
                 Imp.Related_Opportunity__c=oo.id;         
                 
                 Insert Imp;
                 //ImplementationInsertList.add(Imp) ;
             }     
             
             /*  if(ImplementationInsertList.size()>0)
{   Insert ImplementationInsertList;
} */
             
            }
        }
        
        if(Flag==false  ) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Atleast one or more opportunities should be selected to perform this operation. Please select opportunities after finding some records'));
            return null;
        }
        
        if(selectedOpportunitys.size()==0) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Atleast one or more opportunities should be selected to perform this operation. Please select opportunities after finding some records'));
            return null;
        }
        PageReference ref = Page.OpportunityImplementationAutomation;
        ref.setRedirect(true);
        return ref;
        
        
    }
    // RT 122-------------------------------------------------------/
    public void NoISTNeeded(){
        
        List<Opportunity> selectedOpportunitys = new List<Opportunity>();
        
        //We will cycle through our list of oOpportunitys and will check to see if the selected property is set to true, if it is we add the Opportunity to the selectedOpportunitys list
        Set<oOpportunity> OpportunitySet = new Set<oOpportunity>();
        List<Opportunity> OpportunityUpadated = new List<Opportunity>();
        OpportunitySet.addAll(OpportunityList);
        for(oOpportunity cCon:OpportunitySet) {
            if(cCon.selected == true) {
                selectedOpportunitys.add(cCon.con);
                OpportunitySet.remove(cCon);
            }
        }
        for(Opportunity objId :selectedOpportunitys){
            
            objId.NoISTNeeded__c  = True;
            OpportunityUpadated.add(objId);
        }
        OpportunityList.clear();
        OpportunityList.addAll(OpportunitySet);
        UPDATE OpportunityUpadated;
        //system.debug('-----Updatedlist--->>>'+OpportunityUpadated);
        
        
        
    }
    
    
    
    public PageReference GoToOpportunityLink() {
        
        OpportunityRefID=System.currentPageReference().getParameters().get('OpportunityRefID');
        
        //system.debug('------OpportunityRefID------'+OpportunityRefID); 
        PageReference pageRef = new PageReference('/'+OpportunityRefID);
        
        return pageRef ;
    }
    
}