force-app/main/default/objects/Event_Webcasting_Rates__c/Event_Webcasting_Rates__c.object-meta.xml
<CustomObject>
    <label>Event &amp; Webcasting Rates</label>
    <nameField>
        <displayFormat>Rate{000000000}</displayFormat>
        <label>Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event &amp; Webcasting Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Webcasting_Rates__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <label>Related Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventWebcastingRateTriggerHandler.cls
public without sharing class EventWebcastingRateTriggerHandler extends TriggerHandler {
	public EventWebcastingRateTriggerHandler() {
		super('EventWebcastingRateTriggerHandler');
	}
	protected override void beforeInsert() {
		checkForDuplicates();
	}
	private Set<Id> accountIds = new Set<Id>();
	private void checkForDuplicates() {
		for(Event_Webcasting_Rates__c rate: existingWebcastingRates) {
			accountIds.add(rate.Related_Account__c);
		}
		for(Event_Webcasting_Rates__c rate: (List<Event_Webcasting_Rates__c>)Trigger.new) {
			if(accountIds.contains(rate.Related_Account__c)) {
				rate.addError('Only one Event Webcasting Rate record is allowed per account');
			}
		}
	}
	@TestVisible private static List<Event_Webcasting_Rates__c> existingWebcastingRates { get {
		if(existingWebcastingRates == null) {
			Set<Id> accountIds = new Set<Id>();
			for(Event_Webcasting_Rates__c rate: (List<Event_Webcasting_Rates__c>)Trigger.new) {
				if(rate.Related_Account__c != null) {
					accountIds.add(rate.Related_Account__c);
				}
			}
			existingWebcastingRates = [SELECT Id, Related_Account__c FROM Event_Webcasting_Rates__c WHERE Related_Account__c IN: accountIds];
		}
		return existingWebcastingRates;
	} set; }
}