force-app/main/default/objects/OtherChargeCredit__c/OtherChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Object to hold Other Charges and Credits</description>
    <label>Other Charge or Credit</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>OtherChargeCredit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Charges Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherChargeCredit__c/fields/AccessCode__c.field-meta.xml
<CustomField>
    <fullName>AccessCode__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Other Charges Credits</relationshipLabel>
    <relationshipName>OtherChargesCredits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>AccessCode__r.Contact__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/BilledDate__c.field-meta.xml
<CustomField>
    <fullName>BilledDate__c</fullName>
    <label>Billed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/ChargeOrCredit__c.field-meta.xml
<CustomField>
    <fullName>ChargeOrCredit__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge/(Credit) Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>(AccessCode__r.Contact__r.FirstName &amp;&quot;  &quot;&amp; AccessCode__r.Contact__r.LastName)</formula>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Event Info Only. Information will be printed on invoice.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blackberry Charge - Event Manager Assisted - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Live Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - On Demand - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Operator Assisted Live - Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Vidyard Recording -  Hosting</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Webcasting</fullName>
            </value>
            <value>
                <fullName>Charge - Audio 300 Port Capacity Upgrade</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Participants</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Closed Captioning Services</fullName>
            </value>
            <value>
                <fullName>Charge - Corporate License Subscription</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Annual Maintenance</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Set-up</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Add&apos;l Monitoring &amp; Support</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Cancellation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Communication Line</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dress Rehearsal w/ Op. Svcs.</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dry Run</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Event Call Director</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Full Event Moderation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Other</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Pre-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Re-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Transcription Services</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Webinar Set-Up &amp; Customization</fullName>
            </value>
            <value>
                <fullName>Charge - FEM Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Full Event Moderation Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/RTEventName__c.field-meta.xml
<CustomField>
    <fullName>RTEventName__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>RT Event Name</label>
    <referenceTo>RTEvent__c</referenceTo>
    <relationshipLabel>Other Charges Credits</relationshipLabel>
    <relationshipName>OtherChargesCredits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/RTEvent__c.object-meta.xml
<CustomObject>
    <description>Primary ReadyTalk Events record.</description>
    <label>RT Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTEvent__c/fields/Broadcast_Audio_Event_Duration2__c.field-meta.xml
<CustomField>
    <fullName>Broadcast_Audio_Event_Duration2__c</fullName>
    <label>Broadcast Audio Event Duration*</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Broadcast_Audio_Event_Participants__c.field-meta.xml
<CustomField>
    <fullName>Broadcast_Audio_Event_Participants__c</fullName>
    <description>Number of participants utilizing BA for an event.</description>
    <inlineHelpText>Enter number of participants utilizing Broadcast Audio for this event.</inlineHelpText>
    <label>Broadcast Audio Event Participants</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Broadcast_Audio_Type__c.field-meta.xml
<CustomField>
    <fullName>Broadcast_Audio_Type__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Indicates if BA will be utilized on a gold, platinum, standalone or wholesale customer basis for this event.</description>
    <inlineHelpText>Select which Event Package/Service Type will utilize Broadcast Audio.</inlineHelpText>
    <label>Broadcast Audio Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Audio_Broadcast__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Gold Event</fullName>
            </value>
            <value>
                <fullName>Platinum Event</fullName>
            </value>
            <value>
                <fullName>Stand Alone</fullName>
            </value>
            <value>
                <fullName>Wholesale Per Participant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Date__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Displays date of event.</inlineHelpText>
    <label>Event Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Int_l_Toll_Free_Booked__c.field-meta.xml
<CustomField>
    <fullName>Int_l_Toll_Free_Booked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS
Customer requested that International Toll Free numbers are booked for the RT Event.</description>
    <inlineHelpText>Were ITFs booked?</inlineHelpText>
    <label>Int&apos;l Toll Free Booked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTEvent__c/fields/Support_Type__c.field-meta.xml
<CustomField>
    <fullName>Support_Type__c</fullName>
    <description>**IF NEW SUPPORT TYPE ADDED NEEDS TO BE MAPPED IN PROCESS BUILDER TO THE APPROPRIATE SUPPORT DURATION**
CAUTION - USED IN INTEGRATIONS</description>
    <label>Support Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>100%</fullName>
            </value>
            <value>
                <fullName>100% - 15 min</fullName>
            </value>
            <value>
                <fullName>100% - 30/30</fullName>
            </value>
            <value>
                <fullName>100% - 30/30 - 15 min</fullName>
            </value>
            <value>
                <fullName>100% - 30/30 - 30 min</fullName>
            </value>
            <value>
                <fullName>100% - 30/30 - 45 min</fullName>
            </value>
            <value>
                <fullName>100% - 30/30 - 60 min</fullName>
            </value>
            <value>
                <fullName>100% - 30 min</fullName>
            </value>
            <value>
                <fullName>100% - 45 min</fullName>
            </value>
            <value>
                <fullName>100% - 60 min</fullName>
            </value>
            <value>
                <fullName>100% - None</fullName>
            </value>
            <value>
                <fullName>15/15</fullName>
            </value>
            <value>
                <fullName>30/30</fullName>
            </value>
            <value>
                <fullName>30/30 - 15 min</fullName>
            </value>
            <value>
                <fullName>30/30 - 30 min</fullName>
            </value>
            <value>
                <fullName>30/30 - 45 min</fullName>
            </value>
            <value>
                <fullName>30/30 - 60 min</fullName>
            </value>
            <value>
                <fullName>30/30 - None</fullName>
            </value>
            <value>
                <fullName>30/60</fullName>
            </value>
            <value>
                <fullName>30/90</fullName>
            </value>
            <value>
                <fullName>300 Port</fullName>
            </value>
            <value>
                <fullName>300 Port - None</fullName>
            </value>
            <value>
                <fullName>45/30</fullName>
            </value>
            <value>
                <fullName>45/60</fullName>
            </value>
            <value>
                <fullName>45/90</fullName>
            </value>
            <value>
                <fullName>60/100</fullName>
            </value>
            <value>
                <fullName>60/30</fullName>
            </value>
            <value>
                <fullName>60/60</fullName>
            </value>
            <value>
                <fullName>60/90</fullName>
            </value>
            <value>
                <fullName>90/100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTEventClose__c/RTEventClose__c.object-meta.xml
<CustomObject>
    <description>Contains information regarding billing of RTEvent objects. Used to calculate Other Charges and Credits</description>
    <label>RT Event Close</label>
    <nameField>
        <label>Event Close Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Event Close</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTEventClose__c/fields/Base_Event_Charge__c.field-meta.xml
<CustomField>
    <fullName>Base_Event_Charge__c</fullName>
    <description>Base Event Charge amount (defaulted from Account ,based on event type)</description>
    <inlineHelpText>Base Event Charge amount (defaulted from Account ,based on event type)</inlineHelpText>
    <label>Base Event Charge</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEventClose__c/fields/RT_Event__c.field-meta.xml
<CustomField>
    <fullName>RT_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Parent event</description>
    <label>RT Event</label>
    <referenceTo>RTEvent__c</referenceTo>
    <relationshipLabel>RT Event Close</relationshipLabel>
    <relationshipName>RT_Event_Close</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <description>Used for workflow notifications only. Not visible on the page layout.</description>
    <formula>Contact__r.Account.Name</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>If there was an error in provisioning the subscription, then it is of this record type</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/RTEventCloseController.cls
public class RTEventCloseController {
    
    private RTEvent__c event;
    private RTEventClose__c eventClose;
    
    private ApexPages.StandardController stdController;
    
    private List<OtherChargeCredit__c> postedCharges;
    private List<OtherChargeCredit__c> previewCharges = null;

    
    /* initializer method.
     * gets the parent event object, and any charges/credits that are associated
     * with this event.
     */
    public RTEventCloseController(ApexPages.StandardController controller) {
        stdController = controller;
        
        system.debug('Getting eventClose from standard controller..');
        eventClose = (RTEventClose__c)controller.getRecord();
        String eventID = eventClose.RT_Event__c;
        system.debug('EventClose record is ' + controller.getRecord());
        system.debug('Event id is ' + eventID);
        if (eventID != null) {
          event = (RTEvent__C)RTDatabaseUtils.getEntireSObject(new RTEvent__c(), eventID);
          system.debug('Found event: ' + event);
        }
        
        postedCharges = findPostedOtherChargeCredit();
        
    }
    
    public PageReference cancel() {
      PageReference eventPage = new ApexPages.StandardController(event).view();
      eventPage.setRedirect(true);
      return eventPage;
    }
    
    
    /* calls doSave and implements error handling. */
    public void save() {
      try {
         doSave();
      } catch (DmlException ex) {
        ApexPages.addMessages(ex);
      }
    }
    
    /* does the actual save of the object. Throws DMLException if error */
    private void doSave() {
      update eventClose;
      update event;
    }
    
    
    private boolean validateForOCC() {
    
      if (event.Event_Date__c == null) {
        throw new NotFoundException('The Event Date must be populated before closing the Event. Click the Cancel button to return to the RT Event.');
      }
      
      if (event.Broadcast_Audio_Event_Duration2__c == null || event.Broadcast_Audio_Event_Participants__c == null) { 
        throw new NotFoundException('Total Participants and Event Duration fields must be populated before before previewing or posting charges.');
      }
      
      return true;
    }
    
    /* Controller method to handle Preview button action (with reRender tag).
     * Calls the charge calc method and then stores the result
     * for the VIEW to access.
    */
    public void preview() {
      try {
        previewCharges = null;
        doSave();
        
        // throws exception if something is missing.
        validateForOCC();
       
        previewCharges = calculateOtherChargesCredits();
      } catch (Exception ex) {
        ApexPages.addMessages(ex);
      } 
        
    }
    
    
    /* Controller method to handle the Post button action 
     * Calls the charge calc method and then inserts
     * each record.
    */
    public void post() {
    
      try {
        previewCharges = null;
        doSave();
        
        // throws exception if something is missing.
        validateForOCC();
        
        SavePoint sp = Database.setSavePoint();
        
        try {
          for (OtherChargeCredit__c occ: calculateOtherChargesCredits()) {
            insert occ;
          }
          
        } catch (DMLException dbEx) {
          Database.rollback(sp);
          ApexPages.addMessages(dbEx);
        }
        
        postedCharges = findPostedOtherChargeCredit();
         
      } catch (Exception ex) {
        ApexPages.addMessages(ex);
      } 

    }
    

    /* does a query to find any charges and credits related to this event. */
    private List<OtherChargeCredit__c> findPostedOtherChargeCredit() {
        System.debug('Getting OtherChargeCredit for event.');
        List<OtherChargeCredit__c>  charges = null;
        if (event != null) {
            System.debug('Searching based on event id: ' + event.Id);
        charges =  [select Id, Name, AccessCode__c, Account_Name__c, BilledDate__c, ChargeOrCredit__c, 
                 Contact_Name__c, Description__c, Product__c, RTEventName__c, ServiceDate__c from OtherChargeCredit__c WHERE RTEventName__c = :event.Id];
        } else {
            System.debug('No event record found. Skipping OCC lookup.');
        }
        
        return charges;
    }
    
    private List<OtherChargeCredit__c> calculateOtherChargesCredits() {
      system.debug('Enter calculateOtherChargesCredits');
      List<OtherChargeCredit__c> charges = new List<OtherChargeCredit__c>();
      system.debug('calling to calc additional minute charge');
      Decimal additionalMinuteCharge = calcAdditionalMinuteCharge();
      
      system.debug('Calling to calc additional participants charge');
      Decimal additionalParticipantCharge = calcAdditionalParticipantCharge();
      
      system.debug('adding base price charge');
      charges.add(buildOCCRecord('Base Price', eventClose.Base_Event_Charge__c));
      
      if (additionalMinuteCharge > 0) {
        system.debug('creating occ record for additional minutes');
        charges.add(buildOCCRecord('Additional Minutes', additionalMinuteCharge));
      }
      if (additionalParticipantCharge > 0) {
        system.debug('creating occ record for additional participants');
        charges.add(buildOCCRecord('Additional Participants', additionalParticipantCharge));
      }
      system.debug('Is internaltional tollfree booked?');
      Decimal intlTollFreeAddOn = calcIntlTollFreeAddOn();
      if (event.Int_l_Toll_Free_Booked__c == true && intlTollFreeAddOn > 0) {
        system.debug('yes it is');
        charges.add(buildOCCRecord('International Toll-Free Add-On', intlTollFreeAddOn));
      }
      
      system.debug('Checking support type for live event monitoring... support type is: '+event.Support_type__c);
      if ((event.Support_Type__c != null && event.Support_Type__c.startsWith('100%'))
          && ('Gold Event'.equalsIgnoreCase(event.Broadcast_Audio_Type__c) || 'Stand Alone'.equalsIgnoreCase(event.Broadcast_Audio_Type__c))
          && event.First_Presenter_Event__c == false 
          && event.First_Organizer_Event__c == false) {
            charges.add(buildOCCRecord('Full Live Event Monitoring & Support', eventClose.Live_Event_Monitoring_Rate__c));
      }
      
      system.debug('checking for op-assist add-on.');
      if ('Operator Assisted Premium'.equalsIgnoreCase(event.RT_Event_type__c) 
         && ('Platinum Event'.equalsIgnoreCase(event.Broadcast_Audio_Type__c) || 'Gold Event'.equalsIgnoreCase(event.Broadcast_Audio_Type__c))) {
          charges.add(buildOCCRecord('Premium Op-Assist Add-On', eventClose.Premium_Op_Assist_Rate__c));
      }

      system.debug('done creating occ records for preview/post');
      return charges;
    }

    private OtherChargeCredit__c buildOCCRecord(String chargeType, Decimal charge) {
      OtherChargeCredit__c occ = new OtherChargeCredit__c();
      Date serviceDate = event.Event_Date__c;
      occ.ServiceDate__c = serviceDate;
      occ.RTEventName__c = event.Id;
      List<Subscription__c> subList = [select Name from Subscription__c where Id = :event.Access_Code__c limit 1];
      String subscrName = '-';
      if (subList != null && subList.size() > 0) {
        subscrName = subList.get(0).Name;
      }
      String description = 'Total Participants: {0} Duration: {1} Access Code: {2}';
      String[] arguments = new String[] {String.valueOf(event.Broadcast_Audio_Event_Participants__c), 
          String.valueOf(event.Broadcast_Audio_Event_Duration2__c != null ? event.Broadcast_Audio_Event_Duration2__c : 0), 
          subscrName};
      occ.Description__c = String.format(description, arguments);
      occ.Product__c = getProduct(chargeType);
      occ.ChargeOrCredit__c = charge;
      occ.AccessCode__c = event.Bill_to_Access_Code__c;
      
      return occ;
    }
    
    private String getProduct(String chargeType) {
      String product = 'Charge - ';
      if (event.Broadcast_Audio_Type__c != null) {
        if (event.Broadcast_Audio_Type__c.equals('Gold Event')) {
          product += 'Gold Webinar - ';
        } else if (event.Broadcast_Audio_Type__c.equals('Platinum Event')) {
          product += 'Platinum Webinar - ';
        } else {
          product += 'Broadcast Audio - ';
        }
      } else {
        product += 'Broadcast Audio - ';
      }
      return product += chargeType;
    }
    
    private Decimal calcAdditionalMinuteCharge() {
      
      Integer participants = Integer.valueOf(event.Broadcast_Audio_Event_Participants__c);
      Integer duration = Integer.valueOf(event.Broadcast_Audio_Event_Duration2__c);
      Decimal rate = eventClose.Additional_Minutes_Rate__c;
      Decimal charge = 0;
      Integer timeOverageUnits = calcTimeOverageUnits(duration);
      system.debug('Additional minute units = ' + timeOverageUnits);
      
      charge = rate * (timeOverageUnits * (calcParticipantOverageUnits(participants)+1));
      
      system.debug('additonal minutes charge is ' + charge);
      return charge;
    }
        
    private Decimal calcAdditionalParticipantCharge() {
      Integer participants = Integer.valueOf(event.Broadcast_Audio_Event_Participants__c);
      Decimal rate = eventClose.Additional_Participants_Rate__c;
      Decimal charge = 0;
      
      charge = rate * calcParticipantOverageUnits(participants);
      
      system.debug('participant charge is ' + charge);
      
      return charge;
    }
    
    private Integer calcTimeOverageUnits(Integer duration) {
      Integer includedMinutes = 70;
      Double minutesPerUnit = 30;
      Integer overageUnits = 0;
      system.debug('CalcTimeOverageUnits - duration is ' + duration);
      if (duration > includedMinutes) {
        // find out which 'incremental block of time' the conf falls into.
        overageUnits = Integer.valueOf(Math.ceil((duration - includedMinutes) / minutesPerUnit));
        system.debug('CalcTimeOverageUnits - overage units is ' + overageUnits);
      }
      return overageUnits;
    }
    
    private Integer calcParticipantOverageUnits(Integer participants) {
      Integer includedParticipants = 110;
      Double participantsPerUnit = 100;
      Integer overageUnits = 0;
      
      if (participants > includedParticipants) {
        overageUnits = Integer.valueOf(Math.ceil((participants - includedParticipants)/participantsPerUnit));
      }
      return overageUnits;
    }
    
    private Decimal calcIntlTollFreeAddOn() {
      Decimal rate = eventClose.ITF_Add_on_Rate__c;
      Decimal linesReserved = event.Total_lines_reserved__c;
      Decimal charge = 0;
      
      if ( linesReserved != null && ('Gold Event'.equalsIgnoreCase(event.Broadcast_Audio_Type__c) || 'Platinum Event'.equalsIgnoreCase(event.Broadcast_Audio_Type__c)) ) {
        charge = rate * Math.ceil(linesReserved/10);
      }
      return charge;
    }
    
    /* Getter to put the parent event on the VIEW layer */
    public RTEvent__c getEvent() {
        return event;
    }
    
    /* Getter for unit testing */
    public RTEventClose__c getEventClose() {
        return eventClose;
    }

    
    /* Getter to put any preview OtherChargeCredit on the VIEW layer */
    public List<OtherChargeCredit__c> getPostedOtherChargeCredit() {
      return postedCharges;
    }
    
    /* getter to get preview values for VIEW layer */
    public List<OtherChargeCredit__c> getPreviewOtherChargeCredit() {
      return previewCharges;
    }
}