force-app/main/default/objects/OtherChargeCredit__c/OtherChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Object to hold Other Charges and Credits</description>
    <label>Other Charge or Credit</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>OtherChargeCredit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Charges Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherChargeCredit__c/fields/ChargeOrCredit__c.field-meta.xml
<CustomField>
    <fullName>ChargeOrCredit__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge/(Credit) Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Event Info Only. Information will be printed on invoice.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blackberry Charge - Event Manager Assisted - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Live Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - On Demand - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Operator Assisted Live - Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Vidyard Recording -  Hosting</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Webcasting</fullName>
            </value>
            <value>
                <fullName>Charge - Audio 300 Port Capacity Upgrade</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Participants</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Closed Captioning Services</fullName>
            </value>
            <value>
                <fullName>Charge - Corporate License Subscription</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Annual Maintenance</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Set-up</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Add&apos;l Monitoring &amp; Support</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Cancellation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Communication Line</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dress Rehearsal w/ Op. Svcs.</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dry Run</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Event Call Director</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Full Event Moderation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Other</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Pre-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Re-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Transcription Services</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Webinar Set-Up &amp; Customization</fullName>
            </value>
            <value>
                <fullName>Charge - FEM Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Full Event Moderation Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ValidateOtherChargeCreditFields.cls
public class ValidateOtherChargeCreditFields {

  public static boolean validateChargeCredit(OtherChargeCredit__c otherChargeCredit){

    //Description cannot be > 100 characters
    if(otherChargeCredit.Description__c != null && otherChargeCredit.Description__c.length() > 100) {
      otherChargeCredit.addError('Description cannot be longer than 100 characters.  Currently, the description contains '+otherChargeCredit.Description__c.length()+' characters.');
      return false;
    }

    //Cannot be a $0 value
    if(otherChargeCredit.ChargeOrCredit__c == 0){
      otherChargeCredit.addError('Charge/(Credit) cannot be $0');
      return false;
    }

    //If Product starts with "Credit", then ensure the amount is negative
    if(otherChargeCredit.Product__c.startsWith('Credit') && otherChargeCredit.ChargeOrCredit__c > 0) {
      otherChargeCredit.addError('All credits must be a negative amount.');
      return false;
    }

    //Anything else is a charge, ensure the amount is positive
    if(!otherChargeCredit.Product__c.startsWith('Credit') && otherChargeCredit.ChargeOrCredit__c < 0) {
      otherChargeCredit.addError('All charges must be a positive amount.');
      return false;
    }


    return true;
  } 
}