force-app/main/default/objects/OtherChargeCredit__c/OtherChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Object to hold Other Charges and Credits</description>
    <label>Other Charge or Credit</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>OtherChargeCredit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Charges Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherChargeCredit__c/fields/ChargeOrCredit__c.field-meta.xml
<CustomField>
    <fullName>ChargeOrCredit__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge/(Credit) Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blackberry Charge - Event Manager Assisted - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Live Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - On Demand - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Operator Assisted Live - Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Vidyard Recording -  Hosting</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Webcasting</fullName>
            </value>
            <value>
                <fullName>Charge - Audio 300 Port Capacity Upgrade</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Participants</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Closed Captioning Services</fullName>
            </value>
            <value>
                <fullName>Charge - Corporate License Subscription</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Annual Maintenance</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Set-up</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Add&apos;l Monitoring &amp; Support</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Cancellation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Communication Line</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dress Rehearsal w/ Op. Svcs.</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dry Run</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Event Call Director</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Full Event Moderation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Other</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Pre-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Re-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Transcription Services</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Webinar Set-Up &amp; Customization</fullName>
            </value>
            <value>
                <fullName>Charge - FEM Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Full Event Moderation Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RTEventClose__c/RTEventClose__c.object-meta.xml
<CustomObject>
    <description>Contains information regarding billing of RTEvent objects. Used to calculate Other Charges and Credits</description>
    <label>RT Event Close</label>
    <nameField>
        <label>Event Close Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Event Close</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTEventClose__c/fields/Additional_Minutes_Rate__c.field-meta.xml
<CustomField>
    <fullName>Additional_Minutes_Rate__c</fullName>
    <description>Extended Duration Charge amount (per 30 minutes)</description>
    <inlineHelpText>Extended Duration Charge amount (per 30 minutes)</inlineHelpText>
    <label>Additional Minutes Rate</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEventClose__c/fields/Additional_Participants_Rate__c.field-meta.xml
<CustomField>
    <fullName>Additional_Participants_Rate__c</fullName>
    <description>Additional Participant Charge amount (per 100 participants)</description>
    <inlineHelpText>Additional Participant Charge amount (per 100 participants)</inlineHelpText>
    <label>Additional Participants Rate</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTEventClose__c/fields/ITF_Add_on_Rate__c.field-meta.xml
<CustomField>
    <fullName>ITF_Add_on_Rate__c</fullName>
    <description>ITF Add-on Rate Override</description>
    <inlineHelpText>ITF Add-on Rate Override</inlineHelpText>
    <label>ITF Add-on Rate</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/testRTEventCloseController.cls
@isTest
private class testRTEventCloseController {
  private static RTEventClose__c eventClose;
  private static ApexPages.StandardController controller;

  static {
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
    eventClose = MockRTEventClose.getNewRTEventClose();
    controller = new ApexPages.StandardController(RTDatabaseUtils.getEntireSObject(new RTEventClose__c(), eventClose.id));
    ApexPages.currentPage().getParameters().put('id', eventClose.id);
  }

  static testMethod void testConstruct() {
    RTEventCloseController c = new RTEventCloseController(controller);
    System.assert(c != null);    
    System.assert(c.getEvent().Event_Date__c == Date.newInstance(3010, 1, 1));
  }

  static testMethod void testDateValidation() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.getEvent().Event_Date__c = null;    
    c.preview();    
    System.assert(c != null);
  }
 
  static testMethod void testDurationValidation() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.getEvent().Broadcast_Audio_Event_Duration2__c = null;
    c.preview();    
    System.assert(c != null);
  }

  static testMethod void testIntlTollFreeBookedTrue() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.getEventClose().ITF_Add_on_Rate__c = 115.25;
    c.getEvent().Int_l_Toll_Free_Booked__c = true;
    c.preview();
    
    for (OtherChargeCredit__c occ : c.getPreviewOtherChargeCredit()) {
      if (occ.Product__c.contains('International Toll-Free Add-On')) {
        System.assertEquals(115.25, occ.ChargeOrCredit__c);
      }
    }
    System.assert(c != null);
  }

  static testMethod void testIntlTollFreeBookedFalse() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.getEventClose().ITF_Add_on_Rate__c = 115.25;
    c.getEvent().Int_l_Toll_Free_Booked__c = false;
    c.preview();
    
    for (OtherChargeCredit__c occ : c.getPreviewOtherChargeCredit()) {
      if (occ.Product__c.contains('International Toll-Free Add-On')) {
        //throw new ValidationException('Did not expect an International Toll-Free Add-On occ record.');
      }
    }
    System.assert(c != null);
  }  
  
  static testMethod void testAdditionalMinutesCharge() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.getEvent().Broadcast_Audio_Event_Participants__c = 111;
    c.getEvent().Broadcast_Audio_Event_Duration2__c = 71;
    c.getEventClose().Additional_Minutes_Rate__c = 250.00;
    c.preview();
    
    for (OtherChargeCredit__c occ : c.getPreviewOtherChargeCredit()) {
      if (occ.Product__c.contains('Additional Minutes')) {
        System.assertEquals(500.00, occ.ChargeOrCredit__c);
      }
    }

    System.assert(c != null);
  }

  static testMethod void testAdditionalParticipantCharge() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.getEvent().Broadcast_Audio_Event_Participants__c = 300;
    c.getEventClose().Additional_Participants_Rate__c = 500.00;
    c.preview();
    
    for (OtherChargeCredit__c occ : c.getPreviewOtherChargeCredit()) {
      if (occ.Product__c.contains('Additional Participants')) {
        System.assertEquals(1000.00, occ.ChargeOrCredit__c);
      }
    }
    System.assert(c != null);
  }

  static testMethod void testPost() {
    RTEventCloseController c = new RTEventCloseController(controller);
    c.post();
    System.assert(c != null);
  }
}