force-app/main/default/objects/OtherChargeCredit__c/OtherChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Object to hold Other Charges and Credits</description>
    <label>Other Charge or Credit</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>OtherChargeCredit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Charges Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherChargeCredit__c/fields/AccessCode__c.field-meta.xml
<CustomField>
    <fullName>AccessCode__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Other Charges Credits</relationshipLabel>
    <relationshipName>OtherChargesCredits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/BilledDate__c.field-meta.xml
<CustomField>
    <fullName>BilledDate__c</fullName>
    <label>Billed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
The date that this record was deleted.</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <description>The user that deleted this record.</description>
    <label>Deleted By</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Inactivated_By__c.field-meta.xml
<CustomField>
    <fullName>Inactivated_By__c</fullName>
    <description>Person who inactivated the subscription</description>
    <label>Deleted By</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subscription__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscription__c/recordTypes/Error.recordType-meta.xml
<RecordType>
    <fullName>Error</fullName>
    <active>true</active>
    <description>If there was an error in provisioning the subscription, then it is of this record type</description>
    <label>Error</label>
</RecordType>

force-app/main/default/classes/OtherChargesCreditsController.cls
public with sharing class OtherChargesCreditsController {

    OtherChargeCredit__c otherChargeCredit;
    Id accessCodeID;

    public OtherChargesCreditsController(ApexPages.StandardController controller) {        
        otherChargeCredit = (OtherChargeCredit__c)controller.getRecord(); 
        accessCodeID = otherChargeCredit.AccessCode__c;
    }
    
    public PageReference save() {
        try{
            if(!ValidateOtherChargeCreditFields.validateChargeCredit(otherChargeCredit)) return null;                            
            upsert(otherChargeCredit);
        }
        catch(DmlException ex){
            ApexPages.addMessages(ex);
            return null;
        }
        
        return goBack();
    }    
    
    public PageReference customDelete() {
        this.otherChargeCredit.Inactive__c = true;
        this.otherChargeCredit.Inactivated_By__c = Userinfo.getUserName();
        this.otherChargeCredit.Date_Deleted__c = Datetime.now();
        update(this.otherChargeCredit);
        return goBack();        
    }
    
    public PageReference checkBilledStatus() {
        String delID = ApexPages.currentPage().getParameters().get('delID');
        String id = ApexPages.currentPage().getParameters().get('id');
        
        //If we are deleting and the billed date is null, then allow the delete, and go back to the subscription page
        if(delID != null && otherChargeCredit.BilledDate__c == null) {
            return customDelete();            
        }
        
        //If we are deleting and the billed date is not null, then don't allow the delete, and display an error message
        else if(delID != null && otherChargeCredit.BilledDate__c != null) {
            otherChargeCredit.addError('You cannot delete an Other Charge or Credit that has already been billed.');
            return null;
        }
        
        //If we are editing (have and ID param) and the billed date is not null, then display an error message
        else if(id != null && otherChargeCredit.BilledDate__c != null) {
            otherChargeCredit.addError('You cannot edit an Other Charge or Credit that has already been billed.');
            return null;
        }
        
        return null;
    }
    
    public OtherChargeCredit__c getOtherChargeCredit(){
        return otherChargeCredit;
    }
    
    public PageReference goBack() {
        //Redirect back to the owning subscription page
        Subscription__c subscription = [select id from Subscription__c where id = : accessCodeID];
          
        PageReference subscriptionPage = new ApexPages.StandardController(subscription).view();
        subscriptionPage.setRedirect(true);

        return subscriptionPage;
    }
}