force-app/main/default/objects/OtherChargeCredit__c/OtherChargeCredit__c.object-meta.xml
<CustomObject>
    <description>Object to hold Other Charges and Credits</description>
    <label>Other Charge or Credit</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>OtherChargeCredit</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Other Charges Credits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OtherChargeCredit__c/fields/AccessCode__c.field-meta.xml
<CustomField>
    <fullName>AccessCode__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Access Code</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Other Charges Credits</relationshipLabel>
    <relationshipName>OtherChargesCredits</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/BilledDate__c.field-meta.xml
<CustomField>
    <fullName>BilledDate__c</fullName>
    <label>Billed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/ChargeOrCredit__c.field-meta.xml
<CustomField>
    <fullName>ChargeOrCredit__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge/(Credit) Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <inlineHelpText>Event Info Only. Information will be printed on invoice.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Internal_Notes__c.field-meta.xml
<CustomField>
    <fullName>Internal_Notes__c</fullName>
    <description>Insert details for internal review. This information is NOT printed on the invoice.</description>
    <inlineHelpText>Insert details for internal review. This information is NOT printed on the invoice.</inlineHelpText>
    <label>Internal Notes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blackberry Charge - Event Manager Assisted - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Live Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - On Demand - Recording</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Operator Assisted Live - Webinars</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Vidyard Recording -  Hosting</fullName>
            </value>
            <value>
                <fullName>Blackberry Charge - Webcasting</fullName>
            </value>
            <value>
                <fullName>Charge - Audio 300 Port Capacity Upgrade</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Additional Participants</fullName>
            </value>
            <value>
                <fullName>Charge - Broadcast Audio - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Closed Captioning Services</fullName>
            </value>
            <value>
                <fullName>Charge - Corporate License Subscription</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Annual Maintenance</fullName>
            </value>
            <value>
                <fullName>Charge - Custom Start Page - Set-up</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Add&apos;l Monitoring &amp; Support</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Cancellation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Communication Line</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dress Rehearsal w/ Op. Svcs.</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Dry Run</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Event Call Director</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Full Event Moderation</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Other</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Pre-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Re-record</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Simulive - Base Price</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Transcription Services</fullName>
            </value>
            <value>
                <fullName>Charge - Event Services - Webinar Set-Up &amp; Customization</fullName>
            </value>
            <value>
                <fullName>Charge - FEM Additional Minutes</fullName>
            </value>
            <value>
                <fullName>Charge - Full Event Moderation Promotion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OtherChargeCredit__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Error</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error - Intercall</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error - Level 3</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error- PGi</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure - Intercall</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure - Level 3</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure- PGi</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Service - GX Outage</fullName>
            </value>
            <value>
                <fullName>Service - Intercall Outage</fullName>
            </value>
            <value>
                <fullName>Service- PGi Outage</fullName>
            </value>
            <value>
                <fullName>Service - RT Outage</fullName>
            </value>
            <value>
                <fullName>Setup Error - RT</fullName>
            </value>
            <value>
                <fullName>Subscription Frequency Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MockOtherChargeCredit.cls
public class MockOtherChargeCredit {
    
    public Id AccessCode = MockSubscription.getNewSubscription().Id;
    public Date BilledDate = Date.newInstance(3010, 1, 1);
    public String Description = 'Test Description';
    public Decimal ChargeOrCredit = 1.0;
    public String Product = 'Test Product';
    public String InternalNotes = 'foo';
    public String Reason = 'Fraud';
        
    private void setupOtherChargeCredit(OtherChargeCredit__c o) {
        o.AccessCode__c = AccessCode;    
        o.BilledDate__c = BilledDate;
        o.Description__c = Description;
        o.ChargeOrCredit__c = ChargeOrCredit;
        o.Product__c = Product;
        o.Internal_Notes__c = InternalNotes;
        o.Reason__c = Reason;
    }
       
    public static OtherChargeCredit__c getNewOtherChargeCredit() {
        OtherChargeCredit__c o = new OtherChargeCredit__c();
        MockOtherChargeCredit m = new MockOtherChargeCredit();
        m.setupOtherChargeCredit(o);        
        Database.insert(o);        
        return o;
    }
    
    public OtherChargeCredit__c getOtherChargeCredit() {
        OtherChargeCredit__c o = new OtherChargeCredit__c();
        setupOtherChargeCredit(o);        
        Database.insert(o);        
        return o;
    }
}