force-app/main/default/objects/OT_Member__c/OT_Member__c.object-meta.xml
<CustomObject>
    <label>Opportunity Team Engine</label>
    <nameField>
        <label>Opportunity Team Engine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Team Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OT_Member__c/fields/Evaluation_Order__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Order__c</fullName>
    <label>Evaluation Order</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OT_Member__c/fields/Rule_Order__c.field-meta.xml
<CustomField>
    <fullName>Rule_Order__c</fullName>
    <label>Rule Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OT_Rule__c/OT_Rule__c.object-meta.xml
<CustomObject>
    <label>Opportunity Team Rule</label>
    <nameField>
        <label>Opportunity Team Engine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Team Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OT_Rule__c/fields/Field_Operator__c.field-meta.xml
<CustomField>
    <fullName>Field_Operator__c</fullName>
    <label>Field Operator</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OT_Rule__c/fields/Field_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Type__c</fullName>
    <label>Field Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OT_Rule__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <label>Field Value</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OT_Rule__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/OT_Rule__c/fields/OT_Member__c.field-meta.xml
<CustomField>
    <fullName>OT_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Team Member</label>
    <referenceTo>OT_Member__c</referenceTo>
    <relationshipLabel>Opportunity Team Rules</relationshipLabel>
    <relationshipName>Opportunity_Team_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/OT_Member__c.field-meta.xml
<CustomField>
    <fullName>OT_Member__c</fullName>
    <label>Opportunity Team Engine</label>
    <referenceTo>OT_Member__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OTE_CMP_ControllerTest.cls
/**  
* \arg ClassName        : OTE_CMP_ControllerTest
* \arg JIRATicket       : 
* \arg CreatedOn        : 19/July/2019
* \arg LastModifiedOn   : 
* \arg CreatededBy      : Vijay
* \arg ModifiedBy       : 
* \arg Description      : Test class for OTE_CMP_Controller class
*/
@isTest
private class OTE_CMP_ControllerTest 
{	
    static OT_Member__c objOTMember;
    static OT_Rule__c objOTRule;
    static Team_Member__c objTeamMember;
    
    @testSetup static void setup() 
    {
        Account objAcc = new Account(Name = 'Test1');
        INSERT objAcc;
        List<OT_Member__c> otMemberList = new List<OT_Member__c>{new OT_Member__c(Name = 'Test1' , Evaluation_Order__c = '1 AND 2' , Rule_Order__c = 1),
            new OT_Member__c(Name = 'Test12' , Evaluation_Order__c = '1 AND 2' , Rule_Order__c = 2)};
                Insert otMemberList;     
        List<OT_Rule__c> otRoleList = new List<OT_Rule__c>{new OT_Rule__c(Name = 'Test1', OT_Member__c = otMemberList[0].Id , Object_Name__c = 'Account' , Field_Type__c = 'Text' , Field_Operator__c = 'notEqual' , Field_Value__c = 'opp' , Line_Number__c = 1 , Field_Name__c = 'Name' , CurrencyIsoCode = 'USD'),
            new OT_Rule__c(Name = 'Test12', OT_Member__c = otMemberList[1].Id , Object_Name__c = 'OpportunityLineItem' , Field_Type__c = 'Text' , Field_Operator__c = 'notEqual' , Field_Value__c = 'opp' , Line_Number__c = 2 , Field_Name__c = 'Name' , CurrencyIsoCode = 'USD')};
                INSERT otRoleList;
        List<Team_Member__c> teamMemberList = new List<Team_Member__c>{new Team_Member__c(Name = 'Test1' , OT_Member__c = otMemberList[0].Id , Role__c = 'Sales Rep' , CurrencyIsoCode = 'USD' ,User__c = UserInfo.getUserId()),
            new Team_Member__c(Name = 'Test12' , OT_Member__c = otMemberList[1].Id , Role__c = 'Sales Rep' , CurrencyIsoCode = 'USD' ,User__c = UserInfo.getUserId()),
            new Team_Member__c(Name = 'Test13' , OT_Member__c = otMemberList[1].Id , Role__c = 'Sales Rep' , CurrencyIsoCode = 'USD' ,User__c = UserInfo.getUserId())};
                Insert teamMemberList;  
        
        objOTMember = new OT_Member__c(Name = 'Member_test01' , Evaluation_Order__c = '1' , Rule_Order__c = 1);
        objOTRule = new OT_Rule__c(Name = 'TestRule1' , Object_Name__c = 'Account' , Field_Type__c = 'Text' , Field_Operator__c = 'notEqual' , Field_Value__c = 'opp' , Line_Number__c = 1 , Field_Name__c = 'Name' , CurrencyIsoCode = 'USD');
        objTeamMember = new Team_Member__c(Name = 'Test12' , OT_Member__c = otMemberList[1].Id , Role__c = 'Sales Rep' , CurrencyIsoCode = 'USD' ,User__c = UserInfo.getUserId());
    }
    static testMethod void method1()
    {
        setup();
        List<OT_Member__c> otMembList =[SELECT Id,Name,Evaluation_Order__c,Rule_Order__c FROM OT_Member__c]; 
        
        OTE_CMP_Controller.getObjectKeyPrefix();
        OTE_CMP_Controller.getOTERecords(otMembList[0].Id);
        OTE_CMP_Controller.getALLFields('Account');
        OTE_CMP_Controller.getRoleValues();
        Map<Id,OT_Rule__c> roleIdMap = new Map<Id,OT_Rule__c>([Select Id from OT_Rule__c WHERE OT_Member__c = :otMembList[0].Id]);
        Map<Id,Team_Member__c> teamMemberMap = new Map<Id,Team_Member__c>([Select Id from Team_Member__c where OT_Member__c =:otMembList[0].Id]);
        
        OTE_CMP_Controller.saveOppyTeamEngineRecords(JSON.serialize(objOTMember),'['+JSON.serialize(objOTRule)+']','['+JSON.serialize(objTeamMember)+']',new List<Id>(roleIdMap.keySet()),new List<Id>(teamMemberMap.keySet()));
        OTE_CMP_Controller.deleteRecord(String.valueOf(new List<Id>(roleIdMap.keySet())[0]));
        system.assertEquals([SELECT count() FROM OT_Rule__c WHERE OT_Member__c = :otMembList[0].Id],0);
    }
}