force-app/main/default/objects/ChargeCode__c/ChargeCode__c.object-meta.xml
<CustomObject>
    <label>Charge Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeCode__c/fields/chargeCodeType__c.field-meta.xml
<CustomField>
    <fullName>chargeCodeType__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge Code Type</label>
    <referenceTo>ChargeCodeType__c</referenceTo>
    <relationshipLabel>Charge Codes</relationshipLabel>
    <relationshipName>ChargeCodes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NegotiatedProduct__c/NegotiatedProduct__c.object-meta.xml
<CustomObject>
    <description>Configured Components under Products assigned to an Account.</description>
    <label>Negotiated Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NegotiatedProduct__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Negotiated Products</relationshipLabel>
    <relationshipName>NegotiatedProducts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/PlanAssignment__c.object-meta.xml
<CustomObject>
    <description>Assigned Products related to Access Codes.</description>
    <label>Plan Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/fields/FoxDen_User__c.field-meta.xml
<CustomField>
    <fullName>FoxDen_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>FoxDen_User</description>
    <label>FoxDen User</label>
    <referenceTo>FoxDen_User__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>Plan_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>PlanAssignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/fields/S3User__c.field-meta.xml
<CustomField>
    <fullName>S3User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Replay User</label>
    <referenceTo>S3User__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>Plan_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/RateOverride__c.object-meta.xml
<CustomObject>
    <label>Rate Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateOverride__c/fields/chargeCode__c.field-meta.xml
<CustomField>
    <fullName>chargeCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Charge Code</label>
    <referenceTo>ChargeCode__c</referenceTo>
    <relationshipLabel>Rate Overrides</relationshipLabel>
    <relationshipName>Rate_Overrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/fields/customSchedule__c.field-meta.xml
<CustomField>
    <fullName>customSchedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Custom Schedule</label>
    <referenceTo>CustomSchedule__c</referenceTo>
    <relationshipLabel>Rate Overrides</relationshipLabel>
    <relationshipName>RateOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/fields/ReadyTalk_Rate__c.field-meta.xml
<CustomField>
    <fullName>ReadyTalk_Rate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Rate</label>
    <precision>14</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/ReadyTalk_Rate__c.object-meta.xml
<CustomObject>
    <label>ReadyTalk Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ReadyTalk Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/chargeCode__c.field-meta.xml
<CustomField>
    <fullName>chargeCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge Code</label>
    <referenceTo>ChargeCode__c</referenceTo>
    <relationshipLabel>ReadyTalk Rates</relationshipLabel>
    <relationshipName>ReadyTalk_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/ReadyTalk_Rate__c.field-meta.xml
<CustomField>
    <fullName>ReadyTalk_Rate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>ReadyTalk Rate</label>
    <precision>14</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>ReadyTalk Rates</relationshipLabel>
    <relationshipName>ReadyTalk_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecurringChargeOverride__c/RecurringChargeOverride__c.object-meta.xml
<CustomObject>
    <label>Recurring Charge Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recurring Charge Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RecurringChargeOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Recurring Charge Overrides</relationshipLabel>
    <relationshipName>RecurringChargeOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/RT_Product__c.object-meta.xml
<CustomObject>
    <description>Components related to a Package; e.g. Web component of Web Meeting Pro (25).</description>
    <label>RT Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RT Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RT_Product__c/fields/package__c.field-meta.xml
<CustomField>
    <fullName>package__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Package</label>
    <referenceTo>Package__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RT_Product__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>RT Products</relationshipLabel>
    <relationshipName>RT_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleOverride__c/ScheduleOverride__c.object-meta.xml
<CustomObject>
    <label>Schedule Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedule Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ScheduleOverride__c/fields/customSchedule__c.field-meta.xml
<CustomField>
    <fullName>customSchedule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Custom Schedule</label>
    <referenceTo>CustomSchedule__c</referenceTo>
    <relationshipLabel>Schedule Overrides</relationshipLabel>
    <relationshipName>ScheduleOverrides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ScheduleOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Schedule Overrides</relationshipLabel>
    <relationshipName>ScheduleOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SingleChargeOverride__c/SingleChargeOverride__c.object-meta.xml
<CustomObject>
    <label>Single Charge Override</label>
    <nameField>
        <label>Single Charge Overrides Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Single Charge Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SingleChargeOverride__c/fields/negotiatedProduct__c.field-meta.xml
<CustomField>
    <fullName>negotiatedProduct__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Negotiated Product</label>
    <referenceTo>NegotiatedProduct__c</referenceTo>
    <relationshipLabel>Single Charge Overrides</relationshipLabel>
    <relationshipName>SingleChargeOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SFPCTestHelper.cls
public with sharing class SFPCTestHelper {

  public Package__c pkg;
  public Package__c quantityPkg;
  public Schedule__c schedule;
  public RT_Product__c product;
  public Plan__c plan;
  public Plan__c fdPlan;
  public Plan__c s3Plan;
  public Plan__c quantityPlan;
  public CustomSchedule__c customSchedule;
  public NegotiatedProduct__c negotiatedProduct;
  public SingleChargeOverride__c singleChargeOverride;
  public RecurringChargeOverride__c recurringChargeOverride;
  public ScheduleOverride__c scheduleOverride;
  public ChargeCode__c chargeCode;
  public ChargeCodeType__c chargeCodeType;
  public ReadyTalk_Rate__c rate;
  public RateOverride__c rateOverride;

  public Package__c unassignedPackage;
  public Plan__c unassignedPlan;
  public Schedule__c unassignedSchedule;

  public Package__c unassignedPackage2;
  public RT_Product__c unassignedProduct;

  public PlanAssignment__c accessCodePlanAssignment;
  public PlanAssignment__c foxDenPlanAssignment;
  public PlanAssignment__c s3UserPlanAssignment;

  public Subscription__c subscription;
  public FoxDen_User__c foxDenUser;
  public S3User__c s3User;

  public void createForAccount(Account account) {    
    
    Pkg packageRepo = new Pkg();
    Schedule scheduleRepo = new Schedule();
    Product productRepo = new Product();
    Plan planRepo = new Plan();
    CustomSchedule customScheduleRepo = new CustomSchedule();
    NegotiatedProduct npRepo = new NegotiatedProduct();
    SingleChargeOverride scoRepo = new SingleChargeOverride();
    RecurringChargeOverride rcoRepo = new RecurringChargeOverride();
    ScheduleOverride soRepo = new ScheduleOverride();
    RateOverride roRepo = new RateOverride();
    Rate rateRepo = new Rate();   
    ChargeCodeType chargeCodeTypeRepo = new ChargeCodeType();
    ChargeCode chargeCodeRepo = new ChargeCode(); 
    PlanAssignment planAssignmentRepo = new PlanAssignment();
    subscription = MockSubscription.getNewSubscription();
    foxDenUser = MockFoxDenUser.getNewFoxDenUser();
    s3User = MockS3User.getNewS3User();

    String emailContext = '{"package":{"name":"Meeting Free Trial"}, "card":{"callMeAnchorText": "callme.readytalk.com", "callMeAnchorType": "callme", "callMeText": "Audio & Online Meetings", "renderVOIPLinkData": true }, "startButton":{"renderStartMeetingButton": true, "startMeetingButtonText": "Start My First Meeting Now"} }';

   Test.startTest();

    pkg = packageRepo.savePackage('fooPackage', 'ACCESS_CODE', 'A test package', emailContext);
    quantityPkg = packageRepo.savePackage('quantityPackage', 'ACCESS_CODE', 'A test package', emailContext);
    quantityPkg.quantityEnabled__c = true;
    update quantityPkg;
    schedule = scheduleRepo.saveSchedule('fooSchedule', 'A test schedule', 'Audio', Math.Random() * 100);
    product = productRepo.saveProduct('fooProduct', pkg.Id, 49.00, 'INVOICE', schedule.Id, 0.00, 'WEB', true);
    plan = planRepo.savePlan('fooPlan', account.Id, pkg.Id, 'ACCESS_CODE', '1/1/2013', null, null, null);
    fdPlan = planRepo.savePlan('fdPlan', account.Id, pkg.Id, 'FOXDEN_USER', '1/1/2013', null, null, null);
    s3Plan = planRepo.savePlan('s3Plan', account.Id, pkg.Id, 'S3_USER', '1/1/2013', null, null, null);
    quantityPlan = planRepo.savePlan('quantityPlan', account.Id, quantityPkg.Id, 'SEAT', '1/1/2013', null, '10', '1/1/2017');
    customSchedule = customScheduleRepo.saveCustomSchedule('fooCustomSchedule', account.Id, schedule.Id, 'A test custom schedule', false);
    negotiatedProduct = npRepo.saveNegotiatedProduct('fooNP', product.Id, plan.Id, account.Id);
    singleChargeOverride = scoRepo.saveSingleChargeOverride('fooSCO', 0.00, negotiatedProduct.Id, 49.00, '1/1/2013', null);
    recurringChargeOverride = rcoRepo.saveRecurringChargeOverride('fooRCO', 0.00, negotiatedProduct.Id, 1.00, 'INVOICE', '1/1/2013', null);
    scheduleOverride = soRepo.saveScheduleOverride('fooSO', negotiatedProduct.Id, schedule.Id, customSchedule.Id, '2/1/2013', null);
    chargeCodeType = chargeCodeTypeRepo.saveChargeCodeType('DTF', 'Audio: Domestic Toll-Free Usage', 'Dom Toll-Free');
    chargeCode =  chargeCodeRepo.saveChargeCode('USA-TF', chargeCodeType.Id, 'USA', 'United States Toll Free');
    rate = rateRepo.saveRate('fooRate', chargeCode.Id, '1/1/2013', 0.1000, schedule.Id, null, Math.Random() * 9999999);
    rateOverride = roRepo.saveRateOverride(chargeCode.Id, customSchedule.Id, 'fooRateOverride', 0.2000, '2/1/2013', null);  

    unassignedPackage = packageRepo.savePackage('unassignedPackage', 'ACCESS_CODE', 'A test package', emailContext);
    unassignedPlan = planRepo.savePlan('unassignedPlan', account.Id, unassignedPackage.Id, 'ACCESS_CODE', '1/1/2013', null, null, null);
    unassignedSchedule = scheduleRepo.saveSchedule('unassignedSchedule', 'A test schedule #2', 'Audio', Math.Random() * 101);

    unassignedPackage2 = packageRepo.savePackage('unassignedPackage2', 'ACCESS_CODE', 'A test package #2', emailContext);
    unassignedProduct = productRepo.saveProduct('unassignedProduct', unassignedPackage2.Id, 49.00, 'INVOICE', schedule.Id, 0.00, 'WEB', true);    

    accessCodePlanAssignment = planAssignmentRepo.savePlanAssignment('acPlanAssignment', plan.Id, 'Subscription__c', subscription.Id, Date.today(), null);
    foxDenPlanAssignment = planAssignmentRepo.savePlanAssignment('fdPlanAssignment', fdPlan.Id, 'FoxDen_User__c', foxDenUser.Id, Date.today(), null);
  }
}