force-app/main/default/objects/ChargeCode__c/ChargeCode__c.object-meta.xml
<CustomObject>
    <label>Charge Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeCode__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Description</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargeCode__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Object Id</description>
    <externalId>true</externalId>
    <inlineHelpText>Object Id - do not set manually in SF. Only used for data load.</inlineHelpText>
    <label>Object Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CustomSchedule__c/CustomSchedule__c.object-meta.xml
<CustomObject>
    <label>Custom Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomSchedule__c/fields/baseSchedule__c.field-meta.xml
<CustomField>
    <fullName>baseSchedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>Custom Schedules</relationshipLabel>
    <relationshipName>CustomSchedules</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomSchedule__c/fields/baseScheduleType__c.field-meta.xml
<CustomField>
    <fullName>baseScheduleType__c</fullName>
    <description>Parent Schedule Usage Type</description>
    <formula>TEXT(baseSchedule__r.scheduleType__c)</formula>
    <inlineHelpText>Parent Schedule Usage Type</inlineHelpText>
    <label>Schedule Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/RateOverride__c.object-meta.xml
<CustomObject>
    <label>Rate Override</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateOverride__c/fields/baseRate__c.field-meta.xml
<CustomField>
    <fullName>baseRate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Base Rate</label>
    <referenceTo>ReadyTalk_Rate__c</referenceTo>
    <relationshipLabel>Rate Overrides</relationshipLabel>
    <relationshipName>RateOverrides</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/fields/chargeCode__c.field-meta.xml
<CustomField>
    <fullName>chargeCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Charge Code</label>
    <referenceTo>ChargeCode__c</referenceTo>
    <relationshipLabel>Rate Overrides</relationshipLabel>
    <relationshipName>Rate_Overrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/fields/customSchedule__c.field-meta.xml
<CustomField>
    <fullName>customSchedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Custom Schedule</label>
    <referenceTo>CustomSchedule__c</referenceTo>
    <relationshipLabel>Rate Overrides</relationshipLabel>
    <relationshipName>RateOverrides</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/fields/ReadyTalk_Rate__c.field-meta.xml
<CustomField>
    <fullName>ReadyTalk_Rate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Rate</label>
    <precision>14</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RateOverride__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/ReadyTalk_Rate__c.object-meta.xml
<CustomObject>
    <label>ReadyTalk Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ReadyTalk Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/chargeCode__c.field-meta.xml
<CustomField>
    <fullName>chargeCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge Code</label>
    <referenceTo>ChargeCode__c</referenceTo>
    <relationshipLabel>ReadyTalk Rates</relationshipLabel>
    <relationshipName>ReadyTalk_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/ReadyTalk_Rate__c.field-meta.xml
<CustomField>
    <fullName>ReadyTalk_Rate__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>ReadyTalk Rate</label>
    <precision>14</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>ReadyTalk Rates</relationshipLabel>
    <relationshipName>ReadyTalk_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Description</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/scheduleType__c.field-meta.xml
<CustomField>
    <fullName>scheduleType__c</fullName>
    <description>Usage Type for this Schedule</description>
    <inlineHelpText>Select the appropriate usage type for this schedule</inlineHelpText>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audio</fullName>
                <default>true</default>
                <label>Audio</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Hosting</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RateListController.cls
global with sharing class RateListController {
  private Id accountId;
  private Id scheduleId;
  private Id customScheduleId;
  private String scheduleType;

  public RateListController(ApexPages.StandardController controller) {
    this.accountId = ApexPages.currentPage().getParameters().get('id');    
    this.scheduleId = ApexPages.currentPage().getParameters().get('baseScheduleId');   
    this.scheduleType = ApexPages.currentPage().getParameters().get('scheduleType');   
    this.customScheduleId = ApexPages.currentPage().getParameters().get('customScheduleId');   
  }

  /**
  * Remote Action to get Header Information (i.e. Base Schedule Name, Account Name, Account Number)
  */
  @RemoteAction
  global static Map<String,String> getRateListHeaderInformation(String accountId, String baseScheduleId, String customScheduleId){
    Map<String, String> obj = new Map<String, String>();
    Schedule__c schedule = (Schedule__c) RTDatabaseUtils.getEntireSObject(new Schedule__c(), baseScheduleId);
    Account account = (Account) RTDatabaseUtils.getEntireSObject(new Account(), accountId);

    obj.put('baseScheduleName', schedule.Name);
    obj.put('accountName', account.Name);
    obj.put('accountNumber', account.AccountNumber);
    return obj;
  }

  /**
  * Remote Action to get Header Information (i.e. Base Schedule Name, Account Name, Account Number)
  */
  @RemoteAction
  global static Map<String,String> getRateListHeaderInformationForEdit(String baseScheduleId){
    Map<String, String> obj = new Map<String, String>();
    Schedule__c schedule = (Schedule__c) RTDatabaseUtils.getEntireSObject(new Schedule__c(), baseScheduleId);

    obj.put('baseScheduleName', schedule.Name);
    obj.put('description', schedule.description__c);
    obj.put('objectId', schedule.objectId__c.toPlainString());
    obj.put('scheduleType', schedule.scheduleType__c);
    return obj;
  }  

  /*
  * Remote Action to get a list of Rates by type.  Bundled into a List of RateDTO objects
  */
  @RemoteAction
  global static List<RateDTO> getRatesByType(String customOrStandard, String id, List<String> chargeCodeTypes){
    List<RateDTO> rateDTOList; 

    if('Standard'.equals(customOrStandard)){
      rateDTOList = getRatesByScheduleIdAndChargeCodeType(id, chargeCodeTypes);
    }
    else if('Custom'.equals(customOrStandard)){
      rateDTOList = getRatesByCustomScheduleIdAndChargeCodeType(id, chargeCodeTypes);
    }

    return rateDTOList;
  }

  /*
  * Remote Action to get a list of Rates by schedule id and charge code type.
  */
  @RemoteAction
  global static List<RateDTO> getRatesByScheduleIdAndChargeCodeType(String scheduleId, List<String> chargeCodeTypes){
    Schedule scheduleLookup = new Schedule();
    Schedule__c schedule = scheduleLookup.findByIdAndRateChargeCodeType(scheduleId, chargeCodeTypes);
    Map<Id, RateDTO> chargeCodeToRateDTOMap = new Map<Id, RateDTO>();

    if(schedule == null)
      return chargeCodeToRateDTOMap.values();   

    for (ReadyTalk_Rate__c rate : schedule.ReadyTalk_Rates__r) {      
      RateDTO rateDTO = new RateDTO();             
      Boolean inMap = chargeCodeToRateDTOMap.containsKey(rate.chargeCode__c);  
      Boolean inRange = RTUtils.dateInRange(Date.today(), rate.startDate__c, rate.endDate__c, true, false);

      //If this charge code is not in the map, then we need to add it
      if(!inMap){
        chargeCodeToRateDTOMap.put(rate.chargeCode__c, rateDTO);
      }  

      //See if this is the current rate; if so, then set it on the rateDTO
      if(inRange){
        chargeCodeToRateDTOMap.get(rate.chargeCode__c).currentRate = rate.clone(true,true,true,true);            
      }

      //Add this rate to the List of Base Schedule Rates (keep these separate from overrides).
      if(chargeCodeToRateDTOMap.get(rate.chargeCode__c).baseScheduleRates == null)
        chargeCodeToRateDTOMap.get(rate.chargeCode__c).baseScheduleRates = new List<ReadyTalk_Rate__c>();
          
      chargeCodeToRateDTOMap.get(rate.chargeCode__c).baseScheduleRates.add(rate);
    }

    //Get the List of RateDTO objects from the map
    List<RateDTO> rateDTOList = chargeCodeToRateDTOMap.values();
    
    //Sort the List (see compareTo method on the RateDTO class)
    rateDTOList.sort();
    return rateDTOList;
  }

  /*
  * Remote Action to get a list of Rates by Custom Schedule Id and Charge Code Type
  */
  @RemoteAction
  global static List<RateDTO> getRatesByCustomScheduleIdAndChargeCodeType(String customScheduleId, List<String> chargeCodeTypes){
    CustomSchedule customScheduleLookup = new CustomSchedule();

    //Lookup the custom schedule
    CustomSchedule__c customSchedule = customScheduleLookup.findById(customScheduleId);

    if(customSchedule == null)
      return new List<RateDTO>();

    //Get all of the base schedule rates (as a DTO from the method above)
    List<RateDTO> rateDTOList = getRatesByScheduleIdAndChargeCodeType(customSchedule.baseSchedule__c, chargeCodeTypes);

    //If there are no Rate Override objects associated to this custom schedule, just return the rateDTOList
    if(customSchedule.RateOverrides__r == null)
      return rateDTOList;

    //Iterate through the rateDTO and set current and overrides 
    for(RateDTO rateDTO : rateDTOList){

      Boolean haveEndedBaseScheduleRate = false;

      for(RateOverride__c rateOverride : customSchedule.RateOverrides__r){    
        //Make sure we're adding rate overrides to the correct rate (match it up with it's parent)
        if(rateOverride.chargeCode__c == rateDTO.currentRate.chargeCode__c){

          /*
          //Need to put an "end date" on the standard schedule that has a NULL end date (if and only if this override also has a null end date)
          for(ReadyTalk_Rate__c baseScheduleRate : rateDTO.baseScheduleRates){
            if(!haveEndedBaseScheduleRate && 
              (baseScheduleRate.endDate__c == null || baseScheduleRate.endDate__c >= Date.newInstance(3000, 1, 1)) 
              && RTUtils.dateInRange(rateOverride.startDate__c, baseScheduleRate.startDate__c, baseScheduleRate.endDate__c, true, true)){
                baseScheduleRate.endDate__c = rateOverride.startDate__c;              
                haveEndedBaseScheduleRate = true;
            }
          }
          */

          //Set this override to the current rate if it's in range
          if(RTUtils.dateInRange(Date.today(), rateOverride.startDate__c, rateOverride.endDate__c, true, false)){                        
            rateDTO.currentRate.ReadyTalk_rate__c = rateOverride.ReadyTalk_rate__c;
            rateDTO.currentRate.startDate__c = rateOverride.startDate__c;
            rateDTO.currentRate.endDate__c = rateOverride.endDate__c;
          }
          
          //Add this override to the list
          if(rateDTO.rateOverrides == null)
            rateDTO.rateOverrides = new List<RateOverride__c>();

          rateDTO.rateOverrides.add(rateOverride);
        }
      }
    }

    return rateDTOList;
  }

  /*
  * Remote Action to get Rates from an Account Id, Charge Code Types and Schedule Type
  */
  @RemoteAction 
  global static List<RateDTO> getAccountRates(String accountId, List<String> chargeCodeTypes, String scheduleType){
    CustomSchedule customScheduleLookup = new CustomSchedule();
    List<RateDTO> rateDTOList = new List<RateDTO>();

    List<CustomSchedule__c> customSchedules = customScheduleLookup.findByAccountId(accountId);
    for(CustomSchedule__c customSchedule : customSchedules){
      if(customSchedule.baseScheduleType__c.equals(scheduleType) && customSchedule.isDefault__c){
        rateDTOList = getRatesByCustomScheduleIdAndChargeCodeType(customSchedule.Id, chargeCodeTypes);
        break;
      }
    }

    return rateDTOList;
  }

  /*
  * Remote Action to create a custom schedule and save rate overrides under that custom schedule
  */
  @RemoteAction
  global static void saveNewCustomScheduleAndRateOverrides(String accountId, String baseScheduleId, String name, String description, String rateChangeStartDate, Map<String,String> rateOverrides){
    /* SFB-1071: Need to be able to add/create new custom schedule without making a rate change.
    if(rateOverrides==null || rateOverrides.isEmpty())
      throw new ValidationException('You must change at least one rate.');  
    */

    CustomSchedule customScheduleRepo = new CustomSchedule();
    CustomSchedule__c newCustomSchedule = customScheduleRepo.saveCustomSchedule(name, accountId, baseScheduleId, description, false);
    saveRateOverrides(newCustomSchedule.Id, rateChangeStartDate, rateOverrides);
  }

  /*
  * Remote Action to save rate overrides and end the latest rate override
  */
  @RemoteAction
  global static void saveRateOverrides(String customScheduleId, String rateChangeStartDate, Map<String,String> rateOverrides){
    RateOverride roRepo = new RateOverride();

    for(String key : rateOverrides.keySet()){

      //Expire the most current rate override
      roRepo.expirePreviousOverride(key, customScheduleId, rateChangeStartDate);

      //Save the new Rate Override
      roRepo.saveRateOverride(key, customScheduleId, key+'-override', Decimal.valueOf(rateOverrides.get(key).replaceAll('\\$', '')), rateChangeStartDate, null);
    }  
  }

  /*
  * Remote Action to save base rate overrides and end the latest rateOverride if it meets or exceeds the entered price
  */
  @RemoteAction
  global static String saveBaseScheduleRateOverride(String scheduleId, String rateChangeStartDate, String name, String description, String objectId, String scheduleType, String endRateOverrides, Map<String,String> rateOverrides){
    Rate rateRepo = new Rate();
    RateOverride rateOverrideRepo = new RateOverride();
    Schedule scheduleRepo = new Schedule();    

    //Save the schedule information
    Schedule__c s = (Schedule__c) new Schedule.builderValidator()
      .forObject(new Schedule__c())
      .set('id', scheduleId)
      .set('name', name)
      .set('description__c', description)
      .set('scheduleType__c', scheduleType)
      .set('objectId__c', Double.valueOf(objectId))
      .buildAndValidate()
      .save();    

    if(rateOverrides.size() > 1){
      throw new ValidationException('Cannot end more than one base schedule rate at a time.  Do them separately!');
    }

    if(rateOverrides.size() <= 0){
     throw new ValidationException('You must change at least one base schedule rate!'); 
    }      

    Double maxRateObjectId = rateRepo.findMaxObjectId(Rate.table);    
    String updated = '';

    for(String chargeCodeId : rateOverrides.keySet()){      
      Decimal newRate = Decimal.valueOf(rateOverrides.get(chargeCodeId).replaceAll('\\$', ''));    

      //Expire the base rate being changed
      rateRepo.expirePreviousRate(chargeCodeId, scheduleId, rateChangeStartDate);

      //Save the new rate
      rateRepo.saveRate(chargeCodeId, chargeCodeId, rateChangeStartDate, newRate, scheduleId, null, maxRateObjectId+1);

      //Save ALL rate overrides that do no exceed the new rate
      if('on'.equals(endRateOverrides)){
        List<RateOverride__c> ros = rateOverrideRepo.findByBaseScheduleAndChargeCodeAndNullEndDateAndRateAbove(scheduleId, chargeCodeId, newRate);

        for(RateOverride__c ro : ros){
          Date d = Date.parse(rateChangeStartDate);
          if(ro.startDate__c > d)
            ro.endDate__c = ro.startDate__c;
          else
            ro.endDate__c = Date.parse(rateChangeStartDate);
        }

        try{
          Database.update(ros);       
          updated = updated+'Updated '+ros.size()+' Rate Override Records.';             

        }
        catch (Exception e){
          throw new ValidationException('Error while saving: '+e.getMessage());
        }      
      }
    }    

    return updated;
  }

  public String getAccountId() {
    return this.accountId;
  }

  public String getScheduleId() {
    return this.scheduleId;
  } 

  public String getCustomScheduleId() {
    return this.customScheduleId;
  }

  public String getScheduleType() {
    return this.scheduleType;
  }

}