force-app/main/default/objects/ChargeCode__c/ChargeCode__c.object-meta.xml
<CustomObject>
    <label>Charge Code</label>
    <nameField>
        <label>Charge Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeCodeType__c/ChargeCodeType__c.object-meta.xml
<CustomObject>
    <label>Charge Code Type</label>
    <nameField>
        <label>Charge Code Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Code Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeCodeType__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/ChargeCodeType__c/fields/objectId__c.field-meta.xml
<CustomField>
    <fullName>objectId__c</fullName>
    <description>Object Id</description>
    <externalId>true</externalId>
    <inlineHelpText>Object Id - do not set via SF. Only used for data initialization</inlineHelpText>
    <label>Object Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/ReadyTalk_Rate__c.object-meta.xml
<CustomObject>
    <label>ReadyTalk Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ReadyTalk Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/chargeCode__c.field-meta.xml
<CustomField>
    <fullName>chargeCode__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Charge Code</label>
    <referenceTo>ChargeCode__c</referenceTo>
    <relationshipLabel>ReadyTalk Rates</relationshipLabel>
    <relationshipName>ReadyTalk_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ReadyTalk_Rate__c/fields/schedule__c.field-meta.xml
<CustomField>
    <fullName>schedule__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Schedule</label>
    <referenceTo>Schedule__c</referenceTo>
    <relationshipLabel>ReadyTalk Rates</relationshipLabel>
    <relationshipName>ReadyTalk_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Schedule__c/Schedule__c.object-meta.xml
<CustomObject>
    <label>Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule__c/fields/description__c.field-meta.xml
<CustomField>
    <fullName>description__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Description</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule__c/fields/scheduleType__c.field-meta.xml
<CustomField>
    <fullName>scheduleType__c</fullName>
    <description>Usage Type for this Schedule</description>
    <inlineHelpText>Select the appropriate usage type for this schedule</inlineHelpText>
    <label>Schedule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Audio</fullName>
                <default>true</default>
                <label>Audio</label>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Hosting</fullName>
            </value>
            <value>
                <fullName>System</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Schedule.cls
public with sharing class Schedule extends AbstractRepository {

  public final static String table = 'Schedule__c';
  public final static String columns = 'id,name,description__c,scheduleType__c,objectId__c';   
  
  /**
   * Validations
   */    
  public class builderValidator extends AbstractValidator {  
    
    public override void validate(SObject o) {  
      Schedule__c schedule = (Schedule__c)o;
      
    }        
  } 
  
  /**
   * Queries
   */
  public List<Schedule__c> findAllSchedules(){
    return (List<Schedule__c>) Database.query(selectBuilder(table,columns,'order by name'));
  }

  public List<Schedule__c> findAllSchedulesByType(String type){
    return (List<Schedule__c>) Database.query(selectBuilder(table,columns,'where scheduleType__c = :type order by name desc'));
  }
  
  public Schedule__c findById(Id id) {
    String columnsWithRelations = columns+innerSelectBuilder('ReadyTalk_Rates__r', Rate.columns+relationBuilder('chargeCode__r', ChargeCode.columns)+',chargeCode__r.chargeCodeType__r.Name', 'order by chargeCode__r.description__c, chargeCode__r.chargeCodeType__c');
    List<Schedule__c> schedules = Database.query(selectBuilder(table,columnsWithRelations,'where id = :id'));
    if(schedules.size() > 0)
      return schedules.get(0);
    else
      return null;
  }

  public Schedule__c findByIdAndRateChargeCodeType(Id id, List<String> chargeCodeTypes){    
    String columnsWithRelations = columns+innerSelectBuilder('ReadyTalk_Rates__r', Rate.columns+relationBuilder('chargeCode__r', ChargeCode.columns)+',chargeCode__r.chargeCodeType__r.Name', 'where chargeCode__r.chargeCodeType__r.Name in :chargeCodeTypes order by chargeCode__r.description__c, chargeCode__r.chargeCodeType__c');
    List<Schedule__c> schedules = Database.query(selectBuilder(table,columnsWithRelations,'where id = :id'));
    if(schedules.size() > 0)
      return schedules.get(0);
    else
      return null;    
  }

  /**
   * Helper for save
   */
  public Schedule__c saveSchedule(String name, String description, String scheduleType, Double objectId) {
    Schedule__c s = (Schedule__c) new Schedule.builderValidator()
      .forObject(new Schedule__c())
      .set('name', name)
      .set('description__c', description)
      .set('scheduleType__c', scheduleType)
      .set('objectId__c', objectId)
      .buildAndValidate()
      .save();    
    return s;
  }
}