force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Related_SCA__c.field-meta.xml
<CustomField>
    <fullName>Related_SCA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related SCA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request_for_Change__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Standard Change Accreditation Request</value>
        </filterItems>
        <filterItems>
            <field>Request_for_Change__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Request_for_Change__c</referenceTo>
    <relationshipLabel>Standard RFCs</relationshipLabel>
    <relationshipName>Request_for_Change</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Schedule_Repeat_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Repeat_Frequency__c</fullName>
    <label>Schedule Repeat Frequency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Monthly on 1st {Friday}</fullName>
            </value>
            <value>
                <fullName>Monthly on 2nd {Friday}</fullName>
            </value>
            <value>
                <fullName>Monthly on 3rd {Friday}</fullName>
            </value>
            <value>
                <fullName>Monthly on Last {Friday}</fullName>
            </value>
            <value>
                <fullName>Weekly on {Friday}</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Schedule_Start_Day__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Start_Day__c</fullName>
    <label>Schedule Start Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CAB Approved</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateRequestForChangeControllerTest.cls
/*
 * Test class for CreateRequestForChangeController apex class
*/
@isTest
public class CreateRequestForChangeControllerTest {
	
    @isTest
    public static void testPageInitMethods() {
  //  	Request_For_Change__c testRFCRelatedSCA = PGITestUtilities.createRFC(false);
  //      testRFCRelatedSCA.Status__c = 'Approved';
  //      testRFCRelatedSCA.RecordTypeId = PGITestUtilities.RFCStandardRT;
  //      testRFCRelatedSCA.Schedule_Start_Day__c = System.Today();
  //      testRFCRelatedSCA.Schedule_Repeat_Frequency__c = 'Daily';
  //      insert testRFCRelatedSCA;
        
  //      Request_For_Change__c testRecord = PGITestUtilities.createRFC(false);
  //      testRecord.Related_SCA__c = testRFCRelatedSCA.Id;
  //      testRecord.Schedule_Start_Day__c = System.Today();
  //      testRecord.Schedule_Repeat_Frequency__c = 'Daily';
  //      insert testRecord;

  //      RFC_Risk_Assessment__c testRiskAssessment = new RFC_Risk_Assessment__c(Request_For_Change__c = testRecord.Id);
  //      insert testRiskAssessment;
  //      RFCImpact__c testRFCImpact = new RFCImpact__c(RequestForChange__c = testRecord.Id);
  //      insert testRFCImpact;

  //      Test.startTest();

  //   	PageReference pageRef = Page.CreateRequestForChange;
  //      Test.setCurrentPage(pageRef);
  //   	ApexPages.StandardController sc = new ApexPages.StandardController(testRecord);
  //   	CreateRequestForChangeController controller = new CreateRequestForChangeController(sc);
		//Boolean hasBeenPickedUp = controller.hasBeenPickedUp;
  //      Boolean hasSCASelect = controller.hasSCASelected;
  //      List<LayoutDescriberHelper.LayoutSection> testLayoutSectionsGetSet = controller.layoutSections;
  //      List<LayoutDescriberHelper.AssignmentModel> testAssignmentSectionsGetSet = controller.assignmentSections;
  //      System.assert(controller.createFromScratch() == null);
  //      System.assert(!controller.promptForRCA);
  //      System.assert(controller.prSelectRelatedSCA() == null);
  //      System.assertEquals(controller.scheduleRepeatFrequency.isEmpty(), false);
  //      // populate frequency and assert no errors
  //      controller.selectedScheduleRepeatFrequency = new String[]{'Daily'};
  //      System.assert(controller.createRFC() != null);
  //      System.assert(!controller.relatedSCAs.isEmpty());

  //      Test.stopTest();
    }


}