force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ServiceNow_Change_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <inlineHelpText>Record Ownership will be auto set based off this field when the record is created</inlineHelpText>
    <label>Assignment Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PGi-RFC-EU-Branding&amp;Conf Email</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-EU-Tier 1-CS (Audio)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Audio Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Business Intelligence (BI)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-GM Tools &amp; Integration Proj</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-GM Web Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-iMeet Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-InfoSec</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-QA</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-QA/DEV Lab</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 2-Deskside Support</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 2-Integrations</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Audio Applications</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Database Operations</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-iMeet Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Network</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SaaS Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SAN Admin</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SRE (Denver)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Systems Admin</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Systems Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Telco</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Voice Delivery</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Agenday</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Audio Interoperabili</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Database Development</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D (Customer Sites)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D(GM Dsktp&amp;Phone)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D (GM Mobile Phone)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D (HUB&amp;MyInfo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Planned_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_End_Date_Time__c</fullName>
    <inlineHelpText>The time visible is dependent on your user settings.</inlineHelpText>
    <label>Planned End Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Planned_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Planned_Start_Date_Time__c</fullName>
    <inlineHelpText>The time visible is dependent on your user settings.</inlineHelpText>
    <label>Planned Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <inlineHelpText>Select level of risk to the business</inlineHelpText>
    <label>Risk</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
                <color>#0B6FCE</color>
                <label>Normal</label>
            </value>
            <value>
                <fullName>Urgent</fullName>
                <color>#78C953</color>
                <label>Urgent</label>
            </value>
            <value>
                <fullName>Emergency</fullName>
                <color>#E27001</color>
                <label>Emergency</label>
            </value>
            <value>
                <fullName>Vendor</fullName>
                <color>#A845DC</color>
                <label>Vendor</label>
            </value>
            <value>
                <fullName>Release</fullName>
                <color>#F3D904</color>
                <label>Release</label>
            </value>
            <value>
                <fullName>Unauthorized</fullName>
                <color>#A53711</color>
                <label>Unauthorized</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssignToMeListBtnRFCControllerTest.cls
@isTest
public class AssignToMeListBtnRFCControllerTest {
static testmethod void testupdateRecord(){
            Request_for_Change__c objRFC = new Request_for_Change__c();
            objRFC.Assignment_Group__c = 'PGi-RFC-GL-Audio Projects';
            objRFC.Type__c = 'Normal';
            objRFC.Risk__c = 'Low';
            objRFC.Planned_Start_Date_Time__c = System.today();
            objRFC.Planned_End_Date_Time__c = System.today().addDays(2);
            INSERT objRFC;
        List<Request_for_Change__c> rfcList = New List<Request_for_Change__c>();
        rfcList.add(objRFC);
        Test.StartTest(); 

			ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(rfcList);
        ssc.setSelected(rfcList);
			AssignToMeListBtnRFCController obj = New AssignToMeListBtnRFCController(ssc);
        obj.assignRecords();
        obj.returnToHomepage();
		Test.StopTest();
        Request_for_Change__c rfcObj =[SELECT Id,Assigned_To__c FROM Request_for_Change__c WHERE ID =:objRFC.Id];
        System.assertEquals(rfcObj.Assigned_To__c, UserInfo.getUserId());
    }
}