force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/isWithdrawRequestClicked__c.field-meta.xml
<CustomField>
    <fullName>isWithdrawRequestClicked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isWithdrawRequestClicked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CAB Approved</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RFCWithdrawApproval.cls
public class RFCWithdrawApproval {
    private ApexPages.StandardController controller {get; set;}
    public RFCWithdrawApproval(ApexPages.StandardController std) {
        this.controller = std;
    }
    public PageReference withdraw() {
        Request_For_Change__c myObj = [SELECT isWithdrawRequestClicked__c, Status__c FROM Request_For_Change__c WHERE Id =: controller.getId()];
        if(myObj.Status__c == 'Approved') { 
	        myObj.Status__c = 'Draft'; 
            myObj.isWithdrawRequestClicked__c  = !myObj.isWithdrawRequestClicked__c ;
        } else if(myObj.Status__c == 'Complete' || myObj.Status__c == 'Unsuccessful') { 
	        myObj.Status__c = 'Approved'; 
        } else { 
	        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Withdrawing is only for Approved or Closed requests,if your request is Pending Approval then use the ' + 'Recall Approval Request'+ ' button down in the Approval area')); 
            return null;
        }
        try {
            update myObj;
        } catch (exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage())); 
        }
        return new PageReference('/' + myObj.Id);
    }
}