force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Related_SCA__c.field-meta.xml
<CustomField>
    <fullName>Related_SCA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related SCA</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Request_for_Change__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Standard Change Accreditation Request</value>
        </filterItems>
        <filterItems>
            <field>Request_for_Change__c.Status__c</field>
            <operation>equals</operation>
            <value>Approved</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Request_for_Change__c</referenceTo>
    <relationshipLabel>Standard RFCs</relationshipLabel>
    <relationshipName>Request_for_Change</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CAB Approved</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateRFCImpactControllerTest.cls
@isTest
public class CreateRFCImpactControllerTest {
	//@isTest
 //   public static void testPageInitMethods() {
 //   	Request_For_Change__c testRFCRelatedSCA = PGITestUtilities.createRFC(false);
 //       testRFCRelatedSCA.Status__c = 'Approved';
 //       testRFCRelatedSCA.RecordTypeId = PGITestUtilities.RFCStandardRT;
 //       insert testRFCRelatedSCA;
        
 //       Request_For_Change__c testRecord = PGITestUtilities.createRFC(false);
 //       testRecord.Related_SCA__c = testRFCRelatedSCA.Id;
 //       insert testRecord;

 //       RFC_Risk_Assessment__c testRiskAssessment = new RFC_Risk_Assessment__c(Request_For_Change__c = testRecord.Id);
 //       insert testRiskAssessment;
 //       RFCImpact__c testRFCImpact = new RFCImpact__c(RequestForChange__c = testRecord.Id);
 //       insert testRFCImpact;

 //       Test.startTest();

 //    	PageReference pageRef = Page.CreateRequestForChangeImpact;
 //       Test.setCurrentPage(pageRef);
 //    	ApexPages.StandardController sc = new ApexPages.StandardController(testRFCImpact);
 //    	CreateRequestForChangeImpactController controller = new CreateRequestForChangeImpactController(sc);
 //       List<LayoutDescriberHelper.LayoutSection> testLayoutSectionsGetSet = controller.layoutSections;
 //       List<LayoutDescriberHelper.AssignmentModel> testAssignmentSectionsGetSet = controller.assignmentSections;
 //       System.assert(controller.saveAndNext() != null);

 //       Test.stopTest();
 //   }
}