force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>CAB Approved</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RequestForChangeRetractApprovalTest.cls
@IsTest
public with sharing class RequestForChangeRetractApprovalTest {
	@isTest
	public static void testFailureController() {
    	Request_For_Change__c testRelatedRFCRecord = PGITestUtilities.createRFC(false);
        insert testRelatedRFCRecord;

		//ApexPages.StandardController sc = new ApexPages.StandardController(testRelatedRFCRecord);
		//RequestForChangeRetractApproval ext = new RequestForChangeRetractApproval(sc);
		//ext.retractApproval();
		//System.assertEquals([SELECT Status__c FROM Request_For_Change__c].Status__c, 'Approved');

		//PageReference pr = Page.RequestForChangeRetractApproval;
		//pr.getParameters().put('id', testRelatedRFCRecord.Id);
		//Test.setCurrentPage(pr);
		//ext.recordId = testRelatedRFCRecord.Id;
		//ext.retractApproval();
		//System.assertEquals([SELECT Status__c FROM Request_For_Change__c].Status__c, 'New');
	}
}