force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Assignment_Group__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group__c</fullName>
    <inlineHelpText>Record Ownership will be auto set based off this field when the record is created</inlineHelpText>
    <label>Assignment Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>PGi-RFC-EU-Branding&amp;Conf Email</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-EU-Tier 1-CS (Audio)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Audio Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Business Intelligence (BI)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-GM Tools &amp; Integration Proj</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-GM Web Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-iMeet Projects</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-InfoSec</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-QA</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-QA/DEV Lab</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 2-Deskside Support</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 2-Integrations</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Audio Applications</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Database Operations</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-iMeet Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Network</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SaaS Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SAN Admin</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-SRE (Denver)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Systems Admin</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Systems Ops</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Telco</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 3-Voice Delivery</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Agenday</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Audio Interoperabili</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-Database Development</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D (Customer Sites)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D(GM Dsktp&amp;Phone)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D (GM Mobile Phone)</fullName>
            </value>
            <value>
                <fullName>PGi-RFC-GL-Tier 4-R&amp;D (HUB&amp;MyInfo)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Request_for_Change__c/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is auto populated via code from the Custom Metadata settings list (https://na68.salesforce.com/m00?setupid=CustomMetadata)</description>
    <label>Approval Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Request_for_Change</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RFC_Settings__mdt/RFC_Settings__mdt.object-meta.xml
<CustomObject>
    <label>RFC Setting</label>
    <pluralLabel>RFC Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/RFC_Settings__mdt/fields/Assignment_Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Group_Name__c</fullName>
    <label>Assignment Group Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RFC_Settings__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ABM</fullName>
            </value>
            <value>
                <fullName>ACS</fullName>
            </value>
            <value>
                <fullName>ACSS</fullName>
            </value>
            <value>
                <fullName>ACT Automated Audio</fullName>
                <isActive>false</isActive>
                <label>ACT Automated Audio</label>
            </value>
            <value>
                <fullName>ACT Reserved Audio</fullName>
                <isActive>false</isActive>
                <label>ACT Reserved Audio</label>
            </value>
            <value>
                <fullName>ACT Webcast</fullName>
                <isActive>false</isActive>
                <label>ACT Webcast</label>
            </value>
            <value>
                <fullName>Adobe Connect</fullName>
            </value>
            <value>
                <fullName>Adobe - Outlook Toolbar</fullName>
                <isActive>false</isActive>
                <label>Adobe - Outlook Toolbar</label>
            </value>
            <value>
                <fullName>APS</fullName>
            </value>
            <value>
                <fullName>APSXML.DLL</fullName>
            </value>
            <value>
                <fullName>AVS</fullName>
            </value>
            <value>
                <fullName>AXIS</fullName>
            </value>
            <value>
                <fullName>BOB (Audio)</fullName>
            </value>
            <value>
                <fullName>Branding Editor</fullName>
            </value>
            <value>
                <fullName>Call Manager</fullName>
            </value>
            <value>
                <fullName>CES</fullName>
            </value>
            <value>
                <fullName>Clerical</fullName>
            </value>
            <value>
                <fullName>Cloud Loader</fullName>
            </value>
            <value>
                <fullName>DDS</fullName>
            </value>
            <value>
                <fullName>Desktop</fullName>
            </value>
            <value>
                <fullName>Direct Number Room</fullName>
                <isActive>false</isActive>
                <label>Direct Number Room</label>
            </value>
            <value>
                <fullName>Event Conferencing</fullName>
                <isActive>false</isActive>
                <label>Event Conferencing</label>
            </value>
            <value>
                <fullName>Event Conferencing - Greeted Entry</fullName>
            </value>
            <value>
                <fullName>Event Conferencing - Greeted Entry Connection</fullName>
                <isActive>false</isActive>
                <label>Event Conferencing - Greeted Entry Connection</label>
            </value>
            <value>
                <fullName>Event Conferencing - Passcode Entry</fullName>
            </value>
            <value>
                <fullName>Event Conferencing - Slide Assist</fullName>
                <isActive>false</isActive>
                <label>Event Conferencing - Slide Assist</label>
            </value>
            <value>
                <fullName>Event Portal</fullName>
            </value>
            <value>
                <fullName>GlobalMeet</fullName>
                <isActive>false</isActive>
                <label>GlobalMeet</label>
            </value>
            <value>
                <fullName>GlobalMeet.com</fullName>
            </value>
            <value>
                <fullName>GlobalMeet - Admin Portal (Conf. HUB)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RFC_Settings__mdt/fields/Product_Manager_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager_ID__c</fullName>
    <label>Manager ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RequestForChangeTriggerHandler.cls
public without sharing class RequestForChangeTriggerHandler extends TriggerHandler {
	public RequestForChangeTriggerHandler() {
		super('RequestForChangeTriggerHandler');
	}
	protected override void beforeInsert() {
		setOwnerFromAssignmentGroup(); //KEEP

		setApprovalManager();
	}
	protected override void beforeUpdate() {
		setOwnerFromAssignmentGroup();

		setApprovalManager();
		
	}
	protected override void afterUpdate() {
		
	}


	private void setApprovalManager() {
		for(Request_For_Change__c rfc: (List<Request_For_Change__c>)Trigger.new) {
			if(!String.isBlank(rfc.Assignment_Group__c)) {
				if(!String.isBlank(approvalManagerByAssignmentGroup.get(rfc.Assignment_Group__c))) {
					//TODO - rfc.Assignment_Group_Manager__c
					rfc.Product_Manager__c = approvalManagerByAssignmentGroup.get(rfc.Assignment_Group__c);
				}
			}
		}
	}

	private static Map<String, Id> approvalManagerByAssignmentGroup {get{
		if(approvalManagerByAssignmentGroup == null) {
			approvalManagerByAssignmentGroup = new Map<String, Id>();
			for(RFC_Settings__mdt setting: [SELECT Id, Product__c, Product_Manager_Id__c, Assignment_Group_Name__c FROM RFC_Settings__mdt]) {
				if(String.isNotBlank(setting.Assignment_Group_Name__c)) {
					approvalManagerByAssignmentGroup.put(setting.Assignment_Group_Name__c, setting.Product_Manager_ID__c);
				}
			}
		}
		return approvalManagerByAssignmentGroup;
	}set;}
	private void setOwnerFromAssignmentGroup() {
		for(Request_For_Change__c rfc: (List<Request_For_Change__c>)Trigger.new) {
			if(isChanged('Assignment_Group__c', rfc) && !String.isBlank(rfc.Assignment_Group__c)) {
				if(rfcQueueByName.get(rfc.Assignment_Group__c) != null) {
					rfc.OwnerId = rfcQueueByName.get(rfc.Assignment_Group__c);
				}
			}
		}
	}

	private static Map<String, Id> rfcQueueByName {get {
		if(rfcQueueByName == null) {
			rfcQueueByName = new Map<String, Id>();
			for(QueueSobject q: [SELECT QueueId, Queue.DeveloperName, Queue.Name FROM QueueSobject WHERE SobjectType = 'Request_For_Change__c']){
				rfcQueueByName.put(q.Queue.Name, q.QueueId);
			}	
		}
		return rfcQueueByName;
	} set;}
}