force-app/main/default/objects/Request_for_Change__c/Request_for_Change__c.object-meta.xml
<CustomObject>
    <description>Request for Change, also known as Change Management or RFC</description>
    <label>Request for Change</label>
    <nameField>
        <displayFormat>RFC-{00000}</displayFormat>
        <label>Request for Change</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request for Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Request_for_Change__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ServiceNow_Change_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignToMeListBtnRFCController.cls
public with sharing class AssignToMeListBtnRFCController {
    private ApexPages.StandardSetController standardController;
    public boolean noRecords{get; set;}
    
    public AssignToMeListBtnRFCController(ApexPages.StandardSetController standardController) {
        this.standardController = standardController;
        noRecords = false;
    }
  
    public void assignRecords(){
         Set<Id> selectedIds = new Map<Id, SObject>(standardController.getSelected()).keySet(); 
        if(!selectedIds.isEmpty()){
            Request_for_Change__c rfcObj = [SELECT Id, Assigned_To__c 
                                              FROM Request_for_Change__c 
                                              WHERE Id =:selectedIds];
            rfcObj.Assigned_To__c = UserInfo.getUserId();
            try{
                UPDATE rfcObj;
            }
            catch(Exception e){
            } 
        } else{
            noRecords = true;   
        } 

    }
    public Pagereference returnToHomepage(){ 
        return standardController.cancel();
    }
}