force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>This object handles departments (children of accounts) so accounts will not have children accounts.</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Business_Type__c</fullName>
    <label>Business Type</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Corporate Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrative Assistant</fullName>
            </value>
            <value>
                <fullName>Analyst</fullName>
            </value>
            <value>
                <fullName>C-Level/VP/Director</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Engineering</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Investor Relations</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Operations</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Product Marketing</fullName>
            </value>
            <value>
                <fullName>R&amp;D</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Telecom</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>HR Generalist</fullName>
            </value>
            <value>
                <fullName>HR Recruiting</fullName>
            </value>
            <value>
                <fullName>IT/IS</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
            <value>
                <fullName>Customer Service/Care/Support</fullName>
            </value>
            <value>
                <fullName>Accounting/Finance</fullName>
            </value>
            <value>
                <fullName>Procurement</fullName>
            </value>
            <value>
                <fullName>Exec - &quot;C&quot; Level</fullName>
            </value>
            <value>
                <fullName>Product Management</fullName>
            </value>
            <value>
                <fullName>Corporate Communications</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DoNotSolicit__c.field-meta.xml
<CustomField>
    <fullName>DoNotSolicit__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Ecomm: used in back office for company create</description>
    <label>DoNotSolicit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ECommerce_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>ECommerce_Account_Number__c</fullName>
    <label>ECommerce Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Interest__c.field-meta.xml
<CustomField>
    <fullName>Product_Interest__c</fullName>
    <label>Initial Product of Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Audio: GlobalMeet Audio</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Audio for Skype for Business</fullName>
            </value>
            <value>
                <fullName>Audio: GlobalMeet Webcast Managed Event</fullName>
            </value>
            <value>
                <fullName>Audio: Op. Assisted: Premium Event</fullName>
            </value>
            <value>
                <fullName>Audio: Op. Assisted: Standard Auditorium</fullName>
            </value>
            <value>
                <fullName>Bundle: GlobalMeet</fullName>
            </value>
            <value>
                <fullName>Bundle: GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Web: Cisco WebEx</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Active Host</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webcast</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webcast Managed Event</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Web for Microsoft Lync</fullName>
            </value>
            <value>
                <fullName>Web: GlobalMeet Webinar</fullName>
            </value>
            <value>
                <fullName>Web: iMeet Central</fullName>
            </value>
            <value>
                <fullName>Web: UCaaS</fullName>
            </value>
            <value>
                <fullName>Web: vCube</fullName>
            </value>
            <value>
                <fullName>Web: Webcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Z_Source__c.field-meta.xml
<CustomField>
    <fullName>Z_Source__c</fullName>
    <description>Source Value</description>
    <label>Z-Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>eCommerce</fullName>
            </value>
            <value>
                <fullName>Salesgateway</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadUpsertJSON.cls
@RestResource(urlMapping='/LeadUpsertJSON/*')
global with sharing class LeadUpsertJSON {
    global class LeadRequest{
       public  String leadId;
       public  String FirstName;
        public String LastName;
        public String Phone;
        public String Email;
        public String ECommerceAccountNumber;
        public Boolean ECommerceConvert;
        public String LeadSource;
        public String Company;
        public String Status;
        public String Street;
        public String City;
        public String State;
        public String PostalCode;
        public String Country;
        public Integer BusinessType;
        public Boolean DoNotSolicit;
        public String CompanyID;
        public String ProductOfInterest;
        public string Department;
        //public string Topic;
    }

    global class LeadResponse{
        String errorMessage;
        String leadId;
        String accountId;
        String contactId;
        String opportunityId;
    }
    
    @HttpPut
    global static LeadResponse upsertLeadJSON(){
       
        LeadRequest ldReq =  (LeadRequest)JSON.deserializestrict(
                        RestContext.request.requestbody.tostring(),LeadRequest.class);
        Lead ld = setLeadRecord(ldReq);
        upsert ld;
        //Savepoint sp = Database.setSavepoint();
        
        
        LeadUpsertJSON.LeadResponse resp = new LeadUpsertJSON.LeadResponse();
        ld = [select id, convertedaccountid, convertedcontactid, convertedopportunityid from lead where id = :ld.id];
        resp.leadid = ld.id;
        resp.accountId = ld.convertedaccountid;
        resp.contactId = ld.convertedContactid;
        resp.opportunityId = ld.convertedopportunityid;
        system.debug('resp: ' + resp);
        
       return resp;
    }
   
    public static lead setLeadRecord(LeadUpsertJSON.LeadRequest ldReq){
          
       String leadRecordTypeId = [Select Id From RecordType Where SobjectType = 'Lead' and Name LIKE '%PGi%'].Id;   
          
       Lead ld = new Lead();      
       ld.FirstName = ldReq.FirstName;
       ld.Id = ldReq.leadId;
       ld.LastName = ldReq.LastName;
       ld.Phone = ldReq.Phone;
       ld.Email = ldReq.Email;
       ld.ECommerce_Account_Number__c = ldReq.ECommerceAccountNumber;
       ld.ECommerce_Convert__c = ldReq.ECommerceConvert;
       ld.LeadSource = ldReq.LeadSource;
       ld.Company = ldReq.Company;
       ld.Status = ldReq.Status;
       ld.Street = ldReq.Street;
       ld.City = ldReq.City ;
       ld.State = ldReq.State;
       ld.PostalCode = ldReq.PostalCode ;
       ld.Country = ldReq.Country ;
       system.debug('country:'+ld.Country);
       ld.Business_Type__c= ldReq.BusinessType;
       ld.DoNotSolicit__c = ldReq.DoNotSolicit;
       ld.Product_Interest__c = ldReq.ProductOfInterest;
       ld.recordtypeid = leadRecordTypeId;
       ld.z_Source__c = Label.Default_Z_Source;
       ld.Department__c = ldreq.Department;
       //ld.Topic__c = ldreq.Topic;
       
       return ld;
    }
}