force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>This object handles departments (children of accounts) so accounts will not have children accounts.</description>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Department</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MockDepartment.cls
public class MockDepartment {

    public String Status = 'New';
    public String Name = 'Mock Department Object';
    public String ParentAccount = MockAccount.getNewAccount().id;
    public Id OwnerId = MockUser.getNewUser().Id;

    
    public void setupDepartment(Department__c d) {
        d.Status__c = Status;
        d.Name = Name;
        d.Parent_Account__c = ParentAccount;
        d.OwnerId = OwnerId;
    }
       
    public static Department__c getNewDepartment() {
        Department__c d = new Department__c();
        MockDepartment md = new MockDepartment();
        md.setupDepartment(d);
        System.runAs(new User(Id = UserInfo.getUserId())){
          Database.insert(d);
        }
        return d;
    }
    
    public Department__c getDepartment() {
        Department__c d = new Department__c();
        setupDepartment(d);        
        Database.insert(d);        
        return d;
    }
}