force-app/main/default/objects/S3User__c/S3User__c.object-meta.xml
<CustomObject>
    <label>Replay User</label>
    <nameField>
        <label>Replay User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replay Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S3User__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>CASESAFEID(Contact__r.Account.Id)</formula>
    <label>accountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Auth0_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Auth0_User_Id__c</fullName>
    <label>Auth0 User Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Replay Users</relationshipLabel>
    <relationshipName>Replay_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Replay Username (Email)</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/ProvisioningEmailSent__c.field-meta.xml
<CustomField>
    <fullName>ProvisioningEmailSent__c</fullName>
    <label>Provisioning Email Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Status_Description__c.field-meta.xml
<CustomField>
    <fullName>Status_Description__c</fullName>
    <label>Status Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/S3User.cls
public with sharing class S3User extends AbstractRepository {

  public final static String table = 'S3User__c';
  public final static String columns = 'id,Account__c,Auth0_User_Id__c,Contact__c,Date_Deleted__c,Inactive__c,Deleted_By__c,Email__c,Password__c,ProvisioningEmailSent__c,Status__c,Status_Description__c';

  /**
   * Validations
   */    
  public class builderValidator extends AbstractValidator {      
    public override void validate(SObject o) { 
      S3User__c user = (S3User__c)o; 
    }
  }
  
  /**
   * Queries
   */  
  public S3User__c findById(Id userId) {    
    return (S3User__c) Database.query(selectBuilder(table,columns,'where id = :userId limit 1'));
  }
}