force-app/main/default/objects/PGIServicesInformation__c/PGIServicesInformation__c.object-meta.xml
<CustomObject>
    <label>CPQ - Contract General Content</label>
    <nameField>
        <label>PGIPDFServicesInformation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Contract General Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGIServicesInformation__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <inlineHelpText>These values are defined by iContract, and adding values here that iContract does not use on its own will have no effect!</inlineHelpText>
    <label>Agreement Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subscription License Order</fullName>
            </value>
            <value>
                <fullName>Subscription License Agreement</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Rate Modification Amendment</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>TPx Service Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGIServicesInformation__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>These values are defined by iContract, and adding values here that iContract does not use on its own will have no effect!</inlineHelpText>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intro Table</fullName>
                <default>true</default>
                <label>Pre-Intro Table</label>
            </value>
            <value>
                <fullName>Intro</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Services and Pricing Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGIServicesInformation__c/fields/Version_History__c.field-meta.xml
<CustomField>
    <fullName>Version_History__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Version History</label>
    <referenceTo>Version_History__c</referenceTo>
    <relationshipLabel>CPQ - Contract General Content</relationshipLabel>
    <relationshipName>CPQ_Contract_General_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Version_History__c/Version_History__c.object-meta.xml
<CustomObject>
    <description>To store the details of Compared Versions</description>
    <label>Version History</label>
    <nameField>
        <label>Version History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Version Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/VersioningTriggerHandlerTest.cls
@isTest
public without sharing class VersioningTriggerHandlerTest {
    @testSetup static void setup() {
        PGIServicesInformation__c cgcObj= new PGIServicesInformation__c();
        cgcObj.Name='Test';
        cgcObj.Agreement_Type__c='Service Agreement';
        cgcObj.Order__c=2;
        cgcObj.Unique_ID__c='Test';
        cgcObj.Section__c='Intro';
        Insert cgcObj;
    }
    // static  testmethod void testSaveVersionHistory(){
    //     Test.startTest();
    //    PGIServicesInformation__c  cgcObj = [Select Name,Agreement_Type__c,Order__c,Unique_ID__c,Section__c from PGIServicesInformation__c where Name='Test'];
    //     List<Version_History__c> verHisLst =[Select Name from Version_History__c];
    //     Attachment att = new Attachment();
    //     att.Name='Test';
    //     att.ParentId=verHisLst[0].Id;
    //     Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    //     att.Body=bodyBlob;
    //     Insert att;
        
    //     System.assertEquals(verHisLst.size(), 1);
    //     test.stopTest();
    // }
    
    static  testmethod void testSaveAttachment(){
        Test.startTest();
       PGIServicesInformation__c  cgcObj = [Select Name,Agreement_Type__c,Order__c,Unique_ID__c,Section__c from PGIServicesInformation__c where Name='Test'];
        List<Version_History__c> verHisLst =[Select Name from Version_History__c];
        Attachment att = new Attachment();
        att.Name='Test';
        att.ParentId=verHisLst[0].Id;
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        att.Body=bodyBlob;
        Insert att;
        cgcObj .Name='Test1';
        update cgcObj ;
        List<Attachment> cretedAttachment = [Select Id,Name From Attachment];
        System.assertEquals(cretedAttachment.size(), 3);
        System.assertEquals(verHisLst.size(), 1);
        test.stopTest();
    }
}