force-app/main/default/objects/Associated_Rate__c/Associated_Rate__c.object-meta.xml
<CustomObject>
    <label>Associated Rate</label>
    <nameField>
        <label>Associated Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Rate__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <label>Default</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipName>Associated_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <label>Override</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Associated Rates</relationshipLabel>
    <relationshipName>Associated_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Rate_Name__c.field-meta.xml
<CustomField>
    <fullName>Rate_Name__c</fullName>
    <label>Rate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <label>Sales Rep</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>CONMAN_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/fields/Required_Approval_Billing__c.field-meta.xml
<CustomField>
    <fullName>Required_Approval_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required Approval: Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <label>Payment Plan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Subscription_License_Term_Months__c.field-meta.xml
<CustomField>
    <fullName>Subscription_License_Term_Months__c</fullName>
    <label>Subscription License Term(Months)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Custom field used to map Lead Description to Opportunity Description. By default, SFDC only maps the Lead Description field to the Contact Description field. This will allow for it to also be mapped to the Opportunity via Lead Mapping. A workflow rule on Opportunity will then update the standard Opportunity Description field on the page layout from this custom field.</description>
    <label>Description__c</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>CPQ - Rate</label>
    <nameField>
        <label>Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate_Name__c.field-meta.xml
<CustomField>
    <fullName>Rate_Name__c</fullName>
    <label>Agreement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <label>Recurrence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how the Rate is presented in iContract and on agreements.</description>
    <inlineHelpText>Affects how the Rate is presented in iContract and on agreements.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Usage</fullName>
                <default>true</default>
                <label>Usage</label>
            </value>
            <value>
                <fullName>Sub</fullName>
                <label>Subscription</label>
            </value>
            <value>
                <fullName>Once</fullName>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Commit</fullName>
                <label>Minimum Commitment</label>
            </value>
            <value>
                <fullName>Bundle</fullName>
                <label>Bundled Rate</label>
            </value>
            <value>
                <fullName>Access</fullName>
                <label>Access Type</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AssociatedRateTrigger_Test.cls
@isTest
public class AssociatedRateTrigger_Test {
    static testMethod void testInsertingNameNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Unique_ID__c='1');
        insert rate;

        Test.startTest();

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Custom Name', Description__c='Testing Description', Recurrence__c='Minute',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testInsertingDescriptionNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Unique_ID__c='1');
        insert rate;

        Test.startTest();
        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Custom Description', Recurrence__c='Minute',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testInsertingRecurrenceNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description',
                                   Recurrence__c='Minute', Unique_ID__c='1');
        insert rate;

        Test.startTest();
        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Custom Recurrence', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingNameFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Rate_Name__c = 'New Name';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingDescriptionFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Description__c = 'New Description';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingRecurrenceFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description',
                                   Recurrence__c='Minute', Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Recurrence__c = 'New Recurrence';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingToUnknownFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description',
                                   Recurrence__c='Minute', Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Rate__c = null;
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testInsertingUnknownFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description',
                                   Recurrence__c='Minute', Unique_ID__c='1');
        insert rate;

        Test.startTest();
        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingUnknownNameFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Test.startTest();
        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        testContract.Required_Approval_Billing__c = false;
        update testContract;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        associatedRate.Rate_Name__c = 'Updated Name';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingUnknownDescriptionFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Test.startTest();
        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        testContract.Required_Approval_Billing__c = false;
        update testContract;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        associatedRate.Description__c = 'Updated Description';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingUnknownRecurrenceFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Test.startTest();
        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        testContract.Required_Approval_Billing__c = false;
        update testContract;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        associatedRate.Recurrence__c = 'Updated Recurrence';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingWaivedNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description',
                                   Recurrence__c='Minute', Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Recurrence__c = 'Waived';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingPriceNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description',
                                   Recurrence__c='Minute', Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Recurrence__c='Minute', Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Override__c = 0.50;
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingDescriptionTwiceFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Description__c = 'New Description';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(true, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        testContract.Required_Approval_Billing__c = false;
        update testContract;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');

        associatedRate.Override__c = 0.50;
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testInsertingNameAccessTypeNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Type__c='Access', Unique_ID__c='1');
        insert rate;

        Test.startTest();

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Custom Name', Description__c='Custom Description', Recurrence__c='Custom', Rate__c=rate.Id, LicenseSet__c=licenseSet.Id, Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }

    static testMethod void testUpdatingNameAccessTypeNoFlagsBilling(){
        Opportunity testOppty = PGITestUtilities.getOpportunityDetails();
        insert testOppty;
        Account testAcct = PGITestUtilities.getAccountDetails();
        insert testAcct;
        CONMAN_Contract__c testContract = PGITestUtilities.getConManContractDetails(testAcct.Id, testOppty.Id);
        insert testContract;

        LicenseSet__c licenseSet = new LicenseSet__c(Name='Test LS',Subscription_License_Term_Months__c=12,
                                  Product_Name__c='Test LS',Price__c=58.54,Opportunity__c=testOppty.Id,
                                  Payment_Plan__c='Annual', PGi_Contract__c=testContract.Id);
        insert licenseSet;

        Rate__c rate = new Rate__c(Name='Arate', Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                   Type__c='Access', Unique_ID__c='1');
        insert rate;

        Associated_Rate__c associatedRate = new Associated_Rate__c(Rate_Name__c='Arate', Description__c='Testing Description', Recurrence__c='Minute',
                                                                   Rate__c=rate.Id, LicenseSet__c=licenseSet.Id,
                                                                   Sales_Rep__c=0.050, Default__c=0.070);
        insert associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];

        Test.startTest();
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'Contract starts at no Billing Approval');

        associatedRate.Rate_Name__c = 'New Name';
        associatedRate.Description__c = 'New Description';
        associatedRate.Recurrence__c = 'New Recurrence';
        update associatedRate;

        testContract = [SELECT Id, Required_Approval_Billing__c
                        FROM CONMAN_Contract__c WHERE Id = :testContract.Id];
        System.assertEquals(false, testContract.Required_Approval_Billing__c,
                            'New Billing Approval Value');
        Test.stopTest();
    }
}