force-app/main/default/objects/Associated_Rate__c/Associated_Rate__c.object-meta.xml
<CustomObject>
    <label>Associated Rate</label>
    <nameField>
        <label>Associated Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Rate__c/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipName>Associated_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Subscription License Order</fullName>
                <default>true</default>
                <label>Subscription License Order</label>
            </value>
            <value>
                <fullName>Subscription License Agreement</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Rate Modification Amendment</fullName>
            </value>
            <value>
                <fullName>Agent Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Email Order</fullName>
            </value>
            <value>
                <fullName>Gateway Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Gateway Subscription License Order</fullName>
            </value>
            <value>
                <fullName>Master Services Agreement</fullName>
            </value>
            <value>
                <fullName>Related Document</fullName>
            </value>
            <value>
                <fullName>WebEx Agreement</fullName>
            </value>
            <value>
                <fullName>WebEx Amend</fullName>
            </value>
            <value>
                <fullName>Wholesale Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Services Agreement</fullName>
            </value>
            <value>
                <fullName>Local Affiliate Service Agreement</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>TPx Service Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/recordTypes/iContract.recordType-meta.xml
<RecordType>
    <fullName>iContract</fullName>
    <active>true</active>
    <description>NA Contract going through the iContract system</description>
    <label>NA Contract</label>
</RecordType>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/CONMAN_Contract_Verbiage__c.object-meta.xml
<CustomObject>
    <description>Terms and Conditions are are specific to a PGi Contract and can be edited by Legal.</description>
    <label>PGi Contract Verbiage</label>
    <nameField>
        <label>PGi Contract Verbiage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Contract Verbiage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/fields/Contract_General_Content__c.field-meta.xml
<CustomField>
    <fullName>Contract_General_Content__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The Contract General Content that this Verbiage originated from.</inlineHelpText>
    <label>Contract General Content</label>
    <referenceTo>PGIServicesInformation__c</referenceTo>
    <relationshipLabel>PGi Contract Verbiage</relationshipLabel>
    <relationshipName>PGi_Contract_Verbiage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>The order in which this Verbiage appears on the PGi Contract.</inlineHelpText>
    <label>Order</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <inlineHelpText>Which PGi Contract is this Verbiage for?</inlineHelpText>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>PGi Contract Verbiage</relationshipLabel>
    <relationshipName>PGi_Contract_Verbiage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/fields/Pricing_Team_Changes_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Team_Changes_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the Deal Desk can edit this Verbiage. Legal can edit all Verbiage.</description>
    <inlineHelpText>Whether or not the Deal Desk can edit this Verbiage. Legal can edit all Verbiage.</inlineHelpText>
    <label>Pricing Team Changes Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>AT&amp;T SHELL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EMEA - TP Direct</fullName>
            </value>
            <value>
                <fullName>Event Center - Slide Assist</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>ON24 Forced Conv</fullName>
            </value>
            <value>
                <fullName>PGi Consolidated Billing</fullName>
            </value>
            <value>
                <fullName>PWN</fullName>
            </value>
            <value>
                <fullName>Ready Talk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGIServicesInformation__c/PGIServicesInformation__c.object-meta.xml
<CustomObject>
    <label>CPQ - Contract General Content</label>
    <nameField>
        <label>PGIPDFServicesInformation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Contract General Content</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGIServicesInformation__c/fields/Agreement_Type__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Type__c</fullName>
    <inlineHelpText>These values are defined by iContract, and adding values here that iContract does not use on its own will have no effect!</inlineHelpText>
    <label>Agreement Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Subscription License Order</fullName>
            </value>
            <value>
                <fullName>Subscription License Agreement</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Rate Modification Amendment</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>TPx Service Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGIServicesInformation__c/fields/Contract_General_Content__c.field-meta.xml
<CustomField>
    <fullName>Contract_General_Content__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SelfLookup</description>
    <label>Contract General Content</label>
    <referenceTo>PGIServicesInformation__c</referenceTo>
    <relationshipLabel>CPQ - Contract General Content</relationshipLabel>
    <relationshipName>CPQ_Contract_General_Content</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGIServicesInformation__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Field to identify the country specific Billing footnotes.</description>
    <inlineHelpText>Field to identify the country specific Billing footnotes.</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>CAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGIServicesInformation__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <inlineHelpText>These values are defined by iContract, and adding values here that iContract does not use on its own will have no effect!</inlineHelpText>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Intro Table</fullName>
                <default>true</default>
                <label>Pre-Intro Table</label>
            </value>
            <value>
                <fullName>Intro</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Services and Pricing Schedule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/test_iContractConversion.cls
@isTest
public class test_iContractConversion {
     @testSetup static void setup() {
       PGITestUtilities.disableSalesWings();
    }
	
    private static String LOG_TAG = 'iContractConversion:';
    private static final String REQUEST_URI = '/services/apexrest/iContractConversion/';
    
    static String request(String parameters, String convertType) {
        RestRequest req     = new RestRequest();
        RestResponse res    = new RestResponse();
        req.requestURI      = REQUEST_URI + parameters;
        req.httpMethod      = 'GET';

        RestContext.request = req;
        RestContext.response= res;
        return iContractConversion.convert(convertType);
    }

    static List<PGIServicesInformation__c> createTerms() {
        List<PGIServicesInformation__c> terms = new List<PGIServicesInformation__c>();
        terms.add(new PGIServicesInformation__c(Name='Parties, Underlying Agreement & Amendment Effective Date',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Amendment',
            Section__c='Intro',
            Region__c='US', Unique_ID__c='100'));
        terms.add(new PGIServicesInformation__c(Name='Parties, Underlying Agreement & Amendment Effective Date CAN',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Amendment',
            Section__c='Intro',
            Region__c='CAN', Unique_ID__c='200'));
        terms.add(new PGIServicesInformation__c(Name='Recitals',
            Order__c=2,Language__c = 'en_US',
            Agreement_Type__c='Amendment',
            Section__c='Pre-Intro Table',
            Region__c='US;CAN', Unique_ID__c='300'));
        terms.add(new PGIServicesInformation__c(Name='Acknowledgement Amendment',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Amendment',
            Section__c='Intro',
            Region__c='US;CAN', Unique_ID__c='400'));
        terms.add(new PGIServicesInformation__c(Name='Signing Area Amendment',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Amendment',
            Section__c='Signature',
            Region__c='US;CAN', Unique_ID__c='500'));
        terms.add(new PGIServicesInformation__c(Name='Services & Pricing Schedule Billing Footnotes SG',
            Order__c=100,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order;Subscription License Agreement;Amendment;Rate Modification Amendment',
            Section__c='Intro',
            Region__c='US', Unique_ID__c='600'));
        terms.add(new PGIServicesInformation__c(Name='Services & Pricing Schedule Billing Footnotes CAN',
            Order__c=100,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order;Subscription License Agreement;Amendment;Rate Modification Amendment',
            Section__c='Intro',
            Region__c='CAN', Unique_ID__c='700'));
        terms.add(new PGIServicesInformation__c(Name='Rate Modification Agreement US',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Rate Modification Amendment',
            Section__c='Intro',
            Region__c='US;CAN', Unique_ID__c='800'));
        terms.add(new PGIServicesInformation__c(Name='Services, Rates and Terms iContract SLO',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order',
            Section__c='Intro',
            Region__c='US', Unique_ID__c='900'));
        terms.add(new PGIServicesInformation__c(Name='Services, Rates and Terms iContract CAN SLO',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order',
            Section__c='Intro',
            Region__c='CAN', Unique_ID__c='110'));
        terms.add(new PGIServicesInformation__c(Name='Term SG',
            Order__c=2,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order;Subscription License Agreement',
            Section__c='Pre-Intro Table',
            Region__c='US;CAN', Unique_ID__c='120'));
        terms.add(new PGIServicesInformation__c(Name='Acknowledgement',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order;Subscription License Agreement',
            Section__c='Intro',
            Region__c='US;CAN', Unique_ID__c='130'));
        terms.add(new PGIServicesInformation__c(Name='Signing Area',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Order;Subscription License Agreement',
            Section__c='Signature',
            Region__c='US;CAN', Unique_ID__c='140'));
        terms.add(new PGIServicesInformation__c(Name='Services, Rates and Terms iContract SLA',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Agreement',
            Section__c='Intro',
            Region__c='US', Unique_ID__c='150'));
        terms.add(new PGIServicesInformation__c(Name='Services, Rates and Terms iContract CAN SLA',
            Order__c=1,Language__c = 'en_US',
            Agreement_Type__c='Subscription License Agreement',
            Section__c='Intro',
            Region__c='CAN', Unique_ID__c='160'));
        return terms;
    }

    static testMethod void test_emptyCartRequest_invalid() {
        System.debug(LOG_TAG + 'test_emptyCartRequest_invalid Started!');
        test.startTest();
        system.assertNotEquals('"success"', request('badid', 'badconvert'),
                              'Success message for an invalid ID');
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequest_invalid Finished!');
    }

    static testMethod void test_emptyCartRequest_empty() {
        System.debug(LOG_TAG + 'test_emptyCartRequest_empty Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        opptytest.AccountId = accttest.Id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Quote';
        insert ctrctest;
        
        List<PGIServicesInformation__c> terms = createTerms();
        insert terms;
        
        System.debug(LOG_TAG + 'test_emptyCartRequest_empty Started!');
        test.startTest();
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id, 'Subscription License Order'),
                              'No success message for a valid ID that\'s already empty');
        CONMAN_Contract__c foundContract = [SELECT Contract_Type__c from CONMAN_Contract__c where id= :ctrctest.id];
        
        system.assertEquals('Subscription License Order', foundContract.Contract_Type__c, 'Contract Type has not been updated');
        List<CONMAN_Contract_Verbiage__c> verbiageList = [SELECT Id, Pricing_Team_Changes_Allowed__c FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id];
        system.assertEquals(5, verbiageList.size(),
                              'ContractVerbiage not created');
        for (CONMAN_Contract_Verbiage__c verbiage : verbiageList)
            system.assertEquals(false, verbiage.Pricing_Team_Changes_Allowed__c,
                              'ContractVerbiage editable by Pricing');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequest_empty Finished!');
    }

    static testMethod void test_emptyCartRequest() {
        System.debug(LOG_TAG + 'test_emptyCartRequest Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        opptytest.AccountId = accttest.Id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Subscription License Order';
        insert ctrctest;
        
        LicenseSet__c licSet = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licSet;
        
        Associated_Rate__c assoRate = new Associated_Rate__c(LicenseSet__c = licSet.id);
        insert assoRate;
        
        CONMAN_Contract_Verbiage__c verb = new CONMAN_Contract_Verbiage__c(Name='Custom Language from Legal', PGi_Contract__c = ctrctest.id);
        insert verb;
        
        List<PGIServicesInformation__c> terms = createTerms();
        insert terms;
        
        system.assertEquals(1, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not attached to Contract during setup');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not attached to LicenseSet during setup');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not attached to Contract during setup');
        
        System.debug(LOG_TAG + 'test_emptyCartRequest Started!');
        test.startTest();
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id, 'Subscription License Order'),
                              'No success message for a valid ID with records');
        
        CONMAN_Contract__c foundContract = [SELECT Contract_Type__c from CONMAN_Contract__c where id= :ctrctest.id];
        
        system.assertEquals('Subscription License Order', foundContract.Contract_Type__c, 'Contract Type has not been updated');
        
        system.assertEquals(1, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not deleted');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not deleted');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not added (no conversion)');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequest Finished!');
    }

    static testMethod void test_emptyCartRequestSLA() {
        System.debug(LOG_TAG + 'test_emptyCartRequestSLA Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        opptytest.AccountId = accttest.Id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Subscription License Agreement';
        insert ctrctest;
        
        LicenseSet__c licSet = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licSet;
        
        Associated_Rate__c assoRate = new Associated_Rate__c(LicenseSet__c = licSet.id);
        insert assoRate;
        
        CONMAN_Contract_Verbiage__c verb = new CONMAN_Contract_Verbiage__c(Name='Custom Pricing Langauge', PGi_Contract__c = ctrctest.id);
        insert verb;
        
        List<PGIServicesInformation__c> terms = createTerms();
        insert terms;
        
        system.assertEquals(1, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not attached to Contract during setup');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not attached to LicenseSet during setup');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not attached to Contract during setup');
        
        System.debug(LOG_TAG + 'test_emptyCartRequestSLA Started!');
        test.startTest();
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id, 'Subscription License Agreement'),
                              'No success message for a valid ID with records');

        CONMAN_Contract__c foundContract = [SELECT Contract_Type__c from CONMAN_Contract__c where id= :ctrctest.id];
        
        system.assertEquals('Subscription License Agreement', foundContract.Contract_Type__c, 'Contract Type has not been updated');
        
        system.assertEquals(1, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not deleted');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not deleted');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not deleted (no conversion)');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequestSLA Finished!');
    }

    static testMethod void test_emptyCartRequestExisting() {
        System.debug(LOG_TAG + 'test_emptyCartRequestExisting Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        opptytest.AccountId = accttest.Id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Amendment';
        insert ctrctest;
        
        LicenseSet__c licSet = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licSet;
        
        LicenseSet__c licS = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licS;
                
        Associated_Rate__c assoRate = new Associated_Rate__c(LicenseSet__c = licSet.id);
        insert assoRate;
        
        List<PGIServicesInformation__c> terms = createTerms();
        insert terms;
        
        CONMAN_Contract_Verbiage__c verb = new CONMAN_Contract_Verbiage__c(Name=terms.get(3).Name, Contract_General_Content__c = terms.get(3).Id, PGi_Contract__c = ctrctest.id);
        insert verb;
        
        system.assertEquals(2, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not attached to Contract during setup');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not attached to LicenseSet during setup');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not attached to Contract during setup');
        
        System.debug(LOG_TAG + 'test_emptyCartRequestExisting Started!');
        test.startTest();
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id, 'Amendment'),
                              'No success message for a valid ID with records');
        
        CONMAN_Contract__c foundContract = [SELECT Contract_Type__c from CONMAN_Contract__c where id= :ctrctest.id];
       
        system.assertEquals('Amendment', foundContract.Contract_Type__c, 'Contract Type has not been updated');
        
        system.assertEquals(2, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not deleted');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not deleted');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not deleted (no conversion)');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequestExisting Finished!');
    }

    static testMethod void test_emptyCartRequestRCA() {
        System.debug(LOG_TAG + 'test_emptyCartRequestRCA Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        opptytest.AccountId = accttest.Id;
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Amendment';
        insert ctrctest;
        
        LicenseSet__c licSet = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licSet;
        
        LicenseSet__c licS = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licS;
                
        Associated_Rate__c assoRate = new Associated_Rate__c(LicenseSet__c = licSet.id);
        insert assoRate;
        
        List<PGIServicesInformation__c> terms = createTerms();
        insert terms;
        
        CONMAN_Contract_Verbiage__c verb = new CONMAN_Contract_Verbiage__c(Name=terms.get(3).Name, Contract_General_Content__c = terms.get(3).Id, PGi_Contract__c = ctrctest.id);
        insert verb;
        
        system.assertEquals(2, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not attached to Contract during setup');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not attached to LicenseSet during setup');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not attached to Contract during setup');
        
        System.debug(LOG_TAG + 'test_emptyCartRequestRCA Started!');
        test.startTest();
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id, 'Rate Modification Amendment'),
                              'No success message for a valid ID with records');
        
        CONMAN_Contract__c foundContract = [SELECT Contract_Type__c from CONMAN_Contract__c where id= :ctrctest.id];
       
        system.assertEquals('Rate Modification Amendment', foundContract.Contract_Type__c, 'Contract Type has not been updated');
        
        system.assertEquals(2, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet deleted');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate deleted');
        // system.assertEquals(3, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
        //                       'ContractVerbiage not deleted and re-created');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequestRCA Finished!');
    }
}