force-app/main/default/objects/Associated_Rate__c/Associated_Rate__c.object-meta.xml
<CustomObject>
    <label>Associated Rate</label>
    <nameField>
        <label>Associated Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Rate__c/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipName>Associated_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract__c/fields/Contract_Type__c.field-meta.xml
<CustomField>
    <fullName>Contract_Type__c</fullName>
    <label>Contract Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Subscription License Order</fullName>
                <default>true</default>
                <label>Subscription License Order</label>
            </value>
            <value>
                <fullName>Subscription License Agreement</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Rate Modification Amendment</fullName>
            </value>
            <value>
                <fullName>Agent Agreement</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Email Order</fullName>
            </value>
            <value>
                <fullName>Gateway Customer Service Order</fullName>
            </value>
            <value>
                <fullName>Gateway Subscription License Order</fullName>
            </value>
            <value>
                <fullName>Master Services Agreement</fullName>
            </value>
            <value>
                <fullName>Related Document</fullName>
            </value>
            <value>
                <fullName>WebEx Agreement</fullName>
            </value>
            <value>
                <fullName>WebEx Amend</fullName>
            </value>
            <value>
                <fullName>Wholesale Agreement</fullName>
            </value>
            <value>
                <fullName>Customer Services Agreement</fullName>
            </value>
            <value>
                <fullName>Local Affiliate Service Agreement</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
            <value>
                <fullName>Service Agreement</fullName>
            </value>
            <value>
                <fullName>TPx Service Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/recordTypes/iContract.recordType-meta.xml
<RecordType>
    <fullName>iContract</fullName>
    <active>true</active>
    <description>NA Contract going through the iContract system</description>
    <label>NA Contract</label>
</RecordType>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/CONMAN_Contract_Verbiage__c.object-meta.xml
<CustomObject>
    <description>Terms and Conditions are are specific to a PGi Contract and can be edited by Legal.</description>
    <label>PGi Contract Verbiage</label>
    <nameField>
        <label>PGi Contract Verbiage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Contract Verbiage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CONMAN_Contract_Verbiage__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <inlineHelpText>Which PGi Contract is this Verbiage for?</inlineHelpText>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>PGi Contract Verbiage</relationshipLabel>
    <relationshipName>PGi_Contract_Verbiage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test_iContractEmptyCart.cls
@isTest
public class test_iContractEmptyCart {
    @testSetup static void setup() {
       PGITestUtilities.disableSalesWings();
    }
    private static String LOG_TAG = 'iContractEmptyCart:';
    private static final String REQUEST_URI = '/services/apexrest/iContractEmptyCart/';
    
    static String request(String parameters) {
        RestRequest req 	= new RestRequest();
        RestResponse res 	= new RestResponse();
        req.requestURI 		= REQUEST_URI + parameters;
        req.httpMethod 		= 'GET';

        RestContext.request = req;
        RestContext.response= res;
        return iContractEmptyCart.emptyCartRequest();
    }

    static testMethod void test_emptyCartRequest_invalid() {
        System.debug(LOG_TAG + 'test_emptyCartRequest_invalid Started!');
        test.startTest();
        system.assertNotEquals('"success"', request('badid'),
                              'Success message for an invalid ID');
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequest_invalid Finished!');
    }

    static testMethod void test_emptyCartRequest_empty() {
        System.debug(LOG_TAG + 'test_emptyCartRequest_empty Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Subscription License Order';
        insert ctrctest;
        
        System.debug(LOG_TAG + 'test_emptyCartRequest_empty Started!');
        test.startTest();
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id),
                              'No success message for a valid ID that\'s already empty');
        system.assertEquals(0, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSets not added');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequest_empty Finished!');
    }

    static testMethod void test_emptyCartRequest() {
        System.debug(LOG_TAG + 'test_emptyCartRequest Initializing!');
        Account accttest = PGITestUtilities.getAccountDetails();
        insert accttest;
        
        Opportunity opptytest = PGITestUtilities.getOpportunityDetails();
        insert opptytest;
        
        Contact cntcttest = PGITestUtilities.getContactDetails(accttest.id);
        insert cntcttest;
        
        insert new OpportunityContactRole(OpportunityId=opptytest.Id, ContactId=cntcttest.Id, IsPrimary=true);
        
        ConMan_Contract__c ctrctest = PGITestUtilities.getConManContractDetails(accttest.id, opptytest.id);
        ctrctest.Contract_Type__c = 'Subscription License Order';
        insert ctrctest;
        
        LicenseSet__c licSet = new LicenseSet__c(PGi_Contract__c = ctrctest.id);
        insert licSet;
        
        Associated_Rate__c assoRate = new Associated_Rate__c(LicenseSet__c = licSet.id);
        insert assoRate;
        
        CONMAN_Contract_Verbiage__c verb = new CONMAN_Contract_Verbiage__c(PGi_Contract__c = ctrctest.id);
        insert verb;
        
        System.debug(LOG_TAG + 'test_emptyCartRequest Started!');
        test.startTest();
        
        system.assertEquals(1, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not attached to Contract during setup');
        system.assertEquals(1, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not attached to LicenseSet during setup');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage not attached to Contract during setup');
        
        system.assertEquals(iContract.SUCCESS, request(ctrctest.id),
                              'No success message for a valid ID with records');
        
        system.assertEquals(0, [SELECT Id FROM LicenseSet__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'LicenseSet not deleted');
        system.assertEquals(0, [SELECT Id FROM Associated_Rate__c WHERE LicenseSet__c = :licSet.id].size(),
                              'AssociatedRate not deleted');
        system.assertEquals(1, [SELECT Id FROM CONMAN_Contract_Verbiage__c WHERE PGi_Contract__c = :ctrctest.id].size(),
                              'ContractVerbiage deleted');
        
        test.stopTest();
        System.debug(LOG_TAG + 'test_emptyCartRequest Finished!');
    }
}