force-app/main/default/objects/Associated_Rate__c/Associated_Rate__c.object-meta.xml
<CustomObject>
    <label>Associated Rate</label>
    <nameField>
        <label>Associated Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Rate__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <label>Default</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipName>Associated_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <label>Override</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Associated Rates</relationshipLabel>
    <relationshipName>Associated_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Associated_Rate__c/fields/Rate_Name__c.field-meta.xml
<CustomField>
    <fullName>Rate_Name__c</fullName>
    <label>Rate Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CONMAN_Contract__c/CONMAN_Contract__c.object-meta.xml
<CustomObject>
    <description>Used for Contract Management going forward as part of the ConMan project</description>
    <label>PGi Contract</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>PGi Contract #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PGi Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/Enterprise_Name__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offering</label>
    <referenceTo>Offerings__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/fields/PGi_Contract__c.field-meta.xml
<CustomField>
    <fullName>PGi_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PGi Contract</label>
    <referenceTo>CONMAN_Contract__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offerings__c/Offerings__c.object-meta.xml
<CustomObject>
    <description>High-level Product Select in iContract</description>
    <label>CPQ - Offering</label>
    <nameField>
        <label>Offering Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Offerings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Offerings__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Agreement Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <label>CPQ - Rate</label>
    <nameField>
        <label>Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ - Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/BP_Access_Country__c.field-meta.xml
<CustomField>
    <fullName>BP_Access_Country__c</fullName>
    <description>Access Country short-code for Billing Platform. Only applicable for International Rates.</description>
    <inlineHelpText>Access Country short-code for Billing Platform. Only applicable for International Rates.</inlineHelpText>
    <label>BP Access Country</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/BP_Bill_Code__c.field-meta.xml
<CustomField>
    <fullName>BP_Bill_Code__c</fullName>
    <description>Bill Code for this Rate. If there&#39;s multiple Bill Codes, they&#39;re separated with a Double-Pipe: ||</description>
    <inlineHelpText>Bill Code for this Rate. If there&#39;s multiple Bill Codes, they&#39;re separated with a Double-Pipe: ||</inlineHelpText>
    <label>BP Bill Code</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/BP_Bridge_Country__c.field-meta.xml
<CustomField>
    <fullName>BP_Bridge_Country__c</fullName>
    <description>Bridge Country short-code for Billing Platform. Only applicable for International Rates.</description>
    <inlineHelpText>Bridge Country short-code for Billing Platform. Only applicable for International Rates.</inlineHelpText>
    <label>BP Bridge Country</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/BP_Package_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>BP_Package_Product_Code__c</fullName>
    <description>PackageProductCode for this Rate. If there&#39;s multiple PackageProductCode, they&#39;re separated with a Double-Pipe: ||</description>
    <inlineHelpText>PackageProductCode for this Rate. If there&#39;s multiple PackageProductCode, they&#39;re separated with a Double-Pipe: ||</inlineHelpText>
    <label>BP Package Product Code</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate_Group__c.field-meta.xml
<CustomField>
    <fullName>Rate_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which Rate Group this Rate will be under on the Contract</description>
    <inlineHelpText>Which Rate Group this Rate will be under on the Contract</inlineHelpText>
    <label>Rate Group</label>
    <referenceTo>Rate_Group__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Rate_Name__c.field-meta.xml
<CustomField>
    <fullName>Rate_Name__c</fullName>
    <label>Agreement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Recurrence__c.field-meta.xml
<CustomField>
    <fullName>Recurrence__c</fullName>
    <label>Recurrence</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Affects how the Rate is presented in iContract and on agreements.</description>
    <inlineHelpText>Affects how the Rate is presented in iContract and on agreements.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Usage</fullName>
                <default>true</default>
                <label>Usage</label>
            </value>
            <value>
                <fullName>Sub</fullName>
                <label>Subscription</label>
            </value>
            <value>
                <fullName>Once</fullName>
                <label>One-Time</label>
            </value>
            <value>
                <fullName>Commit</fullName>
                <label>Minimum Commitment</label>
            </value>
            <value>
                <fullName>Bundle</fullName>
                <label>Bundled Rate</label>
            </value>
            <value>
                <fullName>Access</fullName>
                <label>Access Type</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Unique_ID__c.field-meta.xml
<CustomField>
    <fullName>Unique_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rate_Group__c/Rate_Group__c.object-meta.xml
<CustomObject>
    <label>Rate Group</label>
    <nameField>
        <label>Rate Groups Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/iContract_NA_BP_Export.cls
//DEPRECATED 11-20-19 - Aaron Gaber
global class iContract_NA_BP_Export {
    
    // public static final Integer RATE_DECIMAL_PLACES = 4;
    
    // public CONMAN_Contract__c contract {get;set;}
    // public List<BPRate> lines {get;set;}
    
    // global class BPRate implements Comparable {
        
    //     public String iContractId {get;set;}
    //     public String iContractOffering {get;set;}
    //     public String iContractRateGroup {get;set;}
    //     public String iContractRate {get;set;}
        
    //     public boolean modified {get;set;}
        
    //     public String currencyCode {get;set;}
    //     public String rate {get;set;}
    //     public String intlRate {get;set;}
    //     public String bridgeCountry {get;set;}
    //     public String accessCountry {get;set;}
        
    //     public String billCode {get;set;}
    //     public String packageProductCode {get;set;}
        
    //     public BPRate(String id, String offr, String rg, String r) {
    //         iContractId = id;
    //         iContractOffering = offr;
    //         iContractRateGroup = rg;
    //         iContractRate = r;
    //     }
    
    //     public BPRate duplicate() {
    //         BPRate clone = new BPRate(iContractId, iContractOffering, iContractRateGroup, iContractRate);
    //         clone.modified = modified;
    //         clone.currencyCode = currencyCode;
    //         clone.rate = rate;
    //         clone.intlRate = intlRate;
    //         clone.bridgeCountry = bridgeCountry;
    //         clone.accessCountry = accessCountry;
    //         clone.billCode = billCode;
    //         clone.packageProductCode = packageProductCode;
    //         return clone;
    //     }
        
    //     // This is needed to sort the list of BPRates by their names
    //     global Integer compareTo(Object compareTo) {
    //         BPRate compareToLicense = (BPRate)compareTo;
            
    //         String thisOffr = this.iContractOffering;
    //         String thatOffr = compareToLicense.iContractOffering;
            
    //         String thisRG = this.iContractRateGroup;
    //         String thatRG = compareToLicense.iContractRateGroup;
            
    //         String thisRate = this.iContractRate;
    //         String thatRate = compareToLicense.iContractRate;
            
    //         Integer returnValue = 0; // equal
    //         if (thisOffr > thatOffr) {
    //             returnValue = 1;
    //         } else if (thisOffr < thatOffr) {
    //             returnValue = -1;
    //         } else { // try by Rate Group then
    //             if (thisRG > thatRG) {
    //                 returnValue = 1;
    //             } else if (thisRG < thatRG) {
    //                 returnValue = -1;
    //             } else { // try by Rate then
    //                 if (thisRate > thatRate) {
    //                     returnValue = 1;
    //                 } else if (thisRate < thatRate) {
    //                     returnValue = -1;
    //                 }
    //             }
    //         }
            
    //         return returnValue;
    //     }
    // }
    
    // public iContract_NA_BP_Export(ApexPages.StandardController stdController) {
    //     contract = getContractDetails(stdController.getRecord().Id);
    //     lines = getBPRates(contract.Id);
    // }
    
    // public static List<BPRate> getBPRates(Id contractId) {
    //     // Fetch all necessary data: LicenseSets and AssociatedRates
    //     Map<Id, LicenseSet__c> licenses = getLicenses(contractId);
    //     Map<Id, Associated_Rate__c> assoRates = getAssociatedRates(licenses.keySet());
        
    //     List<BPRate> bpRates = new List<BPRate>();
        
    //     for (Associated_Rate__c assoRate : assoRates.values()) {
    //         LicenseSet__c license = licenses.get(assoRate.LicenseSet__c);
            
    //         // Find the Unique ID if there's a Rate
    //         String uniqueId = 'DEAL_DESK_RATE';
    //         if (assoRate.Rate__c != null)
    //             uniqueId = assoRate.Rate__r.Unique_ID__c;
            
    //         // Find the Rate Group if there's a Rate with a Rate Group
    //         String rateGroup = '';
    //         if (assoRate.Rate__c != null && assoRate.Rate__r.Rate_Group__c != null)
    //             rateGroup = assoRate.Rate__r.Rate_Group__r.Name;
            
    //         // Create the BPRate with basic info
    //         BPRate bpRate = new BPRate(uniqueId, license.Product_Name__c,
    //                                    rateGroup, assoRate.Rate_Name__c);
            
    //         // Mark the BPRate as modified if it is
    //         bpRate.modified = isLicenseModified(license) || isAssociatedRateModified(assoRate);
            
    //         bpRate.currencyCode = assoRate.CurrencyIsoCode;
            
    //         // Different types of BPRates for Standard and International Grid Rates
    //         if (assoRate.Rate__c == null || assoRate.Rate__r.Type__c == null || assoRate.Rate__r.Type__c != 'Access') {
    //             // Simple Rate
    //             bpRate.rate = assoRate.Override__c.setScale(RATE_DECIMAL_PLACES).toPlainString();
                
    //             if (!hasBPFields(assoRate))
    //     			bpRates.add(bpRate);
    //             else
	// 				bpRates.addAll(createBPRates(bpRate, assoRate.Rate__r));
                
    //         } else {
    //             // International Rate
    //             bpRate.rate = '0';
    //             bpRate.bridgeCountry = assoRate.Rate__r.BP_Bridge_Country__c;
    //             bpRate.accessCountry = assoRate.Rate__r.BP_Access_Country__c;

    //             bpRate.iContractRate = assoRate.Name;
    //             bpRate.intlRate = assoRate.Override__c.setScale(RATE_DECIMAL_PLACES).toPlainString();
    //             if (!hasBPFields(assoRate))
    //                 bpRates.add(bpRate);
    //             else
    //                 bpRates.addAll(createBPRates(bpRate, assoRate.Rate__r));
    //         }
    //     }
        
    //     bpRates.sort();
    //     return bpRates;
    // }
    
    // public static CONMAN_Contract__c getContractDetails(Id contractId) {
    //     return [SELECT Id, Name FROM CONMAN_Contract__c WHERE Id = :contractId];
    // }
    
    // public static Map<Id, LicenseSet__c> getLicenses(Id contractId) {
    //     return new Map<Id, LicenseSet__c>([
    //         SELECT Id, Name,
    //         Product_Name__c,
    //         Enterprise_Name__c,
    //         Enterprise_Name__r.Product_Name__c
    //         FROM LicenseSet__c
    //         WHERE PGi_Contract__c = :contractId
    //     ]);
    // }
    
    // public static Map<Id, Associated_Rate__c> getAssociatedRates(Set<Id> licenseIds) {
    //     return new Map<Id, Associated_Rate__c>([
    //         SELECT Id, Name, CurrencyIsoCode,
    //         Rate_Name__c,
    //         Description__c,
    //         Recurrence__c,
    //         Override__c,
    //         Default__c,
    //         LicenseSet__c,
    //         Rate__c,
    //         Rate__r.Unique_ID__c,
    //         Rate__r.Rate_Name__c,
    //         Rate__r.Description__c,
    //         Rate__r.Recurrence__c,
    //         Rate__r.Type__c,
    //         Rate__r.BP_Bill_Code__c,
    //         Rate__r.BP_Package_Product_Code__c,
    //         Rate__r.BP_Access_Country__c,
    //         Rate__r.BP_Bridge_Country__c,
    //         Rate__r.Rate_Group__c,
    //         Rate__r.Rate_Group__r.Name
    //         FROM Associated_Rate__c
    //         WHERE LicenseSet__c IN :licenseIds
    //     ]);
    // }
    
    // public static boolean isLicenseModified(LicenseSet__c license) {
    //     // no name?
    //     if (license.Product_Name__c == null)
    //         return true;
        
    //     // no original Offering
    //     if (license.Enterprise_Name__c == null)
    //         return true;
        
    //     // modified Product Name
    //     if (license.Product_Name__c != license.Enterprise_Name__r.Product_Name__c)
    //     	return true;
        
    //     return false;
    // }
    
    // public static boolean isAssociatedRateModified(Associated_Rate__c rate) {
    //     // no name?
    //     if (rate.Rate_Name__c == null)
    //         return true;
        
    //     // no original Rate
    //     if (rate.Rate__c == null)
    //         return true;
        
    //     // modified Rate Name
    //     if (rate.Rate_Name__c != rate.Rate__r.Rate_Name__c && rate.Rate__r.Type__c != 'Access')
    //         return true;
        
    //     // modified Rate Description
    //     if (rate.Description__c != rate.Rate__r.Description__c)
    //         return true;
        
    //     // modified Rate Recurrence
    //     if (rate.Recurrence__c != rate.Rate__r.Recurrence__c && rate.Rate__r.Type__c == 'Usage')
    //         return true;
        
    //     return false;
    // }
    
    // public static boolean hasBPFields(Associated_Rate__c rate) {
    //     return rate.Rate__c != null &&
    //         (
    //             (rate.Rate__r.BP_Bill_Code__c != null && !String.isEmpty(rate.Rate__r.BP_Bill_Code__c))
    //             ||
    //             (rate.Rate__r.BP_Package_Product_Code__c != null && !String.isEmpty(rate.Rate__r.BP_Package_Product_Code__c))
    //         );
    // }
    
    // public static List<BPRate> createBPRates(BPRate baseBPRate, Rate__c rate) {
    //     List<BPRate> bpRates = new List<BPRate>();
        
    //     if (rate == null)
    //         return bpRates;
        
    //     // Check for single/multiple Bill Codes and/or Package Product Codes
    //     List<String> billCodes = new List<String>();
    //     List<String> packageProductCodes = new List<String>();
    //     if (rate.BP_Bill_Code__c != null && !String.isEmpty(rate.BP_Bill_Code__c))
    //         billCodes = rate.BP_Bill_Code__c.split('\\|\\|');
    //     if (rate.BP_Package_Product_Code__c != null && !String.isEmpty(rate.BP_Package_Product_Code__c))
    //         packageProductCodes = rate.BP_Package_Product_Code__c.split('\\|\\|');
        
    //     if (billCodes.isEmpty() || packageProductCodes.isEmpty())
    //         return bpRates;
        
    //     // Create a new BPRate for each Bill Code or Package Product Codes
    //     // Except, if the fields are different sizes, use the last item
    //     for (integer i = 0; i < Math.max(billCodes.size(), packageProductCodes.size()); i++) {
    //         BPRate newBPRate = baseBPRate.duplicate();
            
    //         if (!billCodes.isEmpty())
    //             newBPRate.billCode = billCodes.get(Math.min(i, billCodes.size() - 1));
            
    //         if (!packageProductCodes.isEmpty())
    //             newBPRate.packageProductCode = packageProductCodes.get(Math.min(i, packageProductCodes.size() - 1));
            
    //         bpRates.add(newBPRate);
    //     }
        
    //     return bpRates;
    // }
}