force-app/main/default/objects/Associated_Rate__c/Associated_Rate__c.object-meta.xml
<CustomObject>
    <label>Associated Rate</label>
    <nameField>
        <label>Associated Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Associated Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Associated_Rate__c/fields/LicenseSet__c.field-meta.xml
<CustomField>
    <fullName>LicenseSet__c</fullName>
    <label>LicenseSet</label>
    <referenceTo>LicenseSet__c</referenceTo>
    <relationshipName>Associated_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LicenseSet__c/LicenseSet__c.object-meta.xml
<CustomObject>
    <label>LicenseSet</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseSets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LicenseSet__c/fields/Enterprise_Name__c.field-meta.xml
<CustomField>
    <fullName>Enterprise_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Offering</label>
    <referenceTo>Offerings__c</referenceTo>
    <relationshipLabel>LicenseSets</relationshipLabel>
    <relationshipName>LicenseSets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/iContractCreateLicenseSetEndpoint.cls
@RestResource(urlMapping='/iContractCreateLicenseSet/*')
global with sharing class iContractCreateLicenseSetEndpoint {
    @HttpPost
    global static String createLicenseSet(Id contractId, List<LicenseSet__c> LicenseSets, List<List<Associated_Rate__c>> AssociatedRates) {
        try {
            List<LicenseSet__c> licenseSetsToCreate = new List<LicenseSet__c>();
            List<Associated_Rate__c> associatedRatesToCreate = new List<Associated_Rate__c>();

            Set<Id> offeringIds = new Set<Id>();
            for (LicenseSet__c lc : LicenseSets) {
                offeringIds.add(lc.Enterprise_Name__c);
            }

            for (Integer index = 0; index < LicenseSets.size(); index++) {
                LicenseSet__c lc = LicenseSets.get(index);
                List<Associated_Rate__c> ars = AssociatedRates.get(index);

                licenseSetsToCreate.add(lc);

                if (ars != null) {
                    for(Associated_Rate__c ar : ars)
                        ar.LicenseSet__r = lc;
                    associatedRatesToCreate.addAll(ars);
                }
            }

           INSERT licenseSetsToCreate;

            // retrieve the inserted IDs before adding ARs
            for (Associated_Rate__c ar : associatedRatesToCreate) {
                ar.LicenseSet__c = ar.LicenseSet__r.Id;
            }
            INSERT associatedRatesToCreate;

            iContract.handleTerms(contractId);

            return iContract.SUCCESS;
        } catch(Exception e){
            return iContract.formatException(e);
        }
    }
}