force-app/main/default/objects/Lead/fields/Eloqua_Lead_Score__c.field-meta.xml
<CustomField>
    <fullName>Eloqua_Lead_Score__c</fullName>
    <inlineHelpText>The letters A-D are a profile grade, with A as best fit; and the numbers are an engagement score, with 1 as most engaged.</inlineHelpText>
    <label>Eloqua Lead Score</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Global_MQL__c.field-meta.xml
<CustomField>
    <fullName>Global_MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AutoAssignUnassignedLeadsHandler.cls
public class AutoAssignUnassignedLeadsHandler {
// @future
// public static void assignleads(Set<Id> userIds) {
    
// List<Lead> Leadsforusers = [Select id,ownerid,status from lead where isConverted = False and recordtype.name like '%PGi%' and status <> 'Disqualified' and ownerid IN :userids AND Global_MQL__c = true];

// system.debug('ARC debug LeadIds:' +Leadsforusers);

// if(!Leadsforusers.isEmpty())
// {
//     for(Lead ld : Leadsforusers)
//     {
//         ld.ownerid = '00Ga0000003werP';
//         ld.status = 'Assigned';
//         ld.Eloqua_Lead_Score__c = null;
//     }
//     update Leadsforusers;
// }
// }
}