force-app/main/default/objects/Lead/fields/Omniture_Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Omniture_Campaign_Code__c</fullName>
    <label>Inbound Call Color</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BLUE</fullName>
            </value>
            <value>
                <fullName>COPPER</fullName>
            </value>
            <value>
                <fullName>CYAN</fullName>
            </value>
            <value>
                <fullName>GOLD</fullName>
            </value>
            <value>
                <fullName>GREEN</fullName>
            </value>
            <value>
                <fullName>GREY</fullName>
            </value>
            <value>
                <fullName>NAVY</fullName>
            </value>
            <value>
                <fullName>NO COLOR</fullName>
            </value>
            <value>
                <fullName>OLIVE</fullName>
            </value>
            <value>
                <fullName>ORANGE</fullName>
            </value>
            <value>
                <fullName>PERIWINKLE</fullName>
            </value>
            <value>
                <fullName>PINK</fullName>
            </value>
            <value>
                <fullName>PURPLE</fullName>
            </value>
            <value>
                <fullName>RED</fullName>
            </value>
            <value>
                <fullName>SKY BLUE</fullName>
            </value>
            <value>
                <fullName>VIOLET</fullName>
            </value>
            <value>
                <fullName>WHITE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Omniture_Campaign_Code_Copy__c.field-meta.xml
<CustomField>
    <fullName>Omniture_Campaign_Code_Copy__c</fullName>
    <label>Campaign Code(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Omniture_Campaign_Code__c/Omniture_Campaign_Code__c.object-meta.xml
<CustomObject>
    <label>Omniture Campaign Code</label>
    <nameField>
        <displayFormat>OC-{0000}</displayFormat>
        <label>Auto Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Omniture Campaign Code</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Omniture_Campaign_Code__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>Campaign</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Omniture_Campaign_Code__c/fields/Omniture_Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Omniture_Campaign_Code__c</fullName>
    <label>Omniture Campaign Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CreateCampaignHistoryFromLeadTest.cls
@isTest
public class CreateCampaignHistoryFromLeadTest {
    @testSetup static void setup() {
        PGITestUtilities.disableSalesWings();
        Id pgiRecordTypeIdLead = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PGi Leads').getRecordTypeId();
        
        List<Lead> leadList = new List<Lead>{new Lead(LastName = 'TestLead',LeadSource = 'ECommerce Customer',Company = 'testlead',
                                                      CurrencyIsoCode = 'USD',Status = 'New',   
                                                      Omniture_Campaign_Code_Copy__c = 'TestOCcode',Email = 'testlead@gmail.com',
                                                      RecordTypeId = pgiRecordTypeIdLead,Omniture_Campaign_Code__c = 'GREEN') };
                                                          
        Insert leadList;
        
        List<Campaign> cmgnList = new List<Campaign>{
            new Campaign(Name = 'testCmpn',IsActive = true) };
                Insert cmgnList;

        List<CampaignMember> cmList = new List<CampaignMember>	{
            new CampaignMember(status = 'Opened',CampaignId = cmgnList[0].Id,LeadId = leadList[0].Id) };
                Insert cmList;

        List<Omniture_Campaign_Code__c> occList = new List<Omniture_Campaign_Code__c>{
            new Omniture_Campaign_Code__c(campaign__c = cmgnList[0].id ,omniture_campaign_code__c = 'TestOCCode')};
                Insert occList;
    }
    static testMethod  void  testCreateCampaignHistoryFromLead(){
        Test.startTest(); 
		Lead lObj = [Select id,status,lastname from Lead where LastName = 'TestLead' limit 1];
        lObj.status = 'Open';
        Update lObj;
        Test.stopTest();
    }
}