force-app/main/default/objects/PGi_Vendor_List__c/PGi_Vendor_List__c.object-meta.xml
<CustomObject>
    <description>List of PGi Vendors, including carriers and 3rd Party vendors</description>
    <label>PGi Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PGi_Vendor_List__c/fields/Show_on_Surveys__c.field-meta.xml
<CustomField>
    <fullName>Show_on_Surveys__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show on Surveys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/Vendor_Scorecard__c.object-meta.xml
<CustomObject>
    <label>Vendor Scorecard</label>
    <nameField>
        <displayFormat>VSC-{0000}</displayFormat>
        <label>Vendor Scorecard</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Communicates_network_impacting_issues__c.field-meta.xml
<CustomField>
    <fullName>Communicates_network_impacting_issues__c</fullName>
    <label>Total for CNIS</label>
    <summarizedField>Vendor_Survey__c.Communicates_network_impacting_issues__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Communicates_network_impacting_issues__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Knowledgeable_of_outstanding_problems__c.field-meta.xml
<CustomField>
    <fullName>Knowledgeable_of_outstanding_problems__c</fullName>
    <label>Total for KOP</label>
    <summarizedField>Vendor_Survey__c.Knowledgeable_of_outstanding_problems__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Knowledgeable_of_outstanding_problems__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Month_Year__c</fullName>
    <label>Month Year</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Provides_accurate_timely_ticket_updates__c.field-meta.xml
<CustomField>
    <fullName>Provides_accurate_timely_ticket_updates__c</fullName>
    <label>Total for PATTU</label>
    <summarizedField>Vendor_Survey__c.Provides_accurate_timely_ticket_updates__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Provides_accurate_timely_ticket_updates__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Related_PGi_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Related_PGi_Vendor__c</fullName>
    <label>Related PGi Vendor</label>
    <referenceTo>PGi_Vendor_List__c</referenceTo>
    <relationshipLabel>Vendor Scorecards</relationshipLabel>
    <relationshipName>Vendor_Scorecards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendor_Scorecard__c/fields/Responsive_when_PGi_escalations_occur__c.field-meta.xml
<CustomField>
    <fullName>Responsive_when_PGi_escalations_occur__c</fullName>
    <label>Total for REO</label>
    <summarizedField>Vendor_Survey__c.Responsive_when_PGi_escalations_occur__c</summarizedField>
    <summaryFilterItems>
        <field>Vendor_Survey__c.Responsive_when_PGi_escalations_occur__c</field>
        <operation>notEqual</operation>
        <value>0,</value>
    </summaryFilterItems>
    <summaryForeignKey>Vendor_Survey__c.Vendor_Scorecard__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/Vendor_Survey__c.object-meta.xml
<CustomObject>
    <label>Vendor Survey</label>
    <nameField>
        <displayFormat>VS-{0000}</displayFormat>
        <label>Vendor Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Survys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Survey__c/fields/Communicates_network_impacting_issues__c.field-meta.xml
<CustomField>
    <fullName>Communicates_network_impacting_issues__c</fullName>
    <label>Communicates network impacting issues</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Familiar_with_PGi_business_and_trouble__c.field-meta.xml
<CustomField>
    <fullName>Familiar_with_PGi_business_and_trouble__c</fullName>
    <label>Familiar with PGi business and troubles</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Knowledgeable_of_outstanding_problems__c.field-meta.xml
<CustomField>
    <fullName>Knowledgeable_of_outstanding_problems__c</fullName>
    <label>Knowledgeable of outstanding problems</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Provides_accurate_timely_ticket_updates__c.field-meta.xml
<CustomField>
    <fullName>Provides_accurate_timely_ticket_updates__c</fullName>
    <label>Provides accurate/timely ticket updates</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Responsive_when_PGi_escalations_occur__c.field-meta.xml
<CustomField>
    <fullName>Responsive_when_PGi_escalations_occur__c</fullName>
    <label>Responsive when PGi escalations occur</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vendor_Survey__c/fields/Vendor_Scorecard__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Scorecard__c</fullName>
    <label>Vendor Scorecard</label>
    <referenceTo>Vendor_Scorecard__c</referenceTo>
    <relationshipLabel>Vendor Survies</relationshipLabel>
    <relationshipName>Vendor_Survies</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ScorecardController_Test.cls
@isTest
private class ScorecardController_Test {
	//This test method is used to coverage the code of ScheduleBatchScorecardGenerator class
    static testMethod void testScorecardController0() {
    	PGi_Vendor_List__c vl = new PGi_Vendor_List__c();
		vl.Show_on_Surveys__c = true;
		vl.Name ='ABC';
		insert vl;
			
		Vendor_Scorecard__c vs = new Vendor_Scorecard__c();
		vs.Month_Year__c = 'sep-2017';
		vs.Related_PGi_Vendor__c = vl.id;
		insert vs;	
		
		vl = new PGi_Vendor_List__c();
		vl.Show_on_Surveys__c = true;
		vl.Name ='ABCD';
		insert vl;
					
		vs = new Vendor_Scorecard__c();
		vs.Month_Year__c = 'sep-2017';
		vs.Related_PGi_Vendor__c = vl.id;
		insert vs;				
														
		Vendor_Survey__c vsy = new Vendor_Survey__c();
		vsy.Vendor_Scorecard__c = vs.Id;
		vsy.Communicates_network_impacting_issues__c = 0;
		vsy.Familiar_with_PGi_business_and_trouble__c = 0;
		vsy.Knowledgeable_of_outstanding_problems__c = 0;
		vsy.Provides_accurate_timely_ticket_updates__c = 0;
		vsy.Responsive_when_PGI_escalations_occur__c = 0;
		insert vsy;
		
		vl = new PGi_Vendor_List__c();
		vl.Show_on_Surveys__c = true;
		vl.Name ='ABCE';
		insert vl;
 		vs = new Vendor_Scorecard__c();
		vs.Month_Year__c = 'sep-2017';
		vs.Related_PGi_Vendor__c = vl.id;
		insert vs;	
		     
 		PageReference pageRef = Page.scorecard;
		pageRef.getParameters().put('data', vs.Month_Year__c);
		
		Test.setCurrentPageReference(pageRef);
        ScorecardController sc = new ScorecardController(); 
        sc.nextVendor();
        sc.previousVendor();
        
        pageRef = Page.scorecard;
		pageRef.getParameters().put('data', '');
		
		Test.setCurrentPageReference(pageRef);		         
        sc = new ScorecardController(); 
    }  
    //This test method is used to coverage the code of ScheduleBatchScorecardGenerator class
    static testMethod void testScorecardController1() {
		PGi_Vendor_List__c vl = new PGi_Vendor_List__c();
		vl.Show_on_Surveys__c = true;
		vl.Name ='ABC';
		insert vl;
			
		Vendor_Scorecard__c vs = new Vendor_Scorecard__c();
		vs.Month_Year__c = 'sep-2017';
		vs.Related_PGi_Vendor__c = vl.id;
		insert vs;	
				 	
    	PageReference pageRef = Page.scorecard;
		pageRef.getParameters().put('data', vs.Month_Year__c);
			
		Test.setCurrentPageReference(pageRef);
        ScorecardController sc = new ScorecardController(); 
        sc.nextVendor();
        sc.previousVendor();
    }  
     
}