force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel from Opportunity Owner&#39;s user record</description>
    <label>Owner&#39;s Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <description>Populated from ASX</description>
    <inlineHelpText>Number of months for the contract</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>AT&amp;T SHELL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EMEA - TP Direct</fullName>
            </value>
            <value>
                <fullName>Event Center - Slide Assist</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>ON24 Forced Conv</fullName>
            </value>
            <value>
                <fullName>PGi Consolidated Billing</fullName>
            </value>
            <value>
                <fullName>PWN</fullName>
            </value>
            <value>
                <fullName>Ready Talk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Active_Host_NA_Only__c.field-meta.xml
<CustomField>
    <fullName>Active_Host_NA_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A flag for opportunities for Active Host - GlobalMeet Web.</description>
    <inlineHelpText>A flag for opportunities for Active Host - GlobalMeet Web.</inlineHelpText>
    <label>Active Host</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>One Time Event</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <label>Contract Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Existing_Service__c.field-meta.xml
<CustomField>
    <fullName>Existing_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enter 2 Products- 1st with the box checked for Existing Service, 2nd for New Service being added</inlineHelpText>
    <label>Existing Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Initial_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Bill_Date__c</fullName>
    <inlineHelpText>Expected date (confirmed by IST or PMO) when GCS customer will be initially billed for this new service</inlineHelpText>
    <label>Initial Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Min_Commit__c.field-meta.xml
<CustomField>
    <fullName>Min_Commit__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>May need to enter 2 Products- 1st with the box checked for the Min. Commit amount, 2nd if necessary, for estimated amount</inlineHelpText>
    <label>Min. Commit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/New_Quantity__c.field-meta.xml
<CustomField>
    <fullName>New_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/New_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>New_Sales_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Device(s)</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Licenses</fullName>
            </value>
            <value>
                <fullName>Minutes</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/X100_Ramp_Date__c.field-meta.xml
<CustomField>
    <fullName>X100_Ramp_Date__c</fullName>
    <inlineHelpText>Expected date (confirmed by IST or PMO) when GCS customer will be billed full MRR for this new service</inlineHelpText>
    <label>100% Ramp Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product_Existing_Service__c.field-meta.xml
<CustomField>
    <fullName>Product_Existing_Service__c</fullName>
    <formula>Product2.Existing_Service_Eligible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Existing Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product_Min_Commitment_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Product_Min_Commitment_Eligible__c</fullName>
    <formula>Product2.Min_Commitment_Eligible__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Min Commitment Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product_RecordType_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_RecordType_Name__c</fullName>
    <description>Stores the associated product&#39;s record type name</description>
    <formula>Product2.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product&#39;s RecordType Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Billing_Frequency_Options__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency_Options__c</fullName>
    <label>Billing Frequency Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>One Time Event</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Min_Commitment_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Min_Commitment_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Min Commitment Eligible</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used to determine what shows up in Product Select VF page</description>
    <inlineHelpText>What regions should be able to see this product when adding to Opps?</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Unit_Type_Options__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type_Options__c</fullName>
    <label>Unit Type Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Device(s)</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Licenses</fullName>
            </value>
            <value>
                <fullName>Minutes</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Care - CEM</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Finance&amp;Pricing</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>IST Team</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Service &amp; Care</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
    <label>DB Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <color>#009900</color>
                <label>NA</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
                <label>APAC</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <color>#990000</color>
                <label>LA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Region__c.field-meta.xml
<CustomField>
    <fullName>User_Region__c</fullName>
    <label>User Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/opportunityProductEntryExtension.cls
public with sharing class opportunityProductEntryExtension {
    public class CustomException extends Exception{}
    public Opportunity theOpp {get;set;}
    public String searchString {get;set;}
    public opportunityLineItem[] shoppingCart {get;set;}
    public priceBookEntry[] AvailableProducts {get;set;}
    public Pricebook2 theBook {get;set;}  
    public String prodname{get;set;} 
    public Map<String, List<SelectOption>> ShoppingCartBillFreqOptions {get;set;}
    public Map<String, List<SelectOption>> ShoppingCartUnitTypeOptions {get;set;}
    public Map<String, String> ShoppingCartExistingService {get;set;}
    public Map<String, String> ShoppingCartMinCommitment {get;set;}
    public String toSelect {get; set;}
    public String rowIndex {get;set;}
    public Decimal Total {get;set;}
    public String boolvalue {get;set;}
    
    public Boolean overLimit {get;set;}
    public Boolean error {get;set;}
    public Boolean multipleCurrencies {get; set;}
    public Boolean isCurrentUserAdmin {get;set;}
    private Boolean forcePricebookSelection = false;
    
    private opportunityLineItem[] forDeletion = new opportunityLineItem[]{};
    //public String query {get;set;}
    public opportunityProductEntryExtension(ApexPages.StandardController controller) {
    
        
        // Need to know if org has multiple currencies enabled
        multipleCurrencies = UserInfo.isMultiCurrencyOrganization();
        isCurrentUserAdmin = PGIAppConstants.ADMIN_PROFILES.contains(UserInfo.getProfileId());
        // Get information about the Opportunity being worked on
        if(multipleCurrencies)
            theOpp = database.query('select Id, Pricebook2Id, Pricebook2.Name, CurrencyIsoCode from Opportunity where Id = \'' + controller.getRecord().Id + '\' limit 1');
        else
            theOpp = [select Id, Pricebook2Id, PriceBook2.Name from Opportunity where Id = :controller.getRecord().Id limit 1];
        
        // If products were previously selected need to put them in the "selected products" section to start with
        shoppingCart = [select Id,New_Quantity__c, Active_Host_NA_Only__c, Min_Commit__c, Existing_Service__c, New_Sales_Price__c, Unit_Type__c, Billing_Frequency__c, Contract_Term__c, TotalPrice, UnitPrice, Description, PriceBookEntryId, PriceBookEntry.Name, PriceBookEntry.IsActive, PriceBookEntry.Product2Id, PriceBookEntry.Product2.Name, PriceBookEntry.Product2.Unit_Type_Options__c,PriceBookEntry.Product2.Billing_Frequency_options__c,PriceBookEntry.PriceBook2Id, Initial_Bill_Date__c, X100_Ramp_Date__c from opportunityLineItem where OpportunityId=:theOpp.Id order by PriceBookEntry.Product2.Name, Id];
        ShoppingCartBillFreqOptions = getBillFreqOptions();
        ShoppingCartUnitTypeOptions = getUnitTypeOptions();
        ShoppingCartExistingService = getExistingService();
        ShoppingCartMinCommitment = getMinCommitment();
        // Check if Opp has a pricebook associated yet
        if(theOpp.Pricebook2Id == null){
            Pricebook2[] activepbs = [select Id, Name from Pricebook2 where isActive = true limit 2];
            if(activepbs.size() == 2){
                forcePricebookSelection = true;
                theBook = new Pricebook2();
            }
            else{
                theBook = activepbs[0];
            }
        }
        else{
            theBook = theOpp.Pricebook2;
        }
        
        if(!forcePricebookSelection)
            updateAvailableList();
    }
    

       
    public String getChosenCurrency(){
    
        if(multipleCurrencies)
            return (String)theOpp.get('CurrencyIsoCode');
        else
            return '';
    }

    public void updateAvailableList() {
    
        // We dynamically build a query string and exclude items already in the shopping cart
        String qString = 'select Id, Pricebook2Id, IsActive, Product2.Unit_Type_Options__c,Product2.Billing_Frequency_options__c,Product2.Name, Product2.Family, Product2.IsActive, Product2.Description, UnitPrice,Product_Existing_Service__c,Product_Min_Commitment_Eligible__c from PricebookEntry where IsActive=true and Product_RecordType_Name__c LIKE \'%PGi%\' and Product2.Name != \'PGI Standard Product\' and Pricebook2Id = \'' + theBook.Id + '\'';
        if(multipleCurrencies)
            qstring += ' and CurrencyIsoCode = \'' + theOpp.get('currencyIsoCode') + '\'';
        
        // note that we are looking for the search string entered by the user in the name OR description
        // modify this to search other fields if desired
        if(searchString != null && searchString != ''){
            qString+= ' and (Product2.Name like \'%' + searchString + '%\' or Product2.Description like \'%' + searchString + '%\')';
        }
        
       
        Id currentProfileId = UserInfo.getProfileId();
        Boolean filterRegion = false; //include close bracket if region is filtered
        User currentUser = [SELECT User_Region__c, Channel__c FROM User WHERE Id =: UserInfo.getUserId()];
        if(!PGIAppConstants.ADMIN_PROFILES.contains(currentProfileId) && !PGIAppConstants.GCS_DIAMOND_PROFILES.contains(currentProfileId)){
            if(currentUser.User_Region__c != null && currentUser.User_Region__c != '' && currentUser.User_Region__c != 'None'){
                qString += ' and (Product2.Region__c = \'ALL\' or Product2.Region__c includes (\'' + currentUser.User_Region__c + '\')';
                filterRegion = true;
            }
            if(currentUser.Channel__c != null && currentUser.Channel__c != '' && currentUser.Channel__c != 'None'){
                qString += ' or Product2.Channel_to_Included__c includes (\'' + currentUser.Channel__c + '\'))';
                qString += ' and Product2.Channel_to_Excluded__c excludes (\'' + currentUser.Channel__c + '\')';
            }
            else if (filterRegion){
                qString += ')';
            }
        }
        
        qString+= ' order by Product2.Name';
        qString+= ' limit 101';
        
        error = false;
        
        try{        
            AvailableProducts = database.query(qString);
            //query = qString + '; size='+AvailableProducts.size();
                        
            // We only display up to 100 results... if there are more than we let the user know (see vf page)
            if(AvailableProducts.size()==101){
                AvailableProducts.remove(100);
                overLimit = true;
            }
            else{
                overLimit=false;
            }
        }
        catch(Exception ex){
            error = true;
        }
    }

   
    public Map<String, List<SelectOption>> getBillFreqOptions() {
        Map<String, List<SelectOption>> billfreqoptns = new Map<String, List<SelectOption>>();
        List<Product2> allprodlist = [Select id,name,billing_frequency_options__c from product2 where recordtype.name like '%PGi%' and isActive=True];
        for(Product2 prd : allprodlist) {
            if(prd.Billing_Frequency_Options__c <> NULL){
                List<SelectOption> options = new List<SelectOption>();
                if(prd.Billing_Frequency_Options__c.split(';').size() > 1) {
                    options.add(new Selectoption('','-Select-'));
                }
                List<String> productbillfreqoptions = new List<String> (prd.Billing_Frequency_Options__c.split(';'));
                for (String str: productbillfreqoptions) {
                    SelectOption op = new SelectOption(str, str);
                    options.add(op);
                }
                billfreqoptns.put(prd.name, options);
            }
        }
        return billfreqoptns;
    }
    
    public Map<String, List<SelectOption>> getUnitTypeOptions() {
        Map<String, List<SelectOption>> unittypeoptns = new Map<String, List<SelectOption>>();
        List<Product2> allprodlist = [Select id,name,unit_type_options__c from product2 where recordtype.name like '%PGi%' and isActive=True];
        for(Product2 prd : allprodlist){
            if(prd.unit_type_options__c <> NULL){
                List<SelectOption> options = new List<SelectOption>();
                if(prd.Unit_Type_Options__c.split(';').size() > 1) {
                    options.add(new Selectoption('','-Select-'));    
                }
                List<String> productunittypeoptions = new List<String> (prd.Unit_Type_Options__c.split(';'));
                for (String str: productunittypeoptions) {
                    SelectOption op = new SelectOption(str, str);
                    options.add(op);
                }
                unittypeoptns.put(prd.name, options);
            }    
        }
        return unittypeoptns;
    }    
    
    public Map<String, String> getExistingService() {
    Map<String, String> prodexistingservice = new Map<String, String>();
    List<Product2> allprodlist = [Select id,name,existing_service_eligible__c from product2 where recordtype.name like '%PGi%' and isactive=True];
    for(Product2 prd : allprodlist){
        String boolvalue;
        if(prd.existing_service_eligible__c == True)
            boolvalue = 'False';
        else
            boolvalue = 'True'; 
        prodexistingservice.put(prd.name,boolvalue);        
        }    
    return prodexistingservice;
    }  
    
    public Map<String, String> getMinCommitment() {
    Map<String, String> prodmincommitment = new Map<String, String>();
    List<Product2> allprodlist = [Select id,name,Min_Commitment_Eligible__c from product2 where recordtype.name like '%PGi%' and isactive=True];
    for(Product2 prd : allprodlist){
        String boolvalue;
        if(prd.Min_Commitment_Eligible__c == True)
            boolvalue = 'False';
        else
            boolvalue = 'True'; 
        prodmincommitment.put(prd.name,boolvalue);        
        }    
    return prodmincommitment;
    }  
    
    public void addToShoppingCart(){
    
        // This function runs when a user hits "select" button next to a product
    
        for(PricebookEntry d : AvailableProducts){
            if((String)d.Id==toSelect){
                shoppingCart.add(new opportunityLineItem(Opportunity = theOpp,OpportunityId=theOpp.Id, PriceBookEntry=d, PriceBookEntryId=d.Id, UnitPrice=d.UnitPrice));
                break;
            }
        }
        updateAvailableList();  
    }
    

    public PageReference removeFromShoppingCart(){
    
        // This function runs when a user hits "remove" on an item in the "Selected Products" section
        Integer selectedRowIndex = Integer.valueOf(rowIndex);
        OpportunityLineItem oli = shoppingCart[selectedRowIndex];
        if(oli != null && oli.Id != null){
            forDeletion.add(oli);
        }
        shoppingCart.remove(selectedRowIndex);
        updateAvailableList();
        
        return null;
    }
    
    public PageReference onSave(){
        
        // Validate required fields
        Boolean isError = false;
        for(opportunityLineItem d : shoppingCart){
                if(d.New_Quantity__c == null){
                d.New_Quantity__c.addError('You must enter a value');
                isError = true;
            }
            if(d.New_Sales_Price__c == null){
                d.New_Sales_Price__c.addError('You must enter a value');
                isError = true;
            }
            if(d.Unit_Type__c == null){
                d.Unit_Type__c.addError('You must enter a value');
                isError = true;
            }
            if(d.Billing_Frequency__c == null){
                d.Billing_Frequency__c.addError('You must enter a value');
                isError = true;
            }
            if(d.Contract_Term__c == null){
                d.Contract_Term__c.addError('You must enter a value');
                isError = true;
            }
        }
        
        if(isError)
                return null;
        
        // If previously selected products are now removed, we need to delete them
        try{
        if(forDeletion.size()>0)
            delete(forDeletion);
            forDeletion.clear();
            // Previously selected products may have new quantities and amounts, and we may have new products listed, so we use upsert here
            try{
                if(shoppingCart.size()>0)
                    upsert(shoppingCart);
            }
            catch(Exception e){
                ApexPages.addMessages(e);
                return null;
            }  
        }
         catch(Exception e){
            ApexPages.addMessages(e);
            return null;
        }
   
        // After save return the user to the Opportunity
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
    
    public PageReference onCancel(){
 
        // If user hits cancel we commit no changes and return them to the Opportunity   
        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
    }
    
    public void deselectcheckbox()  {
        for(opportunityLineItem d : shoppingCart){
            d.min_commit__c = False; 
        }  
    }
    
    public PageReference redirect(){
    system.debug('ARC debug oppproductextension oppid:'+theopp.id);
    return null;
    }
    

}