force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Channel from Opportunity Owner&#39;s user record</description>
    <label>Owner&#39;s Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source_Open__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source_Open__c</fullName>
    <label>Opportunity Source</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Contact Us</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Customer Referral</fullName>
            </value>
            <value>
                <fullName>Demo Request</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Inbound Email</fullName>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
            </value>
            <value>
                <fullName>Lead Gen: Other</fullName>
            </value>
            <value>
                <fullName>LinkedIn Sales Navigator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Web Chat</fullName>
            </value>
            <value>
                <fullName>Zoom Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Asia Pacific</fullName>
            </value>
            <value>
                <fullName>AT&amp;T SHELL</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>EMEA - TP Direct</fullName>
            </value>
            <value>
                <fullName>Event Center - Slide Assist</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>ON24 Forced Conv</fullName>
            </value>
            <value>
                <fullName>PGi Consolidated Billing</fullName>
            </value>
            <value>
                <fullName>PWN</fullName>
            </value>
            <value>
                <fullName>Ready Talk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Channel_to_Included__c.field-meta.xml
<CustomField>
    <fullName>Channel_to_Included__c</fullName>
    <label>Channel to Include</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used to determine what shows up in Product Select VF page</description>
    <inlineHelpText>What regions should be able to see this product when adding to Opps?</inlineHelpText>
    <label>Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>ALL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Care - CEM</fullName>
            </value>
            <value>
                <fullName>Carrier</fullName>
            </value>
            <value>
                <fullName>Cloud</fullName>
            </value>
            <value>
                <fullName>Finance&amp;Pricing</fullName>
            </value>
            <value>
                <fullName>iMeetCentral</fullName>
            </value>
            <value>
                <fullName>Information Systems</fullName>
            </value>
            <value>
                <fullName>IST Team</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Major Accounts</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Modality</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>ReadyTalk</fullName>
            </value>
            <value>
                <fullName>Sales Engineers</fullName>
            </value>
            <value>
                <fullName>Sales Operations</fullName>
            </value>
            <value>
                <fullName>Service &amp; Care</fullName>
            </value>
            <value>
                <fullName>TalkPoint</fullName>
            </value>
            <value>
                <fullName>Tier One</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>This is a field that is installed by and used with the Adoption Dashboard AppExchange package. If your org already has a similar field, you can change the reports that are part of the Adoption Dashboard package to use your custom field and then delete this field.</description>
    <label>DB Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NA</fullName>
                <color>#009900</color>
                <label>NA</label>
            </value>
            <value>
                <fullName>EMEA</fullName>
                <color>#3333FF</color>
                <label>EMEA</label>
            </value>
            <value>
                <fullName>APAC</fullName>
                <color>#CC6600</color>
                <label>APAC</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <color>#990000</color>
                <label>LA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/User_Region__c.field-meta.xml
<CustomField>
    <fullName>User_Region__c</fullName>
    <label>User Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/opportunityProductEntryTests.cls
@istest
private class opportunityProductEntryTests {
    //@isTest(SeeAllData=true)
    //private static void Test_opportunityProductEntry(){     
    //    Test.startTest();
    //    Profile testProfile = [SELECT Id FROM Profile WHERE Name='Standard User'];
    //    User testUser = PGITestUtilities.getTestUser(testProfile);
    //    testUser.User_Region__c = 'NA';
    //    testUser.Channel__c = 'Cloud';
    //    insert testUser;
        
    //    system.runAs(testUser){   
    //        Account testAccount = PGITestUtilities.getAccountDetails();
    //        testaccount.numberofemployees=5;
    //        testaccount.AnnualRevenue=100;
    //        insert testAccount;
    //        Product2 product = PGITestUtilities.getStdProduct();
    //        product.Region__c='ALL';
    //        product.Channel_to_Included__c = 'Major Accounts';
    //        insert product;
    //        PricebookEntry pbe = PGITestUtilities.CreatePriceBookEntryForProduct(product);
    //        insert pbe;
    //        Opportunity testOpp = PGITestUtilities.getOpportunityDetails();
    //        testOpp.AccountId = testAccount.Id;
    //        insert testOpp;
    //        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(testOpp.Id, pbe.Id);
    //        oli.Opportunity = testOpp;
    //        oli.PricebookEntry = pbe;
    //        oli.Opportunity.AccountId = testAccount.Id;
    //        insert oli;  

    //        PageReference pageRef = Page.opportunityProductEntry;
    //        pageRef.getParameters().put('Id',testOpp.Id);
    //        Test.setCurrentPageReference(pageRef);
    //        opportunityProductEntryExtension oPEE = new opportunityProductEntryExtension(new ApexPages.StandardController(oli.Opportunity));
            
    //        // test 'getChosenCurrency' method
    //        if(UserInfo.isMultiCurrencyOrganization())
    //            System.assert(oPEE.getChosenCurrency()!='');
    //        else
    //            System.assertEquals(oPEE.getChosenCurrency(),'');
    
    //        Integer startCount = oPEE.ShoppingCart.size();
    //        system.assert(startCount>0);
    
    //         //test search functionality without finding anything
    //        oPEE.searchString = 'michaelforce is a hip cat';
    //        oPEE.updateAvailableList();
    //        system.assert(oPEE.AvailableProducts.size()==0);
            
    //        // test search again, this time we will find something
    //        oPEE.searchString = oli.PricebookEntry.Name;
    //        oPEE.updateAvailableList();
    //        system.assert(oPEE.AvailableProducts.size()>0);       
    
    //        // test add to Shopping Cart function
    //        oPEE.toSelect = oPEE.AvailableProducts[0].Id;
    //        oPEE.addToShoppingCart();
    //        system.assert(oPEE.shoppingCart.size()>0);
                    
    //        // test save method - WITHOUT quanitities and amounts entered and confirm that error message is displayed
    //        oPEE.onSave();
    //        system.assert(ApexPages.getMessages().size()>0);
            
    //        // add required info and try save again
    //        for(OpportunityLineItem o : oPEE.ShoppingCart){
    //            o.quantity = 5;
    //            o.unitprice = 300;
    //        }
    //        oPEE.onSave();
    //        integer rowCount = oPEE.shoppingCart.size();        
    //        oPEE.rowIndex = '0';
    //        oPEE.removeFromShoppingCart();
    //        system.assert(oPEE.shoppingCart.size() == rowCount-1);
            
    //        // final quick check of cancel button
    //        System.assert(oPEE.onCancel()!=null);
    //    }

    //    Test.stopTest();
    //}
    
    private static testMethod void Test_opportunityProductRedirectExtension(){
        Test.startTest();
        Account testAccount = PGITestUtilities.getAccountDetails();
        insert testAccount;
        Opportunity testOpp = PGITestUtilities.getOpportunityDetails();
        testOpp.AccountId = testAccount.Id;
        insert testOpp;
        Product2 product = PGITestUtilities.getStdProduct();
        insert product;
        PricebookEntry pbe = PGITestUtilities.CreatePriceBookEntryForProduct(product);
        insert pbe;
        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(testOpp.Id, pbe.Id);
        oli.Opportunity = testOpp;
        oli.PricebookEntry = pbe;
        oli.Opportunity.AccountId = testAccount.Id;
        insert oli;
        
        PageReference pageRef = Page.opportunityProductRedirect;
        pageRef.getParameters().put('Id',oli.Id);
        Test.setCurrentPageReference(pageRef);
        opportunityProductRedirectExtension oPRE = new opportunityProductRedirectExtension(new ApexPages.StandardController(oli));
        PageReference pageRef2 = oPRE.redirect();
        Test.stopTest();
        system.assert(pageRef2.getUrl().contains('opportunityProductEntry'));
    }
    // for IMC account record type
    private static testMethod void Test_IMCAccRT_opportunityProductRedirectExtension(){
        Test.startTest();
        Account testAccount = PGITestUtilities.getAccountDetails();
        insert testAccount;
        Id oppIMCRecordtypeId = [SELECT Id,Name FROM RecordType WHERE sObjectType = 'Opportunity' AND Name LIKE '%IMC%' LIMIT 1].id;
        Opportunity testOpp = new Opportunity(Name = 'TestOpportunity',StageName = 'Awareness',CloseDate = date.today() + 10,
                                              Opportunity_Source_Open__c = 'None',recordtypeid = oppIMCRecordtypeId);
        insert testOpp;
        //Opportunity testOpp = PGITestUtilities.getOpportunityDetails();
        //testOpp.AccountId = testAccount.Id;
        //insert testOpp;
        Product2 product = PGITestUtilities.getStdProduct();
        insert product;
        PricebookEntry pbe = PGITestUtilities.CreatePriceBookEntryForProduct(product);
        insert pbe;
        OpportunityLineItem oli = PGITestUtilities.getOpportunityLineItemDetails(testOpp.Id, pbe.Id);
        oli.Opportunity = testOpp;
        oli.PricebookEntry = pbe;
        oli.Opportunity.AccountId = testAccount.Id;
        insert oli;
        
        PageReference pageRef = Page.opportunityProductRedirect;
        pageRef.getParameters().put('Id',oli.Id);
        Test.setCurrentPageReference(pageRef);
        opportunityProductRedirectExtension oPRE = new opportunityProductRedirectExtension(new ApexPages.StandardController(oli));
        PageReference pageRef2 = oPRE.redirect();
        Test.stopTest();
        system.assert(pageRef2.getUrl().contains('OpportunityProductEditPage'));
    }
}