force-app/main/default/objects/Opportunity/fields/Competitor_s__c.field-meta.xml
<CustomField>
    <fullName>Competitor_s__c</fullName>
    <label>Competitor(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>8X8</fullName>
            </value>
            <value>
                <fullName>AAPT</fullName>
            </value>
            <value>
                <fullName>Airtel</fullName>
            </value>
            <value>
                <fullName>Amacus</fullName>
            </value>
            <value>
                <fullName>Arcano</fullName>
            </value>
            <value>
                <fullName>Arkadin</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Atlassian/Jira</fullName>
            </value>
            <value>
                <fullName>Bluejeans</fullName>
                <label>BlueJeans</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>British Telecom</label>
            </value>
            <value>
                <fullName>Broadsoft</fullName>
            </value>
            <value>
                <fullName>Budget Conference</fullName>
            </value>
            <value>
                <fullName>Chorus Call</fullName>
            </value>
            <value>
                <fullName>Cisco Teams</fullName>
            </value>
            <value>
                <fullName>CommuniCloud</fullName>
            </value>
            <value>
                <fullName>DSNL</fullName>
            </value>
            <value>
                <fullName>FreeConferenceCall</fullName>
            </value>
            <value>
                <fullName>Fuze Business</fullName>
                <label>Fuze</label>
            </value>
            <value>
                <fullName>Google+ Hangout</fullName>
                <label>Google Hangouts</label>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>GoToWebinar</fullName>
            </value>
            <value>
                <fullName>Intercall (West)</fullName>
            </value>
            <value>
                <fullName>Inxpo</fullName>
            </value>
            <value>
                <fullName>Join.me</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
                <label>Level 3 (CenturyLink)</label>
            </value>
            <value>
                <fullName>Microsoft Meeting Broadcast</fullName>
            </value>
            <value>
                <fullName>Microsoft Skype for Business</fullName>
            </value>
            <value>
                <fullName>Microsoft Teams</fullName>
            </value>
            <value>
                <fullName>NASDAQ OMX</fullName>
                <label>NASDAQ (West)</label>
            </value>
            <value>
                <fullName>ON24</fullName>
                <label>On24</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incumbent__c.field-meta.xml
<CustomField>
    <fullName>Incumbent__c</fullName>
    <label>Incumbent</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>8X8</fullName>
            </value>
            <value>
                <fullName>AAPT</fullName>
            </value>
            <value>
                <fullName>Airtel</fullName>
            </value>
            <value>
                <fullName>Amacus</fullName>
            </value>
            <value>
                <fullName>Arcano</fullName>
            </value>
            <value>
                <fullName>Arkadin</fullName>
            </value>
            <value>
                <fullName>AT&amp;T</fullName>
            </value>
            <value>
                <fullName>Atlassian/Jira</fullName>
            </value>
            <value>
                <fullName>Avaya</fullName>
            </value>
            <value>
                <fullName>Bluejeans</fullName>
                <label>BlueJeans</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>British Telecom</label>
            </value>
            <value>
                <fullName>BudgetConference</fullName>
            </value>
            <value>
                <fullName>Chorus Call</fullName>
            </value>
            <value>
                <fullName>Cisco Teams</fullName>
            </value>
            <value>
                <fullName>CommuniCloud</fullName>
            </value>
            <value>
                <fullName>DSNL</fullName>
            </value>
            <value>
                <fullName>FreeConferenceCall</fullName>
            </value>
            <value>
                <fullName>Fuze Business</fullName>
                <label>Fuze</label>
            </value>
            <value>
                <fullName>Google+ Hangout</fullName>
                <label>Google Hangouts</label>
            </value>
            <value>
                <fullName>GoToMeeting</fullName>
            </value>
            <value>
                <fullName>GoToWebinar</fullName>
            </value>
            <value>
                <fullName>Intercall (West)</fullName>
            </value>
            <value>
                <fullName>Inxpo</fullName>
            </value>
            <value>
                <fullName>Jive</fullName>
            </value>
            <value>
                <fullName>Join.me</fullName>
            </value>
            <value>
                <fullName>Level 3</fullName>
                <label>Level 3 (CenturyLink)</label>
            </value>
            <value>
                <fullName>Microsoft Meeting Broadcast</fullName>
            </value>
            <value>
                <fullName>Microsoft Skype for Business</fullName>
            </value>
            <value>
                <fullName>Microsoft Teams</fullName>
            </value>
            <value>
                <fullName>Mitel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Source_Close__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Source_Close__c</fullName>
    <label>Opportunity Source Close</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Hoovers</fullName>
            </value>
            <value>
                <fullName>iMeet Sales Accelerator</fullName>
            </value>
            <value>
                <fullName>LinkedIn Sales Navigator</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partners</fullName>
            </value>
            <value>
                <fullName>Purchased List</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Zoom Info</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary Contact Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Won_Reason__c.field-meta.xml
<CustomField>
    <fullName>Primary_Won_Reason__c</fullName>
    <label>Primary Won Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Add-on or Renewal</fullName>
            </value>
            <value>
                <fullName>Customer Support Model</fullName>
            </value>
            <value>
                <fullName>Pricing Structure</fullName>
            </value>
            <value>
                <fullName>Relationship Loyalty</fullName>
            </value>
            <value>
                <fullName>Reliability of the Service</fullName>
            </value>
            <value>
                <fullName>Reseller Only - Undisclosed</fullName>
            </value>
            <value>
                <fullName>Superior Product Functionality</fullName>
            </value>
            <value>
                <fullName>Value for Price</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CheckPrimaryContactRoleTEST.cls
@isTest
public class CheckPrimaryContactRoleTEST {
    @testSetup static void setup() {
        PGITestUtilities.disableSalesWings();
    }
    static testMethod void testContactRole() {
        
        //create an account
        Account acc = new Account();
        acc.Name = 'Acc-ContactRoles';
        acc.BillingCountry = 'United States';
        acc.BillingState = 'California';
        acc.BillingStreet = 'Street1';
        acc.BillingPostalCode = '12345';
        
        
        insert acc;
        
        //create 2 contacts
        Contact con1 = new Contact();
        con1.FirstName = 'ContactRoles1';
        con1.LastName = 'Surname1';
        con1.AccountId = acc.Id;
        
        insert con1;
        
        Contact con2 = new Contact();
        con2.FirstName = 'ContactRoles2';
        con2.LastName = 'Surname2';
        con2.AccountId = acc.Id;
        
        insert con2;
        
        //create an opportunity
        Opportunity opp = new Opportunity();
        opp.Name = 'Opp-ContactRoles';
        opp.AccountId = acc.Id;
        opp.stagename = 'Awareness';
        opp.Amount = 10000;
        opp.CloseDate = System.Today();
        
        
        insert opp;
        
        //add 2 contact roles and make 1 the primary
        OpportunityContactRole ocr1 = new OpportunityContactRole();
        ocr1.OpportunityId = opp.Id;
        ocr1.ContactId = con1.Id;
        ocr1.IsPrimary = TRUE;
        ocr1.role='Business User';
        
        OpportunityContactRole ocr2 = new OpportunityContactRole();
        ocr2.OpportunityId = opp.Id;
        ocr2.ContactId = con2.Id;
        ocr2.IsPrimary = FALSE;
        
        
        insert ocr1;
        insert ocr2;
        
        opp.Competitor_s__c = 'Airtel';
        opp.Incumbent__c='Airtel';
        opp.Primary_Won_Reason__c = 'Budget Available';
        opp.Opportunity_Source_Close__c = 'Hoovers';
        opp.StageName = 'Awareness';
        
        OpportunityTriggerHandler.bypassContactRole = false;
        update opp;
        
        
        
        
        Integer oppAmount = 0;
        Integer singleAmount = 1;
        for (Opportunity o:[SELECT Id FROM Opportunity 
                            WHERE Name = 'Opp-ContactRoles' AND
                            Primary_contact_assigned__c = TRUE]) {
                                oppAmount++;
                            }
        System.assertEquals(singleAmount, oppAmount);
    }
    
}