force-app/main/default/objects/Opportunity/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <description>Populated from ASX</description>
    <inlineHelpText>Number of months for the contract</inlineHelpText>
    <label>Contract Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/highest_MRR_Product_Value__c.field-meta.xml
<CustomField>
    <fullName>highest_MRR_Product_Value__c</fullName>
    <label>highest MRR Product Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_ACV_Total_Collab__c.field-meta.xml
<CustomField>
    <fullName>Product_ACV_Total_Collab__c</fullName>
    <label>Product ACV Total (Collab)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_ACV_Total_Webcast__c.field-meta.xml
<CustomField>
    <fullName>Product_ACV_Total_Webcast__c</fullName>
    <label>Product ACV Total (Webcast)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_ACV_Total_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Product_ACV_Total_Webinar__c</fullName>
    <label>Product ACV Total (Webinar)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_NRR_Total_Collab__c.field-meta.xml
<CustomField>
    <fullName>Product_NRR_Total_Collab__c</fullName>
    <label>Product NRR Total (Collab)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_NRR_Total_Webcast__c.field-meta.xml
<CustomField>
    <fullName>Product_NRR_Total_Webcast__c</fullName>
    <label>Product NRR Total (Webcast)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_NRR_Total_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Product_NRR_Total_Webinar__c</fullName>
    <label>Product NRR Total (Webinar)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Annual_Value__c.field-meta.xml
<CustomField>
    <fullName>Annual_Value__c</fullName>
    <description>andy = updated from = Minutes to contains Minute 4/24/2014</description>
    <formula>/*****************************************************/ 
/*Annual Value || Annual_Value__c*/ 
IF( 
AND( 
CONTAINS(TEXT(Unit_Type__c), &quot;Minute&quot;), 
Min_Commit__c = False 
), 0, 
IF(ISPICKVAL(Unit_Type__c, &quot;Contract&quot;), 0, 
IF(ISPICKVAL(Billing_Frequency__c, &quot;One Time Event&quot;), 0, 
IF(ISPICKVAL(Unit_Type__c, &quot;Ancillary&quot;), 0, 
IF(isReportable_Text__c = &quot;Invalid&quot;, 0, 
IF( 
ISPICKVAL(Billing_Frequency__c,&apos;Annually&apos;), 
New_Sales_Price__c* New_Quantity__c, IF( 
ISPICKVAL(Billing_Frequency__c,&apos;Quarterly&apos;), 
New_Sales_Price__c * New_Quantity__c * 4, 
IF( 
AND( 
ISPICKVAL(Billing_Frequency__c, &quot;One Time Event&quot;), 
Contract_Term__c &gt; 11 
), 
New_Sales_Price__c* New_Quantity__c, 
IF( Contract_Term__c &gt; 12, New_Sales_Price__c* New_Quantity__c*12, 
New_Sales_Price__c* New_Quantity__c * Contract_Term__c 
) 
) 
) 
) 
) 
) 
) 
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product ACV</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>One Time Event</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Annually</fullName>
            </value>
            <value>
                <fullName>Pay Per Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Contract_Term__c.field-meta.xml
<CustomField>
    <fullName>Contract_Term__c</fullName>
    <label>Contract Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Existing_Service__c.field-meta.xml
<CustomField>
    <fullName>Existing_Service__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Enter 2 Products- 1st with the box checked for Existing Service, 2nd for New Service being added</inlineHelpText>
    <label>Existing Service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Historic_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Historic_Line_Item__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Historic Line Item</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/iMCNRRProduct__c.field-meta.xml
<CustomField>
    <fullName>iMCNRRProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>updated by WFR from Products if the Product is selected as an iMC NRR</description>
    <label>iMC NRR Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/iMCProduct__c.field-meta.xml
<CustomField>
    <fullName>iMCProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <description>auto set based off WFR that if the Oppty Product comes from the iMC Product Catalog</description>
    <label>iMC Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/isReportable_Text__c.field-meta.xml
<CustomField>
    <fullName>isReportable_Text__c</fullName>
    <defaultValue>&quot;Valid&quot;</defaultValue>
    <label>Line Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Legacy_MRR__c.field-meta.xml
<CustomField>
    <fullName>Legacy_MRR__c</fullName>
    <label>Legacy MRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/New_Quantity__c.field-meta.xml
<CustomField>
    <fullName>New_Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/New_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>New_Sales_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/NRR__c.field-meta.xml
<CustomField>
    <fullName>NRR__c</fullName>
    <formula>IF(iMCNRRProduct__c = TRUE &amp;&amp; iMCProduct__c = TRUE, TotalPrice,
IF(ISPICKVAL(Billing_Frequency__c, &quot;One Time Event&quot;), New_Sales_Price__c * New_Quantity__c, 
IF(ISPICKVAL(Billing_Frequency__c, &quot;Pay Per Use&quot;), New_Sales_Price__c * New_Quantity__c,
IF(ISPICKVAL(Unit_Type__c , &quot;Ancillary&quot;), New_Sales_Price__c * New_Quantity__c,
0))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product NRR</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ancillary</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
            <value>
                <fullName>Device(s)</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Licenses</fullName>
            </value>
            <value>
                <fullName>Minutes</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/iMCNRRProduct__c.field-meta.xml
<CustomField>
    <fullName>iMCNRRProduct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>iMC NRR Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Override_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>Override_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used exclusively to give users the ability to override validation rules by having this checked.  Also is built into every validation rule that shouldnt affect end users.</description>
    <inlineHelpText>Do not check this box for any users who are not admins</inlineHelpText>
    <label>Override Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OpportunityLineItemTest.cls
@isTest
private class OpportunityLineItemTest {
    static testMethod void testValidateExistingService() {
        /*
        Opportunity testOpp1 = PGITestUtilities.getOpportunityDetails();
        testOpp1.Type = 'Existing Cust- Existing Svc';
        insert testOpp1;
        Product2 testProduct = PGITestUtilities.getStdProduct();
        insert testProduct;
        PricebookEntry testPbe = PGITestUtilities.CreatePriceBookEntryForProduct(testProduct);
        insert testPbe;
        OpportunityLineItem testOpli1 = PGITestUtilities.getOpportunityLineItemDetails(testOpp1.Id, testPbe.Id);
        testOpli1.Existing_Service__c = false;
        OpportunityLineItem testOpli2 = PGITestUtilities.getOpportunityLineItemDetails(testOpp1.Id, testPbe.Id);
        testOpli2.Existing_Service__c = false;
        User u = PGITestUtilities.getTestUser();
        u.Override_Validation_Rules__c = false;
        insert u;
        Test.startTest();
        System.runAs(u){
            //If Opp = Existing Cust- Existing Svc & OPLI Existing Service = False, error message is displayed
            try{
                insert testOpli1;
                system.assert(false);
            }
            catch(Exception ex){
                system.assert(true);
            }   
            
            //If Opp = Existing Cust- Existing Svc & OPLI Existing Service = True, no error saving record
            testOpli1.Existing_Service__c = true;
            insert testOpli1;
            insert testOpli2;
            
            //If Opp = Existing Cust- New Svc & OPLI Existing Service = False, no error saving record
            Opportunity testOpp2 = PGITestUtilities.getOpportunityDetails();
            testOpp2.Type = 'Existing Cust- New Svc';
            insert testOpp2;
            OpportunityLineItem testOpli3 = PGITestUtilities.getOpportunityLineItemDetails(testOpp2.Id, testPbe.Id);
            testOpli3.Existing_Service__c = false;
            insert testOpli3;
            testOpli3.Quantity = 12;
            update testOpli3;
        }
     
        Test.stopTest();
        */
        
        Id pricebookId = Test.getStandardPricebookId();
       Product2 prod = new Product2(
            Name = 'Product X',
            ProductCode = 'Pro-X'
        );
        insert prod;

        PricebookEntry pbEntry = new PricebookEntry(
            Pricebook2Id = pricebookId,
            Product2Id = prod.Id,
            UnitPrice = 100.00,
            IsActive = true
        );
        insert pbEntry;

        Pricebook2 customPB = new Pricebook2(
            Name='Custom Pricebook',
            isActive=true
        );
        insert customPB;

        Opportunity oppo = new Opportunity();
            oppo.StageName      = 'native activise';
            oppo.Name           = '3';
            //oppo.WFCE__WP_ID__c = '13';
            //po.MRR_c = 3;
            oppo.highest_MRR_Product_Value__c = -1;
            oppo.Pricebook2Id = pricebookId;
            oppo.CloseDate = Date.today();
        insert oppo;

        OpportunityLineItem oli = new OpportunityLineItem(
            OpportunityId = oppo.Id,
            Quantity = 20,
            Product2Id  = prod.Id,
            PricebookEntryId = pbEntry.Id,
            UnitPrice = 10,
         Billing_Frequency__c ='Annually',
           iMCNRRProduct__c = FALSE, 
            iMCProduct__c = TRUE,
            Historic_Line_Item__c = TRUE,
            isReportable_Text__c = 'Invalid',
            Unit_Type__c='Ancillary',
            Contract_Term__c =0,
            New_Sales_Price__c = 12345,
            New_Quantity__c = 12
        );
        insert oli;
      OpportunityLineItem oliitems = new OpportunityLineItem(
        OpportunityId = oppo.Id,
            Quantity = 20,
            Product2Id  = prod.Id,
            PricebookEntryId = pbEntry.Id,
            UnitPrice = 10,
         Billing_Frequency__c ='One Time Event',
           iMCNRRProduct__c = TRUE, 
            iMCProduct__c = TRUE,
            Historic_Line_Item__c = TRUE,
          New_Sales_Price__c = 123,
            New_Quantity__c = 5,
          Unit_Type__c='Ancillary',
           Legacy_MRR__c = 123
                   );
        insert oliitems;
    }
    /**
    * @description : this method is to test the NRR and ACV Values for Product hich has product family= 'Collaboration'
    * @author Anup Kage (anup@cloudfastener.com) | 1/7/2020 
    * @return testMethod 
    * @Ticket : RT-397
    **/
    static testMethod void testCollaboration() {
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                Family = 'Collaboration'
            );
            insert prod;

            PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = prod.Id,
                UnitPrice = 100.00,
                IsActive = true
            );
            insert pbEntry;

            Pricebook2 customPB = new Pricebook2(
                Name='Custom Pricebook',
                isActive=true
            );
            insert customPB;

            Opportunity oppo = new Opportunity();
                oppo.StageName      = 'native activise';
                oppo.Name           = '3';
                oppo.highest_MRR_Product_Value__c = -1;
                oppo.Pricebook2Id = pricebookId;
                oppo.CloseDate = Date.today();
            insert oppo;

            OpportunityLineItem oli = new OpportunityLineItem(
                OpportunityId = oppo.Id,
                Quantity = 20,
                Product2Id  = prod.Id,
                PricebookEntryId = pbEntry.Id,
                UnitPrice = 10,
                Billing_Frequency__c ='Annually',
                iMCNRRProduct__c = FALSE, 
                iMCProduct__c = TRUE,
                Historic_Line_Item__c = TRUE,
                isReportable_Text__c = 'Invalid',
                Unit_Type__c='Ancillary',
                Contract_Term__c =0,
                New_Sales_Price__c = 12,
                New_Quantity__c = 12
            );
            insert oli;
            system.assertEquals(oppo.Product_NRR_Total_Collab__c, oli.NRR__c);
            system.assertEquals(oppo.Product_ACV_Total_Collab__c, oli.Annual_Value__c);
    }
    /**
    * @description : this method is to test the NRR and ACV Values for Product hich has product family= 'Webinar'
    * @author Anup Kage (anup@cloudfastener.com) | 1/7/2020 
    * @return testMethod 
    * @Ticket : RT-397
    **/
   
/*    static testMethod void testWebinar() {
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                Family = 'Webinar'
            );
            insert prod;

            PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = prod.Id,
                UnitPrice = 100.00,
                IsActive = true
            );
            insert pbEntry;

            Pricebook2 customPB = new Pricebook2(
                Name='Custom Pricebook',
                isActive=true
            );
            insert customPB;

            Opportunity oppo = new Opportunity();
                oppo.StageName      = 'native activise';
                oppo.Name           = '3';
                oppo.highest_MRR_Product_Value__c = -1;
                oppo.Pricebook2Id = pricebookId;
                oppo.CloseDate = Date.today();
            insert oppo;

            OpportunityLineItem oli = new OpportunityLineItem(
                OpportunityId = oppo.Id,
                Quantity = 20,
                Product2Id  = prod.Id,
                PricebookEntryId = pbEntry.Id,
                UnitPrice = 10,
                Billing_Frequency__c ='Annually',
                iMCNRRProduct__c = FALSE, 
                iMCProduct__c = TRUE,
                Historic_Line_Item__c = TRUE,
                isReportable_Text__c = 'Invalid',
                Unit_Type__c='Ancillary',
                Contract_Term__c =0,
                New_Sales_Price__c = 12,
                New_Quantity__c = 12
            );
            insert oli;
            system.assertEquals(oppo.Product_NRR_Total_Webinar__c, oli.NRR__c);
            system.assertEquals(oppo.Product_ACV_Total_Webinar__c, oli.Annual_Value__c);
             }    */ 
    /**
    * @description : this method is to test the NRR and ACV Values for Product hich has product family= 'Webicast'
    * @author Anup Kage (anup@cloudfastener.com) | 1/7/2020 
    * @return testMethod 
    * @Ticket : RT-397
    **/ 
    static testMethod void testWebcast() {
        Id pricebookId = Test.getStandardPricebookId();
        Product2 prod = new Product2(
                Name = 'Product X',
                ProductCode = 'Pro-X',
                Family = 'Webcast'
            );
            insert prod;

            PricebookEntry pbEntry = new PricebookEntry(
                Pricebook2Id = pricebookId,
                Product2Id = prod.Id,
                UnitPrice = 100.00,
                IsActive = true
            );
            insert pbEntry;

            Pricebook2 customPB = new Pricebook2(
                Name='Custom Pricebook',
                isActive=true
            );
            insert customPB;

            Opportunity oppo = new Opportunity();
                oppo.StageName      = 'native activise';
                oppo.Name           = '3';
                oppo.highest_MRR_Product_Value__c = -1;
                oppo.Pricebook2Id = pricebookId;
                oppo.CloseDate = Date.today();
            insert oppo;

            OpportunityLineItem oli = new OpportunityLineItem(
                OpportunityId = oppo.Id,
                Quantity = 20,
                Product2Id  = prod.Id,
                PricebookEntryId = pbEntry.Id,
                UnitPrice = 10,
                Billing_Frequency__c ='One Time Event',
                iMCNRRProduct__c = FALSE, 
                iMCProduct__c = TRUE,
                Historic_Line_Item__c = TRUE,
                isReportable_Text__c = 'Invalid',
                Unit_Type__c='Ancillary',
                Contract_Term__c =0,
                New_Sales_Price__c = 12,
                New_Quantity__c = 12
            );
            insert oli;
            // system.assertEquals(oppo.Product_ACV_Total_Webcast__c, oli.Annual_Value__c);
            // system.assertEquals(oppo.Product_NRR_Total_Webcast__c, oli.NRR__c); 
            
    }
    
}