force-app/main/default/objects/Contact/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Date/time the contact is marked as deleted (therefore, inactive in SF &amp; deleted with GX).</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/FoxDen_User__c.object-meta.xml
<CustomObject>
    <description>A similar object to access code, but for FoxDen.</description>
    <label>FoxDen User</label>
    <nameField>
        <label>FoxDen Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FoxDen Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FoxDen_User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FoxDen Users</relationshipLabel>
    <relationshipName>FoxDen_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>FoxDen Email address</description>
    <inlineHelpText>This is the email address the user will use as their login for FoxDen. This must be a unique email from any other FoxDen user.</inlineHelpText>
    <label>FoxDen Username (Email)</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FoxDen_User__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/testFoxDenUserController.cls
@isTest
private class testFoxDenUserController {
  
  private static SFPCTestHelper sfpcTestHelper;


  @TestSetup
  static void makeData(){
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
  }
  private static void init(){        

    sfpcTestHelper = new SFPCTestHelper();
    sfpcTestHelper.createForAccount(MockAccount.getNewAccount());
    ApexPages.currentPage().getParameters().put('retURL', sfpcTestHelper.foxDenUser.Contact__c);
  }

/*  static testMethod void testConstruct() {
    init();
    FoxDenUserController c = new FoxDenUserController();
    System.assert(c!=null);
  } */

  static testMethod void testStandardConstruct() {
    init();
    FoxDenUserController c = new FoxDenUserController(new ApexPages.StandardController(sfpcTestHelper.foxDenUser));
    System.assert(c!=null);
  }

  static testMethod void testSave() {
    init();
    FoxDenUserController c = new FoxDenUserController(new ApexPages.StandardController(sfpcTestHelper.foxDenUser));
    c.planStartDate = Date.today().format();
    c.planId = sfpcTestHelper.fdPlan.Id;
    c.isDelete=false;
    c.save();    
    System.assert(c!=null);
  }
    static testMethod void testSaveNull() {
    init();
       
    FoxDenUserController c = new FoxDenUserController(new ApexPages.StandardController(sfpcTestHelper.foxDenUser));
    c.planStartDate ='';
    c.planId = null;
    c.save();    
  //  System.assert(c.planId==null);
  }
    static testMethod void testConstruct() {
        init();
        Contact c = new Contact();
        c.LastName = 'test Contact';
        INSERT c;
        
        FoxDen_User__c FUser = new FoxDen_User__c();
        FUser.Contact__c = c.Id;
        FUser.Email__c = 'vijay@raagvitech.com';
        FUser.Name = 'test';
        FUser.Status__c = 'Pending';
        INSERT FUser;
        FoxDenUser FUserController = new FoxDenUser();
        FUserController.findById(FUser.Id);
        FoxDenUser.builderValidator ObjFuser = new FoxDenUser.builderValidator();
        ObjFuser.validate(FUser);
        
       FoxDen_User__c objUser = [SELECT Id,Name FROM FoxDen_User__c WHERE Id=: FUser.Id];
        System.assertEquals(objUser.Name, 'test');
       
    } 
 /*  static testmethod void getAccountLevelPlansTest(){
         sfpcTestHelper sf = new SFPCTestHelper();
       sf.createForAccount(MockAccount.getNewAccount());
    } */  
    static testmethod void testCustomDelete(){
        init();
         Contact c = new Contact();
        c.LastName = 'test Contact';
        INSERT c;
        
        FoxDen_User__c FUser = new FoxDen_User__c();
        FUser.Contact__c = c.Id;
        FUser.Email__c = 'vijay@raagvitech.com';
        FUser.Name = 'test';
        FUser.Status__c = 'Pending';
        FUser.Inactive__c = true;
        FUser.Date_Deleted__c= null;
        INSERT FUser;
        FoxDenUserController.customDelete(FUser.Id);
      //   Test.startTest();
     //   FoxDenUser foxDenUserRepository = new FoxDenUser(); 
    //    FoxDen_User__c user = foxDenUserRepository.findById(FUser.id);
         
        
      //  FUser.stopTest();
        system.assertEquals('Pending',FUser.Status__c );
    }
    
    static testMethod void testgetUser(){
        init();
    FoxDenUserController c = new FoxDenUserController(new ApexPages.StandardController(sfpcTestHelper.foxDenUser));
        c.getUser();
        c.getUserId();
        c.getIsDelete();
        c.getContactId();
       System.assert(c!=null);
    } 
     static testmethod void testgetAccountLevelPlans(){
         FoxDenUserController f = new FoxDenUserController();
         f.getAccountLevelPlans();
     }
}