force-app/main/default/objects/Contact/fields/Date_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Date_Deleted__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
Date/time the contact is marked as deleted (therefore, inactive in SF &amp; deleted with GX).</description>
    <label>Date Deleted</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS
GX Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Provisioned</fullName>
                <default>true</default>
                <label>Not Provisioned</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Provisioned</fullName>
            </value>
            <value>
                <fullName>UpdateError</fullName>
            </value>
            <value>
                <fullName>DeleteError</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>AddError</fullName>
            </value>
            <value>
                <fullName>SyncError</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>BillingError</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
            <value>
                <fullName>Restoring</fullName>
            </value>
            <value>
                <fullName>RestoreError</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/S3User__c/S3User__c.object-meta.xml
<CustomObject>
    <label>Replay User</label>
    <nameField>
        <label>Replay User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Replay Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/S3User__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Replay Users</relationshipLabel>
    <relationshipName>Replay_Users</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Replay Username (Email)</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/S3User__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Deleting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testS3UserController.cls
@isTest
private class testS3UserController {
  
  @TestSetup
  static void makeData(){
    Test.startTest();
    PGITestUtilities.disableSalesWings();
    Test.stopTest();
  }
  private static SFPCTestHelper sfpcTestHelper;

  private static void init() {        
    sfpcTestHelper = new SFPCTestHelper();
    sfpcTestHelper.createForAccount(MockAccount.getNewAccount());
    ApexPages.currentPage().getParameters().put('retURL', sfpcTestHelper.s3User.Contact__c);
  }

  static testMethod void testConstruct() {
    init();
    S3UserController c = new S3UserController();
    System.assert(c!=null);
  }

  static testMethod void testStandardConstruct() {
    init();
    S3UserController c = new S3UserController(new ApexPages.StandardController(sfpcTestHelper.s3User));
    System.assert(c!=null);
  }

  static testMethod void testSave() {
    init();
    S3UserController c = new S3UserController(new ApexPages.StandardController(sfpcTestHelper.s3User));
    c.planStartDate = Date.today().format();
    c.planId = sfpcTestHelper.s3Plan.Id;
    c.save();    
    System.assert(c!=null);
  }
    static testMethod void testcustomDelete(){
         init();
         Contact c = new Contact();
        c.LastName = 'test Contact';
        INSERT c;
        
        S3User__c s3User = new S3User__c();
        s3User.Contact__c = c.Id;
        s3User.Email__c = 'test01@gmail.com';
        s3User.Name = 'test';
        s3User.Status__c = 'Pending';
        s3User.Inactive__c = true;
        s3User.Date_Deleted__c= null;
        INSERT s3User;
        S3UserController.customDelete(s3User.Id);
        system.assertEquals('Pending',s3User.Status__c );
    }
    
    static testMethod void testgetUser(){
        init();
    S3UserController c = new S3UserController(new ApexPages.StandardController(sfpcTestHelper.s3User));
        c.getUser();
        c.getUserId();
        c.getIsDelete();
        c.getContactId();
       System.assert(c!=null);
    } 
     static testmethod void testgetAccountLevelPlans(){
         S3UserController f = new S3UserController();
         f.getAccountLevelPlans();
     } 
 }