force-app/main/default/objects/Contact/fields/Form_Submissions__c.field-meta.xml
<CustomField>
    <fullName>Form_Submissions__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Form Submissions</label>
    <referenceTo>Form_Submissions__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Global_Contact_MQL__c.field-meta.xml
<CustomField>
    <fullName>Global_Contact_MQL__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Global Contact MQL</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Global_Contact_MQL_Assignment_date__c.field-meta.xml
<CustomField>
    <fullName>Global_Contact_MQL_Assignment_date__c</fullName>
    <label>Global Contact MQL Assignment date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Form_Submissions__c/Form_Submissions__c.object-meta.xml
<CustomObject>
    <description>This is a new table that will serve as a log for all form completions. Fields will be populated through API connection.</description>
    <label>Form Submissions</label>
    <nameField>
        <displayFormat>FS-{000000}</displayFormat>
        <label>Form Submissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Form Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Form_Submissions__c/fields/Contact_Id__c.field-meta.xml
<CustomField>
    <fullName>Contact_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Id</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Form Submissions</relationshipLabel>
    <relationshipName>Form_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FormSubmissionTriggerHandler.cls
public class FormSubmissionTriggerHandler extends TriggerHandler {
    public FormSubmissionTriggerHandler() {
        super('FormSubmissionTriggerHandler');
    }
        protected override void afterInsert(){
            setGlobalContactMql();
        }

        private void setGlobalContactMql(){

            List<Contact> contactList = new List<Contact>();
            Set<Id> contactId = new Set<Id>();

            for(Form_Submissions__c formSubObj : (List<Form_Submissions__c>) Trigger.new){
                if(formSubObj.Contact_Id__c != null){
                    System.debug('Test');
                    contactId.add(formSubObj.Contact_Id__c);
                }
            }

            for(Contact conObj : [SELECT Id, Global_Contact_MQL__c, Global_Contact_MQL_Assignment_date__c, 
                                    (SELECT Id FROM Form_Submissions__r) 
                                    FROM Contact
                                    WHERE Id =: contactId]){

                if(conObj.Form_Submissions__r != null 
                    && conObj.Form_Submissions__r.size() == 1 
                    && conObj.Global_Contact_MQL__c !=true 
                    )
                    {
                       conObj.Global_Contact_MQL__c =true;
                       conObj.Global_Contact_MQL_Assignment_date__c = System.now();
                       contactList.add(conObj);
                   } 
            }

            if(!contactList.isEmpty()){
                UPDATE contactList;
            }
        }
    }