force-app/main/default/objects/Contact/fields/Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Status__c</fullName>
    <label>Prospect Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing Qualified Lead (MQL)</fullName>
            </value>
            <value>
                <fullName>Passive MQL</fullName>
            </value>
            <value>
                <fullName>Sales Sourced</fullName>
            </value>
            <value>
                <fullName>Event Sourced</fullName>
            </value>
            <value>
                <fullName>AM Sourced</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>ToFu</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
            </value>
            <value>
                <fullName>Marketing Qualified</fullName>
            </value>
            <value>
                <fullName>Sales Accepted</fullName>
            </value>
            <value>
                <fullName>Sales Qualified</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Recycle</fullName>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Status__c</fullName>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Prospect Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AM Sourced</fullName>
            </value>
            <value>
                <fullName>Bad Data</fullName>
                <color>#0B24BE</color>
                <label>Bad Data</label>
            </value>
            <value>
                <fullName>Competitor</fullName>
                <color>#419249</color>
                <label>Competitor</label>
            </value>
            <value>
                <fullName>Customer</fullName>
                <color>#A53711</color>
                <label>Customer</label>
            </value>
            <value>
                <fullName>Customer Cancelled</fullName>
            </value>
            <value>
                <fullName>Engaged</fullName>
                <color>#78C953</color>
                <label>Engaged</label>
            </value>
            <value>
                <fullName>Event Sourced</fullName>
            </value>
            <value>
                <fullName>Marketing Qualified</fullName>
                <color>#E27001</color>
                <label>Marketing Qualified</label>
            </value>
            <value>
                <fullName>Marketing Qualified Lead (MQL)</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Passive MQL</fullName>
            </value>
            <value>
                <fullName>PGi</fullName>
            </value>
            <value>
                <fullName>Recycle</fullName>
                <color>#66E9BD</color>
                <label>Recycle</label>
            </value>
            <value>
                <fullName>Sales Accepted</fullName>
                <color>#A845DC</color>
                <label>Sales Accepted</label>
            </value>
            <value>
                <fullName>Sales Qualified</fullName>
                <color>#F3D904</color>
                <label>Sales Qualified</label>
            </value>
            <value>
                <fullName>Sales Sourced</fullName>
            </value>
            <value>
                <fullName>ToFu</fullName>
                <color>#0B6FCE</color>
                <label>ToFu</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prospect_Status__c.field-meta.xml
<CustomField>
    <fullName>Prospect_Status__c</fullName>
    <label>Prospect Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing Qualified Lead (MQL)</fullName>
                <default>true</default>
                <label>Marketing Qualified Lead (MQL)</label>
            </value>
            <value>
                <fullName>Passive MQL</fullName>
            </value>
            <value>
                <fullName>Sales Sourced</fullName>
            </value>
            <value>
                <fullName>Event Sourced</fullName>
            </value>
            <value>
                <fullName>AM Sourced</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Customer Care Sourced</fullName>
            </value>
            <value>
                <fullName>Buy Now</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SAL_Date__c.field-meta.xml
<CustomField>
    <fullName>SAL_Date__c</fullName>
    <inlineHelpText>Date that this opportunity was designated as a &quot;Sales Accepted Lead.&quot;</inlineHelpText>
    <label>SAL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/OpportunityActions.cls
public class OpportunityActions {

  ////SFB-12
  //public static void afterSaveUpdateProspectStatus(List<Opportunity> newOpps, List<Opportunity> oldOpps) {
  //  for(Opportunity opp : newOpps) {
  //    if(!ReadyTalkRecordTypeHelper.readyTalkOpportunityRecordTypeIds.contains(opp.RecordTypeId)) {
  //        continue;
  //    }
  //    if(opp.SAL_Date__c != null) {
  //      List<Contact> contacts = [select id,Prospect_Status__c from Contact where id in (select contactid from OpportunityContactRole where OpportunityId=:opp.Id)];

  //      //Should only be 1 contact
  //      for (Contact c : contacts) {
  //        //Update the Prospect_Status__c to Marketing Qualified Lead (MQL) if it isn't already...if it is, then don't touch it
  //        if(c.Prospect_Status__c != 'Marketing Qualified Lead (MQL)' && 
  //            c.Prospect_Status__c != 'Sales Sourced' && 
  //            c.Prospect_Status__c != 'Event Sourced' &&
  //            c.Prospect_Status__c != 'AM Sourced') {
            
  //          c.Prospect_Status__c = 'Marketing Qualified Lead (MQL)';
  //          update(c);
  //        }
  //      }
  //    }        
  //  }
  //}
}