force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanQuantityHistory__c/PlanQuantityHistory__c.object-meta.xml
<CustomObject>
    <label>PlanQuantityHistory</label>
    <nameField>
        <label>PlanQuantityHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PlanQuantityHistorys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanQuantityHistory__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>PlanQuantityHistorys</relationshipLabel>
    <relationshipName>PlanQuantityHistorys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PlanQuantityHistory__c/fields/quantity__c.field-meta.xml
<CustomField>
    <fullName>quantity__c</fullName>
    <label>quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PlanQuantityHistory__c/fields/startDate__c.field-meta.xml
<CustomField>
    <fullName>startDate__c</fullName>
    <label>startDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PlanQuantityHistory.cls
/**
 * Created by gregory.jensen on 10/3/17.
 */

public with sharing class PlanQuantityHistory extends AbstractRepository {
    public final static String table = 'PlanQuantityHistory__c';
    public final static String columns = 'id,name,plan__c,quantity__c,startDate__c,endDate__c,LastModifiedDate,LastModifiedBy.Name';

    public List<PlanQuantityHistory__c> getPlanQuantityHistorysByPlanId(Id planId){
        List<PlanquantityHistory__c> planQuantityHistorys = (List<PlanQuantityHistory__c>) Database.query(selectBuilder(table,columns,'where plan__c =: planId'));
        return planQuantityHistorys;
    }

}