force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <description>Products related to Accounts.</description>
    <label>Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/PlanAssignment__c.object-meta.xml
<CustomObject>
    <description>Assigned Products related to Access Codes.</description>
    <label>Plan Assignment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PlanAssignment__c/fields/contact__c.field-meta.xml
<CustomField>
    <fullName>contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>Plan_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PlanAssignment__c/fields/plan__c.field-meta.xml
<CustomField>
    <fullName>plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Plan Assignments</relationshipLabel>
    <relationshipName>PlanAssignments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>Object for individual access codes and passcodes for ReadyTalk customers.</description>
    <label>Access Code</label>
    <nameField>
        <label>Access Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Access Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CAUTION - USED IN INTEGRATIONS
Lookup relationship, connects contact with subscription</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Access Codes</relationshipLabel>
    <relationshipName>Subscription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testAssignPlanController.cls
@isTest
private class testAssignPlanController {
  
  private static ApexPages.StandardController controller;
  private static SFPCTestHelper sfpcTestHelper;
  static{
    PGITestUtilities.disableSalesWings();
    
    controller = new ApexPages.StandardController(RTDatabaseUtils.getEntireSObject(new Subscription__c(), MockSubscription.getNewSubscription().Id, ',Contact__r.Account.Id'));
    sfpcTestHelper = new SFPCTestHelper();
    sfpcTestHelper.createForAccount((Account) RTDatabaseUtils.getEntireSObject(new Account(), ((Subscription__c)controller.getRecord()).Contact__r.Account.Id));
  }

  //AssignPlanController.AssignPlanController
  static testMethod void testConstruct() {
    PGITestUtilities.disableSalesWings();
    AssignPlanController c = new AssignPlanController(controller);
    c.getObjectId();
    System.assert(c != null);
  }

  //AssignPlanController.getPlanAssignments
  static testMethod void testGetPlanAssignments() {
    PGITestUtilities.disableSalesWings();
    List<PlanAssignment__c> planAssignments = AssignPlanController.getPlanAssignments(((Subscription__c)controller.getRecord()).Id);
    System.assert(planAssignments != null);
  }

  //AssignPlanController.getPlans
  static testMethod void testGetPlans() {
    PGITestUtilities.disableSalesWings();
    List<Plan__c> plans = AssignPlanController.getPlans(((Subscription__c)controller.getRecord()).Id);
    System.assert(plans != null);
  }

  //AssignPlanController.assignPlan
  static testMethod void testAssignPlan() {
    PGITestUtilities.disableSalesWings();
    //Assert that assign plan doesn't throw an exception
    AssignPlanController.assignPlan(((Subscription__c)controller.getRecord()).Id, '2/1/2013', sfpcTestHelper.plan.Id);

    //Assert that once a plan is assigned, that it cannot be re-assigned for the same date range
  //  AssignPlanController.assignPlan(((Subscription__c)controller.getRecord()).Id, '2/1/2013', sfpcTestHelper.plan.Id);

    //Assert that assign plan with a bad date throws an exception
    try{
      AssignPlanController.assignPlan(((Subscription__c)controller.getRecord()).Id, '2/1/BadDate', sfpcTestHelper.plan.Id);
    }
    catch(ValidationException ve){
      System.assert(ve.getMessage().contains('Invalid start date'));
    }
  }

  //AssignPlanController.hasNoFuturePlanAssignment
  static testMethod void hasNoFuturePlanAssignment() {
    PGITestUtilities.disableSalesWings();
    Boolean tf = AssignPlanController.hasNoFuturePlanAssignment(((Subscription__c)controller.getRecord()).Id);
    System.assert(tf != null);
  }
}