force-app/main/default/objects/Conference__c/Conference__c.object-meta.xml
<CustomObject>
    <description>FSL Conferences</description>
    <label>FSL Conference</label>
    <nameField>
        <displayFormat>CON-{0000}</displayFormat>
        <label>Conference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FSL Conferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Conference__c/fields/Call_End__c.field-meta.xml
<CustomField>
    <fullName>Call_End__c</fullName>
    <label>Call End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Call_Start__c.field-meta.xml
<CustomField>
    <fullName>Call_Start__c</fullName>
    <label>Call Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Call_Type__c.field-meta.xml
<CustomField>
    <fullName>Call_Type__c</fullName>
    <label>Call Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>FSL_Company__c</referenceTo>
    <relationshipName>Conferences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Conference_ID__c.field-meta.xml
<CustomField>
    <fullName>Conference_ID__c</fullName>
    <externalId>true</externalId>
    <label>Conference ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Exclude_From_Reports__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Reports__c</fullName>
    <formula>Company__r.Exclude_From_Reports__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exclude From Reports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Lead_Bridge__c.field-meta.xml
<CustomField>
    <fullName>Lead_Bridge__c</fullName>
    <label>Lead Bridge</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Linked_Bridges__c.field-meta.xml
<CustomField>
    <fullName>Linked_Bridges__c</fullName>
    <label>Linked Bridges</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Conference__c/fields/Pre_Conference__c.field-meta.xml
<CustomField>
    <fullName>Pre_Conference__c</fullName>
    <label>Pre-Conference</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FSL_Company__c/FSL_Company__c.object-meta.xml
<CustomObject>
    <description>FSL_Companies</description>
    <label>FSL Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FSL Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FSL_Company__c/fields/Exclude_From_Reports__c.field-meta.xml
<CustomField>
    <fullName>Exclude_From_Reports__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude From Reports</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Work_Order__r.Company__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Conference__c.field-meta.xml
<CustomField>
    <fullName>Conference__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conference</label>
    <referenceTo>Conference__c</referenceTo>
    <relationshipLabel>FSL Roles</relationshipLabel>
    <relationshipName>FSL_Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Conference_ID__c.field-meta.xml
<CustomField>
    <fullName>Conference_ID__c</fullName>
    <formula>Work_Order__r.Conference__r.Conference_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Conference ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Linked_Bridges__c.field-meta.xml
<CustomField>
    <fullName>Linked_Bridges__c</fullName>
    <formula>Work_Order__r.Conference__r.Linked_Bridges__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linked Bridges</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Role_ID__c.field-meta.xml
<CustomField>
    <fullName>Role_ID__c</fullName>
    <externalId>true</externalId>
    <label>Role ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Role_Not_Needed__c.field-meta.xml
<CustomField>
    <fullName>Role_Not_Needed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Role Not Needed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ServiceAppointment/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Service Appointments</relationshipLabel>
    <relationshipName>Roles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Call_End__c.field-meta.xml
<CustomField>
    <fullName>Call_End__c</fullName>
    <formula>Conference__r.Call_End__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Call End</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Call_Start__c.field-meta.xml
<CustomField>
    <fullName>Call_Start__c</fullName>
    <formula>Conference__r.Call_Start__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Call Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <formula>Conference__r.Company__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Conference__c.field-meta.xml
<CustomField>
    <fullName>Conference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conference</label>
    <referenceTo>Conference__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Role_ID__c.field-meta.xml
<CustomField>
    <fullName>Role_ID__c</fullName>
    <externalId>true</externalId>
    <label>Role ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WorkType/fields/Call_Role__c.field-meta.xml
<CustomField>
    <fullName>Call_Role__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Call Role</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkType/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <precision>7</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Legacy_Reports_Control_Test.cls
@isTest 


public class Legacy_Reports_Control_Test {


   @isTest static void Legacy_Reports_Control_Test_Run() {
   
   

   
   
FSL_Company__c    testCompany = new FSL_Company__c();

testCompany.Exclude_From_Reports__c = false;
testCompany.Name = 'Goldman';
insert testCompany;

   
Conference__c testConference = new Conference__c();
testConference.Lead_Bridge__c = 'GE01';
testConference.Conference_ID__c = '24234234234_234';
testConference.Call_Start__c = DateTime.Now();
testConference.Call_End__c= DateTime.Now().AddHours(1);
testConference.Pre_Conference__c= DateTime.Now();
testConference.Company__c = testCompany.id;
testConference.Call_Type__c= 'PCE';
insert testConference;

Conference__c testConferenceTwo = new Conference__c();
testConferenceTwo.Lead_Bridge__c = 'GE01';
testConferenceTwo.Linked_Bridges__c= 'GE02';
testConferenceTwo.Conference_ID__c = '24234234234_235';
testConferenceTwo.Call_Start__c = DateTime.Now();
testConferenceTwo.Call_End__c= DateTime.Now().AddHours(1);
testConferenceTwo.Company__c = testCompany.id;
testConferenceTwo.Pre_Conference__c= DateTime.Now();
testConferenceTwo.Call_Type__c= 'Event';
insert testConferenceTwo;



WorkType testWorkType = new WorkType();
testWorkType.Name = 'Lead';
testWorkType.EstimatedDuration = 60;
testWorkType.Duration__c = 60;
testWorkType.Call_Role__c = true;
insert testWorkType;


WorkType testWorkTypeTwo = new WorkType();
testWorkTypeTwo.Name = 'AL';
testWorkTypeTwo.EstimatedDuration = 60;
testWorkTypeTwo.Duration__c = 60;
testWorkTypeTwo.Call_Role__c = true;
insert testWorkTypeTwo;


WorkOrder testWorkOrderTwo = new WorkOrder();
testWorkOrderTwo.Status = 'New';
testWorkOrderTwo.WorkType = testWorkType;
testWorkOrderTwo.Conference__c = testConferenceTwo.id;
insert testWorkOrderTwo;


WorkOrder testWorkOrder = new WorkOrder();
testWorkOrder.Status = 'New';
testWorkOrder.WorkType = testWorkType;
testWorkOrder.Conference__c = testConference.id;
insert testWorkOrder;


ServiceAppointment testRole = new ServiceAppointment();
testRole.Role_ID__c ='Test Role';
testRole.Status ='Active';
testRole.Work_Order__r = testWorkOrder;

testRole.ParentRecordid = testWorkOrder.id;
testRole.EarliestStartTime = DateTime.Now();
testRole.DueDate = DateTime.Now().AddHours(1); 
insert testRole;


ServiceAppointment testRoleTwo = new ServiceAppointment();
testRoleTwo.Role_ID__c ='Test Role2';
testRoleTwo.Work_Order__r = testWorkOrderTwo;
testRoleTwo.ParentRecordid = testWorkOrderTwo.id;
testRoleTwo.EarliestStartTime = DateTime.Now();
testRoleTwo.DueDate = DateTime.Now().AddHours(1); 
testRole.Role_Not_Needed__c = true;
insert testRoleTwo;



Legacy_Reports_Control lr = new Legacy_Reports_Control ();
lr.Exclude = false;
lr.Page_Load();
lr.ReportDate = date.today();
lr.Run_Report();
lr.Run_Staffing_Review();




delete testRole;
delete testRoleTwo;

delete testWorkOrder;
delete testWorkType;
delete testConference;
delete testCompany;



}
   
   
}