force-app/main/default/objects/Aggregate_Calculation_Event__e/Aggregate_Calculation_Event__e.object-meta.xml
<CustomObject>
    <label>Aggregate Calculation Event</label>
    <pluralLabel>Aggregate Calculation Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Aggregate_Calculation_Event__e/fields/PGI_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>PGI_Company_Id__c</fullName>
    <label>PGI Company Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/PGi_Company__c.field-meta.xml
<CustomField>
    <fullName>PGi_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Enter the Company ID.</inlineHelpText>
    <label>PGi Company</label>
    <referenceTo>PGi_Company__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PGi_Company__c/PGi_Company__c.object-meta.xml
<CustomObject>
    <label>PGi Company</label>
    <nameField>
        <label>PGi Company ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Companies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/Trigger_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is used to enable/disable all apex triggers</description>
    <label>Trigger Settings</label>
</CustomObject>

force-app/main/default/objects/Trigger_Settings__c/fields/Bypass_Totango__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Totango__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bypass Totango</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CaseCalculationTriggerHandler.cls
public without sharing class CaseCalculationTriggerHandler extends TriggerHandler{
    public CaseCalculationTriggerHandler() {
        super('CaseCalculationTriggerHandler');
    }
    protected override void afterUpdate() {
        fireEventHandler();
    }
    protected override void afterInsert() {
        fireEventHandler();
    }
    /*
    * Method to insert records to fiere Platform Event
    */
    private void fireEventHandler(){
        if(Trigger_Settings__c.getInstance().Bypass_Totango__c) { return; }
        List<Aggregate_Calculation_Event__e> listOfagregateEvents = new List<Aggregate_Calculation_Event__e>();
    
        for(Case caseObj :(List<Case>)Trigger.new){
            if(caseObj.PGI_Company__c != null){
                Aggregate_Calculation_Event__e obj = new Aggregate_Calculation_Event__e() ;   
                obj.PGI_Company_Id__c = caseObj.PGI_Company__c;
                listOfagregateEvents.add(obj);
            }
        }
        if(!listOfagregateEvents.isEmpty()){
            List<Database.SaveResult> results = EventBus.publish(listOfagregateEvents);
            for (Database.SaveResult sr : results) {
                if (sr.isSuccess()) {
                    System.debug('Successfully published event.');
                } else {
                    for(Database.Error err : sr.getErrors()) {
                        System.debug('Error returned: ' +
                                     err.getStatusCode() +
                                     ' - ' +
                                     err.getMessage());
                    }
                }
                
            }
        }
        
    }
}