force-app/main/default/objects/Aggregate_Calculation_Event__e/Aggregate_Calculation_Event__e.object-meta.xml
<CustomObject>
    <label>Aggregate Calculation Event</label>
    <pluralLabel>Aggregate Calculation Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Aggregate_Calculation_Event__e/fields/PGI_Company_Id__c.field-meta.xml
<CustomField>
    <fullName>PGI_Company_Id__c</fullName>
    <label>PGI Company Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aggregate_Calculation_Event__e/fields/PGI_Entity__c.field-meta.xml
<CustomField>
    <fullName>PGI_Entity__c</fullName>
    <label>PGI Entity</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PGi_Entity__c/PGi_Entity__c.object-meta.xml
<CustomObject>
    <label>PGi Entity</label>
    <nameField>
        <label>PGi Entity ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AggregateCalculationTriggerHandler.cls
public without sharing class AggregateCalculationTriggerHandler extends TriggerHandler {
    public AggregateCalculationTriggerHandler() {
        super('AggregateCalculationTriggerHandler');
    }
    protected override void afterInsert() {
        fireQueuableClass();
    }

    private void fireQueuableClass(){
        Set<String> pgiCompanyIdSet = new Set<String>();
        Set<String> pgiEntityIdSet = new Set<String>();
        for (Aggregate_Calculation_Event__e event : (List<Aggregate_Calculation_Event__e>)Trigger.New) {
            if (event.PGI_Company_Id__c != null) {
                pgiCompanyIdSet.add(event.PGI_Company_Id__c);
            }
            if (event.PGI_Entity__c != null) {
                pgiEntityIdSet.add(event.PGI_Entity__c);
            }
        }
        TotangoQueueableRecords objChildQueue = new TotangoQueueableRecords(pgiCompanyIdSet, pgiEntityIdSet);
        system.enqueueJob(objChildQueue); 
    }
}