force-app/main/default/objects/LiveChatTranscript/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>To be used to populate Company field on a Lead</description>
    <inlineHelpText>Company name entered by the chat visitor</inlineHelpText>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Escalated_Lead__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Escalated to Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Country_Code__c</fullName>
    <label>Location_Country_Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Location_Region__c</fullName>
    <description>To be populated based on Country in geolocation Location field</description>
    <label>Location_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmitLeadControllerTest.cls
@IsTest

public class SubmitLeadControllerTest {
   
    static  testMethod void sales_agent_test(){
        Test.startTest(); 
    
        LiveChatVisitor lcv = new LiveChatVisitor();
        INSERT lcv;
        
        LiveChatTranscript ctRecord = new LiveChatTranscript(LiveChatVisitorId = lcv.Id,
                                                             Email_Address__c='test@pgi.com',
                                                             Subject__c='Test',
                                                             First_Name__c='Test',
                                                             Last_Name__c='Test',
                                                             Escalated_Lead__c = false,
                                                             Location_Country_Code__c = 'IE',
                                                             Location_Region__c = 'EMEA',
                                                             Company_Name__c = 'Test'
                                     );
        INSERT ctRecord;
    
       // String FirstName;
       // String LastName;
       // String Company;
       // String Email;
      //  String Phone;
        
        PageReference ref = new PageReference('/apex/Chat_SubmitLead'); 
        ref.getParameters().put('id', String.valueOf(ctRecord.Id));
        Test.setCurrentPage(ref);    
            
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PGi Leads').getRecordTypeId();
         
             Lead l = new Lead();
                
                SubmitLeadController con = new SubmitLeadController();               
                con.init();
                con.submitLead();
                Test.StopTest();
    }
    
   static  testMethod void care_agent_test(){
               Test.startTest(); 
    
        LiveChatVisitor lcv = new LiveChatVisitor();
        INSERT lcv;
        
        LiveChatTranscript ctRecord = new LiveChatTranscript(LiveChatVisitorId = lcv.Id,
                                                             Email_Address__c='test@pgi.com',
                                                             Subject__c='Test',
                                                             First_Name__c='Test',
                                                             Last_Name__c='Test',
                                                             Escalated_Lead__c = false,
                                                             Location_Country_Code__c = 'US',
                                                             Location_Region__c = 'NA',
                                                             Company_Name__c = 'Test'
                                     );
        INSERT ctRecord;
    
       // String FirstName;
       // String LastName;
       // String Company;
       // String Email;
      //  String Phone;
        
        PageReference ref = new PageReference('dev-pgi.cs26.force.com/chatcustompage/Chat_SubmitLead'); 
        ref.getParameters().put('id', String.valueOf(ctRecord.Id));
        Test.setCurrentPage(ref);    
            
        Id recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PGi Leads').getRecordTypeId();
         
             Lead l = new Lead();
                
                SubmitLeadController con = new SubmitLeadController();               
                con.init();
                con.submitLead();
                Test.StopTest();
   
   }
}