force-app/main/default/objects/LiveChatTranscript/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>To be used to populate Company field on a Lead</description>
    <inlineHelpText>Company name entered by the chat visitor</inlineHelpText>
    <label>Company Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Escalated_Lead__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Escalated to Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Country_Code__c</fullName>
    <label>Location_Country_Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Location_Region__c</fullName>
    <description>To be populated based on Country in geolocation Location field</description>
    <label>Location_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmitLeadController.cls
public class SubmitLeadController {
    
    public  Lead l { get; set; }
    public  LiveChatTranscript currentChatTranscript { get; set; }
    public  Id currentRecordId {get; set;}
    public  Id recordTypeId {get; set;}
    
    public String FirstName { get; set; }
    public String LastName { get; set; }
    public String Company { get; set; }
    public String Email { get; set; }
    public String Phone { get; set; }

    
    public SubmitLeadController() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');    
        l = new Lead();    
    }
    
    public  void init(){
        recordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('PGi Leads').getRecordTypeId();
        
        currentChatTranscript = [SELECT ID, Email_Address__c, Subject__c, First_Name__c, Last_Name__c, Escalated_Lead__c, Location_Country_Code__c, Location_Region__c, Company_Name__c
             FROM LiveChatTranscript 
             WHERE Id =: currentRecordId limit 1];
             
             l.Company = currentChatTranscript.Company_Name__c;
             l.Email = currentChatTranscript.Email_Address__c;
             FirstName = currentChatTranscript.First_Name__c;
             LastName = currentChatTranscript.Last_Name__c;
             Company = currentChatTranscript.Company_Name__c;
             Email = currentChatTranscript.Email_Address__c;
    }
    
    public PageReference submitLead() {
            try {
                l.recordTypeId = recordTypeId;
                l.Status = 'Assigned';
                l.CurrencyISOCode = 'USD';
                l.CountryCode = currentChatTranscript.Location_Country_Code__c;
                l.LeadSource = 'Web Chat';
                
                l.FirstName = FirstName;
                l.LastName = LastName;
                l.Email = Email;
                l.Company = Company;
                
                INSERT l;
                currentChatTranscript.LeadId = l.Id;
                currentChatTranscript.Escalated_Lead__c = true;
                UPDATE currentChatTranscript;
                PageReference retURL = new PageReference('/ChatEscalateLandingPage');
                retURL.setRedirect(true);
                return retURL;
            } catch (Exception e) {
                ApexPages.addMessages(e);
                return null;
            }
    }
}