force-app/main/default/objects/Matching_Rule__c/Matching_Rule__c.object-meta.xml
<CustomObject>
    <label>Matching Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matching Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Matching_Rule__c/fields/Evaluation_Order__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Order__c</fullName>
    <label>Evaluation Order</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Matching_Rule__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Matching_Rule__c/fields/Parent_Matching_Rule__c.field-meta.xml
<CustomField>
    <fullName>Parent_Matching_Rule__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Matching Rule</label>
    <referenceTo>Matching_Rule__c</referenceTo>
    <relationshipLabel>Matching Rules</relationshipLabel>
    <relationshipName>Matching_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Matching_Rule__c/fields/Support_Text__c.field-meta.xml
<CustomField>
    <fullName>Support_Text__c</fullName>
    <label>Support Text</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Matching_Rule_Criteria__c/Matching_Rule_Criteria__c.object-meta.xml
<CustomObject>
    <label>Matching Rule Criteria</label>
    <nameField>
        <label>Matching Rule Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Matching Rule Criterias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Matching_Rule_Criteria__c/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Matching_Rule_Criteria__c/fields/Field_Operator__c.field-meta.xml
<CustomField>
    <fullName>Field_Operator__c</fullName>
    <label>Field Operator</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>notEqual</fullName>
            </value>
            <value>
                <fullName>lessThan</fullName>
            </value>
            <value>
                <fullName>greaterThan</fullName>
            </value>
            <value>
                <fullName>lessOrEqual</fullName>
            </value>
            <value>
                <fullName>greaterOrEqual</fullName>
            </value>
            <value>
                <fullName>contains</fullName>
            </value>
            <value>
                <fullName>notContain</fullName>
            </value>
            <value>
                <fullName>startsWith</fullName>
            </value>
            <value>
                <fullName>includes</fullName>
            </value>
            <value>
                <fullName>excludes</fullName>
            </value>
            <value>
                <fullName>within</fullName>
            </value>
            <value>
                <fullName>doesnotcontains</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Matching_Rule_Criteria__c/fields/Matching_Rule__c.field-meta.xml
<CustomField>
    <fullName>Matching_Rule__c</fullName>
    <label>Matching Rule</label>
    <referenceTo>Matching_Rule__c</referenceTo>
    <relationshipLabel>Matching Rule Criterias</relationshipLabel>
    <relationshipName>Matching_Rule_Criterias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MachingRuleCreation_Test.cls
/**  
* \arg ClassName        : MachingRuleCreation_Test
* \arg JIRATicket       : 
* \arg CreatedOn        : 23/April/2019
* \arg LastModifiedOn   : 
* \arg CreatededBy      : Vijay
* \arg ModifiedBy       : 
* \arg Description      : Test class for MachingRuleCreation class
*/
@isTest
private class MachingRuleCreation_Test {
    
    static List<Matching_Rule__c> lstmatchingrule;
    static List<Matching_Rule_Criteria__c> lstmatchingrulecreteria; 
    static List<Matching_Rule_Criteria__c> lstRemoveRowmatchingrulecreteria;
    static Matching_Rule__c objMR;
    static Matching_Rule_Criteria__c objMRcreteria;
    
    static void createData(){
        
        Matching_Rule__c objMR1 = new Matching_Rule__c(Name = 'TestMR3', Object_Name__c = 'Account', Support_Text__c = 'Test_Support2', Evaluation_Order__c = '1 AND 2');
        INSERT objMR1;
        Matching_Rule_Criteria__c objMRcreteria1 = new Matching_Rule_Criteria__c(Matching_Rule__c = objMR1.Id, Field_API_Name__c = 'Name', Field_Operator__c = 'equals', Field_Type__c = 'STRING', Field_Value__c = 'vijay');
        INSERT objMRcreteria1;
        
        lstmatchingrule = new List<Matching_Rule__c>{new Matching_Rule__c(Name = 'TestMR001', Parent_Matching_Rule__c = objMR1.Id,Object_Name__c = 'Account', Support_Text__c = 'Test_Support001', Evaluation_Order__c = '1'),
            new Matching_Rule__c(Name = 'TestMR002', Object_Name__c = 'Contact',  Parent_Matching_Rule__c = objMR1.Id, Support_Text__c = 'Test_Support002', Evaluation_Order__c = '1 AND 2')};
                insert lstmatchingrule;
        
        lstmatchingrulecreteria = new List<Matching_Rule_Criteria__c>{new Matching_Rule_Criteria__c(Matching_Rule__c = lstmatchingrule[0].Id, Field_API_Name__c =  'AccountId', Field_Operator__c = 'greaterthan', Field_Type__c = 'REFERENCE', Field_Value__c = '0012546845741852'),
            new Matching_Rule_Criteria__c(Matching_Rule__c = lstmatchingrule[1].Id, Field_API_Name__c = 'Price', Field_Operator__c = 'greaterThan', Field_Type__c = 'CURRENCY', Field_Value__c = '100')};
                insert lstmatchingrulecreteria;
        
        lstRemoveRowmatchingrulecreteria = new List<Matching_Rule_Criteria__c>{new Matching_Rule_Criteria__c(Matching_Rule__c = lstmatchingrule[0].Id, Field_API_Name__c =  'AccountId', Field_Operator__c = 'greaterthan', Field_Type__c = 'REFERENCE', Field_Value__c = '0012546845741852'),
            new Matching_Rule_Criteria__c(Matching_Rule__c = lstmatchingrule[1].Id, Field_API_Name__c = 'Price', Field_Operator__c = 'greaterThan', Field_Type__c = 'CURRENCY', Field_Value__c = '100')};
                insert lstRemoveRowmatchingrulecreteria;
        
        objMR = new Matching_Rule__c(Name = 'TestMR2', Object_Name__c = 'Opportunity', Parent_Matching_Rule__c = objMR1.Id, Support_Text__c = 'Test_Support2', Evaluation_Order__c = '1 AND 2');
        objMRcreteria = new Matching_Rule_Criteria__c(Field_API_Name__c = 'Name', Field_Operator__c = 'equals', Field_Type__c = 'STRING', Field_Value__c = 'vijay');
        
    }
    
    static testMethod void method1() {
        createData();
        MachingRuleCreation.getallobjects();
        MachingRuleCreation.getALLFields('Account');
        MachingRuleCreation.getRelatedChildObjects('Account');
        MachingRuleCreation.deleteMatchingRuleRecord(lstmatchingrule[0].Id);
        MachingRuleCreation.getMatchingRuleCreteria(lstmatchingrule[0].Id);
    }
    
    static testMethod void method_createRecordsId() {
        createData();
        String recordId  = null;
        
        List<Id> lstDeleteIds = new List<Id>();
        for(Matching_Rule_Criteria__c objMR : lstRemoveRowmatchingrulecreteria){
            lstDeleteIds.add(objMR.Id);
        }
        
        Matching_Rule__c objMR2 = new Matching_Rule__c(Name = 'TestMR2', Object_Name__c = 'Opportunity', Support_Text__c = 'Test_Support2', Evaluation_Order__c = '1 AND 2');
        MachingRuleCreation.createNewRecords(JSON.serialize(objMR), '['+JSON.serialize(objMRcreteria)+']', lstDeleteIds);    
        MachingRuleCreation.createNewRecords(JSON.serialize(objMR), '['+JSON.serialize(objMRcreteria)+']', lstDeleteIds);  
        MachingRuleCreation.createNewRecords(JSON.serialize(objMR2), '['+JSON.serialize(objMRcreteria)+']', lstDeleteIds);  

    }
    
}