force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Bill_To_Client__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>Bill To Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Bill To Client)</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/PGi_Client__c.field-meta.xml
<CustomField>
    <fullName>PGi_Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>You must enter the ID of the Client record, Names will not return any result.  Please ensure you use the Lookup icon to verify the correct client and company details!</inlineHelpText>
    <label>PGi Client</label>
    <referenceTo>PGi_Client__c</referenceTo>
    <relationshipLabel>Financial Requests (Associated Client)</relationshipLabel>
    <relationshipName>Financial_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Error</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error-InterCall</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error-Level 3</fullName>
            </value>
            <value>
                <fullName>Operator Assisted Error-PGi</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure-InterCall</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure-Level 3</fullName>
            </value>
            <value>
                <fullName>Provider Technical Failure-PGi</fullName>
            </value>
            <value>
                <fullName>Service Fee</fullName>
            </value>
            <value>
                <fullName>Service-GX Outage</fullName>
            </value>
            <value>
                <fullName>Service-InterCall Outage</fullName>
            </value>
            <value>
                <fullName>Service-PGi Outage</fullName>
            </value>
            <value>
                <fullName>Service-RT Outage</fullName>
            </value>
            <value>
                <fullName>Setup Error-RT</fullName>
            </value>
            <value>
                <fullName>Subscription Frequency Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Feedback</fullName>
            </value>
            <value>
                <fullName>Awaiting Response</fullName>
            </value>
            <value>
                <fullName>Billing Actions Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Closed - Not Needed</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Customer Replied</fullName>
            </value>
            <value>
                <fullName>Customer UAT</fullName>
            </value>
            <value>
                <fullName>Delayed Release</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Manual Release - Prod</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New - Transferred</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending Approval(s)</fullName>
            </value>
            <value>
                <fullName>Pending Credit Committee Approval</fullName>
            </value>
            <value>
                <fullName>Pipeline</fullName>
            </value>
            <value>
                <fullName>Reactivated</fullName>
            </value>
            <value>
                <fullName>Ready for Demo</fullName>
            </value>
            <value>
                <fullName>Ready for Release</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Re-Opened</fullName>
            </value>
            <value>
                <fullName>Retained</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3rd Party</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Amendment Request</fullName>
            </value>
            <value>
                <fullName>Billing Cycle Change</fullName>
            </value>
            <value>
                <fullName>Billing External Report</fullName>
            </value>
            <value>
                <fullName>Billing Internal Report</fullName>
            </value>
            <value>
                <fullName>Billing Method Change</fullName>
            </value>
            <value>
                <fullName>Bill To Change</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Company Cancellation</fullName>
            </value>
            <value>
                <fullName>Company Inactivation</fullName>
            </value>
            <value>
                <fullName>Contact Information Change</fullName>
            </value>
            <value>
                <fullName>Contract: Manual Edit Request</fullName>
            </value>
            <value>
                <fullName>Contract/Pricing</fullName>
            </value>
            <value>
                <fullName>Copy of Outstanding Invoice</fullName>
            </value>
            <value>
                <fullName>Diamond</fullName>
            </value>
            <value>
                <fullName>Email Support</fullName>
            </value>
            <value>
                <fullName>End Date Shortfall and/or Commitment</fullName>
            </value>
            <value>
                <fullName>General Question/Feedback</fullName>
            </value>
            <value>
                <fullName>Help with Reporting</fullName>
            </value>
            <value>
                <fullName>I Want Something New</fullName>
            </value>
            <value>
                <fullName>Licenses (New Acct)</fullName>
            </value>
            <value>
                <fullName>Licenses (w/ an Existing Acct)</fullName>
            </value>
            <value>
                <fullName>Login/Permission</fullName>
            </value>
            <value>
                <fullName>MOM Corrections</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>New Company Setup Complete</fullName>
            </value>
            <value>
                <fullName>One-Time Manual Charge</fullName>
            </value>
            <value>
                <fullName>Online Billing Center</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PGi_Client__c/PGi_Client__c.object-meta.xml
<CustomObject>
    <label>PGi Client</label>
    <nameField>
        <label>PGi Client ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PGi Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CloneChildFinReqLEXControllerTest.cls
@isTest
public class CloneChildFinReqLEXControllerTest {

    static testMethod void testCloneAnySobjet(){
         Test.startTest();
        
        Profile profile = [SELECT Id FROM Profile WHERE name = 'System Administrator'];
        UserRole portalRole = [SELECT Id FROM UserRole WHERE PortalType = 'None' LIMIT 1];
        
        User u = new User(
            UserRoleId = portalRole.Id,
            ProfileId = profile.Id,
            Username = 'bradBellick321@pgi.com',
            Alias = 'batman',
            Email='bradBellick321@pgi.com',
            EmailEncodingKey='UTF-8',
            Firstname='Bruce',
            Lastname='Wayne',
            LanguageLocaleKey='en_US',
            LocaleSidKey='en_US',
            EmployeeNumber='12345',
            TimeZoneSidKey='America/Chicago');
        INSERT u;
        System.debug('User: '+u);
        
        User objUser = [SELECT Id FROM User WHERE Id =: u.Id LIMIT 1];
        
        System.runas(objUser) {
           
            PGi_Client__c objPgiClient = new PGi_Client__c();
            objPgiClient.Client_ID__c = 'PGITest12';
            INSERT objPgiClient;
            
            Financial_Request__c objFinReq = new Financial_Request__c();
            objFinReq.Status__c = 'New';
            objFinReq.Type__c = 'Other';
            objFinReq.Reason__c = 'NA';
            objFinReq.Bill_To_Client__c = objPgiClient.Id;
            INSERT objFinReq;
            
            String cloneChildRecId=CloneChildFinReqLEXController.cloneAnySobjet(objFinReq.Id,'Financial_Request__c');
            System.assert(cloneChildRecId!=null);
        }
        
        Test.stopTest();
        
    }
}