force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssignToMeListBtnFinReqController.cls
public with sharing class AssignToMeListBtnFinReqController {
    private ApexPages.StandardSetController standardController;
    public boolean noRecords{get; set;}
    
    public AssignToMeListBtnFinReqController(ApexPages.StandardSetController standardController) {
        this.standardController = standardController;
        noRecords = false;
    }
  
    public void assignRecords(){
         Set<Id> selectedIds = new Map<Id, SObject>(standardController.getSelected()).keySet(); 
        if(!selectedIds.isEmpty()){
             Financial_Request__c finReqObj = [SELECT Id, Assigned_To__c 
                                              FROM Financial_Request__c 
                                              WHERE Id =:selectedIds];
            finReqObj.Assigned_To__c = UserInfo.getUserId();
            try{
                UPDATE finReqObj;
            }
            catch(Exception e){
            } 
        } else{
            noRecords = true;   
        } 

    }
    
    public Pagereference returnToHomepage(){ 
        return standardController.cancel();
    }
}