force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Escalated_Lead__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Escalated to Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Chat Transcripts</relationshipLabel>
    <relationshipName>Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Country_Code__c</fullName>
    <label>Location_Country_Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Location_Region__c</fullName>
    <description>To be populated based on Country in geolocation Location field</description>
    <label>Location_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmitFinReqControllerTest.cls
@IsTest
public class SubmitFinReqControllerTest {
    
    static testMethod void testController() {
        
        SubmitFinReqController objFinReqCtrl = new SubmitFinReqController();
        
        PageReference objPageRef = objFinReqCtrl.submitFinReq();
    }
    
    static  testMethod void submitEscalatedFinReqTest(){
        Test.startTest(); 
    
        LiveChatVisitor lcv = new LiveChatVisitor();
        INSERT lcv;
        
        LiveChatTranscript ctRecord = new LiveChatTranscript(LiveChatVisitorId = lcv.Id,
                                                             Email_Address__c='test@pgi.com',
                                                             Subject__c='Test',
                                                             First_Name__c='Test',
                                                             Last_Name__c='Test',
                                                             Escalated_Lead__c = false,
                                                             Location_Country_Code__c = 'IE',
                                                             Location_Region__c = 'EMEA'
                                     );
        INSERT ctRecord; 
        
        PageReference ref = new PageReference('/apex/Chat_SubmitEscalatedFinReq'); 
        ref.getParameters().put('id', String.valueOf(ctRecord.Id));
        Test.setCurrentPage(ref);    
            
        Id recordTypeId = Schema.SObjectType.Financial_Request__c.getRecordTypeInfosByName().get('PGi-Billing Support').getRecordTypeId();
                
                SubmitFinReqController con = new SubmitFinReqController();               
                con.init();
                con.submitEscalatedFinReq();
                Test.StopTest();
    }
    
}