force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/CaseDescription__c.field-meta.xml
<CustomField>
    <fullName>CaseDescription__c</fullName>
    <label>Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submission</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Lync/IM</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>PGi Contract</fullName>
            </value>
            <value>
                <fullName>PGi Service Catalog</fullName>
            </value>
            <value>
                <fullName>SvcNow</fullName>
            </value>
            <value>
                <fullName>PIDR</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>APAC - North</fullName>
            </value>
            <value>
                <fullName>APAC - South</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/Requested_For__c.field-meta.xml
<CustomField>
    <fullName>Requested_For__c</fullName>
    <inlineHelpText>This will default to the email of the person entering the request. If this request is for a different PGi Associate please change this to their email address.</inlineHelpText>
    <label>Requested For</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Financial_Request__c/fields/RequestorsEmail__c.field-meta.xml
<CustomField>
    <fullName>RequestorsEmail__c</fullName>
    <label>Requestor&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Escalated_FinReq__c.field-meta.xml
<CustomField>
    <fullName>Escalated_FinReq__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Escalated to FinReq</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Financial_Request__c.field-meta.xml
<CustomField>
    <fullName>Financial_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Financial Request</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Chat Transcripts</relationshipLabel>
    <relationshipName>Chat_Transcripts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Location_Country_Code__c</fullName>
    <label>Location_Country_Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Location_Region__c</fullName>
    <description>To be populated based on Country in geolocation Location field</description>
    <label>Location_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>To set the case origin when escalating a chat. &#39;Chat&#39; or &#39;Chat - In Product&#39;</description>
    <label>Origin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LiveChatTranscript/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SubmitFinReqController.cls
public class SubmitFinReqController {
    
    public Financial_Request__c f { get; set; }
    public LiveChatTranscript currentChatTranscript { get; set; }
    public Id currentRecordId { get; set; }
    public Id recordTypeId { get; set; }
    
    public String Name { get; set; }
    public String FirstName { get; set; }
    public String LastName { get; set; }
    public String Email { get; set; }
    public String Query { get; set; }
    public String Subject { get; set; }
    public String Region { get; set; }
    
    public String returnId { get; set; }
    
    
    public SubmitFinReqController() {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        f = new Financial_Request__c();
    }
 
    // submitFinReq Method for external FinReq creation from Missed Chat
    public PageReference submitFinReq() {
    
        recordTypeId = Schema.SObjectType.Financial_Request__c.getRecordTypeInfosByName().get('PGi-Billing Support').getRecordTypeId();
    
            try {
                f.Subject__c = 'Missed chat from ' + Name;
                f.Requested_For__c = Email;
                f.RequestorsEmail__c = Email;
                f.CaseDescription__c = Query;
                f.Region__c = Region;
                f.RecordTypeId = recordTypeId;
                INSERT f;
                PageReference retURL = new PageReference('/ChatLandingPage' + '?origin=web');
                retURL.setRedirect(true);
                return retURL;
            } catch (Exception e) {
                ApexPages.addMessages(e);
                return null;
            }
    }
    
    // init Method for internal FinReq escalation from Live Chat
    public  void init(){
        recordTypeId = Schema.SObjectType.Financial_Request__c.getRecordTypeInfosByName().get('PGi-Billing Support').getRecordTypeId();
        
        currentChatTranscript = [SELECT ID, Email_Address__c, Subject__c, First_Name__c, Last_Name__c, Escalated_FinReq__c, Location_Country_Code__c, Location_Region__c
             FROM LiveChatTranscript 
             WHERE Id =: currentRecordId limit 1];
             
             FirstName = currentChatTranscript.First_Name__c;
             LastName = currentChatTranscript.Last_Name__c;
             Name = FirstName + ' ' + LastName;
             Subject = 'Billing Query from' + ' ' + Name;
             Email = currentChatTranscript.Email_Address__c;  
             Region = currentChatTranscript.Location_Region__c;
             
             if (!( (new List<String>{'EMEA','NA','APAC - North','APAC - South','India'}).contains(Region) )){
                   //if no valid region, default region to NA
                   Region = 'NA';
             }
    }
    
      public List<SelectOption> getRegions(){
          List<SelectOption> options = new List<SelectOption>();
            
          Schema.DescribeFieldResult fieldResult = Financial_Request__c.Region__c.getDescribe();
          List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            
          for( Schema.PicklistEntry p : ple)
          {
              options.add(new SelectOption(p.getLabel(), p.getValue()));
          }       
          return options;
      }
    
    
        // submitEscalatedFinReq Method for internal FinReq escalation by Agent from Live Chat
    public PageReference submitEscalatedFinReq() {   
    
            try {
                f.Requested_For__c = Email;
                f.RequestorsEmail__c = Email;
                f.Internal_Comments__c = Query;     
                f.Subject__c = Subject;    
                f.Region__c = Region;
                f.Origin__c = 'Chat';
                f.RecordTypeId = recordTypeId;
                INSERT f;
                currentChatTranscript.Financial_Request__c = f.Id;
                currentChatTranscript.Escalated_FinReq__c = true;
                UPDATE currentChatTranscript;
                
                returnId = f.Id;
                PageReference retURL = new PageReference('/apex/ChatEscalateLandingPage?recordId=' + returnId + '&recordType=FinReq');
                retURL.setRedirect(true);
                return retURL;
            } catch (Exception e) {
                ApexPages.addMessages(e);
                return null;
            }
    }
}