force-app/main/default/objects/Financial_Request__c/Financial_Request__c.object-meta.xml
<CustomObject>
    <description>all financial type requests</description>
    <label>Financial Request</label>
    <nameField>
        <displayFormat>FinReq# {00000000}</displayFormat>
        <label>Financial Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Request__c/fields/Related_FinReq__c.field-meta.xml
<CustomField>
    <fullName>Related_FinReq__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Does this relate to another FinReq</inlineHelpText>
    <label>Related FinReq</label>
    <referenceTo>Financial_Request__c</referenceTo>
    <relationshipLabel>Financial Requests</relationshipLabel>
    <relationshipName>Financial_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CloneChildFinReqLEXController.cls
public class CloneChildFinReqLEXController {
    @AuraEnabled
    public static String cloneAnySobjet(String recordId, String objectName){
        
       Set <String> fieldMap = Schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().keySet();
        String soqlQuery = 'SELECT ' ; 
        for (String s :fieldMap ){
            if(schema.getGlobalDescribe().get(objectName).getDescribe().fields.getMap().get(s).getDescribe().isAccessible()){
                soqlQuery +=  + s+',';
            }
        }
        soqlQuery =  soqlQuery.removeEnd(',');
        soqlQuery += ' FROM ' +objectName +' WHERE ID = \'' + recordId +'\'' ;
        System.debug('soqlQuery'+soqlQuery);
        Financial_Request__c record = Database.query(soqlQuery);
        Financial_Request__c clondedParentRecordID= record.clone(false, false, false, false);
        clondedParentRecordID.Related_FinReq__c=recordId;
        try{
            insert clondedParentRecordID ;
            return clondedParentRecordID.id ;
        }catch(Exception e){
            return '' ;
        }
        
    }
}